export async function ensureAcademicsSchema(database){await database.query(`
 CREATE TABLE IF NOT EXISTS acad_rooms(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,campus_id text REFERENCES school_branches(id) ON DELETE SET NULL,code text NOT NULL,name text NOT NULL,capacity integer,room_type text NOT NULL DEFAULT 'classroom',location_text text,active boolean NOT NULL DEFAULT true,notes text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,code));
 CREATE INDEX IF NOT EXISTS acad_rooms_org_idx ON acad_rooms(organization_id,active,name);
 CREATE TABLE IF NOT EXISTS acad_teacher_availability(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,academic_year_id text REFERENCES school_academic_years(id) ON DELETE CASCADE,term_id text REFERENCES school_terms(id) ON DELETE CASCADE,weekday integer NOT NULL CHECK(weekday BETWEEN 1 AND 7),starts_at text NOT NULL,ends_at text NOT NULL,availability text NOT NULL DEFAULT 'available',reason text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(starts_at<ends_at));
 CREATE INDEX IF NOT EXISTS acad_teacher_availability_idx ON acad_teacher_availability(organization_id,teacher_user_id,term_id,weekday,starts_at);
 CREATE TABLE IF NOT EXISTS acad_timetables(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,academic_year_id text NOT NULL REFERENCES school_academic_years(id) ON DELETE RESTRICT,term_id text NOT NULL REFERENCES school_terms(id) ON DELETE RESTRICT,campus_id text REFERENCES school_branches(id) ON DELETE SET NULL,name text NOT NULL,status text NOT NULL DEFAULT 'draft',notes text,submitted_by text REFERENCES users(id) ON DELETE SET NULL,submitted_at timestamptz,approved_by text REFERENCES users(id) ON DELETE SET NULL,approved_at timestamptz,published_by text REFERENCES users(id) ON DELETE SET NULL,published_at timestamptz,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,academic_year_id,term_id,name));
 CREATE INDEX IF NOT EXISTS acad_timetables_period_idx ON acad_timetables(organization_id,academic_year_id,term_id,status);
 CREATE TABLE IF NOT EXISTS acad_timetable_entries(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,timetable_id text NOT NULL REFERENCES acad_timetables(id) ON DELETE CASCADE,class_id text NOT NULL REFERENCES school_classes(id) ON DELETE CASCADE,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text NOT NULL REFERENCES school_subjects(id) ON DELETE RESTRICT,teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,department_id text REFERENCES school_departments(id) ON DELETE SET NULL,room_id text REFERENCES acad_rooms(id) ON DELETE SET NULL,weekday integer NOT NULL CHECK(weekday BETWEEN 1 AND 7),starts_at text NOT NULL,ends_at text NOT NULL,lesson_type text NOT NULL DEFAULT 'single',lesson_count integer NOT NULL DEFAULT 1 CHECK(lesson_count IN(1,2)),active boolean NOT NULL DEFAULT true,notes text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(starts_at<ends_at));
 CREATE INDEX IF NOT EXISTS acad_tt_class_idx ON acad_timetable_entries(organization_id,timetable_id,class_id,stream_id,weekday,starts_at);
 CREATE INDEX IF NOT EXISTS acad_tt_teacher_idx ON acad_timetable_entries(organization_id,timetable_id,teacher_user_id,weekday,starts_at);
 CREATE TABLE IF NOT EXISTS acad_timetable_changes(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,timetable_entry_id text NOT NULL REFERENCES acad_timetable_entries(id) ON DELETE CASCADE,change_date date NOT NULL,changed_teacher_user_id text REFERENCES users(id) ON DELETE SET NULL,changed_room_id text REFERENCES acad_rooms(id) ON DELETE SET NULL,changed_starts_at text,changed_ends_at text,reason text NOT NULL,status text NOT NULL DEFAULT 'approved',created_by text REFERENCES users(id) ON DELETE SET NULL,approved_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS acad_substitute_lessons(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,timetable_entry_id text REFERENCES acad_timetable_entries(id) ON DELETE SET NULL,lesson_date date NOT NULL,original_teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,substitute_teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,reason text NOT NULL,notes text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS acad_substitute_date_idx ON acad_substitute_lessons(organization_id,lesson_date,substitute_teacher_user_id);
 CREATE TABLE IF NOT EXISTS acad_schemes(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,academic_year_id text NOT NULL REFERENCES school_academic_years(id) ON DELETE RESTRICT,term_id text NOT NULL REFERENCES school_terms(id) ON DELETE RESTRICT,class_id text NOT NULL REFERENCES school_classes(id) ON DELETE RESTRICT,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text NOT NULL REFERENCES school_subjects(id) ON DELETE RESTRICT,teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,title text NOT NULL,status text NOT NULL DEFAULT 'draft',version_no integer NOT NULL DEFAULT 1,coverage_percent double precision NOT NULL DEFAULT 0,teacher_reflection text,hod_feedback text,dos_feedback text,hod_reviewed_by text REFERENCES users(id) ON DELETE SET NULL,hod_reviewed_at timestamptz,dos_approved_by text REFERENCES users(id) ON DELETE SET NULL,dos_approved_at timestamptz,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS acad_schemes_period_idx ON acad_schemes(organization_id,term_id,class_id,subject_id,status);
 CREATE TABLE IF NOT EXISTS acad_scheme_items(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,scheme_id text NOT NULL REFERENCES acad_schemes(id) ON DELETE CASCADE,sequence_no integer NOT NULL DEFAULT 1,week_no integer NOT NULL,lesson_no integer,topic text NOT NULL,subtopic text,learning_objectives text,competencies text,teaching_methods text,learning_materials text,references_text text,planned_activities text,assessment_activities text,planned_date date,coverage_status text NOT NULL DEFAULT 'planned',teacher_reflection text,covered_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(scheme_id,sequence_no));
 CREATE INDEX IF NOT EXISTS acad_scheme_items_week_idx ON acad_scheme_items(organization_id,scheme_id,week_no,sequence_no);
 CREATE TABLE IF NOT EXISTS acad_scheme_versions(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,scheme_id text NOT NULL REFERENCES acad_schemes(id) ON DELETE CASCADE,version_no integer NOT NULL,snapshot_json text NOT NULL,change_note text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(scheme_id,version_no));
 CREATE TABLE IF NOT EXISTS acad_lesson_plan_templates(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name text NOT NULL,description text,template_json text NOT NULL DEFAULT '{}',active boolean NOT NULL DEFAULT true,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,name));
 CREATE TABLE IF NOT EXISTS acad_lesson_plans(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,academic_year_id text NOT NULL REFERENCES school_academic_years(id) ON DELETE RESTRICT,term_id text NOT NULL REFERENCES school_terms(id) ON DELETE RESTRICT,class_id text NOT NULL REFERENCES school_classes(id) ON DELETE RESTRICT,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text NOT NULL REFERENCES school_subjects(id) ON DELETE RESTRICT,teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,timetable_entry_id text REFERENCES acad_timetable_entries(id) ON DELETE SET NULL,scheme_item_id text REFERENCES acad_scheme_items(id) ON DELETE SET NULL,template_id text REFERENCES acad_lesson_plan_templates(id) ON DELETE SET NULL,lesson_date date NOT NULL,week_no integer,lesson_no integer,topic text NOT NULL,subtopic text,lesson_objectives text,prior_knowledge text,introduction_text text,lesson_development text,teacher_activities text,learner_activities text,teaching_methods text,required_materials text,differentiated_instruction text,special_needs_accommodations text,lesson_assessment text,lesson_conclusion text,homework text,teacher_reflection text,hod_feedback text,status text NOT NULL DEFAULT 'draft',approved_by text REFERENCES users(id) ON DELETE SET NULL,approved_at timestamptz,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS acad_lesson_plan_date_idx ON acad_lesson_plans(organization_id,lesson_date,teacher_user_id,status);
 CREATE TABLE IF NOT EXISTS acad_lesson_deliveries(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,timetable_entry_id text REFERENCES acad_timetable_entries(id) ON DELETE SET NULL,lesson_plan_id text REFERENCES acad_lesson_plans(id) ON DELETE SET NULL,academic_year_id text NOT NULL REFERENCES school_academic_years(id) ON DELETE RESTRICT,term_id text NOT NULL REFERENCES school_terms(id) ON DELETE RESTRICT,class_id text NOT NULL REFERENCES school_classes(id) ON DELETE RESTRICT,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text NOT NULL REFERENCES school_subjects(id) ON DELETE RESTRICT,teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,substitute_teacher_user_id text REFERENCES users(id) ON DELETE SET NULL,attendance_session_id text REFERENCES school_student_attendance_sessions(id) ON DELETE SET NULL,scheduled_date date NOT NULL,scheduled_starts_at text,scheduled_ends_at text,actual_starts_at timestamptz,actual_ends_at timestamptz,delivery_status text NOT NULL DEFAULT 'scheduled',actual_topic text,actual_subtopic text,student_attendance_summary text,lesson_notes text,missed_reason text,recovery_date date,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),canonical_attendance_session_id text REFERENCES att_sessions(id) ON DELETE SET NULL);
 CREATE INDEX IF NOT EXISTS acad_delivery_date_idx ON acad_lesson_deliveries(organization_id,scheduled_date,class_id,teacher_user_id,delivery_status);
 CREATE UNIQUE INDEX IF NOT EXISTS acad_delivery_schedule_uq ON acad_lesson_deliveries(organization_id,timetable_entry_id,scheduled_date) WHERE timetable_entry_id IS NOT NULL;
 CREATE INDEX IF NOT EXISTS acad_delivery_att_session_idx ON acad_lesson_deliveries(organization_id,canonical_attendance_session_id);
 CREATE TABLE IF NOT EXISTS acad_delivery_attachments(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,delivery_id text NOT NULL REFERENCES acad_lesson_deliveries(id) ON DELETE CASCADE,file_id text NOT NULL REFERENCES school_files(id) ON DELETE RESTRICT,caption text,uploaded_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(delivery_id,file_id));
 CREATE TABLE IF NOT EXISTS acad_observations(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,observation_type text NOT NULL,scheduled_for timestamptz,observed_at timestamptz,teacher_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,observer_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,class_id text REFERENCES school_classes(id) ON DELETE SET NULL,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text REFERENCES school_subjects(id) ON DELETE SET NULL,lesson_plan_id text REFERENCES acad_lesson_plans(id) ON DELETE SET NULL,status text NOT NULL DEFAULT 'scheduled',rubric_json text NOT NULL DEFAULT '{}',preparation_score double precision,teaching_methods_score double precision,classroom_management_score double precision,learner_participation_score double precision,materials_use_score double precision,time_management_score double precision,strengths text,areas_for_improvement text,recommendations text,confidential_notes text,teacher_acknowledged_at timestamptz,teacher_response text,followup_date date,followup_observation_id text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS acad_observations_teacher_idx ON acad_observations(organization_id,teacher_user_id,scheduled_for,status);
 CREATE TABLE IF NOT EXISTS acad_observation_attachments(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,observation_id text NOT NULL REFERENCES acad_observations(id) ON DELETE CASCADE,file_id text NOT NULL REFERENCES school_files(id) ON DELETE RESTRICT,caption text,uploaded_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(observation_id,file_id));
 CREATE TABLE IF NOT EXISTS acad_inspections(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,inspection_type text NOT NULL,inspected_on date NOT NULL,inspector_user_id text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,teacher_user_id text REFERENCES users(id) ON DELETE SET NULL,class_id text REFERENCES school_classes(id) ON DELETE SET NULL,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text REFERENCES school_subjects(id) ON DELETE SET NULL,sample_size integer,quantity_of_work text,quality_of_marking text,correction_feedback_checks text,date_of_last_marking date,findings text NOT NULL,recommendations text,teacher_response text,followup_date date,status text NOT NULL DEFAULT 'open',confidential_notes text,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS acad_inspection_teacher_idx ON acad_inspections(organization_id,teacher_user_id,inspected_on,status);
 CREATE TABLE IF NOT EXISTS acad_inspection_samples(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,inspection_id text NOT NULL REFERENCES acad_inspections(id) ON DELETE CASCADE,student_id text REFERENCES school_students(id) ON DELETE SET NULL,sample_label text,findings text,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS acad_inspection_attachments(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,inspection_id text NOT NULL REFERENCES acad_inspections(id) ON DELETE CASCADE,file_id text NOT NULL REFERENCES school_files(id) ON DELETE RESTRICT,caption text,uploaded_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(inspection_id,file_id));
 `);}
export async function finalizeAcademicsSchema(database){await database.query(`DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='acad_observations_followup_fk') THEN ALTER TABLE acad_observations ADD CONSTRAINT acad_observations_followup_fk FOREIGN KEY(followup_observation_id) REFERENCES acad_observations(id) ON DELETE SET NULL; END IF; END $$;`);}
