export async function ensureAttendanceSchema(database) {
  await database.query(`
    CREATE TABLE IF NOT EXISTS school_student_attendance_sessions (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,academic_year_id text NOT NULL REFERENCES school_academic_years(id) ON DELETE RESTRICT,term_id text REFERENCES school_terms(id) ON DELETE SET NULL,campus_id text REFERENCES school_branches(id) ON DELETE SET NULL,attendance_date date NOT NULL,session_type text NOT NULL DEFAULT 'daily',class_id text NOT NULL REFERENCES school_classes(id) ON DELETE RESTRICT,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text REFERENCES school_subjects(id) ON DELETE SET NULL,lesson_period_id text REFERENCES school_lesson_periods(id) ON DELETE SET NULL,title text,starts_at text,ends_at text,status text NOT NULL DEFAULT 'open',expected_count integer NOT NULL DEFAULT 0,marked_count integer NOT NULL DEFAULT 0,source text NOT NULL DEFAULT 'manual',notes text,marked_by text REFERENCES users(id) ON DELETE SET NULL,submitted_by text REFERENCES users(id) ON DELETE SET NULL,submitted_at timestamptz,locked_by text REFERENCES users(id) ON DELETE SET NULL,locked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
    CREATE UNIQUE INDEX IF NOT EXISTS school_student_attendance_session_uq ON school_student_attendance_sessions(organization_id,attendance_date,session_type,class_id,COALESCE(stream_id,''),COALESCE(subject_id,''),COALESCE(lesson_period_id,''));
    CREATE INDEX IF NOT EXISTS school_student_attendance_session_date_idx ON school_student_attendance_sessions(organization_id,attendance_date,class_id,stream_id,status);
    CREATE TABLE IF NOT EXISTS school_student_attendance_records (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,session_id text NOT NULL REFERENCES school_student_attendance_sessions(id) ON DELETE CASCADE,student_id text NOT NULL REFERENCES school_students(id) ON DELETE CASCADE,status text NOT NULL,arrival_time text,departure_time text,minutes_late integer NOT NULL DEFAULT 0,reason_code text,reason text,remarks text,source text NOT NULL DEFAULT 'manual',marked_by text REFERENCES users(id) ON DELETE SET NULL,marked_at timestamptz NOT NULL DEFAULT now(),corrected_by text REFERENCES users(id) ON DELETE SET NULL,correction_reason text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,session_id,student_id));
    CREATE INDEX IF NOT EXISTS school_student_attendance_record_student_idx ON school_student_attendance_records(organization_id,student_id,status,marked_at DESC);
    CREATE TABLE IF NOT EXISTS school_student_attendance_changes (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,record_id text NOT NULL REFERENCES school_student_attendance_records(id) ON DELETE CASCADE,session_id text NOT NULL REFERENCES school_student_attendance_sessions(id) ON DELETE CASCADE,student_id text NOT NULL REFERENCES school_students(id) ON DELETE CASCADE,previous_status text,new_status text NOT NULL,before_json text NOT NULL DEFAULT '{}',after_json text NOT NULL DEFAULT '{}',reason text NOT NULL,changed_by text REFERENCES users(id) ON DELETE SET NULL,changed_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS school_staff_attendance_day_locks (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,attendance_date date NOT NULL,locked_by text REFERENCES users(id) ON DELETE SET NULL,locked_at timestamptz NOT NULL DEFAULT now(),reason text,UNIQUE(organization_id,attendance_date));
    CREATE TABLE IF NOT EXISTS school_staff_attendance_records (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,staff_id text NOT NULL REFERENCES school_staff_profiles(id) ON DELETE CASCADE,attendance_date date NOT NULL,campus_id text REFERENCES school_branches(id) ON DELETE SET NULL,department_id text REFERENCES school_departments(id) ON DELETE SET NULL,status text NOT NULL DEFAULT 'present',scheduled_start text,scheduled_end text,first_clock_in timestamptz,last_clock_out timestamptz,worked_minutes integer NOT NULL DEFAULT 0,break_minutes integer NOT NULL DEFAULT 0,overtime_minutes integer NOT NULL DEFAULT 0,minutes_late integer NOT NULL DEFAULT 0,leave_type text,reason text,notes text,source text NOT NULL DEFAULT 'manual',approved_by text REFERENCES users(id) ON DELETE SET NULL,corrected_by text REFERENCES users(id) ON DELETE SET NULL,correction_reason text,locked boolean NOT NULL DEFAULT false,locked_by text REFERENCES users(id) ON DELETE SET NULL,locked_at timestamptz,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,staff_id,attendance_date));
    CREATE INDEX IF NOT EXISTS school_staff_attendance_date_idx ON school_staff_attendance_records(organization_id,attendance_date,status,campus_id,department_id);
    CREATE TABLE IF NOT EXISTS school_staff_attendance_events (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,staff_id text NOT NULL REFERENCES school_staff_profiles(id) ON DELETE CASCADE,daily_record_id text NOT NULL REFERENCES school_staff_attendance_records(id) ON DELETE CASCADE,attendance_date date NOT NULL,event_type text NOT NULL,event_at timestamptz NOT NULL,source text NOT NULL DEFAULT 'clock',device_id text,location_text text,notes text,recorded_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS school_staff_attendance_changes (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,record_id text NOT NULL REFERENCES school_staff_attendance_records(id) ON DELETE CASCADE,staff_id text NOT NULL REFERENCES school_staff_profiles(id) ON DELETE CASCADE,attendance_date date NOT NULL,previous_status text,new_status text NOT NULL,before_json text NOT NULL DEFAULT '{}',after_json text NOT NULL DEFAULT '{}',reason text NOT NULL,changed_by text REFERENCES users(id) ON DELETE SET NULL,changed_at timestamptz NOT NULL DEFAULT now());

    CREATE TABLE IF NOT EXISTS att_policies (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name text NOT NULL,population text NOT NULL DEFAULT 'all',school_starts_at text NOT NULL DEFAULT '08:00',late_after text NOT NULL DEFAULT '08:10',absence_after text NOT NULL DEFAULT '09:00',expected_departure_at text NOT NULL DEFAULT '16:30',duplicate_cooldown_seconds integer NOT NULL DEFAULT 60,early_departure_minutes integer NOT NULL DEFAULT 15,timezone text NOT NULL DEFAULT 'Africa/Kampala',active boolean NOT NULL DEFAULT true,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS att_policies_org_idx ON att_policies(organization_id,active,population);
    CREATE TABLE IF NOT EXISTS att_sessions (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,academic_year_id text REFERENCES school_academic_years(id) ON DELETE SET NULL,term_id text REFERENCES school_terms(id) ON DELETE SET NULL,campus_id text REFERENCES school_branches(id) ON DELETE SET NULL,attendance_date date NOT NULL,session_type text NOT NULL DEFAULT 'daily',population text NOT NULL DEFAULT 'students',class_id text REFERENCES school_classes(id) ON DELETE SET NULL,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,subject_id text REFERENCES school_subjects(id) ON DELETE SET NULL,lesson_period_id text REFERENCES school_lesson_periods(id) ON DELETE SET NULL,external_ref text,title text,starts_at text,ends_at text,status text NOT NULL DEFAULT 'open',expected_count integer NOT NULL DEFAULT 0,marked_count integer NOT NULL DEFAULT 0,source text NOT NULL DEFAULT 'manual',notes text,created_by text REFERENCES users(id) ON DELETE SET NULL,finalized_by text REFERENCES users(id) ON DELETE SET NULL,finalized_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS att_sessions_date_idx ON att_sessions(organization_id,attendance_date,population,status);
    CREATE UNIQUE INDEX IF NOT EXISTS att_sessions_scope_uq ON att_sessions(organization_id,attendance_date,session_type,population,COALESCE(class_id,''),COALESCE(stream_id,''),COALESCE(subject_id,''),COALESCE(lesson_period_id,''));
    CREATE TABLE IF NOT EXISTS att_records (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,session_id text REFERENCES att_sessions(id) ON DELETE CASCADE,attendance_date date NOT NULL,person_type text NOT NULL,person_id text NOT NULL,status text NOT NULL,first_in_at timestamptz,last_out_at timestamptz,minutes_late integer NOT NULL DEFAULT 0,worked_minutes integer NOT NULL DEFAULT 0,break_minutes integer NOT NULL DEFAULT 0,overtime_minutes integer NOT NULL DEFAULT 0,reason_code text,reason text,notes text,source_method text NOT NULL DEFAULT 'MANUAL',official boolean NOT NULL DEFAULT true,finalized boolean NOT NULL DEFAULT false,approved_by text REFERENCES users(id) ON DELETE SET NULL,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
    CREATE UNIQUE INDEX IF NOT EXISTS att_records_person_session_uq ON att_records(organization_id,session_id,person_type,person_id) WHERE session_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS att_records_staff_daily_uq ON att_records(organization_id,attendance_date,person_id) WHERE person_type='staff' AND session_id IS NULL;
    CREATE INDEX IF NOT EXISTS att_records_person_idx ON att_records(organization_id,person_type,person_id,attendance_date DESC);
    CREATE TABLE IF NOT EXISTS att_devices (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_code text NOT NULL,name text NOT NULL,location_name text,campus_id text REFERENCES school_branches(id) ON DELETE SET NULL,population text NOT NULL DEFAULT 'mixed',direction text NOT NULL DEFAULT 'IN',status text NOT NULL DEFAULT 'pending',platform text NOT NULL DEFAULT 'android',app_version text,last_seen_at timestamptz,last_sync_at timestamptz,registered_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,device_code));
    CREATE INDEX IF NOT EXISTS att_devices_org_idx ON att_devices(organization_id,status);
    CREATE TABLE IF NOT EXISTS att_device_credentials (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text NOT NULL REFERENCES att_devices(id) ON DELETE CASCADE,credential_hash text NOT NULL,expires_at timestamptz,last_used_at timestamptz,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS att_device_sync_batches (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text NOT NULL REFERENCES att_devices(id) ON DELETE CASCADE,client_batch_id text NOT NULL,event_count integer NOT NULL DEFAULT 0,accepted_count integer NOT NULL DEFAULT 0,duplicate_count integer NOT NULL DEFAULT 0,rejected_count integer NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'received',received_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,UNIQUE(organization_id,device_id,client_batch_id));
    CREATE TABLE IF NOT EXISTS att_events (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text REFERENCES att_devices(id) ON DELETE SET NULL,sync_batch_id text REFERENCES att_device_sync_batches(id) ON DELETE SET NULL,client_event_id text,person_type text NOT NULL,person_id text,direction text NOT NULL,method text NOT NULL,verification_mode text NOT NULL DEFAULT 'STANDARD',verification_status text NOT NULL DEFAULT 'verified',confidence double precision,liveness_score double precision,captured_at timestamptz NOT NULL,received_at timestamptz NOT NULL DEFAULT now(),synced_at timestamptz,official boolean NOT NULL DEFAULT true,record_id text REFERENCES att_records(id) ON DELETE SET NULL,metadata_json text NOT NULL DEFAULT '{}',created_by text REFERENCES users(id) ON DELETE SET NULL,mobile_sync_device_id text);
    CREATE UNIQUE INDEX IF NOT EXISTS att_events_client_uq ON att_events(organization_id,device_id,client_event_id) WHERE client_event_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS att_events_mobile_client_uq ON att_events(organization_id,mobile_sync_device_id,client_event_id) WHERE mobile_sync_device_id IS NOT NULL AND client_event_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS att_events_recent_idx ON att_events(organization_id,captured_at DESC,verification_status);
    CREATE TABLE IF NOT EXISTS att_biometric_profiles (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,provider_profile_ref text,algorithm_version text NOT NULL,quality_score double precision,consent_status text NOT NULL DEFAULT 'pending',status text NOT NULL DEFAULT 'pending',enrolled_by text REFERENCES users(id) ON DELETE SET NULL,enrolled_at timestamptz,deleted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,person_type,person_id));
    CREATE TABLE IF NOT EXISTS att_person_identifiers (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,method text NOT NULL,identifier text NOT NULL,active boolean NOT NULL DEFAULT true,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,method,identifier));
    CREATE INDEX IF NOT EXISTS att_person_identifiers_person_idx ON att_person_identifiers(organization_id,person_type,person_id,active);
    CREATE TABLE IF NOT EXISTS att_biometric_enrollments (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,profile_id text NOT NULL REFERENCES att_biometric_profiles(id) ON DELETE CASCADE,provider_enrollment_ref text,algorithm_version text NOT NULL,pose_count integer NOT NULL DEFAULT 0,quality_score double precision,liveness_score double precision,status text NOT NULL DEFAULT 'completed',enrolled_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS att_test_mode_grants (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text REFERENCES att_devices(id) ON DELETE CASCADE,allow_screen_image boolean NOT NULL DEFAULT false,allow_printed_image boolean NOT NULL DEFAULT false,reason text NOT NULL,enabled_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,enabled_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,revoked_at timestamptz);
    CREATE TABLE IF NOT EXISTS att_exceptions (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,exception_type text NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,reason text NOT NULL,status text NOT NULL DEFAULT 'approved',approved_by text REFERENCES users(id) ON DELETE SET NULL,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS att_exceptions_person_idx ON att_exceptions(organization_id,person_type,person_id,starts_at,ends_at);
    CREATE TABLE IF NOT EXISTS att_corrections (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,record_id text NOT NULL REFERENCES att_records(id) ON DELETE CASCADE,before_json text NOT NULL,after_json text NOT NULL,reason text NOT NULL,status text NOT NULL DEFAULT 'approved',requested_by text REFERENCES users(id) ON DELETE SET NULL,approved_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),decided_at timestamptz);
    CREATE TABLE IF NOT EXISTS att_notification_rules (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,name text NOT NULL,trigger_type text NOT NULL,channels_json text NOT NULL DEFAULT '["sms"]',recipient_mode text NOT NULL DEFAULT 'primary_guardian',active boolean NOT NULL DEFAULT true,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS att_audit (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,actor_type text NOT NULL,actor_id text,action text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,details_json text NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS att_audit_entity_idx ON att_audit(organization_id,entity_type,entity_id,created_at DESC);
    CREATE TABLE IF NOT EXISTS att_biometric_templates (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,profile_id text NOT NULL REFERENCES att_biometric_profiles(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,algorithm_version text NOT NULL,embedding_ciphertext text NOT NULL,embedding_iv text NOT NULL,embedding_bytes integer NOT NULL DEFAULT 0,quality_score double precision,liveness_score double precision,version integer NOT NULL DEFAULT 1,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,person_type,person_id));
    CREATE TABLE IF NOT EXISTS att_biometric_enrollment_jobs (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text NOT NULL REFERENCES att_devices(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,status text NOT NULL DEFAULT 'pending',consent_status text NOT NULL DEFAULT 'granted',requested_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,requested_at timestamptz NOT NULL DEFAULT now(),claimed_at timestamptz,completed_at timestamptz,failure_reason text,result_profile_id text REFERENCES att_biometric_profiles(id) ON DELETE SET NULL,result_quality_score double precision,result_liveness_score double precision,updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS att_biometric_settings (organization_id text PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,algorithm_version text NOT NULL DEFAULT 'facenet-128-v1',match_threshold double precision NOT NULL DEFAULT 0.78,ambiguity_margin double precision NOT NULL DEFAULT 0.05,liveness_threshold double precision NOT NULL DEFAULT 0.70,quality_threshold double precision NOT NULL DEFAULT 0.55,updated_by text REFERENCES users(id) ON DELETE SET NULL,updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS att_biometric_template_samples (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,profile_id text NOT NULL REFERENCES att_biometric_profiles(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,sample_index integer NOT NULL,algorithm_version text NOT NULL,embedding_ciphertext text NOT NULL,embedding_iv text NOT NULL,embedding_bytes integer NOT NULL DEFAULT 0,quality_score double precision,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,person_type,person_id,sample_index));
    CREATE TABLE IF NOT EXISTS att_device_enrollment_tokens (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text NOT NULL REFERENCES att_devices(id) ON DELETE CASCADE,token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,consumed_at timestamptz,created_by text REFERENCES users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS att_device_enrollment_active_idx ON att_device_enrollment_tokens(organization_id,device_id,expires_at,consumed_at);
    CREATE TABLE IF NOT EXISTS att_mobile_reconciliation_issues (id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,event_id text NOT NULL REFERENCES att_events(id) ON DELETE CASCADE,person_type text NOT NULL,person_id text NOT NULL,attendance_date date NOT NULL,reason_code text NOT NULL,details_json text NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'pending',resolved_by text REFERENCES users(id) ON DELETE SET NULL,resolution_notes text,resolved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(event_id));
    CREATE INDEX IF NOT EXISTS att_mobile_reconciliation_org_idx ON att_mobile_reconciliation_issues(organization_id,status,attendance_date);
  `);
}

export async function finalizeAttendanceSchema(database) {
  await database.query(`
    DO $$ BEGIN
      IF to_regclass('public.mobile_sync_devices') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='att_events_mobile_sync_device_fk') THEN
        ALTER TABLE att_events ADD CONSTRAINT att_events_mobile_sync_device_fk FOREIGN KEY(mobile_sync_device_id) REFERENCES mobile_sync_devices(id) ON DELETE SET NULL;
      END IF;
    END $$;
  `);
}
