export async function ensureBooksSchema(database){await database.query(`
 CREATE TABLE IF NOT EXISTS bks_stock_movements(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,book_type text NOT NULL CHECK(book_type IN('small','a4')),movement_type text NOT NULL CHECK(movement_type IN('receipt','adjustment')),quantity_delta integer NOT NULL CHECK(quantity_delta<>0),movement_on date NOT NULL,reference_text text,notes text,recorded_by text REFERENCES users(id) ON DELETE SET NULL,reversed_at timestamptz,reversed_by text REFERENCES users(id) ON DELETE SET NULL,reversal_reason text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS bks_stock_movements_org_idx ON bks_stock_movements(organization_id,book_type,movement_on,created_at);
 CREATE INDEX IF NOT EXISTS bks_stock_movements_active_idx ON bks_stock_movements(organization_id,book_type,reversed_at);
 CREATE TABLE IF NOT EXISTS bks_distribution_batches(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,academic_year_id text REFERENCES school_academic_years(id) ON DELETE SET NULL,term_id text REFERENCES school_terms(id) ON DELETE SET NULL,class_id text NOT NULL REFERENCES school_classes(id) ON DELETE RESTRICT,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,book_type text NOT NULL CHECK(book_type IN('small','a4')),quantity_per_learner integer NOT NULL CHECK(quantity_per_learner>0),learner_count integer NOT NULL CHECK(learner_count>=0),total_quantity integer NOT NULL CHECK(total_quantity>=0),distributed_on date NOT NULL,notes text,created_by text REFERENCES users(id) ON DELETE SET NULL,reversed_at timestamptz,reversed_by text REFERENCES users(id) ON DELETE SET NULL,reversal_reason text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS bks_distribution_batches_org_idx ON bks_distribution_batches(organization_id,academic_year_id,term_id,class_id,stream_id,distributed_on);
 CREATE TABLE IF NOT EXISTS bks_distributions(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,student_id text NOT NULL REFERENCES school_students(id) ON DELETE RESTRICT,academic_year_id text REFERENCES school_academic_years(id) ON DELETE SET NULL,term_id text REFERENCES school_terms(id) ON DELETE SET NULL,class_id text REFERENCES school_classes(id) ON DELETE SET NULL,stream_id text REFERENCES school_streams(id) ON DELETE SET NULL,batch_id text REFERENCES bks_distribution_batches(id) ON DELETE SET NULL,book_type text NOT NULL CHECK(book_type IN('small','a4')),quantity integer NOT NULL CHECK(quantity>0),distributed_on date NOT NULL,source text NOT NULL DEFAULT 'individual' CHECK(source IN('individual','bulk')),notes text,distributed_by text REFERENCES users(id) ON DELETE SET NULL,reversed_at timestamptz,reversed_by text REFERENCES users(id) ON DELETE SET NULL,reversal_reason text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS bks_distributions_org_date_idx ON bks_distributions(organization_id,distributed_on,book_type);
 CREATE INDEX IF NOT EXISTS bks_distributions_student_idx ON bks_distributions(organization_id,student_id,academic_year_id,term_id,distributed_on);
 CREATE INDEX IF NOT EXISTS bks_distributions_class_idx ON bks_distributions(organization_id,class_id,stream_id,academic_year_id,term_id,distributed_on);
 CREATE INDEX IF NOT EXISTS bks_distributions_batch_idx ON bks_distributions(organization_id,batch_id);
 CREATE TABLE IF NOT EXISTS bks_mobile_operation_intents(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,device_id text,operation_type text NOT NULL CHECK(operation_type IN('stock_movement','individual_issue','bulk_issue')),payload_json text NOT NULL,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','processing','retry','applied','rejected')),server_entity_type text,server_entity_id text,result_json text,error_code text,error_message text,attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0),next_attempt_at timestamptz,created_by text NOT NULL REFERENCES users(id) ON DELETE RESTRICT,client_created_at timestamptz NOT NULL,applied_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
 CREATE INDEX IF NOT EXISTS bks_mobile_intents_pending_idx ON bks_mobile_operation_intents(status,next_attempt_at,created_at);
 CREATE INDEX IF NOT EXISTS bks_mobile_intents_user_idx ON bks_mobile_operation_intents(organization_id,created_by,created_at DESC);
 `);}
export async function finalizeBooksSchema(database){await database.query(`DO $$ BEGIN IF to_regclass('public.mobile_sync_devices') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='bks_mobile_intents_device_fk') THEN ALTER TABLE bks_mobile_operation_intents ADD CONSTRAINT bks_mobile_intents_device_fk FOREIGN KEY(device_id) REFERENCES mobile_sync_devices(id) ON DELETE SET NULL; END IF; END $$;`);}
