const PREFIX='/selfhost/attachments';
function fail(status,code,message){throw Object.assign(new Error(message),{status,code});}
async function principal(runtime,request,scope){const p=await runtime.auth.authenticateRequest({headers:request.headers});runtime.auth.requireScope(p,scope);return p;}
async function json(request,maxBytes){const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>Math.ceil(maxBytes*1.4)+65536)fail(413,'PAYLOAD_TOO_LARGE','request too large');chunks.push(chunk);}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{};}catch{fail(400,'INVALID_JSON','invalid JSON');}}
function decodeContent(value){if(typeof value!=='string'||value==='')fail(400,'ATTACHMENT_CONTENT_REQUIRED','contentBase64 is required');try{const bytes=Buffer.from(value,'base64');if(bytes.toString('base64').replace(/=+$/,'')!==value.replace(/\s+/g,'').replace(/=+$/,''))fail(400,'ATTACHMENT_INVALID_BASE64','contentBase64 is invalid');return bytes;}catch{fail(400,'ATTACHMENT_INVALID_BASE64','contentBase64 is invalid');}}
export default {name:'attachments',prefix:PREFIX,enabled(c){return c.extensions?.attachments?.enabled===true;},async handle({request,url,runtime}){const ext=runtime.extensions.attachments;if(!ext)fail(503,'ATTACHMENTS_NOT_READY','attachments not enabled');
 if(request.method==='GET'&&url.pathname===PREFIX){const p=await principal(runtime,request,'documents:read');const rows=await ext.service.list({organizationId:p.organizationId,entityType:url.searchParams.get('entityType'),entityId:url.searchParams.get('entityId'),limit:url.searchParams.get('limit'),afterCreatedAt:url.searchParams.get('afterCreatedAt'),afterId:url.searchParams.get('afterId')});return{status:200,body:{attachments:rows,next:rows.length?{afterCreatedAt:rows.at(-1).created_at,afterId:rows.at(-1).id}:null}};}
 if(request.method==='POST'&&url.pathname===PREFIX){const p=await principal(runtime,request,'documents:write');const body=await json(request,ext.maxBytes);const row=await ext.service.upload({organizationId:p.organizationId,actor:{actorType:'human',actorId:p.userId},id:body.id,originalName:body.originalName,mimeType:body.mimeType,purpose:body.purpose,entityType:body.entityType,entityId:body.entityId,bytes:decodeContent(body.contentBase64)});return{status:201,body:{attachment:row}};}
 const download=url.pathname.match(/^\/selfhost\/attachments\/([^/]+)\/download$/);if(request.method==='GET'&&download){const p=await principal(runtime,request,'documents:read');const result=await ext.service.createDownloadUrl({organizationId:p.organizationId,id:decodeURIComponent(download[1]),expiresSeconds:url.searchParams.get('expiresSeconds')});return{status:200,body:result};}
 const item=url.pathname.match(/^\/selfhost\/attachments\/([^/]+)$/);if(request.method==='GET'&&item){const p=await principal(runtime,request,'documents:read');const row=await ext.service.get({organizationId:p.organizationId,id:decodeURIComponent(item[1])});if(!row)fail(404,'ATTACHMENT_NOT_FOUND','attachment not found');return{status:200,body:{attachment:row}};}
 if(request.method==='DELETE'&&item){const p=await principal(runtime,request,'documents:write');const row=await ext.service.delete({organizationId:p.organizationId,actor:{actorType:'human',actorId:p.userId},id:decodeURIComponent(item[1])});return{status:200,body:{attachment:row}};}
 fail(404,'ATTACHMENTS_ROUTE_NOT_FOUND','attachments route not found');}};
