import {authenticateFinance,mapFinanceError,ok,readJson,requiredHeader} from '../../finance/http.mjs';
const PREFIX='/api/v1/banking',parts=url=>url.pathname.slice(PREFIX.length).split('/').filter(Boolean);
const SUPPORTED=[['GET',/^\/accounts$/],['POST',/^\/accounts$/],['GET',/^\/accounts\/[^/]+\/transactions$/],['POST',/^\/accounts\/[^/]+\/statements$/],['GET',/^\/accounts\/[^/]+\/reconciliation-statement$/],['GET',/^\/accounts\/[^/]+\/reconciliations$/],['POST',/^\/accounts\/[^/]+\/reconciliations$/],['POST',/^\/accounts\/[^/]+\/charges$/],['POST',/^\/transfers$/],['POST',/^\/transactions\/[^/]+\/match$/]];
function matches({request,url}){const relative=url.pathname.slice(PREFIX.length)||'/';return SUPPORTED.some(([method,pattern])=>request.method===method&&pattern.test(relative));}
export default{name:'finance-banking',prefix:PREFIX,business:true,priority:91,enabled:c=>c.extensions?.['finance-api']?.bankingCutover==='node',matches,async handle({request,url,runtime}){try{const api=runtime.extensions?.['finance-api']?.banking;if(!api)throw Object.assign(new Error('Finance banking runtime unavailable'),{status:503,code:'FINANCE_SELFHOST_NOT_READY'});const p=parts(url);
 if(request.method==='GET'&&p.length===1&&p[0]==='accounts'){const x=await authenticateFinance(runtime,request,'accounts:read');return ok({data:await api.listAccounts(x.organizationId)})}
 if(request.method==='POST'&&p.length===1&&p[0]==='accounts'){const x=await authenticateFinance(runtime,request,'accounts:write');return ok({data:await api.createAccount(x.organizationId,x.userId,await readJson(request))},201)}
 if(request.method==='GET'&&p.length===3&&p[0]==='accounts'&&p[2]==='transactions'){const x=await authenticateFinance(runtime,request,'accounts:read');return ok({data:await api.listTransactions(x.organizationId,p[1],{status:url.searchParams.get('status')||undefined,search:url.searchParams.get('search')||undefined})})}
 if(request.method==='POST'&&p.length===3&&p[0]==='accounts'&&p[2]==='statements'){const x=await authenticateFinance(runtime,request,'payments:write');return ok({data:await api.importStatement(x.organizationId,x.userId,p[1],await readJson(request))},201)}
 if(request.method==='GET'&&p.length===3&&p[0]==='accounts'&&p[2]==='reconciliation-statement'){const x=await authenticateFinance(runtime,request,'accounts:read');return ok({data:await api.listReconciliations(x.organizationId,p[1])})}
 if(request.method==='GET'&&p.length===3&&p[0]==='accounts'&&p[2]==='reconciliations'){const x=await authenticateFinance(runtime,request,'accounts:read');return ok({data:await api.listReconciliations(x.organizationId,p[1])})}
 if(request.method==='POST'&&p.length===3&&p[0]==='accounts'&&p[2]==='reconciliations'){const x=await authenticateFinance(runtime,request,'payments:write');return ok({data:await api.reconcile(x.organizationId,x.userId,p[1],await readJson(request))},201)}
 if(request.method==='POST'&&p.length===3&&p[0]==='accounts'&&p[2]==='charges'){const x=await authenticateFinance(runtime,request,'payments:write'),key=requiredHeader(request,'Idempotency-Key');return ok({data:await api.postCharge(x.organizationId,x.userId,p[1],await readJson(request),key)},201)}
 if(request.method==='POST'&&p.length===1&&p[0]==='transfers'){const x=await authenticateFinance(runtime,request,'payments:write'),key=requiredHeader(request,'Idempotency-Key');return ok({data:await api.transfer(x.organizationId,x.userId,await readJson(request),key)},201)}
 if(request.method==='POST'&&p.length===3&&p[0]==='transactions'&&p[2]==='match'){const x=await authenticateFinance(runtime,request,'payments:write'),body=await readJson(request);return ok({data:await api.matchTransaction(x.organizationId,x.userId,p[1],body.journalLineId)})}
 throw Object.assign(new Error('Banking route not found'),{status:404,code:'NOT_FOUND'});
 }catch(error){if(error instanceof TypeError)throw Object.assign(error,{status:422,code:'VALIDATION_ERROR'});throw mapFinanceError(error)}}};
