import {authenticateFinance,mapFinanceError,ok,pagination,readJson,requiredHeader} from '../../finance/http.mjs';
import {withFinanceIdempotencyLock} from '../../finance/idempotency-lock.mjs';
const PREFIX='/api/v1/payments',parts=url=>url.pathname.slice(PREFIX.length).split('/').filter(Boolean);
const allocationId=(key,index,documentId)=>`pal_${Buffer.from(`${key}:${index}:${documentId}`).toString('base64url').slice(0,48)}`;
async function existingAllocationRetry(database,organizationId,paymentId,allocations,key){if(!key||!Array.isArray(allocations)||!allocations.length)return null;const ids=allocations.map((x,index)=>allocationId(key,index,x.documentId));const rows=(await database.query(`SELECT id,payment_id,document_id,amount_minor,reversed_at FROM payment_allocations WHERE organization_id=$1 AND id=ANY($2::text[])`,[organizationId,ids])).rows;if(rows.length!==ids.length)return null;const byId=new Map(rows.map(row=>[row.id,row])),result=[];for(let index=0;index<allocations.length;index++){const input=allocations[index],id=ids[index],row=byId.get(id);if(!row||row.reversed_at!=null||row.payment_id!==paymentId||row.document_id!==input.documentId||BigInt(row.amount_minor)!==BigInt(input.amountMinor))throw Object.assign(new Error('Idempotency conflict'),{code:'IDEMPOTENCY_CONFLICT'});result.push({id,alreadyApplied:true});}return{id:paymentId,allocations:result,alreadyApplied:true};}
export default{name:'finance-payments',prefix:PREFIX,business:true,priority:95,enabled(config){return config.extensions?.['finance-api']?.paymentsCutover==='node'},async handle({request,url,runtime}){try{const ext=runtime.extensions?.['finance-api'],api=ext?.payments,reads=ext?.paymentsRead,reversals=ext?.reversals;if(!api||!reads||!reversals)throw Object.assign(new Error('Finance payments runtime unavailable'),{status:503,code:'FINANCE_SELFHOST_NOT_READY'});const p=parts(url);
 if(request.method==='GET'&&p.length===1&&p[0]==='manifest'){const x=await authenticateFinance(runtime,request,'payments:read');return ok({data:await reads.manifest(x.organizationId)})}
 if(request.method==='GET'&&p.length===1&&p[0]==='counterparties'){const x=await authenticateFinance(runtime,request,'payments:read');return ok({data:await reads.counterparties(x.organizationId)})}
 if(request.method==='GET'&&p.length===3&&p[0]==='counterparties'&&p[2]==='open-documents'){const x=await authenticateFinance(runtime,request,'payments:read');return ok({data:await reads.openDocuments(x.organizationId,p[1],url.searchParams.get('paymentType'))})}
 if(request.method==='GET'&&p.length===2&&p[1]==='details'){const x=await authenticateFinance(runtime,request,'payments:read');return ok({data:await reads.details(x.organizationId,p[0])})}
 if(request.method==='GET'&&p.length===0){const x=await authenticateFinance(runtime,request,'payments:read'),page=pagination(url);return ok({data:await api.list(x.organizationId,page),pagination:page})}
 if(request.method==='POST'&&p.length===0){const x=await authenticateFinance(runtime,request,'payments:write'),key=requiredHeader(request,'Idempotency-Key'),body=await readJson(request);return ok({data:await withFinanceIdempotencyLock(runtime.services.database,{organizationId:x.organizationId,namespace:'payment-create',key},()=>api.create(x.organizationId,x.userId,body,key))},201)}
 if(request.method==='POST'&&p.length===2&&p[1]==='post'){const x=await authenticateFinance(runtime,request,'payments:write'),body=await readJson(request,{optional:true});return ok({data:await api.post(x.organizationId,x.userId,p[0],body.allocations??[])})}
 if(request.method==='POST'&&p.length===2&&p[1]==='allocations'){const x=await authenticateFinance(runtime,request,'payments:write'),body=await readJson(request),key=request.headers.get('Idempotency-Key'),allocations=body.allocations??[];if(!key)return ok({data:await api.allocate(x.organizationId,x.userId,p[0],allocations,null)});return ok({data:await withFinanceIdempotencyLock(runtime.services.database,{organizationId:x.organizationId,namespace:'payment-allocate',key},async()=>await existingAllocationRetry(runtime.services.database,x.organizationId,p[0],allocations,key)??api.allocate(x.organizationId,x.userId,p[0],allocations,key))})}
 if(request.method==='POST'&&p.length===2&&(p[1]==='reverse'||p[1]==='reverse-safe')){const x=await authenticateFinance(runtime,request,'payments:write');return ok({data:await reversals.reversePayment(x.organizationId,x.userId,p[0],await readJson(request))})}
 if(request.method==='DELETE'&&p.length===1){const x=await authenticateFinance(runtime,request,'payments:write');await api.remove(x.organizationId,x.userId,p[0]);return{status:204,body:null}}
 throw Object.assign(new Error('Finance payments route not found'),{status:404,code:'NOT_FOUND'});
}catch(error){if(error instanceof TypeError)throw Object.assign(error,{status:422,code:'VALIDATION_ERROR'});throw mapFinanceError(error)}}};
