import {authenticateFinance,mapFinanceError,ok,pagination,readJson,requireNodeCutover} from '../../finance/http.mjs';
const PREFIX='/api/v1/accounts',parts=url=>url.pathname.slice(PREFIX.length).split('/').filter(Boolean);
export default{name:'finance-accounts',prefix:PREFIX,business:true,priority:95,enabled(config){return config.extensions?.['finance-api']?.referenceReadCutover==='node'},async handle({request,url,runtime}){try{const ext=runtime.extensions?.['finance-api'],api=ext?.accounts,extra=ext?.accountsExtra;if(!api||!extra)throw Object.assign(new Error('Finance accounts runtime unavailable'),{status:503,code:'FINANCE_SELFHOST_NOT_READY'});const p=parts(url);
 if(request.method==='GET'&&p.length===0){const x=await authenticateFinance(runtime,request,'accounts:read'),page=pagination(url);return ok({data:await api.list(x.organizationId,page),pagination:page})}
 if(request.method==='POST'&&p.length===0){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');return ok({data:await api.create(x.organizationId,x.userId,await readJson(request))},201)}
 if(request.method==='GET'&&p.length===1&&p[0]==='groups'){const x=await authenticateFinance(runtime,request,'accounts:read');return ok({data:await api.groups(x.organizationId)})}
 if(request.method==='POST'&&p.length===1&&p[0]==='groups'){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');return ok({data:await extra.createGroup(x.organizationId,x.userId,await readJson(request))},201)}
 if(request.method==='PUT'&&p.length===2&&p[0]==='groups'){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');return ok({data:await extra.updateGroup(x.organizationId,x.userId,p[1],await readJson(request))})}
 if(request.method==='DELETE'&&p.length===2&&p[0]==='groups'){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');await extra.removeGroup(x.organizationId,x.userId,p[1]);return{status:204,body:null}}
 if(request.method==='POST'&&p.length===1&&p[0]==='opening-balances'){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');const body=await readJson(request);return ok({data:await extra.openingBalances(x.organizationId,x.userId,body,request.headers.get('Idempotency-Key'))},201)}
 if(request.method==='POST'&&p.length===2&&p[1]==='merge'){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');const body=await readJson(request);return ok({data:await extra.merge(x.organizationId,x.userId,p[0],body.targetAccountId)})}
 if(request.method==='PUT'&&p.length===1){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');return ok({data:await api.update(x.organizationId,x.userId,p[0],await readJson(request))})}
 if(request.method==='PATCH'&&p.length===2&&p[1]==='active'){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');const body=await readJson(request);return ok({data:await api.active(x.organizationId,x.userId,p[0],body.active)})}
 if(request.method==='DELETE'&&p.length===1){const x=await authenticateFinance(runtime,request,'accounts:write');requireNodeCutover(ext,'referenceWriteCutover','FINANCE_REFERENCE_WRITE_NOT_CUT_OVER');await api.remove(x.organizationId,x.userId,p[0]);return{status:204,body:null}}
 throw Object.assign(new Error('Finance accounts route not found'),{status:404,code:'NOT_FOUND'});
}catch(error){if(error instanceof TypeError)throw Object.assign(error,{status:422,code:'VALIDATION_ERROR'});throw mapFinanceError(error)}}};
