import {authenticateFinance,mapFinanceError,ok,pagination,readJson,requireNodeCutover} from '../../finance/http.mjs';
const PREFIX='/api/v1/payroll',parts=url=>url.pathname.slice(PREFIX.length).split('/').filter(Boolean);
export default{name:'payroll-finance',prefix:PREFIX,business:true,priority:95,enabled:c=>c.extensions?.['finance-api']?.payrollReadCutover==='node',async handle({request,url,runtime,requestId}){try{const ext=runtime.extensions?.['finance-api'],api=ext?.payroll;if(!api)throw Object.assign(new Error('Payroll runtime unavailable'),{status:503,code:'FINANCE_SELFHOST_NOT_READY'});const p=parts(url),scope=request.method==='GET'?'payroll:read':'payroll:write',x=await authenticateFinance(runtime,request,scope),page=pagination(url);
if(request.method==='GET'&&p[0]==='employees'&&p.length===1)return ok({data:await api.employees(x.organizationId,page.limit),pagination:page});
if(request.method==='GET'&&p[0]==='runs'&&p.length===1)return ok({data:await api.payrollRuns(x.organizationId,page.limit),pagination:page});
if(request.method==='POST'&&p[0]==='runs'&&p.length===1){requireNodeCutover(ext,'payrollWriteCutover','PAYROLL_WRITE_NOT_CUT_OVER');return ok({data:await api.createPayrollRun({principal:x,body:await readJson(request),requestId})},201)}
if(request.method==='GET'&&p[0]==='runs'&&p.length===3&&p[2]==='lines')return ok({data:await api.payrollLines(x.organizationId,p[1],page.limit),pagination:page});
if(request.method==='POST'&&p[0]==='runs'&&p.length===3&&p[2]==='post'){requireNodeCutover(ext,'payrollWriteCutover','PAYROLL_WRITE_NOT_CUT_OVER');return ok({data:await api.linkPostedPayrollRun({principal:x,runId:p[1],body:await readJson(request),requestId})})}
if(request.method==='POST'&&p[0]==='runs'&&p.length===3&&p[2]==='reverse'){requireNodeCutover(ext,'payrollReversalCutover','PAYROLL_REVERSAL_NOT_CUT_OVER');return ok({data:await api.reversePayrollRun({principal:x,runId:p[1],body:await readJson(request),requestId})})}
if(request.method==='GET'&&p[0]==='components'&&p.length===1)return ok({data:await api.payrollComponents(x.organizationId,page.limit),pagination:page});
if(request.method==='POST'&&p[0]==='components'&&p.length===1){requireNodeCutover(ext,'payrollWriteCutover','PAYROLL_WRITE_NOT_CUT_OVER');return ok({data:await api.createPayrollComponent({principal:x,body:await readJson(request),requestId})},201)}
if(request.method==='GET'&&p[0]==='inputs'&&p.length===1)return ok({data:await api.payrollInputs(x.organizationId,page.limit),pagination:page});
if(request.method==='POST'&&p[0]==='inputs'&&p.length===1){requireNodeCutover(ext,'payrollWriteCutover','PAYROLL_WRITE_NOT_CUT_OVER');return ok({data:await api.createPayrollInput({principal:x,body:await readJson(request),requestId})},201)}
if(request.method==='POST'&&p[0]==='salary-payments'&&p.length===1){requireNodeCutover(ext,'payrollWriteCutover','PAYROLL_WRITE_NOT_CUT_OVER');return ok({data:await api.recordSalaryPayment({principal:x,body:await readJson(request),requestId})},201)}
if(request.method==='POST'&&p[0]==='salary-payments'&&p.length===3&&p[2]==='reverse'){requireNodeCutover(ext,'payrollReversalCutover','PAYROLL_REVERSAL_NOT_CUT_OVER');return ok({data:await api.reverseSalaryPayment({principal:x,paymentId:p[1],body:await readJson(request),requestId})})}
throw Object.assign(new Error('Payroll route not found'),{status:404,code:'NOT_FOUND'});}catch(error){if(error instanceof TypeError)throw Object.assign(error,{status:422,code:'VALIDATION_ERROR'});throw mapFinanceError(error)}}};
