const PREFIX='/selfhost/platform/config';
function fail(status,code,message){throw Object.assign(new Error(message),{status,code});}
async function auth(runtime,request,scope){const p=await runtime.auth.authenticateRequest({headers:request.headers});runtime.auth.requireScope(p,scope);return p;}
async function body(request){const chunks=[];for await(const c of request)chunks.push(c);try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{};}catch{fail(400,'INVALID_JSON','invalid JSON');}}
function actor(p){return{actorType:'human',actorId:p.userId};}
export default{name:'platform-config',prefix:PREFIX,enabled(c){return c.extensions?.['platform-config']?.enabled===true;},async handle({request,url,runtime}){const ext=runtime.extensions['platform-config'];if(!ext)fail(503,'PLATFORM_CONFIG_NOT_READY','platform config not enabled');
 if(request.method==='GET'&&url.pathname===`${PREFIX}/overrides`){const p=await auth(runtime,request,'admin:read');return{status:200,body:await ext.service.list({organizationId:p.organizationId,moduleKey:url.searchParams.get('moduleKey')})};}
 let m=url.pathname.match(/^\/selfhost\/platform\/config\/modules\/([^/]+)$/);if(m){const moduleKey=decodeURIComponent(m[1]);const p=await auth(runtime,request,request.method==='GET'?'admin:read':'admin:write');if(request.method==='GET'){return{status:200,body:{override:await ext.repository.getModule(p.organizationId,moduleKey)}};}if(request.method==='PUT'){const b=await body(request);return{status:200,body:{override:await ext.service.setModule({organizationId:p.organizationId,actor:actor(p),moduleKey,enabled:b.enabled,settings:b.settings,expectedVersion:b.expectedVersion??0})}};}if(request.method==='DELETE'){const b=await body(request);return{status:200,body:{cleared:await ext.service.clearModule({organizationId:p.organizationId,actor:actor(p),moduleKey,expectedVersion:b.expectedVersion})}};}}
 m=url.pathname.match(/^\/selfhost\/platform\/config\/features\/([^/]+)\/([^/]+)$/);if(m){const moduleKey=decodeURIComponent(m[1]),featureKey=decodeURIComponent(m[2]);const p=await auth(runtime,request,request.method==='GET'?'admin:read':'admin:write');if(request.method==='GET'){return{status:200,body:{override:await ext.repository.getFeature(p.organizationId,moduleKey,featureKey)}};}if(request.method==='PUT'){const b=await body(request);return{status:200,body:{override:await ext.service.setFeature({organizationId:p.organizationId,actor:actor(p),moduleKey,featureKey,enabled:b.enabled,config:b.config,expectedVersion:b.expectedVersion??0})}};}if(request.method==='DELETE'){const b=await body(request);return{status:200,body:{cleared:await ext.service.clearFeature({organizationId:p.organizationId,actor:actor(p),moduleKey,featureKey,expectedVersion:b.expectedVersion})}};}}
 fail(404,'PLATFORM_CONFIG_ROUTE_NOT_FOUND','platform config route not found');}};
