import { randomUUID } from "node:crypto";
import { recordContactSyncChange } from "./repository.mjs";

const CONTACT_TYPES=new Set(["customer","supplier","employee","other"]);
const ADDRESS_TYPES=new Set(["billing","shipping","registered","other"]);
const fail=(status,code,message,details)=>{throw Object.assign(new Error(message),{status,code,...(details===undefined?{}:{details})});};
const makeId=(prefix)=>`${prefix}_${randomUUID().replaceAll("-","")}`;
const parseJson=(value,fallback={})=>{if(value==null)return fallback;if(typeof value==="object")return value;try{return JSON.parse(String(value));}catch{return fallback;}};
const text=(value,name,{required=false,max=1000}={})=>{if(value==null||value===""){if(required)fail(422,"VALIDATION_ERROR",`${name} is required`);return null;}const out=String(value).trim();if(required&&!out)fail(422,"VALIDATION_ERROR",`${name} is required`);if(out.length>max)fail(422,"VALIDATION_ERROR",`${name} is too long`);return out||null;};
const integer=(value,name,{min=0,max=Number.MAX_SAFE_INTEGER,fallback=0}={})=>{if(value==null||value==="")return fallback;const out=Number(value);if(!Number.isSafeInteger(out)||out<min||out>max)fail(422,"VALIDATION_ERROR",`${name} is invalid`);return out;};
const email=(value,name="email")=>{const out=text(value,name,{max:254});if(out&&!/^\S+@\S+\.\S+$/.test(out))fail(422,"VALIDATION_ERROR",`${name} is invalid`);return out?.toLowerCase()??null;};
const bool=(value,fallback=false)=>value==null?fallback:Boolean(value);
const isUnique=(error)=>String(error?.code??"")==="23505"||String(error?.message??"").toLowerCase().includes("unique");

function contactInput(input,{partial=false}={}){
  const out={},has=(key)=>Object.prototype.hasOwnProperty.call(input,key);
  if(!partial||has("type")){const value=text(input.type,"type",{required:!partial,max:30});if(value&&!CONTACT_TYPES.has(value))fail(422,"VALIDATION_ERROR","Invalid contact type");out.type=value;}
  if(!partial||has("code"))out.code=text(input.code,"code",{max:30});
  if(!partial||has("name"))out.name=text(input.name,"name",{required:!partial,max:160});
  if(!partial||has("email"))out.email=email(input.email);
  if(!partial||has("taxNumber"))out.taxNumber=text(input.taxNumber,"taxNumber",{max:60});
  if(!partial||has("paymentTermsDays"))out.paymentTermsDays=integer(input.paymentTermsDays,"paymentTermsDays",{min:0,max:365,fallback:0});
  if(!partial||has("customFields")){const value=input.customFields??{};if(typeof value!=="object"||Array.isArray(value))fail(422,"VALIDATION_ERROR","customFields must be an object");out.customFields=value;}
  if(!partial||has("creditLimitMinor"))out.creditLimitMinor=integer(input.creditLimitMinor,"creditLimitMinor",{min:0,fallback:0});
  if(!partial||has("pricingTier"))out.pricingTier=text(input.pricingTier,"pricingTier",{max:60});
  if(!partial||has("active"))out.active=bool(input.active,true);
  return out;
}
function addressInput(input,{partial=false}={}){
  const out={},has=(key)=>Object.prototype.hasOwnProperty.call(input,key);
  if(!partial||has("type")){const value=text(input.type,"type",{required:!partial,max:30});if(value&&!ADDRESS_TYPES.has(value))fail(422,"VALIDATION_ERROR","Invalid address type");out.type=value;}
  if(!partial||has("line1"))out.line1=text(input.line1,"line1",{required:!partial,max:300});
  if(!partial||has("line2"))out.line2=text(input.line2,"line2",{max:300});
  if(!partial||has("city"))out.city=text(input.city,"city",{max:120});
  if(!partial||has("state"))out.state=text(input.state,"state",{max:120});
  if(!partial||has("postalCode"))out.postalCode=text(input.postalCode,"postalCode",{max:40});
  if(!partial||has("country")){const value=text(input.country,"country",{required:!partial,max:2});if(value&&value.length!==2)fail(422,"VALIDATION_ERROR","country must be a 2-letter code");out.country=value?.toUpperCase()??null;}
  if(!partial||has("isDefault"))out.isDefault=bool(input.isDefault,false);
  return out;
}
function personInput(input,{partial=false}={}){
  const out={},has=(key)=>Object.prototype.hasOwnProperty.call(input,key);
  if(!partial||has("name"))out.name=text(input.name,"name",{required:!partial,max:160});
  if(!partial||has("email"))out.email=email(input.email);
  if(!partial||has("phone"))out.phone=text(input.phone,"phone",{max:40});
  if(!partial||has("role"))out.role=text(input.role,"role",{max:80});
  if(!partial||has("isPrimary"))out.isPrimary=bool(input.isPrimary,false);
  return out;
}

export class ContactsApiService {
  constructor({database,repository,audit=null}){if(!database?.query||!database?.transaction)throw new TypeError("ContactsApiService requires database");if(!repository)throw new TypeError("ContactsApiService requires repository");this.database=database;this.repository=repository;this.audit=audit;this.provider="postgresql-contacts-api";}
  describe(){return{provider:this.provider,module:"contacts",features:["directory","enabled-module-sources","addresses","contact-people","archive-restore","merge"]};}
  async tableExists(name){const r=await this.database.query("SELECT to_regclass($1) AS t",[`public.${name}`]);return Boolean(r.rows[0]?.t);}
  async readiness(){try{const r=await this.database.query(`SELECT to_regclass('public.contacts') AS contacts,to_regclass('public.contact_addresses') AS addresses,to_regclass('public.contact_people') AS people,to_regclass('public.app_modules') AS modules,to_regclass('public.organization_modules') AS organization_modules,to_regclass('public.mobile_sync_changes') AS mobile_sync_changes`);const missing=Object.entries(r.rows[0]??{}).filter(([,v])=>!v).map(([k])=>k);return{ok:missing.length===0,provider:this.provider,missing};}catch(error){return{ok:false,provider:this.provider,error:error instanceof Error?error.message:String(error)}}}
  async enabledModules(organizationId){const r=await this.database.query(`SELECT m.module_key AS key,m.name,m.category,m.manifest_json AS "manifestJson" FROM app_modules m LEFT JOIN organization_modules om ON om.module_key=m.module_key AND om.organization_id=$1 WHERE m.active=true AND (m.core=true OR om.enabled=true) ORDER BY m.name`,[organizationId]);return r.rows.map(x=>({...x,manifest:parseJson(x.manifestJson,{})}));}
  sourceDefinition(module){if(module.key==="ledgerly-core")return{moduleKey:module.key,name:module.name,groups:["customer","supplier","employee","other"],channels:[]};if(module.key==="communications")return{moduleKey:module.key,name:module.name,groups:["sms_recipient"],channels:Array.isArray(module.manifest?.channels)?module.manifest.channels:[]};if(module.key==="school-management")return{moduleKey:module.key,name:module.name,groups:["student","guardian","staff"],channels:[]};if(module.key==="tasks-work")return{moduleKey:module.key,name:module.name,groups:["organization_user"],channels:[]};return null;}
  async capabilities(organizationId){const enabled=await this.enabledModules(organizationId);return{enabledModules:enabled.map(x=>({key:x.key,name:x.name,category:x.category})),sources:enabled.map(x=>this.sourceDefinition(x)).filter(Boolean)};}
  async people({organizationId,source=null,group=null,channel=null,search="",limit=100,offset=0}){const enabled=await this.enabledModules(organizationId),keys=new Set(enabled.map(x=>x.key)),people=[];
    if(keys.has("ledgerly-core")){const r=await this.database.query(`SELECT c.id,c.type,c.code,c.name,c.email,c.active,(SELECT cp.phone FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id ORDER BY cp.is_primary DESC,cp.created_at LIMIT 1) phone FROM contacts c WHERE c.organization_id=$1 AND c.archived_at IS NULL ORDER BY c.name`,[organizationId]);people.push(...r.rows.map(x=>({id:`ledgerly-core:${x.id}`,entityId:x.id,contactId:x.id,sourceModule:"ledgerly-core",group:x.type,name:x.name,email:x.email,phone:x.phone,code:x.code,active:Boolean(x.active)})));}
    if(keys.has("school-management")&&await this.tableExists("school_students")&&await this.tableExists("school_guardians")&&await this.tableExists("school_staff_profiles")){const [students,guardians,staff]=await Promise.all([this.database.query(`SELECT id,contact_id AS "contactId",admission_number code,TRIM(first_name||' '||COALESCE(middle_name||' ','')||last_name) name,email,phone,status FROM school_students WHERE organization_id=$1 AND deleted_at IS NULL ORDER BY last_name,first_name`,[organizationId]),this.database.query(`SELECT id,contact_id AS "contactId",TRIM(first_name||' '||COALESCE(middle_name||' ','')||last_name) name,email,phone_primary phone,active FROM school_guardians WHERE organization_id=$1 ORDER BY last_name,first_name`,[organizationId]),this.database.query(`SELECT id,contact_id AS "contactId",staff_number code,TRIM(first_name||' '||COALESCE(middle_name||' ','')||last_name) name,email,phone,employment_status status FROM school_staff_profiles WHERE organization_id=$1 AND deleted_at IS NULL ORDER BY last_name,first_name`,[organizationId])]);people.push(...students.rows.map(x=>({id:`school-management:student:${x.id}`,entityId:x.id,contactId:x.contactId,sourceModule:"school-management",group:"student",name:x.name,email:x.email,phone:x.phone,code:x.code,active:x.status==="active"})));people.push(...guardians.rows.map(x=>({id:`school-management:guardian:${x.id}`,entityId:x.id,contactId:x.contactId,sourceModule:"school-management",group:"guardian",name:x.name,email:x.email,phone:x.phone,active:Boolean(x.active)})));people.push(...staff.rows.map(x=>({id:`school-management:staff:${x.id}`,entityId:x.id,contactId:x.contactId,sourceModule:"school-management",group:"staff",name:x.name,email:x.email,phone:x.phone,code:x.code,active:x.status==="active"})));}
    if(keys.has("tasks-work")){const r=await this.database.query(`SELECT u.id,u.display_name name,u.email,u.status,m.role code FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 ORDER BY u.display_name`,[organizationId]);people.push(...r.rows.map(x=>({id:`tasks-work:${x.id}`,entityId:x.id,sourceModule:"tasks-work",group:"organization_user",name:x.name,email:x.email,code:x.code,active:x.status==="active"})));}
    if(keys.has("communications")&&await this.tableExists("communication_recipients")&&await this.tableExists("communication_preferences")){const snapshots=await this.database.query(`SELECT recipient_type AS "recipientType",recipient_id AS "entityId",recipient_name name,phone,MAX(created_at) AS "lastSeen" FROM communication_recipients WHERE organization_id=$1 AND phone IS NOT NULL AND trim(phone)<>'' GROUP BY recipient_type,recipient_id,recipient_name,phone ORDER BY recipient_name`,[organizationId]);const known=new Set(people.map(p=>`${String(p.name).toLowerCase()}|${p.phone||""}`));for(const x of snapshots.rows)if(!known.has(`${String(x.name).toLowerCase()}|${x.phone}`))people.push({id:`communications:${x.recipientType}:${x.entityId||x.phone}`,entityId:x.entityId||x.phone,sourceModule:"communications",group:"sms_recipient",name:x.name,phone:x.phone,active:true});const preferences=await this.database.query(`SELECT recipient_type AS "recipientType",recipient_id AS "recipientId",sms_enabled AS "smsEnabled",whatsapp_enabled AS "whatsappEnabled",do_not_contact AS "doNotContact" FROM communication_preferences WHERE organization_id=$1`,[organizationId]);const prefs=new Map(preferences.rows.map(x=>[`${x.recipientType}:${x.recipientId}`,x]));for(const p of people){if(!p.phone){p.channels=[];continue;}const pref=prefs.get(`${p.group}:${p.entityId}`)||prefs.get(`contact:${p.contactId}`);p.channels=pref?.doNotContact?[]:[pref?.smsEnabled===false?null:"sms",pref?.whatsappEnabled===false?null:"whatsapp"].filter(Boolean);}}
    const q=String(search||"").trim().toLowerCase(),filtered=people.filter(p=>(!source||p.sourceModule===source)&&(!group||p.group===group)&&(!channel||p.channels?.includes(channel))&&(!q||`${p.name} ${p.email||""} ${p.phone||""} ${p.code||""}`.toLowerCase().includes(q))),bounded=Math.max(1,Math.min(Number(limit)||100,1000)),start=Math.max(0,Number(offset)||0);return{items:filtered.slice(start,start+bounded),pagination:{limit:bounded,offset:start,total:filtered.length}};}
  async list({organizationId,type=null,limit=100,offset=0}){const bounded=Math.max(1,Math.min(Number(limit)||100,500)),start=Math.max(0,Number(offset)||0),values=[organizationId],where=["organization_id=$1","archived_at IS NULL"];if(type){values.push(type);where.push(`type=$${values.length}`);}values.push(bounded,start);const r=await this.database.query(`SELECT id,type,code,name,email,tax_number AS "taxNumber",payment_terms_days AS "paymentTermsDays",active,credit_limit_minor AS "creditLimitMinor",pricing_tier AS "pricingTier",custom_fields AS "customFields",created_at AS "createdAt" FROM contacts WHERE ${where.join(" AND ")} ORDER BY name LIMIT $${values.length-1} OFFSET $${values.length}`,values);return{items:r.rows.map(x=>({...x,customFields:parseJson(x.customFields,{})})),pagination:{limit:bounded,offset:start}};}
  async detail(organizationId,id,{includeArchived=true}={}){const r=await this.database.query(`SELECT id,type,code,name,email,tax_number AS "taxNumber",payment_terms_days AS "paymentTermsDays",active,credit_limit_minor AS "creditLimitMinor",pricing_tier AS "pricingTier",custom_fields AS "customFields",archived_at AS "archivedAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM contacts WHERE id=$1 AND organization_id=$2 ${includeArchived?"":"AND archived_at IS NULL"}`,[id,organizationId]);const contact=r.rows[0];if(!contact)fail(404,"NOT_FOUND","Contact not found");contact.customFields=parseJson(contact.customFields,{});const [addresses,people]=await Promise.all([this.addresses(organizationId,id),this.contactPeople(organizationId,id)]);return{contact,addresses,people};}
  async create({organizationId,userId,input,requestId}){const v=contactInput(input),contact={id:makeId("con"),...v};let row;try{row=await this.repository.create({organizationId,contact,changedBy:userId});}catch(error){if(isUnique(error))fail(409,"DUPLICATE_CONTACT","Contact already exists");throw error;}await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.created",entityType:"contact",entityId:row.id,after:v,requestId});return{id:row.id,...v};}
  async update({organizationId,userId,id,input,requestId}){const v=contactInput(input),result=await this.database.transaction(async tx=>{const before=(await tx.query("SELECT * FROM contacts WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL FOR UPDATE",[id,organizationId])).rows[0];if(!before)fail(404,"NOT_FOUND","Contact not found");const r=await tx.query(`UPDATE contacts SET type=$1,code=$2,name=$3,email=$4,tax_number=$5,payment_terms_days=$6,custom_fields=$7,credit_limit_minor=$8,pricing_tier=$9,active=$10,updated_at=now() WHERE id=$11 AND organization_id=$12 RETURNING id,type,code,name,email,tax_number AS "taxNumber",payment_terms_days AS "paymentTermsDays",active,credit_limit_minor AS "creditLimitMinor",pricing_tier AS "pricingTier",custom_fields AS "customFields"`,[v.type,v.code,v.name,v.email,v.taxNumber,v.paymentTermsDays,JSON.stringify(v.customFields),v.creditLimitMinor,v.pricingTier,v.active,id,organizationId]);const row=r.rows[0];await recordContactSyncChange(tx,{organizationId,recordId:id,payload:row,changedBy:userId});return{before,after:row};});result.after.customFields=parseJson(result.after.customFields,{});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.updated",entityType:"contact",entityId:id,before:result.before,after:result.after,requestId});return result.after;}
  async archive({organizationId,userId,id,requestId}){const result=await this.database.transaction(async tx=>{const before=(await tx.query("SELECT * FROM contacts WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL FOR UPDATE",[id,organizationId])).rows[0];if(!before)fail(404,"NOT_FOUND","Contact not found");const after=(await tx.query("UPDATE contacts SET active=false,archived_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *",[id,organizationId])).rows[0];await recordContactSyncChange(tx,{organizationId,recordId:id,payload:after,changedBy:userId});return{before,after};});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.archived",entityType:"contact",entityId:id,before:result.before,after:result.after,requestId});return{id,status:"archived"};}
  async restore({organizationId,userId,id,requestId}){const result=await this.database.transaction(async tx=>{const before=(await tx.query("SELECT * FROM contacts WHERE id=$1 AND organization_id=$2 AND archived_at IS NOT NULL FOR UPDATE",[id,organizationId])).rows[0];if(!before)fail(404,"NOT_FOUND","Archived contact not found");const after=(await tx.query("UPDATE contacts SET active=true,archived_at=NULL,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *",[id,organizationId])).rows[0];await recordContactSyncChange(tx,{organizationId,recordId:id,payload:after,changedBy:userId});return{before,after};});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.restored",entityType:"contact",entityId:id,before:result.before,after:result.after,requestId});return{id,status:"active"};}
  async archived(organizationId){return(await this.database.query(`SELECT id,type,code,name,email,archived_at AS "archivedAt" FROM contacts WHERE organization_id=$1 AND archived_at IS NOT NULL ORDER BY archived_at DESC,name`,[organizationId])).rows;}
  async remove({organizationId,userId,id,requestId}){if(await this.tableExists("documents")){const used=await this.database.query("SELECT 1 FROM documents WHERE organization_id=$1 AND contact_id=$2 LIMIT 1",[organizationId,id]);if(used.rows[0])fail(409,"CONTACT_IN_USE","Contact has financial history; archive it instead");}const result=await this.database.transaction(async tx=>{const before=(await tx.query("SELECT * FROM contacts WHERE id=$1 AND organization_id=$2 FOR UPDATE",[id,organizationId])).rows[0];if(!before)fail(404,"NOT_FOUND","Contact not found");await tx.query("DELETE FROM contacts WHERE id=$1 AND organization_id=$2",[id,organizationId]);await recordContactSyncChange(tx,{organizationId,recordId:id,payload:null,changedBy:userId,operation:"delete"});return before;});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.deleted",entityType:"contact",entityId:id,before:result,requestId});}
  async merge({organizationId,userId,sourceId,targetId,requestId}){if(sourceId===targetId)fail(422,"VALIDATION_ERROR","Invalid merge target");const tables=[];for(const [table,column] of [["documents","contact_id"],["payments","contact_id"],["journal_lines","contact_id"]])if(await this.tableExists(table))tables.push([table,column]);const result=await this.database.transaction(async tx=>{const found=await tx.query("SELECT * FROM contacts WHERE organization_id=$1 AND id=ANY($2::text[]) FOR UPDATE",[organizationId,[sourceId,targetId]]);if(found.rows.length!==2)fail(404,"NOT_FOUND","Contact not found");const source=found.rows.find(x=>x.id===sourceId),target=found.rows.find(x=>x.id===targetId);for(const [table,column] of tables)await tx.query(`UPDATE ${table} SET ${column}=$1 WHERE organization_id=$2 AND ${column}=$3`,[targetId,organizationId,sourceId]);const archived=(await tx.query("UPDATE contacts SET active=false,archived_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *",[sourceId,organizationId])).rows[0];await recordContactSyncChange(tx,{organizationId,recordId:sourceId,payload:archived,changedBy:userId});return{source,target};});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.merged",entityType:"contact",entityId:sourceId,before:result.source,after:{targetContactId:targetId},requestId});return{sourceContactId:sourceId,targetContactId:targetId,status:"merged"};}
  async addresses(organizationId,contactId){return(await this.database.query(`SELECT id,type,line1,line2,city,state,postal_code AS "postalCode",country,is_default AS "isDefault",created_at AS "createdAt",updated_at AS "updatedAt" FROM contact_addresses WHERE organization_id=$1 AND contact_id=$2 ORDER BY is_default DESC,type,line1`,[organizationId,contactId])).rows;}
  async requireContact(organizationId,id){const r=await this.database.query("SELECT 1 FROM contacts WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL",[id,organizationId]);if(!r.rows[0])fail(404,"NOT_FOUND","Contact not found");}
  async createAddress({organizationId,userId,contactId,input,requestId}){await this.requireContact(organizationId,contactId);const v=addressInput(input),addressId=makeId("adr");await this.database.transaction(async tx=>{if(v.isDefault)await tx.query("UPDATE contact_addresses SET is_default=false,updated_at=now() WHERE organization_id=$1 AND contact_id=$2 AND type=$3",[organizationId,contactId,v.type]);await tx.query("INSERT INTO contact_addresses(id,organization_id,contact_id,type,line1,line2,city,state,postal_code,country,is_default) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[addressId,organizationId,contactId,v.type,v.line1,v.line2,v.city,v.state,v.postalCode,v.country,v.isDefault]);});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.address.created",entityType:"contact_address",entityId:addressId,after:{contactId,...v},requestId});return{id:addressId,...v};}
  async updateAddress({organizationId,userId,contactId,addressId,input,requestId}){const v=addressInput(input,{partial:true});if(!Object.keys(v).length)fail(422,"VALIDATION_ERROR","No valid address changes supplied");const result=await this.database.transaction(async tx=>{const current=(await tx.query(`SELECT type,line1,line2,city,state,postal_code AS "postalCode",country,is_default AS "isDefault" FROM contact_addresses WHERE id=$1 AND contact_id=$2 AND organization_id=$3 FOR UPDATE`,[addressId,contactId,organizationId])).rows[0];if(!current)fail(404,"NOT_FOUND","Contact address not found");const next={...current,...v};if(next.isDefault)await tx.query("UPDATE contact_addresses SET is_default=false,updated_at=now() WHERE organization_id=$1 AND contact_id=$2 AND type=$3 AND id<>$4",[organizationId,contactId,next.type,addressId]);await tx.query("UPDATE contact_addresses SET type=$1,line1=$2,line2=$3,city=$4,state=$5,postal_code=$6,country=$7,is_default=$8,updated_at=now() WHERE id=$9 AND contact_id=$10 AND organization_id=$11",[next.type,next.line1,next.line2,next.city,next.state,next.postalCode,String(next.country).toUpperCase(),Boolean(next.isDefault),addressId,contactId,organizationId]);return next;});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.address.updated",entityType:"contact_address",entityId:addressId,after:{contactId,...v},requestId});return{id:addressId,...result,isDefault:Boolean(result.isDefault)};}
  async deleteAddress({organizationId,userId,contactId,addressId,requestId}){const r=await this.database.query("DELETE FROM contact_addresses WHERE id=$1 AND contact_id=$2 AND organization_id=$3 RETURNING id",[addressId,contactId,organizationId]);if(!r.rows[0])fail(404,"NOT_FOUND","Contact address not found");await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.address.deleted",entityType:"contact_address",entityId:addressId,requestId});}
  async contactPeople(organizationId,contactId){return(await this.database.query(`SELECT id,name,email,phone,role,is_primary AS "isPrimary",created_at AS "createdAt",updated_at AS "updatedAt" FROM contact_people WHERE organization_id=$1 AND contact_id=$2 ORDER BY is_primary DESC,name`,[organizationId,contactId])).rows;}
  async createPerson({organizationId,userId,contactId,input,requestId}){await this.requireContact(organizationId,contactId);const v=personInput(input),personId=makeId("cpr");await this.database.transaction(async tx=>{if(v.isPrimary)await tx.query("UPDATE contact_people SET is_primary=false,updated_at=now() WHERE organization_id=$1 AND contact_id=$2",[organizationId,contactId]);await tx.query("INSERT INTO contact_people(id,organization_id,contact_id,name,email,phone,role,is_primary) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[personId,organizationId,contactId,v.name,v.email,v.phone,v.role,v.isPrimary]);});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.person.created",entityType:"contact_person",entityId:personId,after:{contactId,...v},requestId});return{id:personId,...v};}
  async updatePerson({organizationId,userId,contactId,personId,input,requestId}){const v=personInput(input,{partial:true});if(!Object.keys(v).length)fail(422,"VALIDATION_ERROR","No valid person changes supplied");const result=await this.database.transaction(async tx=>{const current=(await tx.query(`SELECT name,email,phone,role,is_primary AS "isPrimary" FROM contact_people WHERE id=$1 AND contact_id=$2 AND organization_id=$3 FOR UPDATE`,[personId,contactId,organizationId])).rows[0];if(!current)fail(404,"NOT_FOUND","Contact person not found");const next={...current,...v};if(next.isPrimary)await tx.query("UPDATE contact_people SET is_primary=false,updated_at=now() WHERE organization_id=$1 AND contact_id=$2 AND id<>$3",[organizationId,contactId,personId]);await tx.query("UPDATE contact_people SET name=$1,email=$2,phone=$3,role=$4,is_primary=$5,updated_at=now() WHERE id=$6 AND contact_id=$7 AND organization_id=$8",[next.name,next.email?.toLowerCase()??null,next.phone,next.role,Boolean(next.isPrimary),personId,contactId,organizationId]);return next;});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.person.updated",entityType:"contact_person",entityId:personId,after:{contactId,...v},requestId});return{id:personId,...result,isPrimary:Boolean(result.isPrimary)};}
  async deletePerson({organizationId,userId,contactId,personId,requestId}){const r=await this.database.query("DELETE FROM contact_people WHERE id=$1 AND contact_id=$2 AND organization_id=$3 RETURNING id",[personId,contactId,organizationId]);if(!r.rows[0])fail(404,"NOT_FOUND","Contact person not found");await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"contact.person.deleted",entityType:"contact_person",entityId:personId,requestId});}
}

export function createContactsApiService(input){return new ContactsApiService(input);}
