// AUTO-GENERATED by scripts/sync-modules.mjs. Do not edit by hand.
export const moduleCatalog = [
  {
    "key": "academics",
    "name": "Academics",
    "version": "1.0.0",
    "description": "Teaching operations, timetables, schemes of work, lesson planning and delivery, teacher supervision, and academic record inspection.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "school-management"
      ],
      "requiresDataFrom": [
        "school-management"
      ],
      "sharedCore": [
        "school_academic_years",
        "school_terms",
        "school_departments",
        "school_classes",
        "school_streams",
        "school_subjects",
        "school_staff_profiles",
        "school_staff_teaching_assignments",
        "school_files",
        "att_sessions",
        "att_records",
        "school_students",
        "users"
      ],
      "features": [
        "class-teacher-department-timetables",
        "room-allocation",
        "single-double-lessons",
        "teacher-availability",
        "conflict-detection",
        "substitute-lessons",
        "temporary-timetable-changes",
        "timetable-approval-publishing",
        "printable-timetables",
        "workload-analysis",
        "schemes-of-work",
        "hod-dos-approval",
        "scheme-version-history",
        "lesson-plans",
        "lesson-plan-templates",
        "lesson-delivery-register",
        "coverage-tracking",
        "recovery-lessons",
        "teacher-supervision",
        "observations",
        "followups",
        "book-record-inspection",
        "evidence-attachments"
      ]
    }
  },
  {
    "key": "attendance",
    "name": "Attendance",
    "version": "1.2.0",
    "description": "Canonical student and staff attendance, devices, offline capture, biometrics, exceptions, corrections and reporting.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresModules": [
        "school-management"
      ],
      "requiresDataFrom": [
        "school-management"
      ],
      "integratesWith": [
        "academics",
        "payroll-payments",
        "communications",
        "school-management"
      ],
      "captureMethods": [
        "FACE",
        "QR",
        "NFC",
        "MANUAL",
        "TEACHER_REGISTER",
        "ADMIN_OVERRIDE",
        "IMPORT",
        "API"
      ],
      "offline": true,
      "primaryKioskPlatform": "android",
      "features": [
        "daily-attendance",
        "class-and-lesson-registers",
        "staff-time",
        "in-out-events",
        "offline-sync",
        "deduplication",
        "biometric-profiles",
        "test-spoof-controls",
        "devices",
        "exceptions",
        "corrections",
        "reports",
        "notification-rules"
      ],
      "mobileClient": "react-native-android",
      "cameraSource": "device",
      "externalCameraSupport": false,
      "deviceCameraOnly": true,
      "faceEngine": "facenet-128-v1",
      "faceDetection": "mlkit-bundled",
      "faceMatching": "on-device-1-n",
      "activeLiveness": "blink-or-head-turn",
      "encryptedTemplateSync": true,
      "faceTestOverrides": [
        "screen-image",
        "printed-image"
      ]
    }
  },
  {
    "key": "communications",
    "name": "Messages & Notifications",
    "version": "1.0.0",
    "description": "Platform-wide SMS and approved-template WhatsApp campaigns for School, Exams, Finance, Attendance, Discipline, Tasks & Work and future modules.",
    "category": "platform",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "channels": [
        "sms",
        "whatsapp"
      ],
      "whatsappTemplate": {
        "name": "general_app_update",
        "language": "en_US",
        "category": "UTILITY"
      },
      "sharedCore": [
        "organizations",
        "users",
        "memberships",
        "contacts",
        "contact_people",
        "school_students",
        "school_guardians",
        "school_staff_profiles"
      ],
      "features": [
        "message-types",
        "audience-preview",
        "fee-reminders",
        "published-results",
        "student-parent-messaging",
        "teacher-staff-messaging",
        "attendance-notices",
        "discipline-notices",
        "task-work-updates",
        "scheduled-campaigns",
        "delivery-history",
        "retry-failed",
        "recipient-preferences",
        "audit-snapshots"
      ]
    }
  },
  {
    "key": "contacts",
    "name": "Contacts",
    "version": "1.0.0",
    "description": "Shared people and organizations directory assembled from the capabilities enabled for each organization.",
    "category": "platform",
    "core": true,
    "active": true,
    "manifest": {
      "standalone": true,
      "owns": [
        "contacts",
        "contact_people",
        "contact_addresses"
      ],
      "discoversEnabledModules": true,
      "contactSources": {
        "ledgerly-core": [
          "customer",
          "supplier",
          "employee",
          "other"
        ],
        "communications": [
          "sms",
          "whatsapp"
        ],
        "school-management": [
          "student",
          "guardian",
          "staff"
        ],
        "tasks-work": [
          "organization_user"
        ]
      }
    }
  },
  {
    "key": "exams",
    "name": "Examinations",
    "version": "1.0.0",
    "description": "Standalone examinations, marks, Uganda PLE grading, report cards, academic reports and audit workflows linked to School Management shared data.",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "requiresDataFrom": [
        "school-management"
      ],
      "sharedCore": [
        "organizations",
        "users",
        "school_students",
        "school_classes",
        "school_streams",
        "school_subjects",
        "school_academic_years",
        "school_terms",
        "att_records"
      ],
      "features": [
        "exam-crud",
        "class-enrolment",
        "subject-configuration",
        "bulk-marks-entry",
        "mark-audit",
        "ple-grading",
        "best-four-aggregate",
        "division-ranking",
        "comment-rules",
        "report-cards",
        "class-marksheets",
        "academic-reports",
        "publication"
      ],
      "reportStyle": "ported-from-attached-exams-project"
    }
  },
  {
    "key": "human-resources",
    "name": "Human Resources",
    "version": "1.0.0",
    "description": "Standalone workforce, employment, departments, onboarding and leave management using people from enabled modules.",
    "category": "people",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "discoversEnabledModules": true,
      "peopleSources": {
        "contacts": [
          "employee"
        ],
        "school-management": [
          "staff"
        ],
        "tasks-work": [
          "organization_user"
        ]
      },
      "features": [
        "workforce-directory",
        "departments",
        "employment-records",
        "onboarding",
        "leave-types",
        "leave-requests",
        "approvals",
        "audit"
      ]
    }
  },
  {
    "key": "ledgerly-core",
    "name": "Ledgerly Core",
    "version": "0.2.0",
    "description": "Core accounting, finance, reporting, organization and administration capabilities.",
    "category": "core",
    "core": true,
    "active": true,
    "manifest": {
      "backendModules": [
        "accounting",
        "sales",
        "purchases",
        "banking",
        "inventory",
        "payroll",
        "reports",
        "administration"
      ]
    }
  },
  {
    "key": "payroll-payments",
    "name": "Payroll & Payments",
    "version": "1.0.0",
    "description": "Complete payroll calculation, statutory deductions, payslips, salary batches, receipts, supplier payments, allocations and reversals.",
    "category": "finance",
    "core": false,
    "active": true,
    "manifest": {
      "standalone": true,
      "discoversEnabledModules": true,
      "requiredData": [
        "contacts",
        "accounts",
        "journals"
      ],
      "optionalSources": [
        "human-resources",
        "school-management",
        "communications"
      ],
      "features": [
        "employees",
        "salary-components",
        "statutory-rules",
        "payroll-inputs",
        "calculation",
        "approval",
        "posting",
        "reversal",
        "payslips",
        "delivery",
        "payment-batches",
        "receipts",
        "supplier-payments",
        "allocations",
        "reversals",
        "webhooks"
      ]
    }
  },
  {
    "key": "school-management",
    "name": "School Management",
    "version": "1.9.0",
    "description": "School administration, fees, promotion, discipline, students, staff, identity and academic setup",
    "category": "education",
    "core": false,
    "active": true,
    "manifest": {
      "backendModules": [
        "setup",
        "iam",
        "student-management",
        "promotion-engine",
        "discipline-behaviour",
        "staff-teacher-management",
        "files",
        "fees-billing"
      ],
      "plannedModules": [
        "library",
        "boarding",
        "transport",
        "communications"
      ],
      "accountingIntegration": true,
      "integratesWith": [
        "academics",
        "attendance",
        "communications",
        "exams"
      ]
    }
  },
  {
    "key": "tasks-work",
    "name": "Tasks & Work",
    "version": "1.1.0",
    "description": "Projects, tasks and execution workflows blended with Ledgerly organizations, users, contacts, people and School staff.",
    "category": "operations",
    "core": false,
    "active": true,
    "manifest": {
      "backendModules": [
        "teams",
        "shared-contacts",
        "projects",
        "tasks",
        "subtasks",
        "assignees",
        "followers",
        "checklists",
        "comments",
        "time-tracking",
        "notifications",
        "reminders",
        "whatsapp-webhook"
      ],
      "communications": [
        "resend",
        "egosms",
        "ulib-whatsapp-hub"
      ],
      "source": "kawalyauma/tasks-work-backend",
      "sourceCommit": "19bda3eee6018bd2f5631a1353adcd71ad366da9",
      "sharedCore": [
        "organizations",
        "users",
        "memberships",
        "contacts",
        "contact_people",
        "school_staff_profiles"
      ]
    }
  }
] as const;
