import { Hono } from "hono";
import { z } from "zod";
import { SignJWT } from "jose";
import type { Env } from "../types";
import { AppError } from "../lib/errors";
import { createId } from "../lib/ids";
import { hashPassword, randomToken, sha256, verifyPassword } from "../lib/crypto";

export const authRoutes=new Hono<{Bindings:Env}>();
const register=z.object({organizationName:z.string().min(2).max(160),baseCurrency:z.string().length(3).toUpperCase().default("UGX"),name:z.string().min(2).max(160),email:z.email(),password:z.string().min(12).max(200)});
const defaultAccounts=[["1000","Cash and Bank","asset","cash","debit"],["1100","Accounts Receivable","asset","receivable","debit"],["1200","Inventory","asset","inventory","debit"],["2000","Accounts Payable","liability","payable","credit"],["2100","Tax Payable","liability","tax","credit"],["2200","Payroll Payable","liability","payroll","credit"],["3000","Owner's Equity","equity","equity","credit"],["4000","Sales Revenue","revenue","sales","credit"],["5000","Cost of Goods Sold","expense","cogs","debit"],["6000","Operating Expenses","expense","operating","debit"],["6100","Payroll Expense","expense","payroll","debit"]] as const;
authRoutes.post("/register",async c=>{const s=register.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid registration",s.error.flatten());const email=s.data.email.toLowerCase();if(await c.env.FINANCE_DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())throw new AppError(409,"EMAIL_EXISTS","Email is already registered");const orgId=createId("org"),userId=createId("usr"),passwordHash=await hashPassword(s.data.password);await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare("INSERT INTO organizations (id,name,base_currency) VALUES (?,?,?)").bind(orgId,s.data.organizationName,s.data.baseCurrency),c.env.FINANCE_DB.prepare("INSERT INTO users (id,email,display_name,password_hash,email_verified_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP)").bind(userId,email,s.data.name,passwordHash),c.env.FINANCE_DB.prepare("INSERT INTO memberships (organization_id,user_id,role,scopes) VALUES (?,?,'owner','[]')").bind(orgId,userId),...defaultAccounts.map(([code,name,type,subtype,normal])=>c.env.FINANCE_DB.prepare("INSERT INTO accounts (id,organization_id,code,name,type,subtype,normal_balance) VALUES (?,?,?,?,?,?,?)").bind(createId("acc"),orgId,code,name,type,subtype,normal))]);return c.json({data:{organizationId:orgId,userId}},201)});
const login=z.object({email:z.email(),password:z.string(),organizationId:z.string().optional()});
async function tokens(env:Env,userId:string,organizationId:string,role:string,scopes:string[],meta:{ip?:string;userAgent?:string}){const now=Math.floor(Date.now()/1000);const accessToken=await new SignJWT({org:organizationId,role,scopes}).setProtectedHeader({alg:"HS256"}).setSubject(userId).setIssuer(env.JWT_ISSUER).setAudience(env.JWT_AUDIENCE).setIssuedAt(now).setExpirationTime(now+900).sign(new TextEncoder().encode(env.JWT_SECRET));const refreshToken=randomToken(48),sessionId=createId("ses");await env.FINANCE_DB.prepare("INSERT INTO sessions (id,user_id,organization_id,refresh_token_hash,expires_at,ip_address,user_agent) VALUES (?,?,?,?,datetime('now','+30 days'),?,?)").bind(sessionId,userId,organizationId,await sha256(refreshToken),meta.ip??null,meta.userAgent??null).run();return{accessToken,expiresIn:900,refreshToken,sessionId}}
authRoutes.post("/login",async c=>{const s=login.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid login",s.error.flatten());const user=await c.env.FINANCE_DB.prepare("SELECT id,password_hash AS passwordHash,status FROM users WHERE email=?").bind(s.data.email.toLowerCase()).first<{id:string;passwordHash:string|null;status:string}>();if(!user?.passwordHash||user.status!=="active"||!await verifyPassword(s.data.password,user.passwordHash))throw new AppError(401,"INVALID_CREDENTIALS","Invalid email or password");const membership=await c.env.FINANCE_DB.prepare(`SELECT organization_id AS organizationId,role,scopes FROM memberships WHERE user_id=? ${s.data.organizationId?"AND organization_id=?":""} ORDER BY created_at LIMIT 1`).bind(user.id,...(s.data.organizationId?[s.data.organizationId]:[])).first<{organizationId:string;role:string;scopes:string}>();if(!membership)throw new AppError(403,"NO_MEMBERSHIP","No organization membership found");return c.json({data:await tokens(c.env,user.id,membership.organizationId,membership.role,JSON.parse(membership.scopes),{ip:c.req.header("CF-Connecting-IP"),userAgent:c.req.header("User-Agent")})})});
authRoutes.post("/refresh",async c=>{const body=await c.req.json<{refreshToken?:string}>();if(!body.refreshToken)throw new AppError(422,"REFRESH_TOKEN_REQUIRED","Refresh token required");const hash=await sha256(body.refreshToken);const session=await c.env.FINANCE_DB.prepare(`SELECT s.id,s.user_id AS userId,s.organization_id AS organizationId,m.role,m.scopes FROM sessions s JOIN memberships m ON m.user_id=s.user_id AND m.organization_id=s.organization_id WHERE s.refresh_token_hash=? AND s.revoked_at IS NULL AND s.expires_at>CURRENT_TIMESTAMP`).bind(hash).first<{id:string;userId:string;organizationId:string;role:string;scopes:string}>();if(!session)throw new AppError(401,"INVALID_REFRESH_TOKEN","Refresh token is invalid or expired");await c.env.FINANCE_DB.prepare("UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE id=?").bind(session.id).run();return c.json({data:await tokens(c.env,session.userId,session.organizationId,session.role,JSON.parse(session.scopes),{ip:c.req.header("CF-Connecting-IP"),userAgent:c.req.header("User-Agent")})})});
authRoutes.post("/logout",async c=>{const body=await c.req.json<{refreshToken?:string}>();if(body.refreshToken)await c.env.FINANCE_DB.prepare("UPDATE sessions SET revoked_at=CURRENT_TIMESTAMP WHERE refresh_token_hash=? AND revoked_at IS NULL").bind(await sha256(body.refreshToken)).run();return c.body(null,204)});
