import { randomUUID } from "node:crypto";

const TYPES=new Set(["permanent","contract","part_time","casual","intern","volunteer"]);
const STATUSES=new Set(["active","on_leave","suspended","terminated","resigned","retired","inactive"]);
const fail=(status,code,message,details)=>{throw Object.assign(new Error(message),{status,code,...(details===undefined?{}:{details})});};
const newId=(prefix)=>`${prefix}_${randomUUID().replaceAll("-","")}`;
const decode=(value,fallback={})=>{if(value==null)return fallback;if(typeof value==="object")return value;try{return JSON.parse(String(value));}catch{return fallback;}};
const txt=(value,name,{required=false,max=1000}={})=>{if(value==null||value===""){if(required)fail(422,"VALIDATION_ERROR",`${name} is required`);return null;}const out=String(value).trim();if(required&&!out)fail(422,"VALIDATION_ERROR",`${name} is required`);if(out.length>max)fail(422,"VALIDATION_ERROR",`${name} is too long`);return out||null;};
const isoDate=(value,name,required=false)=>{const out=txt(value,name,{required,max:10});if(out==null)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(out)||Number.isNaN(Date.parse(`${out}T00:00:00Z`)))fail(422,"VALIDATION_ERROR",`${name} must be YYYY-MM-DD`);return out;};
const num=(value,name,{required=false,min=-Infinity,max=Infinity}={})=>{if(value==null||value===""){if(required)fail(422,"VALIDATION_ERROR",`${name} is required`);return null;}const out=Number(value);if(!Number.isFinite(out)||out<min||out>max)fail(422,"VALIDATION_ERROR",`${name} is invalid`);return out;};
const bool=(value,fallback=true)=>value==null?fallback:Boolean(value);
const isUnique=(error)=>String(error?.code??"")==="23505"||String(error?.message??"").toLowerCase().includes("unique");

export class HumanResourcesApiService {
  constructor({database,audit=null}){if(!database?.query||!database?.transaction)throw new TypeError("HumanResourcesApiService requires database");this.database=database;this.audit=audit;this.provider="postgresql-human-resources-api";}
  describe(){return{provider:this.provider,module:"human-resources",features:["workforce","departments","onboarding","leave","audit"]};}
  async readiness(){try{const r=await this.database.query(`SELECT to_regclass('public.hr_employees') AS employees,to_regclass('public.hr_departments') AS departments,to_regclass('public.hr_leave_types') AS leave_types,to_regclass('public.hr_leave_requests') AS leave_requests,to_regclass('public.hr_onboarding_tasks') AS onboarding,to_regclass('public.organization_modules') AS modules`);const missing=Object.entries(r.rows[0]??{}).filter(([,v])=>!v).map(([k])=>k);return{ok:missing.length===0,provider:this.provider,missing};}catch(error){return{ok:false,provider:this.provider,error:error instanceof Error?error.message:String(error)}}}
  async tableExists(name){const r=await this.database.query("SELECT to_regclass($1) AS t",[`public.${name}`]);return Boolean(r.rows[0]?.t);}
  async requireEnabled(organizationId){const r=await this.database.query(`SELECT 1 FROM app_modules m LEFT JOIN organization_modules om ON om.module_key=m.module_key AND om.organization_id=$1 WHERE m.module_key='human-resources' AND m.active=true AND (m.core=true OR om.enabled=true) LIMIT 1`,[organizationId]);if(!r.rows[0])fail(404,"MODULE_DISABLED","Human Resources is not enabled for this organization");}
  async enabledModules(organizationId){const r=await this.database.query(`SELECT m.module_key AS key,m.name FROM app_modules m LEFT JOIN organization_modules om ON om.module_key=m.module_key AND om.organization_id=$1 WHERE m.active=true AND (m.core=true OR om.enabled=true) ORDER BY m.name`,[organizationId]);return r.rows;}
  async manifest(organizationId){return{key:"human-resources",name:"Human Resources",version:"1.0.0",enabledModules:await this.enabledModules(organizationId),features:["workforce","departments","onboarding","leave","audit"]};}
  async dashboard(organizationId){const r=await this.database.query(`SELECT (SELECT count(*) FROM hr_employees WHERE organization_id=$1) employees,(SELECT count(*) FROM hr_employees WHERE organization_id=$1 AND employment_status='active') active,(SELECT count(*) FROM hr_departments WHERE organization_id=$1 AND active=true) departments,(SELECT count(*) FROM hr_leave_requests WHERE organization_id=$1 AND status='pending') leave,(SELECT count(*) FROM hr_onboarding_tasks WHERE organization_id=$1 AND status='pending') onboarding`,[organizationId]);const x=r.rows[0]??{};return{employees:Number(x.employees||0),activeEmployees:Number(x.active||0),departments:Number(x.departments||0),pendingLeave:Number(x.leave||0),pendingOnboarding:Number(x.onboarding||0)};}
  async people(organizationId){const modules=new Set((await this.enabledModules(organizationId)).map(x=>x.key)),people=[];
    if(modules.has("contacts")&&await this.tableExists("contacts")&&await this.tableExists("contact_people")){const r=await this.database.query(`SELECT c.id,c.name,c.email,cp.phone FROM contacts c LEFT JOIN contact_people cp ON cp.organization_id=c.organization_id AND cp.contact_id=c.id AND cp.is_primary=true WHERE c.organization_id=$1 AND c.type='employee' AND c.active=true AND c.archived_at IS NULL ORDER BY c.name`,[organizationId]);people.push(...r.rows.map(x=>({sourceModule:"contacts",sourceType:"employee_contact",sourceId:x.id,contactId:x.id,name:x.name,email:x.email,phone:x.phone})))}
    if(modules.has("school-management")&&await this.tableExists("school_staff_profiles")){const r=await this.database.query(`SELECT id,contact_id AS "contactId",user_id AS "userId",staff_number AS code,TRIM(first_name||' '||COALESCE(middle_name||' ','')||last_name) name,email,phone FROM school_staff_profiles WHERE organization_id=$1 AND employment_status='active' AND deleted_at IS NULL ORDER BY last_name,first_name`,[organizationId]);people.push(...r.rows.map(x=>({...x,sourceModule:"school-management",sourceType:"school_staff",sourceId:x.id,schoolStaffId:x.id})))}
    if(modules.has("tasks-work")){const r=await this.database.query(`SELECT u.id,u.display_name name,u.email FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND u.status='active' ORDER BY u.display_name`,[organizationId]);people.push(...r.rows.map(x=>({...x,sourceModule:"tasks-work",sourceType:"organization_user",sourceId:x.id,userId:x.id})))}
    const linked=await this.database.query(`SELECT id,user_id AS "userId",contact_id AS "contactId",school_staff_id AS "schoolStaffId" FROM hr_employees WHERE organization_id=$1`,[organizationId]);for(const p of people){const row=linked.rows.find(x=>(p.userId&&x.userId===p.userId)||(p.contactId&&x.contactId===p.contactId)||(p.schoolStaffId&&x.schoolStaffId===p.schoolStaffId));p.hrEmployeeId=row?.id??null;}return people;}
  async employees(organizationId){const school=await this.tableExists("school_staff_profiles");const schoolJoin=school?"LEFT JOIN school_staff_profiles sp ON sp.id=e.school_staff_id AND sp.organization_id=e.organization_id":"";const schoolName=school?"TRIM(sp.first_name||' '||sp.last_name)":"NULL::text";const schoolEmail=school?"sp.email":"NULL::text";const schoolPhone=school?"sp.phone":"NULL::text";const r=await this.database.query(`SELECT e.*,d.name department_name,m.employee_number manager_number,COALESCE(c.name,${schoolName},u.display_name) name,COALESCE(e.work_email,c.email,${schoolEmail},u.email) email,COALESCE(e.work_phone,${schoolPhone}) phone FROM hr_employees e LEFT JOIN hr_departments d ON d.id=e.department_id AND d.organization_id=e.organization_id LEFT JOIN hr_employees m ON m.id=e.manager_employee_id AND m.organization_id=e.organization_id LEFT JOIN contacts c ON c.id=e.contact_id AND c.organization_id=e.organization_id ${schoolJoin} LEFT JOIN users u ON u.id=e.user_id WHERE e.organization_id=$1 ORDER BY e.employee_number`,[organizationId]);return r.rows.map(x=>({...x,metadata:decode(x.metadata_json,{})}));}
  normalizeEmployee(input,{partial=false}={}){const out={};const has=(k)=>Object.prototype.hasOwnProperty.call(input,k);const set=(k,v)=>{if(!partial||has(k))out[k]=v};set("userId",txt(input.userId,"userId",{max:120}));set("contactId",txt(input.contactId,"contactId",{max:120}));set("schoolStaffId",txt(input.schoolStaffId,"schoolStaffId",{max:120}));set("departmentId",txt(input.departmentId,"departmentId",{max:120}));set("employeeNumber",txt(input.employeeNumber,"employeeNumber",{required:!partial,max:40}));set("jobTitle",txt(input.jobTitle,"jobTitle",{max:120}));if(!partial||has("employmentType")){const v=txt(input.employmentType??(partial?null:"permanent"),"employmentType",{required:!partial,max:30});if(v&&!TYPES.has(v))fail(422,"VALIDATION_ERROR","Invalid employmentType");out.employmentType=v;}if(!partial||has("employmentStatus")){const v=txt(input.employmentStatus??(partial?null:"active"),"employmentStatus",{required:!partial,max:30});if(v&&!STATUSES.has(v))fail(422,"VALIDATION_ERROR","Invalid employmentStatus");out.employmentStatus=v;}if(!partial||has("hireDate"))out.hireDate=isoDate(input.hireDate,"hireDate",!partial);if(!partial||has("terminationDate"))out.terminationDate=isoDate(input.terminationDate,"terminationDate");set("managerEmployeeId",txt(input.managerEmployeeId,"managerEmployeeId",{max:120}));if(!partial||has("workEmail")){const v=txt(input.workEmail,"workEmail",{max:254});if(v&&!/^\S+@\S+\.\S+$/.test(v))fail(422,"VALIDATION_ERROR","workEmail is invalid");out.workEmail=v?.toLowerCase()??null;}set("workPhone",txt(input.workPhone,"workPhone",{max:60}));if(!partial||has("metadata")){const v=input.metadata??{};if(typeof v!=="object"||Array.isArray(v))fail(422,"VALIDATION_ERROR","metadata must be an object");out.metadata=v;}return out;}
  async validateEmployeeRefs(organizationId,v,selfId=null){const checks=[];if(v.userId)checks.push(this.database.query("SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$2",[organizationId,v.userId]).then(r=>["userId",r.rows[0]]));if(v.contactId)checks.push(this.database.query("SELECT 1 FROM contacts WHERE organization_id=$1 AND id=$2",[organizationId,v.contactId]).then(r=>["contactId",r.rows[0]]));if(v.schoolStaffId){if(!await this.tableExists("school_staff_profiles"))fail(422,"INVALID_REFERENCE","School Management staff data is not available");checks.push(this.database.query("SELECT 1 FROM school_staff_profiles WHERE organization_id=$1 AND id=$2",[organizationId,v.schoolStaffId]).then(r=>["schoolStaffId",r.rows[0]]));}if(v.departmentId)checks.push(this.database.query("SELECT 1 FROM hr_departments WHERE organization_id=$1 AND id=$2",[organizationId,v.departmentId]).then(r=>["departmentId",r.rows[0]]));if(v.managerEmployeeId)checks.push(this.database.query("SELECT 1 FROM hr_employees WHERE organization_id=$1 AND id=$2",[organizationId,v.managerEmployeeId]).then(r=>["managerEmployeeId",r.rows[0]]));for(const [k,ok] of await Promise.all(checks))if(!ok)fail(422,"INVALID_REFERENCE",`${k} does not belong to this organization`);if(selfId&&v.managerEmployeeId===selfId)fail(422,"INVALID_MANAGER","An employee cannot be their own manager");}
  async createEmployee({organizationId,userId,input,requestId}){const v=this.normalizeEmployee(input);if(!v.userId&&!v.contactId&&!v.schoolStaffId)fail(422,"VALIDATION_ERROR","Select a person from an enabled module");await this.validateEmployeeRefs(organizationId,v);const employeeId=newId("hre");try{await this.database.query(`INSERT INTO hr_employees(id,organization_id,user_id,contact_id,school_staff_id,department_id,employee_number,job_title,employment_type,employment_status,hire_date,termination_date,manager_employee_id,work_email,work_phone,metadata_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)`,[employeeId,organizationId,v.userId,v.contactId,v.schoolStaffId,v.departmentId,v.employeeNumber,v.jobTitle,v.employmentType,v.employmentStatus,v.hireDate,v.terminationDate,v.managerEmployeeId,v.workEmail,v.workPhone,JSON.stringify(v.metadata)]);}catch(e){if(isUnique(e))fail(409,"DUPLICATE_EMPLOYEE","Employee number or linked person is already in Human Resources");throw e;}await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.employee.created",entityType:"hr_employee",entityId:employeeId,after:v,requestId});return{id:employeeId,...v};}
  async updateEmployee({organizationId,userId,employeeId,input,requestId}){const v=this.normalizeEmployee(input,{partial:true}),map={departmentId:"department_id",jobTitle:"job_title",employmentType:"employment_type",employmentStatus:"employment_status",hireDate:"hire_date",terminationDate:"termination_date",managerEmployeeId:"manager_employee_id",workEmail:"work_email",workPhone:"work_phone"},entries=Object.entries(v).filter(([k])=>map[k]);if(!entries.length)fail(422,"VALIDATION_ERROR","No editable fields supplied");await this.validateEmployeeRefs(organizationId,v,employeeId);const values=entries.map(([,x])=>x??null);values.push(employeeId,organizationId);const r=await this.database.query(`UPDATE hr_employees SET ${entries.map(([k],i)=>`${map[k]}=$${i+1}`).join(",")},updated_at=now() WHERE id=$${entries.length+1} AND organization_id=$${entries.length+2} RETURNING *`,values);if(!r.rows[0])fail(404,"NOT_FOUND","HR employee not found");await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.employee.updated",entityType:"hr_employee",entityId:employeeId,after:v,requestId});return{...r.rows[0],metadata:decode(r.rows[0].metadata_json,{})};}
  async departments(organizationId){return(await this.database.query(`SELECT id,code,name,manager_employee_id AS "managerEmployeeId",active FROM hr_departments WHERE organization_id=$1 ORDER BY name`,[organizationId])).rows;}
  async manager(organizationId,id){if(!id)return;const r=await this.database.query("SELECT 1 FROM hr_employees WHERE id=$1 AND organization_id=$2",[id,organizationId]);if(!r.rows[0])fail(422,"INVALID_MANAGER","Manager must be an HR employee in this organization");}
  departmentInput(input,{partial=false}={}){const out={},has=k=>Object.prototype.hasOwnProperty.call(input,k);if(!partial||has("code"))out.code=txt(input.code,"code",{required:!partial,max:40});if(!partial||has("name"))out.name=txt(input.name,"name",{required:!partial,max:120});if(!partial||has("managerEmployeeId"))out.managerEmployeeId=txt(input.managerEmployeeId,"managerEmployeeId",{max:120});if(!partial||has("active"))out.active=bool(input.active,true);return out;}
  async createDepartment({organizationId,userId,input,requestId}){const v=this.departmentInput(input);await this.manager(organizationId,v.managerEmployeeId);const departmentId=newId("hrd");try{await this.database.query("INSERT INTO hr_departments(id,organization_id,code,name,manager_employee_id,active) VALUES($1,$2,$3,$4,$5,$6)",[departmentId,organizationId,v.code,v.name,v.managerEmployeeId,v.active]);}catch(e){if(isUnique(e))fail(409,"DUPLICATE_DEPARTMENT_CODE","Department code already exists");throw e;}await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.department.created",entityType:"hr_department",entityId:departmentId,after:v,requestId});return{id:departmentId,...v};}
  async updateDepartment({organizationId,userId,departmentId,input,requestId}){const v=this.departmentInput(input,{partial:true}),map={code:"code",name:"name",managerEmployeeId:"manager_employee_id",active:"active"},entries=Object.entries(v);if(!entries.length)fail(422,"VALIDATION_ERROR","No department changes supplied");await this.manager(organizationId,v.managerEmployeeId);const values=entries.map(([,x])=>x??null);values.push(departmentId,organizationId);let r;try{r=await this.database.query(`UPDATE hr_departments SET ${entries.map(([k],i)=>`${map[k]}=$${i+1}`).join(",")},updated_at=now() WHERE id=$${entries.length+1} AND organization_id=$${entries.length+2} RETURNING id,code,name,manager_employee_id AS "managerEmployeeId",active`,values);}catch(e){if(isUnique(e))fail(409,"DUPLICATE_DEPARTMENT_CODE","Department code already exists");throw e;}if(!r.rows[0])fail(404,"NOT_FOUND","HR department not found");await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.department.updated",entityType:"hr_department",entityId:departmentId,after:r.rows[0],requestId});return r.rows[0];}
  async leaveTypes(organizationId){const r=await this.database.query(`SELECT id,code,name,paid,annual_days_micros/1000000.0 AS "annualDays",active FROM hr_leave_types WHERE organization_id=$1 ORDER BY name`,[organizationId]);return r.rows.map(x=>({...x,annualDays:Number(x.annualDays)}));}
  leaveTypeInput(input,{partial=false}={}){const out={},has=k=>Object.prototype.hasOwnProperty.call(input,k);if(!partial||has("code"))out.code=txt(input.code,"code",{required:!partial,max:40});if(!partial||has("name"))out.name=txt(input.name,"name",{required:!partial,max:120});if(!partial||has("paid"))out.paid=bool(input.paid,true);if(!partial||has("annualDays"))out.annualDays=num(input.annualDays??(partial?null:0),"annualDays",{required:!partial,min:0,max:366});if(!partial||has("active"))out.active=bool(input.active,true);return out;}
  async createLeaveType({organizationId,userId,input,requestId}){const v=this.leaveTypeInput(input),leaveTypeId=newId("hlt");try{await this.database.query("INSERT INTO hr_leave_types(id,organization_id,code,name,paid,annual_days_micros,active) VALUES($1,$2,$3,$4,$5,$6,$7)",[leaveTypeId,organizationId,v.code,v.name,v.paid,Math.round(v.annualDays*1e6),v.active]);}catch(e){if(isUnique(e))fail(409,"DUPLICATE_LEAVE_TYPE_CODE","Leave type code already exists");throw e;}await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.leave_type.created",entityType:"hr_leave_type",entityId:leaveTypeId,after:v,requestId});return{id:leaveTypeId,...v};}
  async updateLeaveType({organizationId,userId,leaveTypeId,input,requestId}){const v=this.leaveTypeInput(input,{partial:true}),map={code:"code",name:"name",paid:"paid",annualDays:"annual_days_micros",active:"active"},entries=Object.entries(v);if(!entries.length)fail(422,"VALIDATION_ERROR","No leave type changes supplied");const values=entries.map(([k,x])=>k==="annualDays"?Math.round(Number(x)*1e6):x);values.push(leaveTypeId,organizationId);let r;try{r=await this.database.query(`UPDATE hr_leave_types SET ${entries.map(([k],i)=>`${map[k]}=$${i+1}`).join(",")},updated_at=now() WHERE id=$${entries.length+1} AND organization_id=$${entries.length+2} RETURNING id,code,name,paid,annual_days_micros/1000000.0 AS "annualDays",active`,values);}catch(e){if(isUnique(e))fail(409,"DUPLICATE_LEAVE_TYPE_CODE","Leave type code already exists");throw e;}if(!r.rows[0])fail(404,"NOT_FOUND","Leave type not found");const row={...r.rows[0],annualDays:Number(r.rows[0].annualDays)};await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.leave_type.updated",entityType:"hr_leave_type",entityId:leaveTypeId,after:row,requestId});return row;}
  async leaveRequests(organizationId){const school=await this.tableExists("school_staff_profiles"),join=school?"LEFT JOIN school_staff_profiles sp ON sp.id=e.school_staff_id AND sp.organization_id=e.organization_id":"",schoolName=school?"TRIM(sp.first_name||' '||sp.last_name)":"NULL::text";const r=await this.database.query(`SELECT r.id,r.employee_id AS "employeeId",e.employee_number AS "employeeNumber",COALESCE(c.name,u.display_name,${schoolName}) AS "employeeName",t.name AS "leaveType",r.starts_on AS "startsOn",r.ends_on AS "endsOn",r.days_micros/1000000.0 AS days,r.reason,r.status,r.review_notes AS "reviewNotes",r.created_at AS "createdAt" FROM hr_leave_requests r JOIN hr_employees e ON e.id=r.employee_id AND e.organization_id=r.organization_id JOIN hr_leave_types t ON t.id=r.leave_type_id AND t.organization_id=r.organization_id LEFT JOIN contacts c ON c.id=e.contact_id AND c.organization_id=e.organization_id LEFT JOIN users u ON u.id=e.user_id ${join} WHERE r.organization_id=$1 ORDER BY r.created_at DESC`,[organizationId]);return r.rows.map(x=>({...x,days:Number(x.days)}));}
  async createLeave({organizationId,userId,input,requestId}){const employeeId=txt(input.employeeId,"employeeId",{required:true,max:120}),leaveTypeId=txt(input.leaveTypeId,"leaveTypeId",{required:true,max:120}),startsOn=isoDate(input.startsOn,"startsOn",true),endsOn=isoDate(input.endsOn,"endsOn",true);if(startsOn>endsOn)fail(422,"VALIDATION_ERROR","Leave end date must not be before its start date");const days=num(input.days,"days",{required:true,min:Number.EPSILON,max:366}),reason=txt(input.reason,"reason",{max:1000}),leaveId=newId("hlr");const r=await this.database.query(`SELECT EXISTS(SELECT 1 FROM hr_employees WHERE id=$2 AND organization_id=$1) employee,EXISTS(SELECT 1 FROM hr_leave_types WHERE id=$3 AND organization_id=$1 AND active=true) leave_type`,[organizationId,employeeId,leaveTypeId]);if(!r.rows[0]?.employee)fail(422,"INVALID_REFERENCE","Employee does not belong to this organization");if(!r.rows[0]?.leave_type)fail(422,"INVALID_REFERENCE","Leave type does not belong to this organization or is inactive");await this.database.query(`INSERT INTO hr_leave_requests(id,organization_id,employee_id,leave_type_id,starts_on,ends_on,days_micros,reason,requested_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[leaveId,organizationId,employeeId,leaveTypeId,startsOn,endsOn,Math.round(days*1e6),reason,userId]);const after={id:leaveId,status:"pending",employeeId,leaveTypeId,startsOn,endsOn,days,reason};await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.leave.requested",entityType:"hr_leave_request",entityId:leaveId,after,requestId});return after;}
  async decideLeave({organizationId,userId,leaveId,decision,notes,requestId}){if(!["approve","reject"].includes(decision))fail(404,"NOT_FOUND","Unknown leave decision");const status=decision==="approve"?"approved":"rejected",reviewNotes=txt(notes,"notes",{max:1000});const result=await this.database.transaction(async tx=>{const before=(await tx.query(`SELECT * FROM hr_leave_requests WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[leaveId,organizationId])).rows[0];if(!before)fail(404,"NOT_FOUND","Leave request not found");if(before.status!=="pending")fail(409,"INVALID_STATE","Only pending leave requests can be reviewed");const after=(await tx.query(`UPDATE hr_leave_requests SET status=$1,reviewed_by=$2,reviewed_at=now(),review_notes=$3,updated_at=now() WHERE id=$4 AND organization_id=$5 AND status='pending' RETURNING *`,[status,userId,reviewNotes,leaveId,organizationId])).rows[0];if(!after)fail(409,"INVALID_STATE","Leave request is no longer pending");return{before,after};});await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:status==="approved"?"hr.leave.approved":"hr.leave.rejected",entityType:"hr_leave_request",entityId:leaveId,before:result.before,after:result.after,reason:reviewNotes,requestId});return{id:leaveId,status};}
  async onboarding(organizationId){return(await this.database.query(`SELECT t.*,e.employee_number FROM hr_onboarding_tasks t JOIN hr_employees e ON e.id=t.employee_id AND e.organization_id=t.organization_id WHERE t.organization_id=$1 ORDER BY t.status,t.due_date NULLS LAST,t.created_at`,[organizationId])).rows;}
  async createOnboarding({organizationId,userId,input,requestId}){const employeeId=txt(input.employeeId,"employeeId",{required:true,max:120}),title=txt(input.title,"title",{required:true,max:200}),dueDate=isoDate(input.dueDate,"dueDate"),assignedUserId=txt(input.assignedUserId,"assignedUserId",{max:120}),taskId=newId("hot");const r=await this.database.query(`SELECT EXISTS(SELECT 1 FROM hr_employees WHERE id=$2 AND organization_id=$1) employee,CASE WHEN $3::text IS NULL THEN true ELSE EXISTS(SELECT 1 FROM memberships WHERE organization_id=$1 AND user_id=$3) END assigned`,[organizationId,employeeId,assignedUserId]);if(!r.rows[0]?.employee)fail(422,"INVALID_REFERENCE","Employee does not belong to this organization");if(!r.rows[0]?.assigned)fail(422,"INVALID_REFERENCE","Assigned user does not belong to this organization");await this.database.query("INSERT INTO hr_onboarding_tasks(id,organization_id,employee_id,title,due_date,assigned_user_id) VALUES($1,$2,$3,$4,$5,$6)",[taskId,organizationId,employeeId,title,dueDate,assignedUserId]);const after={id:taskId,status:"pending",employeeId,title,dueDate,assignedUserId};await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:"hr.onboarding.created",entityType:"hr_onboarding_task",entityId:taskId,after,requestId});return after;}
  async setOnboardingStatus({organizationId,userId,taskId,status,requestId}){if(!["pending","completed"].includes(status))fail(422,"VALIDATION_ERROR","status must be pending or completed");const r=await this.database.query(`UPDATE hr_onboarding_tasks SET status=$1,completed_at=CASE WHEN $1='completed' THEN COALESCE(completed_at,now()) ELSE NULL END,updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING *`,[status,taskId,organizationId]);if(!r.rows[0])fail(404,"NOT_FOUND","Onboarding task not found");await this.audit?.write({organizationId,actorType:"human",actorId:userId,action:status==="completed"?"hr.onboarding.completed":"hr.onboarding.reopened",entityType:"hr_onboarding_task",entityId:taskId,after:r.rows[0],requestId});return r.rows[0];}
  async auditEvents(organizationId,limit=50){const bounded=Math.min(200,Math.max(1,Number(limit)||50));const r=await this.database.query(`SELECT a.id,a.action,a.entity_type AS "entityType",a.entity_id AS "entityId",a.after_data AS after,a.occurred_at AS "createdAt",COALESCE(u.display_name,u.email,a.actor_id) AS "actorName" FROM ledgerly_meta.audit_events a LEFT JOIN users u ON u.id=a.actor_id WHERE a.organization_id=$1 AND (a.action LIKE 'hr.%' OR a.entity_type LIKE 'hr_%') ORDER BY a.occurred_at DESC,a.created_at DESC LIMIT $2`,[organizationId,bounded]);return r.rows.map(x=>({...x,after:decode(x.after,x.after??null)}));}
}

export function createHumanResourcesApiService(input){return new HumanResourcesApiService(input);}
