import{useEffect,useState,type ReactNode,type ComponentType}from"react";
import{BarChart3,Bell,BookOpen,Boxes,Building2,ChevronDown,ChevronRight,CircleDollarSign,FileBarChart,FileKey,FileText,HeartPulse,Landmark,LayoutDashboard,LogOut,Menu,ReceiptText,Search,Settings,ShoppingCart,Users,WalletCards,X}from"lucide-react";
import{get,post,can,type Principal,type Session}from"../api";import{useAuth}from"../auth";
type Item={label:string;path:string;scope?:string;admin?:boolean};type Group={label:string;icon:ComponentType<{size?:number}>;items:Item[]};
const groups:Group[]=[
 {label:"Overview",icon:LayoutDashboard,items:[{label:"Dashboard",path:"dashboards",scope:"reports:read"}]},
 {label:"Sales",icon:CircleDollarSign,items:[{label:"Customers",path:"contacts",scope:"contacts:read"},{label:"Invoices & credits",path:"sales",scope:"documents:read"},{label:"Receivables",path:"receivables",scope:"reports:read"},{label:"Customer payments",path:"payments",scope:"payments:read"}]},
 {label:"Purchases",icon:ShoppingCart,items:[{label:"Bills & supplier credits",path:"purchasing",scope:"documents:read"},{label:"Expenses",path:"expenses",scope:"documents:read"},{label:"Approvals",path:"approvals",scope:"documents:read"},{label:"Recurring transactions",path:"recurring",scope:"documents:read"}]},
 {label:"Banking",icon:Landmark,items:[{label:"Bank accounts",path:"banking",scope:"payments:read"},{label:"Reconciliation",path:"banking",scope:"payments:read"}]},
 {label:"Accounting",icon:BookOpen,items:[{label:"Chart of accounts",path:"accounts",scope:"accounts:read"},{label:"Journals",path:"journals",scope:"journals:read"},{label:"Opening balances",path:"opening-balances",scope:"accounts:write"},{label:"Account groups",path:"account-groups",scope:"accounts:read"},{label:"Dimensions",path:"dimensions",scope:"accounts:read"},{label:"Fiscal periods & closing",path:"closing",scope:"periods:read"},{label:"Tax",path:"tax",scope:"accounts:read"}]},
 {label:"Inventory",icon:Boxes,items:[{label:"Products & services",path:"products",scope:"products:read"},{label:"Stock management",path:"inventory",scope:"products:read"}]},
 {label:"Payroll",icon:Users,items:[{label:"Employees & payroll",path:"payroll",scope:"payroll:read"}]},
 {label:"Reports",icon:FileBarChart,items:[{label:"Financial reports",path:"reports",scope:"reports:read"},{label:"Report library",path:"report-library",scope:"reports:read"},{label:"Budgets & forecasts",path:"budgets",scope:"reports:read"},{label:"Projects & time",path:"projects",scope:"documents:read"},{label:"Documents & delivery",path:"document-delivery",scope:"documents:read"}]},
 {label:"Settings",icon:Settings,items:[{label:"Organization",path:"organization",scope:"admin:read"},{label:"Team members",path:"team",scope:"admin:read",admin:true},{label:"API keys",path:"api-keys",scope:"admin:read",admin:true},{label:"Integrations",path:"integrations",scope:"admin:read"},{label:"Audit & compliance",path:"compliance",scope:"admin:read"},{label:"System status",path:"system-status"}]},
];
const allowed=(i:Item,p:Principal|null)=>(!i.scope||can(p,i.scope))&&(!i.admin||!!p&&["owner","admin"].includes(p.role));
function NavGroup({group,active,principal,onNavigate}:{group:Group;active:string;principal:Principal|null;onNavigate:(p:string)=>void}){const items=group.items.filter(i=>allowed(i,principal)),hasActive=items.some(i=>i.path===active),[open,setOpen]=useState(hasActive);useEffect(()=>{if(hasActive)setOpen(true)},[hasActive]);if(!items.length)return null;const Icon=group.icon;if(items.length===1)return <button className={`nav-parent ${hasActive?"active":""}`} onClick={()=>onNavigate(items[0]!.path)}><Icon size={18}/><span>{group.label}</span></button>;return <div className={`nav-group ${hasActive?"current":""}`}><button className="nav-parent" aria-expanded={open} onClick={()=>setOpen(!open)}><Icon size={18}/><span>{group.label}</span>{open?<ChevronDown size={15}/>:<ChevronRight size={15}/>}</button>{open&&<div className="nav-children">{items.map(i=><button key={`${i.path}-${i.label}`} className={i.path===active?"active":""} onClick={()=>onNavigate(i.path)}><span>{i.label}</span></button>)}</div>}</div>}
type Org={id:string;name:string};
export function AppShell({children,active,onNavigate}:{children:ReactNode;active:string;onNavigate:(p:string)=>void}){const[mobile,setMobile]=useState(false),[account,setAccount]=useState(false),[orgs,setOrgs]=useState<Org[]>([]),[switching,setSwitching]=useState(false),[name,setName]=useState("Current user");const{principal,login,logout}=useAuth();useEffect(()=>{get<Org[]>("/organizations").then(setOrgs).catch(()=>{});if(can(principal,"admin:read"))get<Array<{userId:string;displayName:string}>>("/admin/memberships").then(x=>setName(x.find(m=>m.userId===principal?.userId)?.displayName||"Current user")).catch(()=>{})},[principal]);async function switchOrg(id:string){if(id===principal?.organizationId)return;setSwitching(true);try{const s=await post<Session>("/organizations/switch",{organizationId:id});localStorage.setItem("finance.activeOrganization",id);login(s,localStorage.getItem("finance.remember")!=="false");location.reload()}finally{setSwitching(false)}}const navigate=(p:string)=>{onNavigate(p);setMobile(false)};return <div className="app-shell">{mobile&&<button className="scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}<aside className={`sidebar modern-sidebar ${mobile?"sidebar--open":""}`}><div className="brand"><span className="brand__mark"><BarChart3 size={20}/></span><span>ledgerly</span><button className="mobile-close" onClick={()=>setMobile(false)}><X size={19}/></button></div><div className="org-switch"><span>Workspace</span><select aria-label="Active organization" disabled={switching} value={principal?.organizationId||""} onChange={e=>void switchOrg(e.target.value)}>{orgs.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></div><nav className="nav-list modern-nav" aria-label="Main navigation">{groups.map(g=><NavGroup key={g.label} group={g} active={active} principal={principal} onNavigate={navigate}/>)}</nav><div className="sidebar-footer"><small>Finance workspace</small><span>API v1 · Connected</span></div></aside><div className="workspace"><header className="topbar"><button className="menu-button" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={20}/></button><label className="global-search"><Search size={18}/><input placeholder="Search finance workspace…"/></label><div className="topbar__actions"><button className="icon-button" aria-label="Notifications"><Bell size={19}/></button><div className="account-wrap"><button className="profile" onClick={()=>setAccount(!account)}><span className="avatar">{name.slice(0,2).toUpperCase()}</span><span><strong>{name}</strong><small>{principal?.role}</small></span><ChevronDown size={14}/></button>{account&&<div className="account-menu"><p><b>{principal?.role}</b><small>{principal?.scopes.length?principal.scopes.join(", "):"Full organization access"}</small></p><button onClick={logout}><LogOut size={15}/> Log out</button></div>}</div></div></header><main>{children}</main></div></div>}
