import {randomUUID} from 'node:crypto';
import {policyApplies} from './batch-service.mjs';
import {PrinterlyRuntimeError,projectedExceeded} from './runtime-service.mjs';

const id=p=>`${p}_${randomUUID().replaceAll('-','')}`;
const arr=v=>Array.isArray(v)?v.map(String).filter(Boolean):[];
const json=(v,f)=>{try{return v?JSON.parse(String(v)):f}catch{return f}};
const clamp=(v,min,max,f)=>{const n=Math.round(Number(v));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):f};
const action=v=>({block:Boolean(v?.block),blockMessage:String(v?.blockMessage||'This print request is blocked by an organization Printerly policy.').slice(0,500),requireApproval:Boolean(v?.requireApproval),approverRoles:arr(v?.approverRoles).length?arr(v.approverRoles):['owner','admin'],approverUserIds:arr(v?.approverUserIds),allowSelfApproval:Boolean(v?.allowSelfApproval),forceDuplex:Boolean(v?.forceDuplex),forceMonochrome:Boolean(v?.forceMonochrome),forceSecureRelease:Boolean(v?.forceSecureRelease),printerId:v?.printerId?String(v.printerId):null,priority:v?.priority?String(v.priority):null});

export class PrinterlyJobService{
  constructor({database,runtime}){if(!database?.query||!database?.transaction)throw new TypeError('database is required');if(!runtime)throw new TypeError('runtime is required');this.database=database;this.runtime=runtime;}

  async list(organizationId,limit=100){return(await this.database.query(`SELECT j.id,j.job_number "jobNumber",j.title,j.status,j.priority,j.copies,j.page_size "pageSize",j.color_mode "colorMode",j.duplex,j.secure_release "secureRelease",j.total_sheets "totalSheets",j.printer_id "printerId",j.node_id "nodeId",j.error_message "errorMessage",j.created_at "createdAt",j.completed_at "completedAt",j.source_module "sourceModule",j.source_reference "sourceReference",j.charge_project_id "projectId",j.charge_department_type "departmentType",j.charge_department_id "departmentId",j.estimated_pages "estimatedPages",j.estimated_impressions "estimatedImpressions",j.estimated_sheets "estimatedSheets",j.actual_impressions "actualImpressions",j.actual_sheets "actualSheets",j.estimated_cost_minor "estimatedCostMinor",j.actual_cost_minor "actualCostMinor",d.original_name "documentName",d.mime_type "documentMime",cp.journal_entry_id "journalEntryId" FROM prn_jobs j LEFT JOIN prn_documents d ON d.id=j.document_id AND d.organization_id=j.organization_id LEFT JOIN prn_cost_postings cp ON cp.job_id=j.id AND cp.organization_id=j.organization_id WHERE j.organization_id=$1 ORDER BY j.created_at DESC LIMIT $2`,[organizationId,clamp(limit,1,300,100)])).rows;}

  async submit({principal,body,idempotencyKey}){
    const organizationId=String(principal.organizationId),userId=String(principal.userId),documentId=String(body?.documentId||'').trim(),key=String(idempotencyKey||'').trim();
    if(!documentId)throw new PrinterlyRuntimeError('VALIDATION_ERROR','Upload a document before creating the print job');
    if(!key)throw new TypeError('idempotencyKey is required internally');
    return this.database.transaction(async tx=>{
      const duplicate=(await tx.query(`SELECT id,job_number "jobNumber",status FROM prn_jobs WHERE organization_id=$1 AND idempotency_key=$2`,[organizationId,key])).rows[0];
      if(duplicate)return{...duplicate,alreadyCreated:true};
      const doc=(await tx.query(`SELECT id,mime_type,checksum_sha256,status FROM prn_documents WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[documentId,organizationId])).rows[0];
      if(!doc||doc.status!=='staged')throw new PrinterlyRuntimeError('DOCUMENT_UNAVAILABLE','The uploaded document is missing, expired, or already attached');
      let options=this.#options(body),prepared=await this.#prepare(tx,organizationId,options),policy=await this.#policy(tx,organizationId,principal,options,prepared);
      if(policy.blocked)throw new PrinterlyRuntimeError('PRINT_POLICY_BLOCKED',policy.blockedReason,{rules:policy.applied});
      options=this.#options({...options,...policy.effective});prepared=await this.#prepare(tx,organizationId,options);
      if(options.printerId&&!((await tx.query(`SELECT id FROM prn_printers WHERE id=$1 AND organization_id=$2`,[options.printerId,organizationId])).rows[0]))throw new PrinterlyRuntimeError('INVALID_PRINTER','Selected printer does not belong to this organization');
      const jobId=id('prnjob'),jobNumber=`PRT-${new Date().getUTCFullYear()}-${jobId.slice(-8).toUpperCase()}`;
      const quota=await this.#reserve(tx,{organizationId,userId,jobId,prepared,periodKey:new Date().toISOString().slice(0,7)});
      const status=policy.requiresApproval?'approval_pending':options.secureRelease?'held':'queued',sourceModule=body?.sourceModule?String(body.sourceModule).slice(0,80):null,sourceReference=body?.sourceReference?String(body.sourceReference).slice(0,500):null;
      await tx.query(`INSERT INTO prn_jobs(id,organization_id,job_number,title,document_url,document_id,document_mime,document_sha256,printer_id,status,priority,copies,page_size,color_mode,duplex,secure_release,total_sheets,created_by,source_module,source_reference,idempotency_key,charge_project_id,charge_department_type,charge_department_id,estimated_pages,estimated_impressions,estimated_sheets,estimated_cost_minor) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28)`,[jobId,organizationId,jobNumber,String(body?.title||'Print job').trim().slice(0,200),`printerly-document:${documentId}`,documentId,doc.mime_type,doc.checksum_sha256,options.printerId,status,options.priority,options.copies,options.pageSize,options.colorMode,options.duplex,options.secureRelease,prepared.estimatedSheets,userId,sourceModule,sourceReference,key,prepared.projectId,prepared.departmentType,prepared.departmentId,prepared.estimatedPages,prepared.estimatedImpressions,prepared.estimatedSheets,prepared.estimatedCostMinor]);
      const attached=await tx.query(`UPDATE prn_documents SET status='attached',job_id=$1,attached_at=now() WHERE id=$2 AND organization_id=$3 AND status='staged'`,[jobId,documentId,organizationId]);if(attached.rowCount!==1)throw new PrinterlyRuntimeError('DOCUMENT_RACE','Document changed while the print job was being created');
      let approval=null;if(policy.requiresApproval){approval={id:id('prnappr'),status:'pending',jobId};await tx.query(`INSERT INTO prn_approvals(id,organization_id,job_id,rule_ids_json,status,requested_by,approver_roles_json,approver_user_ids_json,allow_self_approval) VALUES($1,$2,$3,$4,'pending',$5,$6,$7,$8)`,[approval.id,organizationId,jobId,JSON.stringify(policy.ruleIds),userId,JSON.stringify(policy.approverRoles),JSON.stringify(policy.approverUserIds),policy.allowSelfApproval]);}
      await tx.query(`INSERT INTO prn_job_events(id,organization_id,job_id,event_type,actor_id,details_json) VALUES($1,$2,$3,$4,$5,$6)`,[id('prnev'),organizationId,jobId,policy.requiresApproval?'approval_requested':'created',userId,JSON.stringify({status,appliedRules:policy.applied})]);
      if(status==='queued')await tx.query(`INSERT INTO prn_dispatch_outbox(id,organization_id,job_id,event_type,status,available_at) VALUES($1,$2,$3,'dispatch','pending',now()) ON CONFLICT(organization_id,job_id,event_type) DO NOTHING`,[id('prnout'),organizationId,jobId]);
      return{id:jobId,jobNumber,status,alreadyCreated:false,costing:{...prepared,estimate:{totalCostMinor:prepared.estimatedCostMinor}},quota,policy:{blocked:false,requiresApproval:policy.requiresApproval,applied:policy.applied,effective:policy.effective},approval};
    });
  }

  async release({organizationId,userId,jobId}){return this.runtime.releaseHeldJob({organizationId,userId,jobId});}
  async cancel({organizationId,userId,jobId}){
    const state=(await this.database.query(`SELECT status FROM prn_jobs WHERE id=$1 AND organization_id=$2`,[jobId,organizationId])).rows[0];
    if(state?.status!=='approval_pending')return this.runtime.cancelJob({organizationId,userId,jobId});
    return this.database.transaction(async tx=>{const job=(await tx.query(`SELECT id,status FROM prn_jobs WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[jobId,organizationId])).rows[0];if(!job)throw new PrinterlyRuntimeError('JOB_NOT_FOUND','Print job not found');if(job.status!=='approval_pending')throw new PrinterlyRuntimeError('INVALID_STATE','Approval job changed before cancellation');await tx.query(`UPDATE prn_approvals SET status='cancelled',decided_by=$1,decided_at=now(),decision_note='Cancelled by requester or administrator' WHERE organization_id=$2 AND job_id=$3 AND status='pending'`,[userId,organizationId,jobId]);await this.#releaseQuota(tx,organizationId,jobId);await tx.query(`UPDATE prn_jobs SET status='cancelled',updated_at=now() WHERE id=$1 AND organization_id=$2`,[jobId,organizationId]);await tx.query(`INSERT INTO prn_job_events(id,organization_id,job_id,event_type,actor_id,details_json) VALUES($1,$2,$3,'cancelled',$4,'{}')`,[id('prnev'),organizationId,jobId,userId]);return{id:jobId,status:'cancelled'};});
  }

  #options(body={}){return{printerId:body.printerId?String(body.printerId):null,copies:clamp(body.copies,1,1000,1),estimatedPages:clamp(body.estimatedPages,1,10000,1),priority:new Set(['urgent','high','normal','bulk']).has(String(body.priority))?String(body.priority):'normal',pageSize:new Set(['A4','A5','Letter','Legal']).has(String(body.pageSize))?String(body.pageSize):'A4',colorMode:String(body.colorMode)==='color'?'color':'monochrome',duplex:Boolean(body.duplex),secureRelease:Boolean(body.secureRelease),projectId:body.projectId?String(body.projectId):null,departmentType:body.departmentId?(String(body.departmentType)==='school'?'school':'finance'):null,departmentId:body.departmentId?String(body.departmentId):null,sourceModule:body.sourceModule?String(body.sourceModule):null};}
  async #prepare(tx,org,o){if(o.projectId&&!((await tx.query(`SELECT 1 FROM projects WHERE id=$1 AND organization_id=$2 AND status='active'`,[o.projectId,org])).rows[0]))throw new PrinterlyRuntimeError('INVALID_PROJECT','Selected project is invalid');if(o.departmentId){const school=o.departmentType==='school',table=school?'school_departments':'dimensions',extra=school?'active=true':`type='department' AND active=true`;if(!((await tx.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2 AND ${extra}`,[o.departmentId,org])).rows[0]))throw new PrinterlyRuntimeError('INVALID_DEPARTMENT','Selected department is invalid');}const p=(await tx.query(`SELECT * FROM prn_cost_profiles WHERE organization_id=$1`,[org])).rows[0]||{},impressions=o.estimatedPages*o.copies,sheets=o.duplex?Math.ceil(impressions/2):impressions,total=sheets*Number(p.paper_cost_minor||0)+impressions*(Number(o.colorMode==='color'?p.color_toner_cost_minor||0:p.bw_toner_cost_minor||0)+Number(p.maintenance_cost_minor||0)+Number(p.electricity_cost_minor||0));return{projectId:o.projectId,departmentType:o.departmentType,departmentId:o.departmentId,estimatedPages:o.estimatedPages,estimatedImpressions:impressions,estimatedSheets:sheets,estimatedCostMinor:total};}
  async #policy(tx,org,principal,o,p){const rules=(await tx.query(`SELECT id,name,priority,match_json,action_json FROM prn_print_rules WHERE organization_id=$1 AND active=true ORDER BY priority,created_at`,[org])).rows,effective={...o},applied=[],roles=new Set(),users=new Set(),ruleIds=[];let blocked=false,blockedReason='',requiresApproval=false,allowSelfApproval=true,route=false,forcedPriority=false;for(const r of rules){const a=action(json(r.action_json,{}));if(!policyApplies(json(r.match_json,{}),principal,o,p))continue;applied.push({id:r.id,name:r.name,priority:r.priority});if(a.block&&!blocked){blocked=true;blockedReason=a.blockMessage;}if(a.requireApproval){requiresApproval=true;ruleIds.push(r.id);a.approverRoles.forEach(x=>roles.add(x));a.approverUserIds.forEach(x=>users.add(x));if(!a.allowSelfApproval)allowSelfApproval=false;}if(a.forceDuplex)effective.duplex=true;if(a.forceMonochrome)effective.colorMode='monochrome';if(a.forceSecureRelease)effective.secureRelease=true;if(a.printerId&&!route){effective.printerId=a.printerId;route=true;}if(a.priority&&!forcedPriority){effective.priority=a.priority;forcedPriority=true;}}if(requiresApproval&&!roles.size&&!users.size){roles.add('owner');roles.add('admin');}return{blocked,blockedReason,requiresApproval,effective,applied,ruleIds,approverRoles:[...roles],approverUserIds:[...users],allowSelfApproval};}
  async #reserve(tx,{organizationId,userId,jobId,prepared,periodKey}){const clauses=[`scope_type='organization'`],values=[organizationId];let n=2;clauses.push(`(scope_type='user' AND scope_id=$${n++})`);values.push(userId);if(prepared.projectId){clauses.push(`(scope_type='project' AND scope_id=$${n++})`);values.push(prepared.projectId);}if(prepared.departmentId){clauses.push(`(scope_type='${prepared.departmentType==='school'?'school':'finance'}_department' AND scope_id=$${n++})`);values.push(prepared.departmentId);}const rows=(await tx.query(`SELECT * FROM prn_quotas WHERE organization_id=$1 AND active=true AND (${clauses.join(' OR ')}) ORDER BY CASE mode WHEN 'hard' THEN 0 ELSE 1 END,id`,values)).rows,out=[];for(const q of rows){await tx.query(`INSERT INTO prn_quota_periods(quota_id,organization_id,period_key) VALUES($1,$2,$3) ON CONFLICT(quota_id,period_key) DO NOTHING`,[q.id,organizationId,periodKey]);const period=(await tx.query(`SELECT * FROM prn_quota_periods WHERE quota_id=$1 AND period_key=$2 AND organization_id=$3 FOR UPDATE`,[q.id,periodKey,organizationId])).rows[0],request={impressions:prepared.estimatedImpressions,sheets:prepared.estimatedSheets,costMinor:prepared.estimatedCostMinor};if(q.mode==='hard'&&projectedExceeded(q,period,request))throw new PrinterlyRuntimeError('PRINTERLY_QUOTA_EXCEEDED',`${q.name} would exceed its monthly Printerly limit`,{quotaId:q.id,periodKey});await tx.query(`UPDATE prn_quota_periods SET reserved_impressions=reserved_impressions+$1,reserved_sheets=reserved_sheets+$2,reserved_cost_minor=reserved_cost_minor+$3,updated_at=now() WHERE quota_id=$4 AND period_key=$5`,[request.impressions,request.sheets,request.costMinor,q.id,periodKey]);await tx.query(`INSERT INTO prn_quota_reservations(id,group_id,organization_id,quota_id,period_key,job_id,reserved_impressions,reserved_sheets,reserved_cost_minor,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'reserved')`,[id('prnqres'),`job:${jobId}`,organizationId,q.id,periodKey,jobId,request.impressions,request.sheets,request.costMinor]);out.push({quotaId:q.id,mode:q.mode});}return{periodKey,quotas:out};}
  async #releaseQuota(tx,organizationId,jobId){const rows=(await tx.query(`SELECT * FROM prn_quota_reservations WHERE organization_id=$1 AND job_id=$2 AND status='reserved' FOR UPDATE`,[organizationId,jobId])).rows;for(const r of rows){await tx.query(`UPDATE prn_quota_periods SET reserved_impressions=GREATEST(0,reserved_impressions-$1),reserved_sheets=GREATEST(0,reserved_sheets-$2),reserved_cost_minor=GREATEST(0,reserved_cost_minor-$3),updated_at=now() WHERE quota_id=$4 AND period_key=$5`,[r.reserved_impressions,r.reserved_sheets,r.reserved_cost_minor,r.quota_id,r.period_key]);await tx.query(`UPDATE prn_quota_reservations SET status='released',updated_at=now() WHERE id=$1`,[r.id]);}}
}
