import {randomUUID} from 'node:crypto';
import {tenantStorageKey} from '../contracts.mjs';

const id=p=>`${p}_${randomUUID().replaceAll('-','')}`;
const json=(value,fallback)=>{try{return value?JSON.parse(String(value)):fallback}catch{return fallback}};
const category=type=>({printer:'printer',node:'node',scanner:'scanner',scan_job:'scan_job',print_job:'print_job',maintenance:'maintenance',consumable:'supplies'})[type]||'other';
const priority=severity=>severity==='critical'?'p1':severity==='warning'?'p2':'p3';

export class PrinterlyMaintenanceService{
  constructor({database,storage,runtime}){if(!database?.query||!database?.transaction)throw new TypeError('database is required');if(!storage?.delete)throw new TypeError('storage is required');this.database=database;this.storage=storage;this.runtime=runtime;}

  async health(organizationId){
    const stale=await this.database.query(`SELECT id,name,location,last_seen_at FROM prn_nodes WHERE organization_id=$1 AND revoked_at IS NULL AND status='online' AND (last_seen_at IS NULL OR last_seen_at<now()-interval '90 seconds') LIMIT 200`,[organizationId]);
    for(const node of stale.rows)await this.database.transaction(async tx=>{await tx.query(`UPDATE prn_nodes SET status='offline',updated_at=now() WHERE id=$1 AND organization_id=$2`,[node.id,organizationId]);await tx.query(`UPDATE prn_printers SET status='offline',health_status='critical',health_message='Printerly Node is offline',updated_at=now() WHERE node_id=$1 AND organization_id=$2`,[node.id,organizationId]);await tx.query(`UPDATE prn_scanners SET status='offline',updated_at=now() WHERE node_id=$1 AND organization_id=$2`,[node.id,organizationId]);await this.#alert(tx,{organizationId,fingerprint:`node-offline:${node.id}`,eventType:'printerly.node_offline',severity:'critical',title:`Printerly Node offline · ${node.name}`,body:`${node.name}${node.location?` (${node.location})`:''} has stopped reporting to Ledgerly.`,entityType:'node',entityId:node.id,details:{lastSeenAt:node.last_seen_at}});});
    return{staleNodes:stale.rows.length};
  }

  async releaseCleanup(organizationId){
    const attempts=await this.database.query(`DELETE FROM prn_release_attempt_log WHERE organization_id=$1 AND created_at<now()-interval '30 days'`,[organizationId]);
    const credentials=await this.database.query(`DELETE FROM prn_release_credentials WHERE organization_id=$1 AND (used_at IS NOT NULL OR revoked_at IS NOT NULL OR expires_at<now()) AND created_at<now()-interval '90 days'`,[organizationId]);
    return{attempts:attempts.rowCount||0,credentials:credentials.rowCount||0};
  }

  async routing(organizationId){
    const jobs=await this.database.query(`SELECT j.id,j.route_pool_id,p.strategy FROM prn_jobs j JOIN prn_printer_pools p ON p.id=j.route_pool_id AND p.organization_id=j.organization_id WHERE j.organization_id=$1 AND j.status='queued' AND j.route_pool_id IS NOT NULL AND (j.printer_id IS NULL OR NOT EXISTS(SELECT 1 FROM prn_printers x WHERE x.id=j.printer_id AND x.organization_id=j.organization_id AND x.status='ready')) ORDER BY j.created_at LIMIT 100`,[organizationId]);let routed=0;
    for(const job of jobs.rows){const chosen=(await this.database.query(`SELECT p.id,p.name FROM prn_printer_pool_members m JOIN prn_printers p ON p.id=m.printer_id AND p.organization_id=m.organization_id WHERE m.organization_id=$1 AND m.pool_id=$2 AND m.enabled=true AND p.status='ready' ORDER BY CASE WHEN $3='priority_load' THEN m.priority ELSE 0 END,(SELECT COUNT(*) FROM prn_jobs j WHERE j.organization_id=p.organization_id AND j.printer_id=p.id AND j.status IN ('queued','claimed','downloading','spooling','printing')),m.priority,p.name LIMIT 1`,[organizationId,job.route_pool_id,job.strategy])).rows[0];if(!chosen)continue;const moved=await this.database.query(`UPDATE prn_jobs SET printer_id=$1,route_strategy=$2,route_reason='Self-hosted pool routing',routed_at=now(),updated_at=now() WHERE id=$3 AND organization_id=$4 AND status='queued'`,[chosen.id,job.strategy,job.id,organizationId]);routed+=moved.rowCount||0;}
    return{routed};
  }

  async batchStatus(organizationId){
    const batches=await this.database.query(`SELECT id FROM prn_batches WHERE organization_id=$1 AND status IN ('dispatching','active','partial') ORDER BY updated_at LIMIT 100`,[organizationId]);
    for(const batch of batches.rows){const r=(await this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE i.status='pending')::int pending,COUNT(*) FILTER(WHERE i.status='dispatching')::int dispatching,COUNT(*) FILTER(WHERE i.status='failed')::int failed,COUNT(*) FILTER(WHERE j.status='completed')::int completed,COUNT(*) FILTER(WHERE j.status IN ('queued','held','approval_pending','claimed','downloading','spooling','printing'))::int active,COUNT(*) FILTER(WHERE j.status IN ('failed','cancelled'))::int bad FROM prn_batch_items i LEFT JOIN prn_jobs j ON j.id=i.job_id AND j.organization_id=i.organization_id WHERE i.organization_id=$1 AND i.batch_id=$2`,[organizationId,batch.id])).rows[0];const total=Number(r.total||0),pending=Number(r.pending||0),dispatching=Number(r.dispatching||0),failed=Number(r.failed||0),completed=Number(r.completed||0),active=Number(r.active||0),bad=Number(r.bad||0);let status='dispatching',done=false;if(!total){status='failed';done=true}else if(pending||dispatching)status='dispatching';else if(active)status='active';else if(completed===total){status='completed';done=true}else if(completed>0){status='partial';done=true}else if(failed+bad>=total){status='failed';done=true}else{status='partial';done=true}await this.database.query(`UPDATE prn_batches SET status=$1,completed_at=CASE WHEN $2 THEN COALESCE(completed_at,now()) ELSE NULL END,updated_at=now() WHERE id=$3 AND organization_id=$4 AND status<>'cancelled'`,[status,done,batch.id,organizationId]);}
    return{batches:batches.rows.length};
  }

  async batchDispatch(organizationId){
    await this.database.query(`UPDATE prn_batch_items SET status='pending',claim_token=NULL,claim_expires_at=NULL,updated_at=now() WHERE organization_id=$1 AND status='dispatching' AND claim_expires_at<now()`,[organizationId]);
    const batches=await this.database.query(`SELECT * FROM prn_batches WHERE organization_id=$1 AND status IN ('scheduled','ready','dispatching') AND (scheduled_at IS NULL OR scheduled_at<=now()) ORDER BY COALESCE(scheduled_at,created_at),created_at LIMIT 8`,[organizationId]);let submitted=0,failed=0;
    for(const batch of batches.rows){const member=(await this.database.query(`SELECT role FROM memberships WHERE organization_id=$1 AND user_id=$2`,[organizationId,batch.created_by])).rows[0];if(!member){await this.database.query(`UPDATE prn_batches SET status='failed',last_error='Batch creator is no longer an organization member',completed_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2`,[batch.id,organizationId]);continue;}await this.database.query(`UPDATE prn_batches SET status='dispatching',started_at=COALESCE(started_at,now()),last_error=NULL,updated_at=now() WHERE id=$1 AND organization_id=$2`,[batch.id,organizationId]);const items=await this.database.query(`SELECT i.*,d.status document_status FROM prn_batch_items i JOIN prn_documents d ON d.id=i.document_id AND d.organization_id=i.organization_id WHERE i.organization_id=$1 AND i.batch_id=$2 AND i.status='pending' ORDER BY i.sort_order,i.created_at LIMIT 25`,[organizationId,batch.id]);const defaults=json(batch.defaults_json,{});for(const item of items.rows){try{if(item.document_status!=='staged')throw new Error('Batch document is no longer staged');const settings={...defaults,...json(item.settings_json,{})};const result=await this.runtime.createJob({organizationId,userId:batch.created_by,documentId:item.document_id,idempotencyKey:`printerly-batch:${batch.id}:${item.id}`,title:item.title,copies:settings.copies||1,estimatedPages:settings.estimatedPages||1,priority:settings.priority||'normal',pageSize:settings.pageSize||'A4',colorMode:settings.colorMode||'monochrome',duplex:Boolean(settings.duplex),secureRelease:Boolean(settings.secureRelease),printerId:settings.printerId||null,projectId:settings.projectId||null,departmentType:settings.departmentType||null,departmentId:settings.departmentId||null});await this.database.query(`UPDATE prn_batch_items SET status='submitted',job_id=$1,error_message=NULL,claim_token=NULL,claim_expires_at=NULL,attempts=attempts+1,updated_at=now() WHERE id=$2 AND organization_id=$3 AND status='pending'`,[result.id,item.id,organizationId]);submitted++;}catch(error){await this.database.query(`UPDATE prn_batch_items SET status='failed',error_message=$1,attempts=attempts+1,updated_at=now() WHERE id=$2 AND organization_id=$3 AND status='pending'`,[String(error?.message||error).slice(0,1000),item.id,organizationId]);failed++;}}}
    await this.batchStatus(organizationId);return{submitted,failed};
  }

  async retention(organizationId){
    const policy=(await this.database.query(`SELECT * FROM prn_retention_policies WHERE organization_id=$1`,[organizationId])).rows[0]||{enabled:true,staged_hours:24,completed_print_days:7,failed_print_days:7,secure_print_minutes:10,scan_inbox_days:30,scan_routed_days:7};if(policy.enabled===false)return{disabled:true,purged:0};
    const holds=new Set((await this.database.query(`SELECT entity_type,entity_id FROM prn_retention_holds WHERE organization_id=$1 AND released_at IS NULL`,[organizationId])).rows.map(r=>`${r.entity_type}:${r.entity_id}`));let purged=0,failed=0;
    const prints=await this.database.query(`SELECT d.*,j.id job_id,j.status job_status,j.secure_release,j.completed_at,j.updated_at job_updated_at FROM prn_documents d LEFT JOIN prn_jobs j ON j.document_id=d.id AND j.organization_id=d.organization_id WHERE d.organization_id=$1 AND d.retention_purged_at IS NULL AND d.status<>'deleted' ORDER BY d.created_at LIMIT 500`,[organizationId]);
    for(const row of prints.rows){if(holds.has(`print_document:${row.id}`)||(row.job_id&&holds.has(`print_job:${row.job_id}`)))continue;let due=false,reason='';const age=(at)=>Date.now()-new Date(at).getTime();if(row.status==='staged'){due=age(row.created_at)>=Number(policy.staged_hours)*3600000;reason='staged-expired';}else if(row.job_id&&['completed','failed','cancelled'].includes(row.job_status)){const at=row.completed_at||row.job_updated_at||row.attached_at||row.created_at;if(row.secure_release){due=age(at)>=Number(policy.secure_print_minutes)*60000;reason='secure-print-retention';}else{const days=row.job_status==='completed'?policy.completed_print_days:policy.failed_print_days;due=age(at)>=Number(days)*86400000;reason=row.job_status==='completed'?'completed-print-retention':'failed-print-retention';}}if(!due)continue;try{await this.#deleteObject(organizationId,row.object_key);await this.database.transaction(async tx=>{await tx.query(`UPDATE prn_documents SET status='deleted',deleted_at=COALESCE(deleted_at,now()),retention_purged_at=now(),retention_purge_reason=$1 WHERE id=$2 AND organization_id=$3 AND retention_purged_at IS NULL`,[reason,row.id,organizationId]);await tx.query(`INSERT INTO prn_retention_events(id,organization_id,event_type,entity_type,entity_id,object_key,details_json) VALUES($1,$2,'object_purged','print_document',$3,$4,$5)`,[id('prnret'),organizationId,row.id,row.object_key,JSON.stringify({reason,jobId:row.job_id,sizeBytes:Number(row.size_bytes||0)})]);});purged++;}catch(error){failed++;}}
    const scans=await this.database.query(`SELECT d.*,j.id job_id,j.status job_status,j.target_type,j.completed_at,j.updated_at job_updated_at FROM prn_scan_documents d JOIN prn_scan_jobs j ON j.id=d.scan_job_id AND j.organization_id=d.organization_id WHERE d.organization_id=$1 AND d.retention_purged_at IS NULL AND j.status='completed' ORDER BY d.created_at LIMIT 500`,[organizationId]);for(const row of scans.rows){if(holds.has(`scan_document:${row.id}`)||holds.has(`scan_job:${row.job_id}`))continue;const days=['student','staff','module'].includes(row.target_type)?policy.scan_routed_days:policy.scan_inbox_days;const at=row.completed_at||row.job_updated_at||row.created_at;if(Date.now()-new Date(at).getTime()<Number(days)*86400000)continue;try{await this.#deleteObject(organizationId,row.object_key);await this.database.transaction(async tx=>{await tx.query(`UPDATE prn_scan_documents SET retention_purged_at=now(),retention_purge_reason=$1 WHERE id=$2 AND organization_id=$3 AND retention_purged_at IS NULL`,['scan-retention',row.id,organizationId]);await tx.query(`INSERT INTO prn_retention_events(id,organization_id,event_type,entity_type,entity_id,object_key,details_json) VALUES($1,$2,'object_purged','scan_document',$3,$4,$5)`,[id('prnret'),organizationId,row.id,row.object_key,JSON.stringify({reason:'scan-retention',jobId:row.job_id,sizeBytes:Number(row.size_bytes||0)})]);});purged++;}catch{failed++;}}
    return{purged,failed};
  }

  async consumables(organizationId){
    const items=await this.database.query(`SELECT c.*,p.marker_levels_json,p.name printer_name FROM prn_consumables c LEFT JOIN prn_printers p ON p.id=c.printer_id AND p.organization_id=c.organization_id WHERE c.organization_id=$1 AND c.active=true`,[organizationId]);let alerts=0;
    for(const item of items.rows){const markers=json(item.marker_levels_json,[]),marker=markers.find(x=>String(x?.name||'').toLowerCase()===String(item.marker_name||'').toLowerCase());if(marker&&Number.isFinite(Number(marker.levelPercent))){const level=Math.max(0,Math.min(100,Number(marker.levelPercent)));await this.database.query(`UPDATE prn_consumables SET last_marker_percent=$1,last_marker_at=now(),updated_at=now() WHERE id=$2 AND organization_id=$3`,[level,item.id,organizationId]);if(level<=Number(item.marker_low_percent||15)){await this.#alert(this.database,{organizationId,fingerprint:`consumable-marker:${item.id}`,eventType:'printerly.printer_fault',severity:level<=5?'critical':'warning',title:`${item.name} is ${level}%`,body:`${item.printer_name||'Printer'}: ${item.name} has reached ${level}%.`,entityType:'consumable',entityId:item.id,details:{printerId:item.printer_id,levelPercent:level}});alerts++;}else await this.#resolveAlert(organizationId,`consumable-marker:${item.id}`);}if(Number(item.on_hand)<=Number(item.reorder_level)){await this.#alert(this.database,{organizationId,fingerprint:`consumable-stock:${item.id}`,eventType:'printerly.printer_fault',severity:Number(item.on_hand)<=0?'critical':'warning',title:`Low Printerly stock · ${item.name}`,body:`${item.name} has ${item.on_hand} ${item.unit||'unit'} remaining.`,entityType:'consumable',entityId:item.id,details:{onHand:Number(item.on_hand),reorderLevel:Number(item.reorder_level)}});alerts++;}else await this.#resolveAlert(organizationId,`consumable-stock:${item.id}`);}
    return{items:items.rows.length,alerts};
  }

  async serviceSla(organizationId){
    const settings=(await this.database.query(`SELECT * FROM prn_service_settings WHERE organization_id=$1`,[organizationId])).rows[0]||{auto_create_from_alerts:true,auto_resolve_recovered:true,p1_response_minutes:30,p1_resolution_minutes:120,p2_response_minutes:120,p2_resolution_minutes:480,p3_response_minutes:480,p3_resolution_minutes:1440,p4_response_minutes:1440,p4_resolution_minutes:4320};let created=0,resolved=0,breaches=0;
    if(settings.auto_create_from_alerts!==false){const alerts=await this.database.query(`SELECT * FROM prn_alerts a WHERE a.organization_id=$1 AND a.resolved_at IS NULL AND a.event_type IN ('printerly.printer_fault','printerly.node_offline','printerly.job_failed','printerly.scan_failed') AND NOT EXISTS(SELECT 1 FROM prn_service_tickets t WHERE t.organization_id=a.organization_id AND t.source_alert_id=a.id) LIMIT 100`,[organizationId]);for(const a of alerts.rows){const p=priority(a.severity),response=Number(settings[`${p}_response_minutes`]||480),resolution=Number(settings[`${p}_resolution_minutes`]||1440),ticketId=id('prnsd'),number=`PRN-SD-${new Date().getUTCFullYear()}-${ticketId.slice(-8).toUpperCase()}`;await this.database.transaction(async tx=>{await tx.query(`INSERT INTO prn_service_tickets(id,organization_id,ticket_number,source_type,source_alert_id,category,priority,status,title,description,response_due_at,resolution_due_at) VALUES($1,$2,$3,'alert',$4,$5,$6,'new',$7,$8,now()+($9||' minutes')::interval,now()+($10||' minutes')::interval) ON CONFLICT(organization_id,ticket_number) DO NOTHING`,[ticketId,organizationId,number,a.id,category(a.entity_type),p,a.title,a.body,String(response),String(resolution)]);await tx.query(`INSERT INTO prn_service_ticket_events(id,organization_id,ticket_id,event_type,details_json) VALUES($1,$2,$3,'created',$4)`,[id('prnsdevt'),organizationId,ticketId,JSON.stringify({sourceAlertId:a.id})]);});created++;}}
    if(settings.auto_resolve_recovered!==false){const r=await this.database.query(`UPDATE prn_service_tickets t SET status='resolved',resolved_at=now(),resolution_notes='Source alert recovered automatically',first_responded_at=now(),updated_at=now() FROM prn_alerts a WHERE t.organization_id=$1 AND a.id=t.source_alert_id AND a.organization_id=t.organization_id AND t.status IN ('new','assigned') AND t.first_responded_at IS NULL AND a.resolved_at IS NOT NULL RETURNING t.id`,[organizationId]);resolved=r.rowCount||0;}
    const response=await this.database.query(`UPDATE prn_service_tickets SET response_breached_at=now(),updated_at=now() WHERE organization_id=$1 AND status IN ('new','assigned','in_progress','waiting') AND first_responded_at IS NULL AND response_breached_at IS NULL AND response_due_at<=now() RETURNING id`,[organizationId]);const resolution=await this.database.query(`UPDATE prn_service_tickets SET resolution_breached_at=now(),updated_at=now() WHERE organization_id=$1 AND status IN ('new','assigned','in_progress','waiting') AND resolution_breached_at IS NULL AND resolution_due_at<=now() RETURNING id`,[organizationId]);breaches=(response.rowCount||0)+(resolution.rowCount||0);return{created,resolved,breaches};
  }

  async procurement(organizationId){
    const settings=(await this.database.query(`SELECT auto_draft_reorders FROM prn_procurement_settings WHERE organization_id=$1`,[organizationId])).rows[0];if(!settings?.auto_draft_reorders)return{enabled:false,created:0};const actor=(await this.database.query(`SELECT user_id FROM memberships WHERE organization_id=$1 AND role IN ('owner','admin') ORDER BY created_at LIMIT 1`,[organizationId])).rows[0]?.user_id;if(!actor)return{enabled:true,created:0,skipped:'no-admin-actor'};
    const recs=await this.database.query(`SELECT c.id consumable_id,c.name,c.target_stock,c.on_hand,sc.supplier_id,sc.supplier_sku,sc.unit_cost_minor,sc.min_order_qty,COALESCE((SELECT SUM(l.quantity_requested-l.quantity_received) FROM prn_purchase_request_lines l JOIN prn_purchase_requests r ON r.id=l.request_id AND r.organization_id=l.organization_id WHERE l.organization_id=c.organization_id AND l.consumable_id=c.id AND r.status IN ('draft','submitted','approved','ordered','partially_received')),0)::int on_order FROM prn_consumables c JOIN prn_supplier_catalog sc ON sc.organization_id=c.organization_id AND sc.consumable_id=c.id AND sc.preferred=true JOIN prn_suppliers s ON s.id=sc.supplier_id AND s.organization_id=sc.organization_id AND s.active=true WHERE c.organization_id=$1 AND c.active=true AND c.on_hand<=c.reorder_level AND NOT EXISTS(SELECT 1 FROM prn_replenishment_claims rc WHERE rc.organization_id=c.organization_id AND rc.consumable_id=c.id) ORDER BY sc.supplier_id,c.name`,[organizationId]);const groups=new Map();for(const r of recs.rows){const need=Math.max(0,Number(r.target_stock)-Number(r.on_hand)-Number(r.on_order));const qty=need>0?Math.max(need,Number(r.min_order_qty||1)):0;if(!qty)continue;if(!groups.has(r.supplier_id))groups.set(r.supplier_id,[]);groups.get(r.supplier_id).push({...r,qty});}let created=0;
    for(const [supplierId,items] of groups){try{await this.database.transaction(async tx=>{for(const item of items){const locked=(await tx.query(`SELECT id FROM prn_consumables WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[item.consumable_id,organizationId])).rows[0];if(!locked)throw new Error('Consumable disappeared during replenishment');const claim=(await tx.query(`SELECT 1 FROM prn_replenishment_claims WHERE organization_id=$1 AND consumable_id=$2`,[organizationId,item.consumable_id])).rows[0];if(claim)throw Object.assign(new Error('already claimed'),{code:'CLAIMED'});}const requestId=id('prnpr'),number=`PRN-PR-${new Date().getUTCFullYear()}-${requestId.slice(-8).toUpperCase()}`,currency=(await tx.query(`SELECT COALESCE((SELECT currency FROM prn_cost_profiles WHERE organization_id=$1),'UGX') currency`,[organizationId])).rows[0].currency,subtotal=items.reduce((s,x)=>s+x.qty*Number(x.unit_cost_minor||0),0);await tx.query(`INSERT INTO prn_purchase_requests(id,organization_id,request_number,supplier_id,status,currency,subtotal_minor,notes,requested_by,auto_generated) VALUES($1,$2,$3,$4,'draft',$5,$6,'Automatic draft created by Printerly replenishment policy',$7,true)`,[requestId,organizationId,number,supplierId,currency,subtotal,actor]);for(const item of items){const lineId=id('prnprline');await tx.query(`INSERT INTO prn_purchase_request_lines(id,organization_id,request_id,consumable_id,description,quantity_requested,unit_cost_minor,supplier_sku) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[lineId,organizationId,requestId,item.consumable_id,item.name,item.qty,item.unit_cost_minor,item.supplier_sku]);await tx.query(`INSERT INTO prn_replenishment_claims(organization_id,consumable_id,request_id) VALUES($1,$2,$3)`,[organizationId,item.consumable_id,requestId]);}await tx.query(`INSERT INTO prn_purchase_request_events(id,organization_id,request_id,event_type,actor_id,details_json) VALUES($1,$2,$3,'created',$4,$5)`,[id('prnprevt'),organizationId,requestId,actor,JSON.stringify({autoGenerated:true,lines:items.length})]);});created++;}catch(error){if(error?.code!=='CLAIMED')throw error;}}
    return{enabled:true,created};
  }

  async #alert(db,input){const existing=(await db.query(`SELECT id FROM prn_alerts WHERE organization_id=$1 AND fingerprint=$2 AND resolved_at IS NULL`,[input.organizationId,input.fingerprint])).rows[0];if(existing){await db.query(`UPDATE prn_alerts SET severity=$1,title=$2,body=$3,details_json=$4,updated_at=now() WHERE id=$5 AND organization_id=$6`,[input.severity,input.title,input.body,JSON.stringify(input.details||{}),existing.id,input.organizationId]);return existing.id;}const alertId=id('prnalert');await db.query(`INSERT INTO prn_alerts(id,organization_id,fingerprint,event_type,severity,title,body,entity_type,entity_id,details_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING`,[alertId,input.organizationId,input.fingerprint,input.eventType,input.severity,input.title,input.body,input.entityType||null,input.entityId||null,JSON.stringify(input.details||{})]);return alertId;}
  async #resolveAlert(organizationId,fingerprint){await this.database.query(`UPDATE prn_alerts SET resolved_at=COALESCE(resolved_at,now()),updated_at=now() WHERE organization_id=$1 AND fingerprint=$2 AND resolved_at IS NULL`,[organizationId,fingerprint]);}
  async #deleteObject(organizationId,logicalKey){const mapped=(await this.database.query(`SELECT target_key FROM ledgerly_meta.object_migration_state WHERE object_key=$1 AND organization_id=$2 AND status='verified' ORDER BY migrated_at DESC LIMIT 1`,[logicalKey,organizationId])).rows[0];const key=mapped?.target_key||tenantStorageKey(organizationId,logicalKey);await this.storage.delete(key);}
}
