import {createHash,randomUUID} from 'node:crypto';
import {PrinterlyRuntimeError,projectedExceeded} from './runtime-service.mjs';
import {policyApplies} from './batch-service.mjs';
import {resolvePrinterRoute} from './routing-core.mjs';

const id=p=>`${p}_${randomUUID().replaceAll('-','')}`;
const json=(v,f)=>{try{return v?JSON.parse(String(v)):f}catch{return f}};
const arr=v=>Array.isArray(v)?v.map(String).filter(Boolean):[];
const int=(v,min=0,max=Number.MAX_SAFE_INTEGER,f=0)=>{const n=Math.round(Number(v));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):f};
const fail=(code,message,status=409,details)=>Object.assign(new PrinterlyRuntimeError(code,message,details),{status});
const canAdmin=p=>p?.role==='owner'||p?.role==='admin'||p?.scopes?.includes?.('admin:write');
const action=v=>({block:Boolean(v?.block),blockMessage:String(v?.blockMessage||'This print request is blocked by an organization Printerly policy.').slice(0,500),requireApproval:Boolean(v?.requireApproval),approverRoles:arr(v?.approverRoles).length?arr(v.approverRoles):['owner','admin'],approverUserIds:arr(v?.approverUserIds),allowSelfApproval:Boolean(v?.allowSelfApproval),forceDuplex:Boolean(v?.forceDuplex),forceMonochrome:Boolean(v?.forceMonochrome),forceSecureRelease:Boolean(v?.forceSecureRelease),printerId:v?.printerId?String(v.printerId):null,priority:v?.priority?String(v.priority):null});
const csvCell=v=>{const s=String(v??'');return /[\",\n]/.test(s)?`\"${s.replaceAll('\"','\"\"')}\"`:s};

export class PrinterlyManagementService{
  constructor({database,runtime,costing,jobs}){if(!database?.query||!database?.transaction)throw new TypeError('database is required');this.database=database;this.runtime=runtime;this.costing=costing;this.jobs=jobs;}

  async manifest(){return{key:'printerly',name:'Printerly',version:'1.13.0',nodeProtocol:'3',capabilities:['remote-print','private-r2-documents','global-print-action','cost-centres','ledger-cost-posting','printer-health','multi-channel-alerts','scannerly','student-staff-scan-routing','module-scan-inbox','usage-reporting','csv-usage-export','monthly-quotas','hard-quota-enforcement','quota-reservations','automatic-print-rules','approval-workflows','scheduled-printing','multi-document-batches','audit-compliance','printer-pools','smart-routing','secure-release','document-retention','consumables-inventory','preventive-maintenance','procurement','service-desk','sla-management','claim-leases','checksum-verification']};}
  async overview(org){const [nodes,printers,jobs,alerts,scans,cost]=await Promise.all([
    this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='online')::int online FROM prn_nodes WHERE organization_id=$1`,[org]),
    this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='ready')::int ready,COUNT(*) FILTER(WHERE health_status='critical')::int critical FROM prn_printers WHERE organization_id=$1`,[org]),
    this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status IN('queued','held','approval_pending','claimed','downloading','spooling','printing'))::int active,COUNT(*) FILTER(WHERE status='approval_pending')::int \"approvalPending\",COUNT(*) FILTER(WHERE status='failed')::int failed FROM prn_jobs WHERE organization_id=$1`,[org]),
    this.database.query(`SELECT COUNT(*) FILTER(WHERE resolved_at IS NULL)::int open,COUNT(*) FILTER(WHERE resolved_at IS NULL AND severity='critical')::int critical FROM prn_alerts WHERE organization_id=$1`,[org]),
    this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status IN('queued','claimed','scanning','uploading'))::int active,COUNT(*) FILTER(WHERE status='completed')::int completed FROM prn_scan_jobs WHERE organization_id=$1`,[org]),
    this.database.query(`SELECT COALESCE(SUM(total_cost_minor),0)::bigint total_cost_minor,COUNT(*)::int jobs FROM prn_cost_ledger WHERE organization_id=$1`,[org]),
  ]);return{nodes:nodes.rows[0]||{},printers:printers.rows[0]||{},jobs:jobs.rows[0]||{},alerts:alerts.rows[0]||{},scannerly:scans.rows[0]||{},costing:{totalCostMinor:Number(cost.rows[0]?.total_cost_minor||0),jobs:Number(cost.rows[0]?.jobs||0)}};}

  async listNodes(org){return(await this.database.query(`SELECT id,name,location,status,last_seen_at \"lastSeenAt\",version,revoked_at \"revokedAt\",created_at \"createdAt\",pairing_expires_at \"pairingExpiresAt\" FROM prn_nodes WHERE organization_id=$1 ORDER BY created_at DESC`,[org])).rows;}
  async createNode(org,userId,data={}){const name=String(data.name||'').trim().slice(0,160);if(!name)throw fail('VALIDATION_ERROR','Node name is required',422);const code=String(int(Math.random()*1_000_000,0,999999)).padStart(6,'0'),hash=createHash('sha256').update(code).digest('hex'),nodeId=id('prnnode'),minutes=int(data.ttlMinutes,2,120,15);await this.database.query(`INSERT INTO prn_nodes(id,organization_id,name,location,status,pairing_code_hash,pairing_expires_at,created_by) VALUES($1,$2,$3,$4,'pairing',$5,now()+($6||' minutes')::interval,$7)`,[nodeId,org,name,String(data.location||'').trim().slice(0,240)||null,hash,String(minutes),userId]);return{id:nodeId,name,pairingCode:code,expiresAt:new Date(Date.now()+minutes*60000).toISOString(),nodeProtocol:3};}
  async revokeNode(org,nodeId){return this.database.transaction(async tx=>{const row=(await tx.query(`SELECT id,status FROM prn_nodes WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[nodeId,org])).rows[0];if(!row)throw fail('NODE_NOT_FOUND','Printerly node not found',404);await tx.query(`UPDATE prn_nodes SET revoked_at=COALESCE(revoked_at,now()),status='revoked',token_hash=NULL,pairing_code_hash=NULL,pairing_expires_at=NULL,updated_at=now() WHERE id=$1 AND organization_id=$2`,[nodeId,org]);await tx.query(`UPDATE prn_printers SET status='offline',updated_at=now() WHERE node_id=$1 AND organization_id=$2`,[nodeId,org]);await tx.query(`UPDATE prn_scanners SET status='offline',updated_at=now() WHERE node_id=$1 AND organization_id=$2`,[nodeId,org]);await tx.query(`UPDATE prn_jobs SET status='queued',node_id=NULL,claim_token=NULL,claim_expires_at=NULL,updated_at=now() WHERE organization_id=$2 AND node_id=$1 AND status IN('claimed','downloading')`,[nodeId,org]);return{id:nodeId,revoked:true};});}
  async listPrinters(org){return(await this.database.query(`SELECT p.id,p.node_id \"nodeId\",p.name,p.system_name \"systemName\",p.location,p.status,p.health_status \"healthStatus\",p.state_reasons_json \"stateReasonsJson\",p.marker_levels_json \"markerLevelsJson\",p.health_message \"healthMessage\",p.last_seen_at \"lastSeenAt\",p.last_health_at \"lastHealthAt\",n.name \"nodeName\",n.status \"nodeStatus\" FROM prn_printers p JOIN prn_nodes n ON n.id=p.node_id AND n.organization_id=p.organization_id WHERE p.organization_id=$1 ORDER BY p.name`,[org])).rows.map(r=>({...r,stateReasons:json(r.stateReasonsJson,[]),markerLevels:json(r.markerLevelsJson,[])}));}

  async costingOptions(org){const [accounts,projects,finance,school]=await Promise.all([
    this.database.query(`SELECT id,code,name,type FROM accounts WHERE organization_id=$1 AND active=true AND allow_posting=true ORDER BY code`,[org]),
    this.database.query(`SELECT id,name FROM projects WHERE organization_id=$1 AND status='active' ORDER BY name`,[org]),
    this.database.query(`SELECT id,name FROM dimensions WHERE organization_id=$1 AND type='department' AND active=true ORDER BY name`,[org]).catch(()=>({rows:[]})),
    this.database.query(`SELECT id,name FROM school_departments WHERE organization_id=$1 AND active=true ORDER BY name`,[org]).catch(()=>({rows:[]})),
  ]);return{accounts:accounts.rows,projects:projects.rows,financeDepartments:finance.rows,schoolDepartments:school.rows};}
  async getCostProfile(org){let row=(await this.database.query(`SELECT * FROM prn_cost_profiles WHERE organization_id=$1`,[org])).rows[0];if(!row){const cur=(await this.database.query(`SELECT base_currency FROM organizations WHERE id=$1`,[org])).rows[0]?.base_currency||'UGX';await this.database.query(`INSERT INTO prn_cost_profiles(organization_id,currency) VALUES($1,$2) ON CONFLICT DO NOTHING`,[org,cur]);row=(await this.database.query(`SELECT * FROM prn_cost_profiles WHERE organization_id=$1`,[org])).rows[0];}return row;}
  async updateCostProfile(org,userId,data={}){const existing=await this.getCostProfile(org),currency=String(data.currency||existing.currency||'UGX').toUpperCase().slice(0,8),expense=data.expenseAccountId??existing.expense_account_id??null,offset=data.offsetAccountId??existing.offset_account_id??null;if(expense||offset){const ids=[...new Set([expense,offset].filter(Boolean))],valid=(await this.database.query(`SELECT id FROM accounts WHERE organization_id=$1 AND active=true AND allow_posting=true AND id=ANY($2::text[])`,[org,ids])).rows;if(valid.length!==ids.length)throw fail('PRINTERLY_ACCOUNTS_INVALID','Printerly cost accounts must be active posting accounts',422);}await this.database.query(`INSERT INTO prn_cost_profiles(organization_id,currency,paper_cost_minor,bw_toner_cost_minor,color_toner_cost_minor,maintenance_cost_minor,electricity_cost_minor,expense_account_id,offset_account_id,auto_post_accounting,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(organization_id) DO UPDATE SET currency=excluded.currency,paper_cost_minor=excluded.paper_cost_minor,bw_toner_cost_minor=excluded.bw_toner_cost_minor,color_toner_cost_minor=excluded.color_toner_cost_minor,maintenance_cost_minor=excluded.maintenance_cost_minor,electricity_cost_minor=excluded.electricity_cost_minor,expense_account_id=excluded.expense_account_id,offset_account_id=excluded.offset_account_id,auto_post_accounting=excluded.auto_post_accounting,updated_by=excluded.updated_by,updated_at=now()`,[org,currency,int(data.paperCostMinor??existing.paper_cost_minor),int(data.bwTonerCostMinor??existing.bw_toner_cost_minor),int(data.colorTonerCostMinor??existing.color_toner_cost_minor),int(data.maintenanceCostMinor??existing.maintenance_cost_minor),int(data.electricityCostMinor??existing.electricity_cost_minor),expense,offset,Boolean(data.autoPostAccounting??existing.auto_post_accounting),userId]);return this.getCostProfile(org);}
  async listCostLedger(org,limit=200){return(await this.database.query(`SELECT c.*,j.job_number \"jobNumber\",j.title,j.created_by \"createdBy\",u.display_name \"createdByName\",p.journal_entry_id \"journalEntryId\" FROM prn_cost_ledger c JOIN prn_jobs j ON j.id=c.job_id AND j.organization_id=c.organization_id LEFT JOIN users u ON u.id=j.created_by LEFT JOIN prn_cost_postings p ON p.job_id=c.job_id AND p.organization_id=c.organization_id WHERE c.organization_id=$1 ORDER BY c.created_at DESC LIMIT $2`,[org,int(limit,1,500,200)])).rows;}
  async postJobCost(org,userId,jobId){return this.database.transaction(async tx=>{const prior=(await tx.query(`SELECT journal_entry_id FROM prn_cost_postings WHERE organization_id=$1 AND job_id=$2`,[org,jobId])).rows[0];if(prior)return{jobId,journalEntryId:prior.journal_entry_id,duplicate:true};const row=(await tx.query(`SELECT c.*,j.job_number,j.title,j.charge_project_id,j.charge_department_type,j.charge_department_id FROM prn_cost_ledger c JOIN prn_jobs j ON j.id=c.job_id AND j.organization_id=c.organization_id WHERE c.organization_id=$1 AND c.job_id=$2 FOR UPDATE OF c,j`,[org,jobId])).rows[0];if(!row)throw fail('COST_NOT_FOUND','Completed Printerly cost record not found',404);const profile=(await tx.query(`SELECT * FROM prn_cost_profiles WHERE organization_id=$1 FOR UPDATE`,[org])).rows[0];if(!profile?.expense_account_id||!profile?.offset_account_id)throw fail('PRINTERLY_ACCOUNTS_REQUIRED','Configure Printerly expense and offset accounts first',409);const total=Number(row.total_cost_minor||0),journal=id('je'),date=new Date().toISOString().slice(0,10);await tx.query(`INSERT INTO journal_entries(id,organization_id,entry_number,transaction_date,posting_date,description,reference,source_type,source_id,status,currency,posted_at,posted_by,idempotency_key,metadata) VALUES($1,$2,$3,$4,$4,$5,$6,'printerly',$7,'posted',$8,now(),$9,$10,$11)`,[journal,org,`PRN-${String(row.job_number).replace(/^PRT-/,'')}`,date,`Printerly cost · ${row.job_number} · ${row.title}`,row.job_number,jobId,row.currency,userId,`printerly-cost:${jobId}`,JSON.stringify({printerlyCostLedgerId:row.id})]);const dept=row.charge_department_type==='finance'?row.charge_department_id:null;await tx.query(`INSERT INTO journal_lines(id,organization_id,journal_entry_id,account_id,description,debit_minor,credit_minor,base_debit_minor,base_credit_minor,project_id,department_id) VALUES($1,$2,$3,$4,$5,$6,0,$6,0,$7,$8),($9,$2,$3,$10,$11,0,$6,0,$6,$7,$8)`,[id('jl'),org,journal,profile.expense_account_id,`Printing cost · ${row.title}`,total,row.charge_project_id||null,dept,id('jl'),profile.offset_account_id,`Printerly cost allocation · ${row.title}`]);await tx.query(`INSERT INTO prn_cost_postings(id,organization_id,job_id,cost_ledger_id,journal_entry_id,posted_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(organization_id,job_id) DO NOTHING`,[id('prnpost'),org,jobId,row.id,journal,userId]);const final=(await tx.query(`SELECT journal_entry_id FROM prn_cost_postings WHERE organization_id=$1 AND job_id=$2`,[org,jobId])).rows[0];return{jobId,journalEntryId:final.journal_entry_id,duplicate:final.journal_entry_id!==journal};});}

  async usageReport(org,from,to){const end=to&&/^\d{4}-\d{2}-\d{2}$/.test(to)?to:new Date().toISOString().slice(0,10),start=from&&/^\d{4}-\d{2}-\d{2}$/.test(from)?from:new Date(Date.now()-30*86400000).toISOString().slice(0,10);const [summary,users,printers,daily]=await Promise.all([
    this.database.query(`SELECT COUNT(*)::int jobs,COALESCE(SUM(actual_impressions),0)::bigint impressions,COALESCE(SUM(actual_sheets),0)::bigint sheets,COALESCE(SUM(actual_cost_minor),0)::bigint cost_minor FROM prn_jobs WHERE organization_id=$1 AND status='completed' AND completed_at::date BETWEEN $2::date AND $3::date`,[org,start,end]),
    this.database.query(`SELECT j.created_by \"userId\",COALESCE(u.display_name,u.email,j.created_by) name,COUNT(*)::int jobs,COALESCE(SUM(j.actual_impressions),0)::bigint impressions,COALESCE(SUM(j.actual_sheets),0)::bigint sheets,COALESCE(SUM(j.actual_cost_minor),0)::bigint \"costMinor\" FROM prn_jobs j LEFT JOIN users u ON u.id=j.created_by WHERE j.organization_id=$1 AND j.status='completed' AND j.completed_at::date BETWEEN $2::date AND $3::date GROUP BY j.created_by,u.display_name,u.email ORDER BY \"costMinor\" DESC`,[org,start,end]),
    this.database.query(`SELECT j.printer_id \"printerId\",COALESCE(p.name,'Unassigned') name,COUNT(*)::int jobs,COALESCE(SUM(j.actual_impressions),0)::bigint impressions,COALESCE(SUM(j.actual_sheets),0)::bigint sheets,COALESCE(SUM(j.actual_cost_minor),0)::bigint \"costMinor\" FROM prn_jobs j LEFT JOIN prn_printers p ON p.id=j.printer_id AND p.organization_id=j.organization_id WHERE j.organization_id=$1 AND j.status='completed' AND j.completed_at::date BETWEEN $2::date AND $3::date GROUP BY j.printer_id,p.name ORDER BY \"costMinor\" DESC`,[org,start,end]),
    this.database.query(`SELECT completed_at::date::text date,COUNT(*)::int jobs,COALESCE(SUM(actual_impressions),0)::bigint impressions,COALESCE(SUM(actual_sheets),0)::bigint sheets,COALESCE(SUM(actual_cost_minor),0)::bigint \"costMinor\" FROM prn_jobs WHERE organization_id=$1 AND status='completed' AND completed_at::date BETWEEN $2::date AND $3::date GROUP BY completed_at::date ORDER BY completed_at::date`,[org,start,end]),
  ]);const s=summary.rows[0]||{};return{from:start,to:end,summary:{jobs:Number(s.jobs||0),impressions:Number(s.impressions||0),sheets:Number(s.sheets||0),costMinor:Number(s.cost_minor||0)},users:users.rows,printers:printers.rows,daily:daily.rows};}
  async usageCsv(org,from,to){const r=await this.usageReport(org,from,to),rows=[['Date','Jobs','Impressions','Sheets','Cost Minor'],...r.daily.map(x=>[x.date,x.jobs,x.impressions,x.sheets,x.costMinor])];return{...r,csv:rows.map(row=>row.map(csvCell).join(',')).join('\n')};}

  async quotaOptions(org){const [users,projects,finance,school]=await Promise.all([this.database.query(`SELECT id,display_name name,email FROM users WHERE id IN(SELECT user_id FROM memberships WHERE organization_id=$1) ORDER BY display_name,email`,[org]),this.database.query(`SELECT id,name FROM projects WHERE organization_id=$1 AND status='active' ORDER BY name`,[org]),this.database.query(`SELECT id,name FROM dimensions WHERE organization_id=$1 AND type='department' AND active=true ORDER BY name`,[org]).catch(()=>({rows:[]})),this.database.query(`SELECT id,name FROM school_departments WHERE organization_id=$1 AND active=true ORDER BY name`,[org]).catch(()=>({rows:[]}))]);return{users:users.rows,projects:projects.rows,financeDepartments:finance.rows,schoolDepartments:school.rows,modes:['soft','hard'],scopeTypes:['organization','user','finance_department','school_department','project']};}
  async listQuotas(org,period=new Date().toISOString().slice(0,7)){return(await this.database.query(`SELECT q.*,p.reserved_impressions,p.reserved_sheets,p.reserved_cost_minor,p.consumed_impressions,p.consumed_sheets,p.consumed_cost_minor,p.updated_at \"periodUpdatedAt\" FROM prn_quotas q LEFT JOIN prn_quota_periods p ON p.quota_id=q.id AND p.period_key=$2 WHERE q.organization_id=$1 ORDER BY q.active DESC,q.created_at DESC`,[org,period])).rows;}
  async saveQuota(org,userId,quotaId,data={}){const type=new Set(['organization','user','finance_department','school_department','project']).has(String(data.scopeType))?String(data.scopeType):'organization',scopeId=type==='organization'?null:String(data.scopeId||'').trim()||null;if(type!=='organization'&&!scopeId)throw fail('QUOTA_SCOPE_REQUIRED','Choose the quota scope target',422);const mode=String(data.mode)==='hard'?'hard':'soft',name=String(data.name||'').trim().slice(0,160);if(!name)throw fail('QUOTA_NAME_REQUIRED','Quota name is required',422);const key=`${type}:${scopeId||'organization'}`,qid=quotaId||id('prnquota'),values=[name,type,scopeId,key,mode,int(data.maxImpressions),int(data.maxSheets),int(data.maxCostMinor),int(data.warningPercent,1,100,80),data.active===false?false:true];if(quotaId){const r=await this.database.query(`UPDATE prn_quotas SET name=$1,scope_type=$2,scope_id=$3,scope_key=$4,mode=$5,max_impressions=$6,max_sheets=$7,max_cost_minor=$8,warning_percent=$9,active=$10,updated_at=now() WHERE id=$11 AND organization_id=$12`,[...values,qid,org]);if(!r.rowCount)throw fail('QUOTA_NOT_FOUND','Printerly quota not found',404);}else await this.database.query(`INSERT INTO prn_quotas(id,organization_id,name,scope_type,scope_id,scope_key,mode,max_impressions,max_sheets,max_cost_minor,warning_percent,active,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[qid,org,...values,userId]);return{id:qid,...data,scopeType:type,scopeId,mode,name};}
  async deactivateQuota(org,quotaId){const r=await this.database.query(`UPDATE prn_quotas SET active=false,updated_at=now() WHERE id=$1 AND organization_id=$2 AND active=true`,[quotaId,org]);if(!r.rowCount)throw fail('QUOTA_NOT_FOUND','Active Printerly quota not found',404);return{id:quotaId,active:false};}
  async checkQuota(org,userId,body={}){const prepared=await this.prepareCost(org,body),periodKey=new Date().toISOString().slice(0,7),clauses=[`scope_type='organization'`],values=[org];let n=2;clauses.push(`(scope_type='user' AND scope_id=$${n++})`);values.push(userId);if(prepared.projectId){clauses.push(`(scope_type='project' AND scope_id=$${n++})`);values.push(prepared.projectId);}if(prepared.departmentId){clauses.push(`(scope_type='${prepared.departmentType==='school'?'school':'finance'}_department' AND scope_id=$${n++})`);values.push(prepared.departmentId);}const quotas=(await this.database.query(`SELECT q.*,p.* FROM prn_quotas q LEFT JOIN prn_quota_periods p ON p.quota_id=q.id AND p.period_key=$${n} WHERE q.organization_id=$1 AND q.active=true AND (${clauses.join(' OR ')}) ORDER BY CASE q.mode WHEN 'hard' THEN 0 ELSE 1 END,q.id`,[...values,periodKey])).rows;const request={impressions:prepared.estimatedImpressions,sheets:prepared.estimatedSheets,costMinor:prepared.estimatedCostMinor},checks=quotas.map(q=>({quotaId:q.id,name:q.name,mode:q.mode,exceeded:projectedExceeded(q,q,request)}));return{periodKey,request,checks,allowed:!checks.some(x=>x.mode==='hard'&&x.exceeded),warnings:checks.filter(x=>x.mode==='soft'&&x.exceeded)};}

  async ruleOptions(org){const [printers,pools,users,projects,finance,school]=await Promise.all([this.database.query(`SELECT id,name,location,status FROM prn_printers WHERE organization_id=$1 ORDER BY name`,[org]),this.database.query(`SELECT id,name FROM prn_printer_pools WHERE organization_id=$1 AND active=true ORDER BY name`,[org]),this.database.query(`SELECT u.id,u.display_name name,u.email,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 ORDER BY u.display_name,u.email`,[org]),this.database.query(`SELECT id,name FROM projects WHERE organization_id=$1 AND status='active' ORDER BY name`,[org]),this.database.query(`SELECT id,name FROM dimensions WHERE organization_id=$1 AND type='department' AND active=true ORDER BY name`,[org]).catch(()=>({rows:[]})),this.database.query(`SELECT id,name FROM school_departments WHERE organization_id=$1 AND active=true ORDER BY name`,[org]).catch(()=>({rows:[]}))]);return{printers:printers.rows,pools:pools.rows,users:users.rows,projects:projects.rows,financeDepartments:finance.rows,schoolDepartments:school.rows,roles:['owner','admin','manager','accountant','viewer'],priorities:['urgent','high','normal','bulk'],colorModes:['monochrome','color'],pageSizes:['A4','A5','Letter','Legal']};}
  async mobileRuleOptions(org){const [base,mods]=await Promise.all([this.ruleOptions(org),this.database.query(`SELECT module_key id FROM organization_modules WHERE organization_id=$1 AND enabled=true AND module_key<>'mobile-sync' ORDER BY module_key`,[org])]);return{...base,modules:mods.rows.map(x=>({id:String(x.id),name:String(x.id).split('-').map(s=>s?s[0].toUpperCase()+s.slice(1):s).join(' ')}))};}
  async listRules(org){return(await this.database.query(`SELECT id,name,description,active,priority,match_json \"matchJson\",action_json \"actionJson\",created_at \"createdAt\",updated_at \"updatedAt\" FROM prn_print_rules WHERE organization_id=$1 ORDER BY active DESC,priority,created_at`,[org])).rows.map(r=>({...r,match:json(r.matchJson,{}),action:json(r.actionJson,{})}));}
  async saveRule(org,userId,ruleId,data={}){const name=String(data.name||'').trim().slice(0,160);if(!name)throw fail('RULE_NAME_REQUIRED','Printerly rule name is required',422);const priority=int(data.priority,1,1000,100),match=data.match&&typeof data.match==='object'?data.match:{},act=data.action&&typeof data.action==='object'?data.action:{},rid=ruleId||id('prnrule');if(ruleId){const r=await this.database.query(`UPDATE prn_print_rules SET name=$1,description=$2,active=$3,priority=$4,match_json=$5,action_json=$6,updated_by=$7,updated_at=now() WHERE id=$8 AND organization_id=$9`,[name,String(data.description||'').slice(0,1000)||null,data.active===false?false:true,priority,JSON.stringify(match),JSON.stringify(act),userId,rid,org]);if(!r.rowCount)throw fail('RULE_NOT_FOUND','Printerly rule not found',404);}else await this.database.query(`INSERT INTO prn_print_rules(id,organization_id,name,description,active,priority,match_json,action_json,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)`,[rid,org,name,String(data.description||'').slice(0,1000)||null,data.active===false?false:true,priority,JSON.stringify(match),JSON.stringify(act),userId]);return{id:rid,name,priority,active:data.active===false?false:true,match,action:act};}
  async deactivateRule(org,ruleId){const r=await this.database.query(`UPDATE prn_print_rules SET active=false,updated_at=now() WHERE id=$1 AND organization_id=$2 AND active=true`,[ruleId,org]);if(!r.rowCount)throw fail('RULE_NOT_FOUND','Active Printerly rule not found',404);return{id:ruleId,active:false};}
  async prepareCost(org,body={}){const o={printerId:body.printerId?String(body.printerId):null,poolId:body.poolId?String(body.poolId):null,copies:int(body.copies,1,1000,1),estimatedPages:int(body.estimatedPages,1,10000,1),priority:new Set(['urgent','high','normal','bulk']).has(String(body.priority))?String(body.priority):'normal',pageSize:new Set(['A4','A5','Letter','Legal']).has(String(body.pageSize))?String(body.pageSize):'A4',colorMode:String(body.colorMode)==='color'?'color':'monochrome',duplex:Boolean(body.duplex),secureRelease:Boolean(body.secureRelease),projectId:body.projectId?String(body.projectId):null,departmentType:body.departmentId?(String(body.departmentType)==='school'?'school':'finance'):null,departmentId:body.departmentId?String(body.departmentId):null,sourceModule:body.sourceModule?String(body.sourceModule):null};const profile=(await this.database.query(`SELECT * FROM prn_cost_profiles WHERE organization_id=$1`,[org])).rows[0]||{},impressions=o.estimatedPages*o.copies,sheets=o.duplex?Math.ceil(impressions/2):impressions,total=sheets*Number(profile.paper_cost_minor||0)+impressions*(Number(o.colorMode==='color'?profile.color_toner_cost_minor||0:profile.bw_toner_cost_minor||0)+Number(profile.maintenance_cost_minor||0)+Number(profile.electricity_cost_minor||0));return{...o,estimatedPages:o.estimatedPages,estimatedImpressions:impressions,estimatedSheets:sheets,estimatedCostMinor:total,estimate:{totalCostMinor:total,currency:String(profile.currency||'UGX')}};}
  async previewRule(org,principal,body={}){const initial=await this.prepareCost(org,body),rules=(await this.database.query(`SELECT id,name,priority,match_json,action_json FROM prn_print_rules WHERE organization_id=$1 AND active=true ORDER BY priority,created_at`,[org])).rows,effective={...initial},applied=[],roles=new Set(),users=new Set();let blocked=false,blockedReason='',requiresApproval=false,allowSelfApproval=true,routeChosen=false,priorityChosen=false;for(const row of rules){const a=action(json(row.action_json,{}));if(!policyApplies(json(row.match_json,{}),principal,initial,initial))continue;applied.push({id:row.id,name:row.name,priority:row.priority});if(a.block&&!blocked){blocked=true;blockedReason=a.blockMessage;}if(a.requireApproval){requiresApproval=true;a.approverRoles.forEach(x=>roles.add(x));a.approverUserIds.forEach(x=>users.add(x));if(!a.allowSelfApproval)allowSelfApproval=false;}if(a.forceDuplex)effective.duplex=true;if(a.forceMonochrome)effective.colorMode='monochrome';if(a.forceSecureRelease)effective.secureRelease=true;if(a.printerId&&!routeChosen){effective.printerId=a.printerId;routeChosen=true;}if(a.priority&&!priorityChosen){effective.priority=a.priority;priorityChosen=true;}}const costing=await this.prepareCost(org,effective),quota=await this.checkQuota(org,principal.userId,costing),routing=await this.database.transaction(tx=>resolvePrinterRoute(tx,org,costing));return{policy:{blocked,blockedReason,requiresApproval,applied,effective,approverRoles:[...roles],approverUserIds:[...users],allowSelfApproval},quota,costing,routing};}

  async listAlerts(org,limit=100){return(await this.database.query(`SELECT a.*,u.display_name \"acknowledgedByName\" FROM prn_alerts a LEFT JOIN users u ON u.id=a.acknowledged_by WHERE a.organization_id=$1 ORDER BY (a.resolved_at IS NULL) DESC,CASE a.severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,a.created_at DESC LIMIT $2`,[org,int(limit,1,500,100)])).rows;}
  async acknowledgeAlert(org,userId,alertId){const r=await this.database.query(`UPDATE prn_alerts SET acknowledged_by=$1,acknowledged_at=COALESCE(acknowledged_at,now()),updated_at=now() WHERE id=$2 AND organization_id=$3 RETURNING id,acknowledged_at \"acknowledgedAt\"`,[userId,alertId,org]);if(!r.rows[0])throw fail('ALERT_NOT_FOUND','Printerly alert not found',404);return r.rows[0];}
  async getAlertPreferences(org,userId){const rows=(await this.database.query(`SELECT event_type \"eventType\",enabled,email,sms,whatsapp,updated_at \"updatedAt\" FROM prn_alert_subscriptions WHERE organization_id=$1 AND user_id=$2 ORDER BY event_type`,[org,userId])).rows;return{items:rows};}
  async updateAlertPreferences(org,userId,data={}){const items=Array.isArray(data.items)?data.items:[];return this.database.transaction(async tx=>{for(const x of items.slice(0,100)){const type=String(x.eventType||'').trim();if(!type)continue;await tx.query(`INSERT INTO prn_alert_subscriptions(organization_id,user_id,event_type,enabled,email,sms,whatsapp,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(organization_id,user_id,event_type) DO UPDATE SET enabled=excluded.enabled,email=excluded.email,sms=excluded.sms,whatsapp=excluded.whatsapp,updated_at=now()`,[org,userId,type,x.enabled!==false,x.email!==false,Boolean(x.sms),Boolean(x.whatsapp)]);}return this.getAlertPreferences(org,userId);});}

  async listPools(org){const pools=(await this.database.query(`SELECT id,name,description,strategy,requirements_json \"requirementsJson\",default_auto \"defaultAuto\",active,created_at \"createdAt\",updated_at \"updatedAt\" FROM prn_printer_pools WHERE organization_id=$1 ORDER BY active DESC,default_auto DESC,name`,[org])).rows;for(const p of pools){p.requirements=json(p.requirementsJson,{});p.members=(await this.database.query(`SELECT m.printer_id \"printerId\",m.priority,m.enabled,p.name,p.location,p.status,p.health_status \"healthStatus\",n.name \"nodeName\" FROM prn_printer_pool_members m JOIN prn_printers p ON p.id=m.printer_id AND p.organization_id=m.organization_id LEFT JOIN prn_nodes n ON n.id=p.node_id AND n.organization_id=p.organization_id WHERE m.organization_id=$1 AND m.pool_id=$2 ORDER BY m.priority,p.name`,[org,p.id])).rows;}return pools;}
  async usablePools(org){return(await this.listPools(org)).filter(p=>p.active).map(p=>({id:p.id,name:p.name,description:p.description,strategy:p.strategy,defaultAuto:Boolean(p.defaultAuto),memberCount:p.members.length,readyMembers:p.members.filter(m=>m.enabled&&m.status==='ready'&&m.healthStatus!=='critical').length,requirements:p.requirements}));}
  async poolOptions(org){return{printers:await this.listPrinters(org),strategies:['least_loaded','priority_load'],pageSizes:['A4','A5','Letter','Legal']};}
  async previewPool(org,data={}){return this.database.transaction(tx=>resolvePrinterRoute(tx,org,data));}
  async savePool(org,userId,poolId,data={}){const name=String(data.name||'').trim().slice(0,160);if(!name)throw fail('POOL_NAME_REQUIRED','Enter a printer pool name',422);const strategy=new Set(['least_loaded','priority_load']).has(String(data.strategy))?String(data.strategy):'least_loaded',requirements={color:Boolean(data.requirements?.color),duplex:Boolean(data.requirements?.duplex),pageSizes:arr(data.requirements?.pageSizes)},members=Array.isArray(data.members)?data.members.slice(0,100):[],ids=[...new Set(members.map(x=>String(x.printerId||'')).filter(Boolean))];if(ids.length!==members.length)throw fail('DUPLICATE_POOL_PRINTER','A printer can appear only once in a pool',422);return this.database.transaction(async tx=>{if(ids.length){const found=(await tx.query(`SELECT id FROM prn_printers WHERE organization_id=$1 AND id=ANY($2::text[])`,[org,ids])).rows;if(found.length!==ids.length)throw fail('INVALID_POOL_PRINTER','One or more pool printers do not belong to this organization',422);}const pid=poolId||id('prnpool'),def=Boolean(data.defaultAuto),active=data.active===false?false:true;if(def)await tx.query(`UPDATE prn_printer_pools SET default_auto=false,updated_at=now() WHERE organization_id=$1 AND id<>$2`,[org,pid]);if(poolId){const r=await tx.query(`UPDATE prn_printer_pools SET name=$1,description=$2,strategy=$3,requirements_json=$4,default_auto=$5,active=$6,updated_by=$7,updated_at=now() WHERE id=$8 AND organization_id=$9`,[name,String(data.description||'').slice(0,800)||null,strategy,JSON.stringify(requirements),def,active,userId,pid,org]);if(!r.rowCount)throw fail('PRINTER_POOL_NOT_FOUND','Printer pool not found',404);await tx.query(`DELETE FROM prn_printer_pool_members WHERE organization_id=$1 AND pool_id=$2`,[org,pid]);}else await tx.query(`INSERT INTO prn_printer_pools(id,organization_id,name,description,strategy,requirements_json,default_auto,active,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$9)`,[pid,org,name,String(data.description||'').slice(0,800)||null,strategy,JSON.stringify(requirements),def,active,userId]);for(const m of members)await tx.query(`INSERT INTO prn_printer_pool_members(organization_id,pool_id,printer_id,priority,enabled) VALUES($1,$2,$3,$4,$5)`,[org,pid,String(m.printerId),int(m.priority,1,1000,100),m.enabled!==false]);return{id:pid,name,strategy,requirements,defaultAuto:def,active};});}
  async deactivatePool(org,poolId){const r=await this.database.query(`UPDATE prn_printer_pools SET active=false,default_auto=false,updated_at=now() WHERE id=$1 AND organization_id=$2 AND active=true`,[poolId,org]);if(!r.rowCount)throw fail('PRINTER_POOL_NOT_FOUND','Active printer pool not found',404);return{id:poolId,active:false};}

  async listSecureJobs(org,principal){const all=canAdmin(principal),values=all?[org]:[org,principal.userId],clause=all?`j.organization_id=$1`:`j.organization_id=$1 AND j.created_by=$2`;return(await this.database.query(`SELECT j.id,j.job_number \"jobNumber\",j.title,j.status,j.printer_id \"printerId\",j.route_pool_id \"routePoolId\",j.created_at \"createdAt\",u.display_name \"requesterName\",p.name \"printerName\",p.location \"printerLocation\",r.id \"credentialId\",r.expires_at \"credentialExpiresAt\",r.attempts \"credentialAttempts\",r.max_attempts \"credentialMaxAttempts\",r.locked_at \"credentialLockedAt\" FROM prn_jobs j LEFT JOIN users u ON u.id=j.created_by LEFT JOIN prn_printers p ON p.id=j.printer_id AND p.organization_id=j.organization_id LEFT JOIN LATERAL(SELECT * FROM prn_release_credentials r2 WHERE r2.organization_id=j.organization_id AND r2.job_id=j.id AND r2.used_at IS NULL AND r2.revoked_at IS NULL ORDER BY r2.created_at DESC LIMIT 1)r ON true WHERE ${clause} AND j.secure_release=true AND j.status IN('held','approval_pending') ORDER BY j.created_at DESC LIMIT 250`,values)).rows.map(r=>({...r,credentialActive:Boolean(r.credentialId&&r.credentialExpiresAt&&Date.parse(r.credentialExpiresAt)>Date.now()&&!r.credentialLockedAt)}));}
  async issueCredential(org,principal,jobId,ttl=15){const job=(await this.database.query(`SELECT id,job_number \"jobNumber\",title,status,secure_release \"secureRelease\",created_by \"createdBy\" FROM prn_jobs WHERE id=$1 AND organization_id=$2`,[jobId,org])).rows[0];if(!job)throw fail('PRINT_JOB_NOT_FOUND','Printerly job not found',404);if(!canAdmin(principal)&&job.createdBy!==principal.userId)throw fail('FORBIDDEN','You can issue release credentials only for your own secure jobs',403);const c=await this.runtime.issueReleaseCredential({organizationId:org,userId:principal.userId,jobId,ttlMinutes:int(ttl,2,120,15)});return{...c,id:c.credentialId,jobId,jobNumber:job.jobNumber,title:job.title,qrValue:`printerly-release:${c.token}`};}
  async revokeCredential(org,principal,jobId){const job=(await this.database.query(`SELECT created_by \"createdBy\" FROM prn_jobs WHERE id=$1 AND organization_id=$2`,[jobId,org])).rows[0];if(!job)throw fail('PRINT_JOB_NOT_FOUND','Printerly job not found',404);if(!canAdmin(principal)&&job.createdBy!==principal.userId)throw fail('FORBIDDEN','You can revoke release credentials only for your own jobs',403);await this.database.query(`UPDATE prn_release_credentials SET revoked_at=COALESCE(revoked_at,now()) WHERE organization_id=$1 AND job_id=$2 AND used_at IS NULL AND revoked_at IS NULL`,[org,jobId]);await this.database.query(`INSERT INTO prn_job_events(id,organization_id,job_id,event_type,actor_id,details_json) VALUES($1,$2,$3,'release_credential_revoked',$4,'{}')`,[id('prnev'),org,jobId,principal.userId]);return{jobId,revoked:true};}
}
