import {PrinterlyRuntimeError} from './runtime-service.mjs';
const json=(v,f)=>{try{return v?JSON.parse(String(v)):f}catch{return f}};
const n=(v,d=0)=>Math.max(0,Math.round(Number(v)||d));
const fail=(code,message,status=409)=>Object.assign(new PrinterlyRuntimeError(code,message),{status});
function compatible(row,input,requirements){const c=json(row.capabilities_json,{}),page=String(input.pageSize||'A4'),color=String(input.colorMode||'monochrome')==='color',duplex=Boolean(input.duplex),pages=Array.isArray(c.pageSizes)?c.pageSizes.map(String):Array.isArray(c.page_sizes)?c.page_sizes.map(String):[],modes=Array.isArray(c.colorModes)?c.colorModes.map(String):[];if((color||requirements.color)&&(c.color===false||(modes.length&&!modes.includes('color'))))return false;if((duplex||requirements.duplex)&&c.duplex===false)return false;if(requirements.pageSizes?.length&&!requirements.pageSizes.includes(page))return false;if(pages.length&&!pages.includes(page))return false;return true;}
export async function resolvePrinterRoute(db,organizationId,input={}){
  if(input.printerId){const p=(await db.query(`SELECT id,name FROM prn_printers WHERE id=$1 AND organization_id=$2`,[String(input.printerId),organizationId])).rows[0];if(!p)throw fail('INVALID_PRINTER','Selected printer does not belong to this organization',422);return{printerId:p.id,printerName:p.name,poolId:null,strategy:'explicit',reason:'Explicit printer selection'};}
  let poolId=input.poolId?String(input.poolId):null;if(!poolId)poolId=(await db.query(`SELECT id FROM prn_printer_pools WHERE organization_id=$1 AND active=true AND default_auto=true LIMIT 1`,[organizationId])).rows[0]?.id||null;
  let pool=null,rows=[];if(poolId){pool=(await db.query(`SELECT * FROM prn_printer_pools WHERE id=$1 AND organization_id=$2 AND active=true`,[poolId,organizationId])).rows[0];if(!pool)throw fail('PRINTER_POOL_NOT_FOUND','Printer pool not found or inactive',404);rows=(await db.query(`SELECT p.id,p.name,p.capabilities_json,m.priority,(SELECT COUNT(*) FROM prn_jobs j WHERE j.organization_id=p.organization_id AND j.printer_id=p.id AND j.status IN ('queued','held','approval_pending','claimed','downloading','spooling','printing'))::int active_jobs FROM prn_printer_pool_members m JOIN prn_printers p ON p.id=m.printer_id AND p.organization_id=m.organization_id JOIN prn_nodes n ON n.id=p.node_id AND n.organization_id=p.organization_id WHERE m.organization_id=$1 AND m.pool_id=$2 AND m.enabled=true AND p.status='ready' AND n.status='online' AND COALESCE(p.health_status,'unknown')<>'critical'`,[organizationId,poolId])).rows;}else rows=(await db.query(`SELECT p.id,p.name,p.capabilities_json,100 priority,(SELECT COUNT(*) FROM prn_jobs j WHERE j.organization_id=p.organization_id AND j.printer_id=p.id AND j.status IN ('queued','held','approval_pending','claimed','downloading','spooling','printing'))::int active_jobs FROM prn_printers p JOIN prn_nodes n ON n.id=p.node_id AND n.organization_id=p.organization_id WHERE p.organization_id=$1 AND p.status='ready' AND n.status='online' AND COALESCE(p.health_status,'unknown')<>'critical'`,[organizationId])).rows;
  const requirements=json(pool?.requirements_json,{color:false,duplex:false,pageSizes:[]}),eligible=rows.filter(row=>compatible(row,input,requirements));if(!eligible.length){if(pool)throw fail('PRINTER_POOL_UNAVAILABLE',`No ready printer in ${pool.name} can satisfy this job right now`);return{printerId:null,printerName:null,poolId:null,strategy:'legacy_wait',reason:'No ready smart-routing candidate; keep job available for a later node claim'};}
  const strategy=pool?.strategy||'least_loaded';eligible.sort((a,b)=>strategy==='priority_load'?(n(a.priority,100)-n(b.priority,100))||(n(a.active_jobs)-n(b.active_jobs)):(n(a.active_jobs)-n(b.active_jobs))||(n(a.priority,100)-n(b.priority,100))||String(a.name).localeCompare(String(b.name)));const best=eligible[0];return{printerId:best.id,printerName:best.name,poolId:pool?.id||null,poolName:pool?.name||null,strategy,reason:`${strategy==='least_loaded'?'Least-loaded':'Priority/load'} route · ${best.active_jobs} active job${Number(best.active_jobs)===1?'':'s'} · ${eligible.length} eligible printer${eligible.length===1?'':'s'}`};
}
