import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {tenantStorageKey} from '../contracts.mjs';
import {PrinterlyRuntimeError} from './runtime-service.mjs';

const MAX_SCAN_BYTES=50*1024*1024;
const SCAN_MIME=new Set(['application/pdf','image/png','image/jpeg']);
const MODULE_TARGETS=new Set(['finance','academics','exams','school']);
const id=p=>`${p}_${randomUUID().replaceAll('-','')}`;
const token=()=>randomBytes(32).toString('base64url');
const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
const safeName=name=>{const x=String(name||'scan').normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');return(x||'scan').slice(0,180);};
const fail=(code,message,status=409)=>Object.assign(new PrinterlyRuntimeError(code,message),{status});
const clamp=(value,min,max,fallback)=>{const n=Math.round(Number(value));return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback;};

export async function readScannerMultipartFile(request,{limit=MAX_SCAN_BYTES+1024*1024}={}){
  const contentType=String(request.headers?.['content-type']||request.headers?.get?.('content-type')||'');
  const match=/multipart\/form-data\s*;\s*boundary=(?:"([^"]+)"|([^;\s]+))/i.exec(contentType);if(!match)throw fail('MULTIPART_REQUIRED','Scannerly result upload must use multipart/form-data',415);
  const boundary=Buffer.from(`--${match[1]||match[2]}`),chunks=[];let total=0;
  for await(const chunk of request){const bytes=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=bytes.length;if(total>limit)throw fail('SCAN_TOO_LARGE','Scannerly results are limited to 50 MB',413);chunks.push(bytes);}
  const body=Buffer.concat(chunks);let cursor=0;
  while(true){const start=body.indexOf(boundary,cursor);if(start<0)break;let headStart=start+boundary.length;if(body.subarray(headStart,headStart+2).toString()==='--')break;if(body.subarray(headStart,headStart+2).toString()==='\r\n')headStart+=2;const headerEnd=body.indexOf(Buffer.from('\r\n\r\n'),headStart);if(headerEnd<0)break;const headers=body.subarray(headStart,headerEnd).toString('utf8'),next=body.indexOf(boundary,headerEnd+4);if(next<0)break;const disposition=/content-disposition:\s*form-data;[^\r\n]*name="([^"]+)"(?:;[^\r\n]*filename="([^"]*)")?/i.exec(headers);if(disposition?.[1]==='file'&&disposition[2]!=null){let end=next;if(body.subarray(end-2,end).toString()==='\r\n')end-=2;const bytes=body.subarray(headerEnd+4,end),mime=(/content-type:\s*([^\r\n]+)/i.exec(headers)?.[1]||'application/octet-stream').trim().toLowerCase();return{name:disposition[2],mime,bytes};}cursor=next;}
  throw fail('SCAN_FILE_REQUIRED','Scannerly result file is missing',422);
}

export class PrinterlyScannerService{
  constructor({database,storage}){if(!database?.query||!database?.transaction)throw new TypeError('database is required');if(!storage?.put||!storage?.get||!storage?.delete)throw new TypeError('storage is required');this.database=database;this.storage=storage;}

  async #event(tx,organizationId,scanJobId,eventType,actorId,details={}){await tx.query(`INSERT INTO prn_scan_events(id,organization_id,scan_job_id,event_type,actor_id,details_json) VALUES($1,$2,$3,$4,$5,$6)`,[id('prnsev'),organizationId,scanJobId,eventType,actorId,JSON.stringify(details||{})]);}

  async claim(node,data={}){
    const requested=(Array.isArray(data.scannerSystemNames)?data.scannerSystemNames:[]).map(String).filter(Boolean);if(!requested.length)return null;
    return this.database.transaction(async tx=>{
      await tx.query(`UPDATE prn_scan_jobs SET status='queued',node_id=NULL,claim_token=NULL,claim_expires_at=NULL,updated_at=now() WHERE organization_id=$1 AND status='claimed' AND claim_expires_at IS NOT NULL AND claim_expires_at<=now()`,[node.organization_id]);
      const local=(await tx.query(`SELECT id,system_name FROM prn_scanners WHERE organization_id=$1 AND node_id=$2 AND status='ready' AND system_name=ANY($3::text[])`,[node.organization_id,node.id,requested])).rows;if(!local.length)return null;
      const job=(await tx.query(`SELECT * FROM prn_scan_jobs WHERE organization_id=$1 AND status='queued' AND scanner_id=ANY($2::text[]) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`,[node.organization_id,local.map(x=>x.id)])).rows[0];if(!job)return null;
      const scanner=local.find(x=>x.id===job.scanner_id);if(!scanner)return null;
      const claimToken=token();const moved=(await tx.query(`UPDATE prn_scan_jobs SET status='claimed',node_id=$1,claim_token=$2,claim_expires_at=now()+interval '15 minutes',updated_at=now() WHERE id=$3 AND organization_id=$4 AND status='queued' RETURNING claim_expires_at`,[node.id,claimToken,job.id,node.organization_id])).rows[0];if(!moved)return null;
      await this.#event(tx,node.organization_id,job.id,'claimed',node.id,{scannerId:scanner.id,systemName:scanner.system_name});
      return{...job,status:'claimed',node_id:node.id,scanner_system_name:scanner.system_name,claim_token:claimToken,claim_expires_at:moved.claim_expires_at};
    });
  }

  async status(node,scanJobId,data={}){
    const requested=String(data.status||''),allowed=new Set(['scanning','uploading','failed']);if(!allowed.has(requested))throw fail('INVALID_SCAN_STATUS','Invalid Scannerly status',422);const claimToken=String(data.claimToken||'');
    return this.database.transaction(async tx=>{
      const job=(await tx.query(`SELECT status,claim_token FROM prn_scan_jobs WHERE id=$1 AND organization_id=$2 AND node_id=$3 FOR UPDATE`,[scanJobId,node.organization_id,node.id])).rows[0];if(!job||job.claim_token!==claimToken)throw fail('SCAN_CLAIM_INVALID','Scannerly claim is no longer valid');if(job.status===requested)return{id:scanJobId,status:requested,duplicate:true};
      const transitions={claimed:new Set(['scanning','failed']),scanning:new Set(['uploading','failed']),uploading:new Set(['failed'])};if(!transitions[job.status]?.has(requested))throw fail('INVALID_SCAN_TRANSITION',`Cannot move Scannerly job from ${job.status} to ${requested}`);
      await tx.query(`UPDATE prn_scan_jobs SET status=$1,error_message=$2,claim_expires_at=CASE WHEN $1='failed' THEN NULL ELSE now()+interval '15 minutes' END,updated_at=now() WHERE id=$3 AND organization_id=$4 AND node_id=$5 AND claim_token=$6`,[requested,String(data.errorMessage||'').slice(0,1000),scanJobId,node.organization_id,node.id,claimToken]);
      await this.#event(tx,node.organization_id,scanJobId,requested,node.id,{errorMessage:data.errorMessage||null});return{id:scanJobId,status:requested};
    });
  }

  async upload(node,scanJobId,claimToken,file){
    if(!claimToken)throw fail('SCAN_CLAIM_REQUIRED','Missing Scannerly claim token',401);const bytes=Buffer.from(file?.bytes||[]);if(!bytes.length)throw fail('EMPTY_SCAN','Scannerly result is empty',422);if(bytes.length>MAX_SCAN_BYTES)throw fail('SCAN_TOO_LARGE','Scannerly results are limited to 50 MB',413);const mime=String(file?.mime||'').toLowerCase();if(!SCAN_MIME.has(mime))throw fail('UNSUPPORTED_SCAN_TYPE','Scannerly accepts PDF, PNG or JPEG output',415);
    const current=(await this.database.query(`SELECT j.*,d.id existing_document_id,d.school_file_id existing_school_file_id FROM prn_scan_jobs j LEFT JOIN prn_scan_documents d ON d.scan_job_id=j.id AND d.organization_id=j.organization_id WHERE j.id=$1 AND j.organization_id=$2 AND j.node_id=$3`,[scanJobId,node.organization_id,node.id])).rows[0];
    if(current?.status==='completed'&&current.existing_document_id)return{id:scanJobId,scanNumber:current.scan_number,status:'completed',documentId:current.existing_document_id,schoolFileId:current.existing_school_file_id||null,duplicate:true};
    if(!current||current.claim_token!==claimToken||!['scanning','uploading'].includes(current.status))throw fail('SCAN_CLAIM_INVALID','Scannerly claim is no longer valid');
    const documentId=id('prnscandoc'),created=new Date().toISOString(),name=safeName(file.name||`${current.scan_number}.${current.output_format}`),logicalKey=`printerly/${node.organization_id}/scans/${created.slice(0,7)}/${documentId}/${name}`,physicalKey=tenantStorageKey(node.organization_id,logicalKey),checksum=digest(bytes);
    await this.storage.put(physicalKey,bytes,{contentType:mime,custom:{organizationId:node.organization_id,scanJobId,checksum,originalName:String(file.name||name)}});
    let school=null;
    try{
      if(current.target_type==='student'||current.target_type==='staff')school=await this.#stageSchoolObject(node.organization_id,current,file.name||name,mime,bytes,checksum);
      const result=await this.database.transaction(async tx=>{
        const job=(await tx.query(`SELECT * FROM prn_scan_jobs WHERE id=$1 AND organization_id=$2 AND node_id=$3 FOR UPDATE`,[scanJobId,node.organization_id,node.id])).rows[0];if(!job||job.claim_token!==claimToken||!['scanning','uploading'].includes(job.status))throw fail('SCAN_CLAIM_INVALID','Scannerly claim is no longer valid');
        let schoolFileId=null;
        if(school){schoolFileId=school.fileId;await tx.query(`INSERT INTO school_files(id,organization_id,object_key,original_name,mime_type,size_bytes,checksum_sha256,purpose,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,'scannerly',$8)`,[school.fileId,node.organization_id,school.logicalKey,String(file.name||name),mime,bytes.length,checksum,job.created_by||null]);if(job.target_type==='student')await tx.query(`INSERT INTO school_student_documents(id,organization_id,student_id,document_type,name,object_key,mime_type,size_bytes,checksum,uploaded_by,file_id) VALUES($1,$2,$3,'scannerly',$4,$5,$6,$7,$8,$9,$10)`,[id('stdoc'),node.organization_id,job.target_id,job.title,school.logicalKey,mime,bytes.length,checksum,job.created_by||null,school.fileId]);else await tx.query(`INSERT INTO school_staff_documents(id,organization_id,staff_id,document_type,name,file_id,notes,uploaded_by) VALUES($1,$2,$3,'scannerly',$4,$5,$6,$7)`,[id('stfdoc'),node.organization_id,job.target_id,job.title,school.fileId,job.notes||null,job.created_by||null]);}
        await tx.query(`INSERT INTO prn_scan_documents(id,organization_id,scan_job_id,object_key,original_name,mime_type,size_bytes,checksum_sha256,target_type,target_module,target_id,school_file_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[documentId,node.organization_id,scanJobId,logicalKey,String(file.name||name),mime,bytes.length,checksum,job.target_type,job.target_module||null,job.target_id||null,schoolFileId]);
        const moved=await tx.query(`UPDATE prn_scan_jobs SET status='completed',document_id=$1,error_message=NULL,completed_at=now(),claim_expires_at=NULL,updated_at=now() WHERE id=$2 AND organization_id=$3 AND node_id=$4 AND claim_token=$5`,[documentId,scanJobId,node.organization_id,node.id,claimToken]);if(moved.rowCount!==1)throw fail('SCAN_CLAIM_INVALID','Scannerly job changed during upload');
        await this.#event(tx,node.organization_id,scanJobId,'completed',node.id,{documentId,mime,sizeBytes:bytes.length,schoolFileId});return{id:scanJobId,scanNumber:job.scan_number,status:'completed',documentId,schoolFileId};
      });
      return result;
    }catch(error){await this.storage.delete(physicalKey).catch(()=>{});if(school?.physicalKey)await this.storage.delete(school.physicalKey).catch(()=>{});throw error;}
  }

  async #stageSchoolObject(organizationId,job,originalName,mime,bytes,checksum){const fileId=id('sfl'),date=new Date(),name=safeName(originalName),logicalKey=`school/${organizationId}/${date.getUTCFullYear()}/${String(date.getUTCMonth()+1).padStart(2,'0')}/${fileId}/${name}`,physicalKey=tenantStorageKey(organizationId,logicalKey);await this.storage.put(physicalKey,bytes,{contentType:mime,custom:{organizationId,fileId,purpose:'scannerly',checksum}});return{fileId,logicalKey,physicalKey};}

  async listScanners(organizationId){const rows=(await this.database.query(`SELECT s.id,s.node_id "nodeId",s.name,s.system_name "systemName",s.status,s.capabilities_json "capabilitiesJson",s.last_seen_at "lastSeenAt",n.name "nodeName",n.location "nodeLocation" FROM prn_scanners s LEFT JOIN prn_nodes n ON n.id=s.node_id AND n.organization_id=s.organization_id WHERE s.organization_id=$1 ORDER BY s.name`,[organizationId])).rows;return rows.map(r=>({...r,capabilities:this.#json(r.capabilitiesJson,{})}));}

  async create({organizationId,userId,data={}}){const scannerId=String(data.scannerId||'').trim();if(!scannerId)throw fail('SCANNER_REQUIRED','Choose a scanner',422);const scanner=(await this.database.query(`SELECT id,node_id,status FROM prn_scanners WHERE id=$1 AND organization_id=$2`,[scannerId,organizationId])).rows[0];if(!scanner)throw fail('INVALID_SCANNER','Selected scanner does not belong to this organization',422);if(scanner.status!=='ready')throw fail('SCANNER_OFFLINE','Selected scanner is not currently ready');const source=String(data.source)==='adf'?'adf':'flatbed',colorMode=new Set(['color','gray','lineart']).has(String(data.colorMode))?String(data.colorMode):'color',resolution=clamp(data.resolutionDpi,75,1200,300),pageSize=new Set(['A4','A5','Letter','Legal']).has(String(data.pageSize))?String(data.pageSize):'A4';let outputFormat=new Set(['pdf','png','jpeg']).has(String(data.outputFormat))?String(data.outputFormat):'pdf';if(source==='adf')outputFormat='pdf';const targetType=new Set(['inbox','student','staff','module']).has(String(data.targetType))?String(data.targetType):'inbox',targetId=data.targetId?String(data.targetId):null,targetModule=data.targetModule?String(data.targetModule):null;if(targetType==='student'){if(!targetId||!((await this.database.query(`SELECT 1 FROM school_students WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[targetId,organizationId])).rows[0]))throw fail('INVALID_SCAN_TARGET','Choose a valid student for this scan',422);}else if(targetType==='staff'){if(!targetId||!((await this.database.query(`SELECT 1 FROM school_staff_profiles WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[targetId,organizationId])).rows[0]))throw fail('INVALID_SCAN_TARGET','Choose a valid staff member for this scan',422);}else if(targetType==='module'&&!MODULE_TARGETS.has(targetModule||''))throw fail('INVALID_SCAN_TARGET','Choose a Ledgerly destination module',422);const scanId=id('prnscan'),created=new Date(),scanNumber=`SCN-${created.getUTCFullYear()}-${scanId.slice(-8).toUpperCase()}`;await this.database.transaction(async tx=>{await tx.query(`INSERT INTO prn_scan_jobs(id,organization_id,scan_number,title,scanner_id,status,source,color_mode,resolution_dpi,page_size,output_format,target_type,target_module,target_id,notes,created_by) VALUES($1,$2,$3,$4,$5,'queued',$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[scanId,organizationId,scanNumber,String(data.title||'Scanned document').trim().slice(0,200),scannerId,source,colorMode,resolution,pageSize,outputFormat,targetType,targetModule,targetId,String(data.notes||'').slice(0,1000),userId]);await this.#event(tx,organizationId,scanId,'created',userId,{scannerId,source,colorMode,resolution,pageSize,outputFormat,targetType,targetModule,targetId});});return{id:scanId,scanNumber,status:'queued'};}

  async list(organizationId,limit=150){return(await this.database.query(`SELECT j.id,j.scan_number "scanNumber",j.title,j.scanner_id "scannerId",s.name "scannerName",j.node_id "nodeId",j.status,j.source,j.color_mode "colorMode",j.resolution_dpi "resolutionDpi",j.page_size "pageSize",j.output_format "outputFormat",j.target_type "targetType",j.target_module "targetModule",j.target_id "targetId",j.notes,j.error_message "errorMessage",j.document_id "documentId",j.created_at "createdAt",j.completed_at "completedAt",d.original_name "documentName",d.mime_type "mimeType",d.size_bytes "sizeBytes",d.school_file_id "schoolFileId" FROM prn_scan_jobs j LEFT JOIN prn_scanners s ON s.id=j.scanner_id AND s.organization_id=j.organization_id LEFT JOIN prn_scan_documents d ON d.id=j.document_id AND d.organization_id=j.organization_id WHERE j.organization_id=$1 ORDER BY j.created_at DESC LIMIT $2`,[organizationId,clamp(limit,1,300,150)])).rows;}
  async cancel({organizationId,userId,scanJobId}){return this.database.transaction(async tx=>{const job=(await tx.query(`SELECT status FROM prn_scan_jobs WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[scanJobId,organizationId])).rows[0];if(!job)throw fail('SCAN_JOB_NOT_FOUND','Scannerly job not found',404);if(job.status==='cancelled')return{id:scanJobId,status:'cancelled',duplicate:true};if(job.status!=='queued')throw fail('INVALID_SCAN_STATE','Only queued Scannerly jobs can be cancelled');await tx.query(`UPDATE prn_scan_jobs SET status='cancelled',updated_at=now() WHERE id=$1 AND organization_id=$2`,[scanJobId,organizationId]);await this.#event(tx,organizationId,scanJobId,'cancelled',userId,{});return{id:scanJobId,status:'cancelled'};});}
  async retry({organizationId,userId,scanJobId}){return this.database.transaction(async tx=>{const job=(await tx.query(`SELECT status FROM prn_scan_jobs WHERE id=$1 AND organization_id=$2 FOR UPDATE`,[scanJobId,organizationId])).rows[0];if(!job)throw fail('SCAN_JOB_NOT_FOUND','Scannerly job not found',404);if(job.status!=='failed')throw fail('INVALID_SCAN_STATE','Only failed Scannerly jobs can be retried');await tx.query(`UPDATE prn_scan_jobs SET status='queued',node_id=NULL,claim_token=NULL,claim_expires_at=NULL,error_message=NULL,updated_at=now() WHERE id=$1 AND organization_id=$2`,[scanJobId,organizationId]);await this.#event(tx,organizationId,scanJobId,'retried',userId,{});return{id:scanJobId,status:'queued'};});}

  async targets(organizationId,query=''){const q=`%${String(query||'').trim().slice(0,80)}%`;const [students,staff,modules]=await Promise.all([this.database.query(`SELECT id,admission_number "admissionNumber",student_number "studentNumber",TRIM(first_name||' '||COALESCE(middle_name||' ','')||last_name) name FROM school_students WHERE organization_id=$1 AND deleted_at IS NULL AND status='active' AND ($2='%%' OR admission_number ILIKE $2 OR student_number ILIKE $2 OR first_name ILIKE $2 OR last_name ILIKE $2) ORDER BY first_name,last_name LIMIT 200`,[organizationId,q]).catch(()=>({rows:[]})),this.database.query(`SELECT id,staff_number "staffNumber",TRIM(first_name||' '||COALESCE(middle_name||' ','')||last_name) name FROM school_staff_profiles WHERE organization_id=$1 AND deleted_at IS NULL AND employment_status IN ('active','on_leave') AND ($2='%%' OR staff_number ILIKE $2 OR first_name ILIKE $2 OR last_name ILIKE $2) ORDER BY first_name,last_name LIMIT 200`,[organizationId,q]).catch(()=>({rows:[]})),this.database.query(`SELECT module_key id FROM organization_modules WHERE organization_id=$1 AND enabled=true`,[organizationId]).catch(()=>({rows:[]}))]);const names={finance:'Finance',academics:'Academics',exams:'Examinations',school:'School Management'};return{students:students.rows,staff:staff.rows,modules:modules.rows.filter(x=>MODULE_TARGETS.has(x.id)).map(x=>({id:x.id,name:names[x.id]||x.id}))};}
  async inbox(organizationId,moduleKey,limit=80){const module=String(moduleKey||'').trim();if(!MODULE_TARGETS.has(module))throw fail('INVALID_SCAN_MODULE','Choose Finance, Academics, Examinations or School Management',422);return(await this.database.query(`SELECT j.id,j.scan_number "scanNumber",j.title,j.notes,j.completed_at "completedAt",j.created_at "createdAt",s.name "scannerName",d.id "documentId",d.original_name "documentName",d.mime_type "mimeType",d.size_bytes "sizeBytes" FROM prn_scan_jobs j JOIN prn_scan_documents d ON d.scan_job_id=j.id AND d.organization_id=j.organization_id LEFT JOIN prn_scanners s ON s.id=j.scanner_id AND s.organization_id=j.organization_id WHERE j.organization_id=$1 AND j.status='completed' AND j.target_type='module' AND j.target_module=$2 ORDER BY COALESCE(j.completed_at,j.created_at) DESC LIMIT $3`,[organizationId,module,clamp(limit,1,200,80)])).rows;}
  async getDocument(organizationId,documentId){const row=(await this.database.query(`SELECT object_key,original_name,mime_type,size_bytes,checksum_sha256 FROM prn_scan_documents WHERE id=$1 AND organization_id=$2`,[documentId,organizationId])).rows[0];if(!row)throw fail('SCAN_DOCUMENT_NOT_FOUND','Scannerly document not found',404);const physicalKey=tenantStorageKey(organizationId,row.object_key);let bytes;try{bytes=await this.storage.get(physicalKey);}catch{throw fail('SCAN_OBJECT_MISSING','Scannerly document is missing from object storage',404);}const actual=digest(bytes);if(actual!==row.checksum_sha256)throw fail('SCAN_CHECKSUM_MISMATCH','Scannerly document checksum validation failed');return{bytes:Buffer.from(bytes),originalName:row.original_name,mimeType:row.mime_type,sizeBytes:Number(row.size_bytes),checksum:actual};}
  async summary(organizationId){const [scanners,jobs]=await Promise.all([this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='ready')::int ready FROM prn_scanners WHERE organization_id=$1`,[organizationId]),this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status IN ('queued','claimed','scanning','uploading'))::int active,COUNT(*) FILTER(WHERE status='completed')::int completed FROM prn_scan_jobs WHERE organization_id=$1`,[organizationId])]);return{scanners:scanners.rows[0]||{},jobs:jobs.rows[0]||{}};}
  #json(value,fallback){try{return value?JSON.parse(String(value)):fallback;}catch{return fallback;}}
}

export {MAX_SCAN_BYTES,SCAN_MIME};
