import {SafeAreaView,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import type {DevicePurpose} from "./devicePurpose";
const OPTIONS:{value:DevicePurpose;title:string;copy:string}[]=[
 {value:"normal",title:"Normal Ledgerly device",copy:"Use the full Ledgerly Mobile workspace."},
 {value:"attendance-kiosk",title:"Attendance kiosk",copy:"Turn this device into a dedicated attendance terminal."},
 {value:"security-camera",title:"Security camera",copy:"Pair this phone by QR and use it as an always-on CCTV camera."},
];
export function DevicePurposeScreen({onSelect}:{onSelect:(purpose:DevicePurpose)=>void}){return <SafeAreaView style={s.root}><View style={s.wrap}><View style={s.brand}><View style={s.mark}><Text style={s.markText}>L</Text></View><Text style={s.brandText}>Ledgerly Mobile</Text></View><Text style={s.title}>Choose device purpose</Text><Text style={s.copy}>You can dedicate old Android phones to attendance or security while keeping the same Ledgerly architecture.</Text><View style={s.options}>{OPTIONS.map(o=><TouchableOpacity key={o.value} style={s.option} activeOpacity={.82} onPress={()=>onSelect(o.value)}><View style={s.radio}/><View style={{flex:1}}><Text style={s.optionTitle}>{o.title}</Text><Text style={s.optionCopy}>{o.copy}</Text></View></TouchableOpacity>)}</View><Text style={s.note}>Security cameras are added by scanning a one-time QR code created from Ledgerly Security.</Text></View></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#071c16"},wrap:{flex:1,padding:24,justifyContent:"center"},brand:{flexDirection:"row",alignItems:"center",gap:11,marginBottom:32},mark:{width:44,height:44,borderRadius:13,backgroundColor:"#19955f",alignItems:"center",justifyContent:"center"},markText:{color:"white",fontSize:23,fontWeight:"900"},brandText:{color:"white",fontSize:18,fontWeight:"900"},title:{color:"white",fontSize:30,fontWeight:"900",letterSpacing:-.6},copy:{color:"#a8c1b6",fontSize:14,lineHeight:21,marginTop:9,marginBottom:22},options:{gap:11},option:{flexDirection:"row",alignItems:"center",gap:13,backgroundColor:"#102c23",borderWidth:1,borderColor:"#244b3c",borderRadius:17,padding:17},radio:{width:20,height:20,borderRadius:10,borderWidth:2,borderColor:"#79d3a8"},optionTitle:{color:"white",fontSize:16,fontWeight:"900"},optionCopy:{color:"#9eb7ac",fontSize:12,lineHeight:18,marginTop:4},note:{color:"#72a18c",fontSize:11,lineHeight:17,marginTop:20}});
