import { createHash } from 'node:crypto';
import { createPrivacyProjector } from './privacy.mjs';
function stable(value){if(Array.isArray(value))return `[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;return JSON.stringify(value);}
function hash(value){return createHash('sha256').update(stable(value)).digest('hex');}
function key(m,c){return `${m}:${c}`;}
export class MobileSyncService{
 constructor({repository,collections=[],privacyProjector=createPrivacyProjector(),maxPush=250,maxPull=500}){if(!repository)throw new TypeError('mobile sync repository required');this.repository=repository;this.collections=new Map();for(const item of collections)this.registerCollection(item);this.privacyProjector=privacyProjector;this.maxPush=Math.max(1,Math.min(maxPush,1000));this.maxPull=Math.max(1,Math.min(maxPull,1000));}
 registerCollection(def){if(!def?.moduleKey||!def?.collectionKey||typeof def.canRead!=='function')throw new TypeError('sync collection requires moduleKey, collectionKey and canRead');this.collections.set(key(def.moduleKey,def.collectionKey),Object.freeze({...def}));}
 async #device({organizationId,userId,deviceId}){const device=await this.repository.getDevice({organizationId,userId,deviceId});if(!device)throw Object.assign(new Error('sync device not found or unauthorized'),{code:'SYNC_DEVICE_UNAUTHORIZED'});return device;}
 async push({organizationId,userId,deviceId,batchUuid,operations}){await this.#device({organizationId,userId,deviceId});if(!batchUuid||!Array.isArray(operations)||operations.length===0)throw new TypeError('batchUuid and operations are required');if(operations.length>this.maxPush)throw Object.assign(new Error('push batch too large'),{code:'SYNC_BATCH_TOO_LARGE'});const requestHash=hash({organizationId,userId,deviceId,batchUuid,operations});const prior=await this.repository.getBatch({organizationId,deviceId,batchUuid});if(prior){if(prior.request_hash!==requestHash)throw Object.assign(new Error('batch idempotency mismatch'),{code:'SYNC_IDEMPOTENCY_MISMATCH'});return {...prior.result,duplicate:true};}const ordered=[...operations].sort((a,b)=>Number(a.sequenceNumber)-Number(b.sequenceNumber));const batch=await this.repository.beginBatch({organizationId,deviceId,batchUuid,requestHash,operations:ordered});const results=[];for(const op of ordered){const def=this.collections.get(key(op.moduleKey,op.collectionKey));if(!def||typeof def.apply!=='function'){results.push(await this.repository.rejectOperation({organizationId,deviceId,batchId:batch.id,operation:op,requestHash:hash(op),code:'SYNC_COLLECTION_READ_ONLY',message:'collection does not accept mobile mutations'}));continue;}const result=await this.repository.applyOperation({organizationId,userId,deviceId,batchId:batch.id,operation:op,requestHash:hash(op),apply:({transaction,currentVersion,nextVersion})=>def.apply({transaction,organizationId,userId,deviceId,operation:op,currentVersion,nextVersion})});results.push(result);}const result={batchId:batch.id,results};await this.repository.completeBatch({organizationId,deviceId,batchId:batch.id,result});return result;}
 async pull({organizationId,userId,deviceId,moduleKey,collectionKey,cursor=0,limit=this.maxPull,requestId}){await this.#device({organizationId,userId,deviceId});const def=this.collections.get(key(moduleKey,collectionKey));if(!def)throw Object.assign(new Error('sync collection unavailable'),{code:'SYNC_COLLECTION_UNAVAILABLE'});const bounded=Math.max(1,Math.min(Number(limit)||this.maxPull,this.maxPull));const changes=await this.repository.listChanges({organizationId,moduleKey,collectionKey,afterChangeId:Number(cursor)||0,limit:bounded});const visible=[];for(const change of changes){if(!await def.canRead({organizationId,userId,deviceId,recordId:change.record_id,change}))continue;let payload=null;if(change.operation!=='delete'&&change.payload_json){const parsed=typeof change.payload_json==='string'?JSON.parse(change.payload_json):change.payload_json;payload=this.privacyProjector(moduleKey,collectionKey,parsed);}visible.push({changeId:Number(change.change_id),recordId:change.record_id,version:Number(change.version),operation:change.operation,payload,changedAt:change.changed_at});}const toChangeId=changes.length?Number(changes.at(-1).change_id):Number(cursor)||0;const delivery=await this.repository.recordPullDelivery({organizationId,deviceId,requestId:requestId||`pull:${moduleKey}:${collectionKey}:${cursor}:${toChangeId}`,moduleKey,collectionKey,fromChangeId:Number(cursor)||0,toChangeId,payloadCount:visible.length});return{items:visible,cursor:toChangeId,hasMore:changes.length===bounded,deliveryId:delivery.id};}
 async acknowledgePull({organizationId,userId,deviceId,deliveryId}){await this.#device({organizationId,userId,deviceId});return this.repository.acknowledgePull({organizationId,deviceId,deliveryId});}
}
