import {execFile} from "node:child_process";import {promisify} from "node:util";import {mkdir,readFile,writeFile,rm} from "node:fs/promises";import path from "node:path";import process from "node:process";
const exec=promisify(execFile),root=process.env.PRINTERLY_HOME||"/etc/printerly",stateFile=path.join(root,"state.json"),configFile=process.env.PRINTERLY_CONFIG||path.join(root,"config.json");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let config,state={};
async function load(){config=JSON.parse(await readFile(configFile,"utf8"));await mkdir(config.workDir||"/var/lib/printerly/jobs",{recursive:true});state=JSON.parse(await readFile(stateFile,"utf8").catch(()=>"{}"))}
async function save(){await mkdir(root,{recursive:true});await writeFile(stateFile,JSON.stringify(state,null,2),{mode:0o600})}
async function request(route,body={},auth=true){const headers={"Content-Type":"application/json"};if(auth&&state.nodeToken)headers.Authorization=`Bearer ${state.nodeToken}`;const r=await fetch(`${config.ledgerlyBaseUrl.replace(/\/$/,"")}/api/v1/printerly${route}`,{method:"POST",headers,body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error?.message||j?.message||`${route}: HTTP ${r.status}`);return j.data}
async function printers(){try{const {stdout}=await exec("lpstat",["-p"]);return stdout.split("\n").filter(Boolean).map(line=>{const m=line.match(/^printer\s+(\S+)\s+(.*)$/);if(!m)return null;return{id:m[1],name:m[1],systemName:m[1],status:/disabled/i.test(m[2])?"offline":"ready",capabilities:{cups:true}}}).filter(Boolean)}catch{return[]}}
async function pair(){if(state.nodeToken)return;if(!config.pairingCode)throw new Error("No pairingCode configured");const data=await request("/node/pair",{pairingCode:String(config.pairingCode).replace(/\s/g,""),version:"1.0.0"},false);state={...state,...data};delete config.pairingCode;await save();console.log(`Paired Printerly Node ${data.nodeId}`)}
async function heartbeat(){try{await request("/node/heartbeat",{version:"1.0.0",printers:await printers()})}catch(e){console.error("heartbeat",e.message)}}
async function status(job,s,errorMessage=""){await request(`/node/jobs/${job.id}/status`,{status:s,claimToken:job.claim_token,errorMessage})}
async function processJob(job){const dir=config.workDir||"/var/lib/printerly/jobs",file=path.join(dir,`${job.id}.pdf`);try{await status(job,"downloading");const r=await fetch(job.document_url);if(!r.ok)throw new Error(`Document download failed: HTTP ${r.status}`);await writeFile(file,Buffer.from(await r.arrayBuffer()));await status(job,"spooling");const args=[];if(job.printer_id)args.push("-d",job.printer_id);args.push("-n",String(job.copies||1));if(job.page_size)args.push("-o",`media=${job.page_size}`);args.push("-o",job.duplex?"sides=two-sided-long-edge":"sides=one-sided");if(job.color_mode==="monochrome")args.push("-o","ColorModel=Gray");args.push(file);const{stdout}=await exec("lp",args);await status(job,"printing");console.log(stdout.trim());await status(job,"completed");}catch(e){console.error(`job ${job.id}`,e);try{await status(job,"failed",String(e.message||e))}catch{}}finally{await rm(file,{force:true}).catch(()=>{})}}
async function loop(){await load();await pair();await heartbeat();setInterval(()=>void heartbeat(),config.heartbeatIntervalMs||15000);for(;;){try{const p=await printers(),job=await request("/node/jobs/claim",{printerIds:p.filter(x=>x.status==="ready").map(x=>x.id)});if(job)await processJob(job);else await sleep(config.pollIntervalMs||3000)}catch(e){console.error("poll",e.message);await sleep(Math.max(5000,config.pollIntervalMs||3000))}}}
loop().catch(e=>{console.error(e);process.exit(1)});
