function error(status,code,message){throw Object.assign(new Error(message),{status,code});}
function object(value){if(!value||typeof value!=='object'||Array.isArray(value))error(422,'VALIDATION_ERROR','Payload must be an object');return value;}
function stableId(value,label){const id=String(value??'').trim();if(id.length<3||id.length>200||/\s/.test(id))error(422,'VALIDATION_ERROR',`${label} has an invalid stable id`);return id;}
function text(value,max=Infinity){if(value==null)return null;const v=String(value);if(v.length>max)error(422,'VALIDATION_ERROR',`Text exceeds ${max} characters`);return v;}
function required(value,label,max=Infinity){const v=String(value??'').trim();if(!v)error(422,'VALIDATION_ERROR',`${label} is required`);if(v.length>max)error(422,'VALIDATION_ERROR',`${label} exceeds ${max} characters`);return v;}
function positive(value,label,{nullable=false}={}){if((value==null||value==='')&&nullable)return null;const n=Number(value);if(!Number.isInteger(n)||n<1)error(422,'VALIDATION_ERROR',`${label} must be a positive integer`);return n;}
function enumValue(value,values,label,{optional=false}={}){if((value==null||value==='')&&optional)return null;const v=String(value);if(!values.includes(v))error(422,'VALIDATION_ERROR',`${label} is invalid`);return v;}
function dateValue(value,label,{optional=false}={}){if((value==null||value==='')&&optional)return null;const v=String(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(v))error(422,'VALIDATION_ERROR',`${label} must use YYYY-MM-DD`);return v;}
function only(payload,allowed){for(const key of Object.keys(payload))if(!allowed.has(key))error(422,'VALIDATION_ERROR',`Unsupported field: ${key}`);}
function parseScopes(value){if(Array.isArray(value))return value.map(String);if(!value)return[];try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return parsed.map(String);}catch{}return String(value).split(',').map(v=>v.trim()).filter(Boolean);}
function camel(row){const out={};for(const[k,v]of Object.entries(row??{}))out[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]=v;delete out.organizationId;return out;}
async function membership(database,organizationId,userId){return(await database.query('SELECT role,scopes FROM memberships WHERE organization_id=$1 AND user_id=$2 LIMIT 1',[organizationId,userId])).rows[0]??null;}
export async function hasAcademicsPermission(database,organizationId,userId,permission){
  const m=await membership(database,organizationId,userId);if(!m)return false;
  if(['owner','admin','super_admin'].includes(m.role))return true;
  const scopes=parseScopes(m.scopes);if(scopes.includes('*')||scopes.includes('school:*')||scopes.includes(permission)||(scopes.includes('school:write')&&permission.endsWith(':write')))return true;
  const r=await database.query(`SELECT 1 FROM school_user_roles ur JOIN school_role_permissions rp ON rp.organization_id=ur.organization_id AND rp.role_id=ur.role_id WHERE ur.organization_id=$1 AND ur.user_id=$2 AND rp.permission=$3 AND rp.effect='allow' AND (ur.starts_at IS NULL OR ur.starts_at<=now()) AND (ur.ends_at IS NULL OR ur.ends_at>=now()) UNION ALL SELECT 1 FROM school_temporary_permissions tp WHERE tp.organization_id=$1 AND tp.user_id=$2 AND tp.permission=$3 AND tp.revoked_at IS NULL AND tp.starts_at<=now() AND tp.ends_at>=now() LIMIT 1`,[organizationId,userId,permission]);
  return r.rowCount>0;
}
async function requireRead(database,organizationId,userId){if(!await hasAcademicsPermission(database,organizationId,userId,'school.academics:read'))error(403,'SYNC_FORBIDDEN','school.academics:read permission required');}
async function requireWrite(database,organizationId,userId){if(!await hasAcademicsPermission(database,organizationId,userId,'school.academics:write'))error(403,'SYNC_FORBIDDEN','school.academics:write permission required');}
async function moduleEnabled(database,organizationId){const r=await database.query(`SELECT 1 FROM organization_modules WHERE organization_id=$1 AND module_key='academics' AND enabled=true LIMIT 1`,[organizationId]);return r.rowCount>0;}
async function canManageTeacher(database,organizationId,userId,teacherUserId){if(teacherUserId===userId)return true;return await hasAcademicsPermission(database,organizationId,userId,'school.academics:approve')||await hasAcademicsPermission(database,organizationId,userId,'school.academics:supervise');}
async function own(database,organizationId,userId,teacherUserId){if(!await canManageTeacher(database,organizationId,userId,teacherUserId))error(403,'SYNC_FORBIDDEN','This academic record belongs to another teacher');}
const ORG_TABLES=new Set(['school_academic_years','school_terms','school_classes','school_streams','school_subjects','acad_lesson_plan_templates','acad_timetable_entries','acad_scheme_items','att_sessions']);
async function orgRef(database,table,id,organizationId,label,{optional=false}={}){if((id==null||id==='')&&optional)return null;if(!ORG_TABLES.has(table))throw new TypeError('Unsafe Academics reference table');const value=required(id,label);const r=await database.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2 LIMIT 1`,[value,organizationId]);if(!r.rows[0])error(422,'INVALID_REFERENCE',`${label} does not belong to this organization`);return value;}
async function teacherRef(database,teacherUserId,organizationId){const r=await database.query(`SELECT 1 FROM school_staff_profiles WHERE organization_id=$1 AND user_id=$2 AND is_teacher=true AND employment_status='active' AND deleted_at IS NULL LIMIT 1`,[organizationId,teacherUserId]);if(!r.rows[0])error(422,'INVALID_TEACHER','Teacher is not an active teacher in this organization');}
function suppressionKey(organizationId,collectionKey,recordId){return `${organizationId}:${collectionKey}:${recordId}`;}
async function suppress(transaction,organizationId,collectionKey,recordId){await transaction.query(`SELECT set_config('ledgerly.academics_mobile_sync_suppression',$1,true)`,[suppressionKey(organizationId,collectionKey,recordId)]);}
async function clearSuppression(transaction){await transaction.query(`SELECT set_config('ledgerly.academics_mobile_sync_suppression','',true)`);}
async function recalcCoverage(transaction,organizationId,schemeId){await transaction.query(`UPDATE acad_schemes SET coverage_percent=COALESCE((SELECT ROUND(100.0*SUM(CASE WHEN coverage_status='covered' THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0),1) FROM acad_scheme_items WHERE scheme_id=$1 AND organization_id=$2),0),updated_at=now() WHERE id=$1 AND organization_id=$2`,[schemeId,organizationId]);}

const READ_TARGETS=Object.freeze({
  schemes:['acad_schemes',null],
  'scheme-items':['acad_scheme_items',null],
  templates:['acad_lesson_plan_templates',null],
  'lesson-plans':['acad_lesson_plans',null],
  deliveries:['acad_lesson_deliveries',null],
});
const SCHEDULING=Object.freeze({room:'acad_rooms',availability:'acad_teacher_availability',timetable:'acad_timetables',entry:'acad_timetable_entries',change:'acad_timetable_changes',substitute:'acad_substitute_lessons',allocation:'school_staff_teaching_assignments'});
const SUPERVISION=Object.freeze({observation:'acad_observations',inspection:'acad_inspections'});
async function recordExists(database,organizationId,collectionKey,recordId){
  if(collectionKey==='actions')return true;
  if(collectionKey==='scheduling'||collectionKey==='supervision'){
    const split=String(recordId).indexOf(':');if(split<1)return false;const kind=String(recordId).slice(0,split),id=String(recordId).slice(split+1),map=collectionKey==='scheduling'?SCHEDULING:SUPERVISION,table=map[kind];if(!table)return false;
    return (await database.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2 LIMIT 1`,[id,organizationId])).rowCount>0;
  }
  const table=READ_TARGETS[collectionKey]?.[0];if(!table)return false;return(await database.query(`SELECT 1 FROM ${table} WHERE id=$1 AND organization_id=$2 LIMIT 1`,[recordId,organizationId])).rowCount>0;
}
export async function canReadAcademicsSync(database,{organizationId,userId,collectionKey,recordId,change}){
  if(!await moduleEnabled(database,organizationId))return false;
  if(!await hasAcademicsPermission(database,organizationId,userId,'school.academics:read'))return false;
  if(change?.operation==='delete')return true;
  return recordExists(database,organizationId,collectionKey,recordId);
}

const schemeCreateFields=new Set(['academicYearId','termId','classId','streamId','subjectId','teacherUserId','title','teacherReflection']);
const schemeEditFields=new Set(['title','teacherReflection']);
export async function applyAcademicsSchemeSync({transaction,organizationId,userId,operation,currentVersion}){
  await requireWrite(transaction,organizationId,userId);if(operation.kind==='delete')error(409,'SERVER_MANAGED_LIFECYCLE','Schemes cannot be deleted offline');
  const recordId=stableId(operation.recordId,'Scheme'),payload=object(operation.payload??{}),old=(await transaction.query('SELECT * FROM acad_schemes WHERE id=$1 AND organization_id=$2 FOR UPDATE',[recordId,organizationId])).rows[0]??null;
  if(!old){
    if(Number(currentVersion)!==0)error(409,'RECORD_MISSING','Scheme no longer exists');only(payload,schemeCreateFields);
    const teacher=String(payload.teacherUserId??userId);await own(transaction,organizationId,userId,teacher);await teacherRef(transaction,teacher,organizationId);
    const academicYearId=await orgRef(transaction,'school_academic_years',payload.academicYearId,organizationId,'Academic year'),termId=await orgRef(transaction,'school_terms',payload.termId,organizationId,'Term'),classId=await orgRef(transaction,'school_classes',payload.classId,organizationId,'Class'),subjectId=await orgRef(transaction,'school_subjects',payload.subjectId,organizationId,'Subject'),streamId=await orgRef(transaction,'school_streams',payload.streamId,organizationId,'Stream',{optional:true});
    await suppress(transaction,organizationId,'schemes',recordId);await transaction.query(`INSERT INTO acad_schemes(id,organization_id,academic_year_id,term_id,class_id,stream_id,subject_id,teacher_user_id,title,status,version_no,teacher_reflection,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',1,$10,$11,$12,$12)`,[recordId,organizationId,academicYearId,termId,classId,streamId,subjectId,teacher,required(payload.title,'Title',250),text(payload.teacherReflection,10000),userId,operation.clientTimestamp??new Date().toISOString()]);await clearSuppression(transaction);
  }else{
    await own(transaction,organizationId,userId,String(old.teacher_user_id));if(!['draft','rejected'].includes(String(old.status)))error(409,'SCHEME_LOCKED','Only draft or rejected schemes can be edited offline');only(payload,schemeEditFields);const sets=[],values=[];
    if(Object.hasOwn(payload,'title')){values.push(required(payload.title,'Title',250));sets.push(`title=$${values.length}`);}if(Object.hasOwn(payload,'teacherReflection')){values.push(text(payload.teacherReflection,10000));sets.push(`teacher_reflection=$${values.length}`);}if(!sets.length)error(422,'VALIDATION_ERROR','No scheme changes supplied');values.push(recordId,organizationId);await suppress(transaction,organizationId,'schemes',recordId);await transaction.query(`UPDATE acad_schemes SET ${sets.join(',')},updated_at=now() WHERE id=$${values.length-1} AND organization_id=$${values.length}`,values);await clearSuppression(transaction);
  }
  const saved=(await transaction.query('SELECT * FROM acad_schemes WHERE id=$1 AND organization_id=$2',[recordId,organizationId])).rows[0];return{payload:camel(saved),result:{id:recordId}};
}

const itemFields=new Set(['schemeId','sequenceNo','weekNo','lessonNo','topic','subtopic','learningObjectives','competencies','teachingMethods','learningMaterials','referencesText','plannedActivities','assessmentActivities','plannedDate','coverageStatus','teacherReflection']);
const itemMap=Object.freeze({sequenceNo:'sequence_no',weekNo:'week_no',lessonNo:'lesson_no',topic:'topic',subtopic:'subtopic',learningObjectives:'learning_objectives',competencies:'competencies',teachingMethods:'teaching_methods',learningMaterials:'learning_materials',referencesText:'references_text',plannedActivities:'planned_activities',assessmentActivities:'assessment_activities',plannedDate:'planned_date',coverageStatus:'coverage_status',teacherReflection:'teacher_reflection'});
export async function applyAcademicsSchemeItemSync({transaction,organizationId,userId,operation,currentVersion}){
  await requireWrite(transaction,organizationId,userId);const recordId=stableId(operation.recordId,'Scheme item'),payload=object(operation.payload??{});only(payload,itemFields);
  const old=(await transaction.query('SELECT * FROM acad_scheme_items WHERE id=$1 AND organization_id=$2 FOR UPDATE',[recordId,organizationId])).rows[0]??null,schemeId=String(old?.scheme_id??payload.schemeId??'');if(!schemeId)error(422,'VALIDATION_ERROR','schemeId is required');
  const scheme=(await transaction.query('SELECT * FROM acad_schemes WHERE id=$1 AND organization_id=$2 FOR UPDATE',[schemeId,organizationId])).rows[0];if(!scheme)error(404,'SCHEME_NOT_FOUND','Scheme not found');await own(transaction,organizationId,userId,String(scheme.teacher_user_id));if(!['draft','rejected'].includes(String(scheme.status)))error(409,'SCHEME_LOCKED','Scheme items can only change while the scheme is draft or rejected');
  if(operation.kind==='delete'){
    if(!old)error(404,'SCHEME_ITEM_NOT_FOUND','Scheme item not found');await suppress(transaction,organizationId,'scheme-items',recordId);await transaction.query('DELETE FROM acad_scheme_items WHERE id=$1 AND organization_id=$2',[recordId,organizationId]);await clearSuppression(transaction);await recalcCoverage(transaction,organizationId,schemeId);return{result:{deleted:true,schemeId}};
  }
  if(!old){
    if(Number(currentVersion)!==0)error(409,'RECORD_MISSING','Scheme item no longer exists');const weekNo=positive(payload.weekNo,'weekNo'),topic=required(payload.topic,'Topic',500),seq=payload.sequenceNo==null?Number((await transaction.query('SELECT COALESCE(MAX(sequence_no),0)+1 AS n FROM acad_scheme_items WHERE scheme_id=$1 AND organization_id=$2',[schemeId,organizationId])).rows[0]?.n??1):positive(payload.sequenceNo,'sequenceNo');const coverage=enumValue(payload.coverageStatus??'planned',['planned','in_progress','covered','carried_forward','skipped'],'coverageStatus');
    await suppress(transaction,organizationId,'scheme-items',recordId);await transaction.query(`INSERT INTO acad_scheme_items(id,organization_id,scheme_id,sequence_no,week_no,lesson_no,topic,subtopic,learning_objectives,competencies,teaching_methods,learning_materials,references_text,planned_activities,assessment_activities,planned_date,coverage_status,teacher_reflection,covered_at,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,CASE WHEN $17='covered' THEN now() ELSE NULL END,$19,$19)`,[recordId,organizationId,schemeId,seq,weekNo,payload.lessonNo==null?null:positive(payload.lessonNo,'lessonNo'),topic,text(payload.subtopic,500),text(payload.learningObjectives,10000),text(payload.competencies,10000),text(payload.teachingMethods,10000),text(payload.learningMaterials,10000),text(payload.referencesText,10000),text(payload.plannedActivities,20000),text(payload.assessmentActivities,20000),dateValue(payload.plannedDate,'plannedDate',{optional:true}),coverage,text(payload.teacherReflection,10000),operation.clientTimestamp??new Date().toISOString()]);await clearSuppression(transaction);
  }else{
    const entries=Object.entries(payload).filter(([k])=>k!=='schemeId'&&itemMap[k]);if(!entries.length)error(422,'VALIDATION_ERROR','No scheme item changes supplied');const vals=[],sets=[];for(const[k,v]of entries){let next=v;if(k==='sequenceNo'||k==='weekNo')next=positive(v,k);else if(k==='lessonNo')next=v==null?null:positive(v,k);else if(k==='topic')next=required(v,'Topic',500);else if(k==='plannedDate')next=dateValue(v,'plannedDate',{optional:true});else if(k==='coverageStatus')next=enumValue(v,['planned','in_progress','covered','carried_forward','skipped'],'coverageStatus');else next=text(v,k==='plannedActivities'||k==='assessmentActivities'?20000:k==='subtopic'?500:10000);vals.push(next);sets.push(`${itemMap[k]}=$${vals.length}`);}const coverage=Object.hasOwn(payload,'coverageStatus')?enumValue(payload.coverageStatus,['planned','in_progress','covered','carried_forward','skipped'],'coverageStatus',{optional:true}):null;vals.push(coverage,recordId,organizationId);await suppress(transaction,organizationId,'scheme-items',recordId);await transaction.query(`UPDATE acad_scheme_items SET ${sets.join(',')},covered_at=CASE WHEN $${vals.length-2}='covered' THEN COALESCE(covered_at,now()) WHEN $${vals.length-2} IS NOT NULL AND $${vals.length-2}<>'covered' THEN NULL ELSE covered_at END,updated_at=now() WHERE id=$${vals.length-1} AND organization_id=$${vals.length}`,vals);await clearSuppression(transaction);
  }
  await recalcCoverage(transaction,organizationId,schemeId);const saved=(await transaction.query('SELECT * FROM acad_scheme_items WHERE id=$1 AND organization_id=$2',[recordId,organizationId])).rows[0];return{payload:camel(saved),result:{id:recordId,schemeId}};
}

const planFields=new Set(['academicYearId','termId','classId','streamId','subjectId','teacherUserId','timetableEntryId','schemeItemId','templateId','lessonDate','weekNo','lessonNo','topic','subtopic','lessonObjectives','priorKnowledge','introductionText','lessonDevelopment','teacherActivities','learnerActivities','teachingMethods','requiredMaterials','differentiatedInstruction','specialNeedsAccommodations','lessonAssessment','lessonConclusion','homework','teacherReflection']);
const editablePlan=Object.freeze({topic:'topic',subtopic:'subtopic',lessonObjectives:'lesson_objectives',priorKnowledge:'prior_knowledge',introductionText:'introduction_text',lessonDevelopment:'lesson_development',teacherActivities:'teacher_activities',learnerActivities:'learner_activities',teachingMethods:'teaching_methods',requiredMaterials:'required_materials',differentiatedInstruction:'differentiated_instruction',specialNeedsAccommodations:'special_needs_accommodations',lessonAssessment:'lesson_assessment',lessonConclusion:'lesson_conclusion',homework:'homework',teacherReflection:'teacher_reflection'});
export async function applyAcademicsLessonPlanSync({transaction,organizationId,userId,operation,currentVersion}){
  await requireWrite(transaction,organizationId,userId);if(operation.kind==='delete')error(409,'SERVER_MANAGED_LIFECYCLE','Lesson plans cannot be deleted offline');const recordId=stableId(operation.recordId,'Lesson plan'),payload=object(operation.payload??{});only(payload,planFields);const old=(await transaction.query('SELECT * FROM acad_lesson_plans WHERE id=$1 AND organization_id=$2 FOR UPDATE',[recordId,organizationId])).rows[0]??null;
  if(!old){
    if(Number(currentVersion)!==0)error(409,'RECORD_MISSING','Lesson plan no longer exists');const teacher=String(payload.teacherUserId??userId);await own(transaction,organizationId,userId,teacher);await teacherRef(transaction,teacher,organizationId);const academicYearId=await orgRef(transaction,'school_academic_years',payload.academicYearId,organizationId,'Academic year'),termId=await orgRef(transaction,'school_terms',payload.termId,organizationId,'Term'),classId=await orgRef(transaction,'school_classes',payload.classId,organizationId,'Class'),subjectId=await orgRef(transaction,'school_subjects',payload.subjectId,organizationId,'Subject'),streamId=await orgRef(transaction,'school_streams',payload.streamId,organizationId,'Stream',{optional:true});const timetableEntryId=await orgRef(transaction,'acad_timetable_entries',payload.timetableEntryId,organizationId,'Timetable entry',{optional:true}),schemeItemId=await orgRef(transaction,'acad_scheme_items',payload.schemeItemId,organizationId,'Scheme item',{optional:true}),templateId=await orgRef(transaction,'acad_lesson_plan_templates',payload.templateId,organizationId,'Lesson plan template',{optional:true});
    await suppress(transaction,organizationId,'lesson-plans',recordId);await transaction.query(`INSERT INTO acad_lesson_plans(id,organization_id,academic_year_id,term_id,class_id,stream_id,subject_id,teacher_user_id,timetable_entry_id,scheme_item_id,template_id,lesson_date,week_no,lesson_no,topic,subtopic,lesson_objectives,prior_knowledge,introduction_text,lesson_development,teacher_activities,learner_activities,teaching_methods,required_materials,differentiated_instruction,special_needs_accommodations,lesson_assessment,lesson_conclusion,homework,teacher_reflection,status,created_by,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,'draft',$31,$32,$32)`,[recordId,organizationId,academicYearId,termId,classId,streamId,subjectId,teacher,timetableEntryId,schemeItemId,templateId,dateValue(payload.lessonDate,'lessonDate'),payload.weekNo==null?null:positive(payload.weekNo,'weekNo'),payload.lessonNo==null?null:positive(payload.lessonNo,'lessonNo'),required(payload.topic,'Topic',500),text(payload.subtopic,500),text(payload.lessonObjectives,20000),text(payload.priorKnowledge,20000),text(payload.introductionText,30000),text(payload.lessonDevelopment,50000),text(payload.teacherActivities,30000),text(payload.learnerActivities,30000),text(payload.teachingMethods,10000),text(payload.requiredMaterials,10000),text(payload.differentiatedInstruction,20000),text(payload.specialNeedsAccommodations,20000),text(payload.lessonAssessment,20000),text(payload.lessonConclusion,20000),text(payload.homework,20000),text(payload.teacherReflection,20000),userId,operation.clientTimestamp??new Date().toISOString()]);await clearSuppression(transaction);
  }else{
    await own(transaction,organizationId,userId,String(old.teacher_user_id));if(!['draft','rejected'].includes(String(old.status)))error(409,'LESSON_PLAN_LOCKED','Only draft or rejected lesson plans can be edited offline');const entries=Object.entries(payload).filter(([k])=>editablePlan[k]);if(!entries.length)error(422,'VALIDATION_ERROR','No editable lesson plan fields supplied');const vals=[],sets=[];for(const[k,v]of entries){const max=k==='topic'||k==='subtopic'?500:k==='lessonDevelopment'?50000:['introductionText','teacherActivities','learnerActivities'].includes(k)?30000:['teachingMethods','requiredMaterials'].includes(k)?10000:20000;vals.push(k==='topic'?required(v,'Topic',500):text(v,max));sets.push(`${editablePlan[k]}=$${vals.length}`);}vals.push(recordId,organizationId);await suppress(transaction,organizationId,'lesson-plans',recordId);await transaction.query(`UPDATE acad_lesson_plans SET ${sets.join(',')},updated_at=now() WHERE id=$${vals.length-1} AND organization_id=$${vals.length}`,vals);await clearSuppression(transaction);
  }
  const saved=(await transaction.query('SELECT * FROM acad_lesson_plans WHERE id=$1 AND organization_id=$2',[recordId,organizationId])).rows[0];return{payload:camel(saved),result:{id:recordId}};
}

const deliveryFields=new Set(['lessonPlanId','attendanceSessionId','actualStartsAt','actualEndsAt','deliveryStatus','actualTopic','actualSubtopic','studentAttendanceSummary','lessonNotes','missedReason','recoveryDate']);
export async function applyAcademicsDeliverySync({transaction,organizationId,userId,operation}){
  await requireWrite(transaction,organizationId,userId);if(operation.kind==='delete')error(409,'SERVER_MANAGED_LIFECYCLE','Lesson deliveries cannot be deleted offline');const recordId=stableId(operation.recordId,'Lesson delivery'),payload=object(operation.payload??{});only(payload,deliveryFields);const old=(await transaction.query('SELECT * FROM acad_lesson_deliveries WHERE id=$1 AND organization_id=$2 FOR UPDATE',[recordId,organizationId])).rows[0];if(!old)error(404,'DELIVERY_NOT_FOUND','Lesson delivery not found; synchronize the timetable first');await own(transaction,organizationId,userId,String(old.teacher_user_id));
  const lessonPlanId=payload.lessonPlanId==null?null:await orgRef(transaction,'acad_lesson_plans',payload.lessonPlanId,organizationId,'Lesson plan'),attendanceSessionId=payload.attendanceSessionId==null?null:await orgRef(transaction,'att_sessions',payload.attendanceSessionId,organizationId,'Attendance session');let attendance=text(payload.studentAttendanceSummary,20000);if(attendanceSessionId){const a=await transaction.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status IN ('present','late'))::int present,count(*) FILTER(WHERE status='absent')::int absent FROM att_records WHERE organization_id=$1 AND session_id=$2 AND person_type='student' AND official=true`,[organizationId,attendanceSessionId]);attendance=JSON.stringify({total:Number(a.rows[0]?.total||0),present:Number(a.rows[0]?.present||0),absent:Number(a.rows[0]?.absent||0)});}const status=enumValue(payload.deliveryStatus,['scheduled','taught','missed','postponed','recovery'],'deliveryStatus',{optional:true});
  await suppress(transaction,organizationId,'deliveries',recordId);await transaction.query(`UPDATE acad_lesson_deliveries SET lesson_plan_id=COALESCE($1,lesson_plan_id),canonical_attendance_session_id=COALESCE($2,canonical_attendance_session_id),actual_starts_at=$3,actual_ends_at=$4,delivery_status=COALESCE($5,delivery_status),actual_topic=$6,actual_subtopic=$7,student_attendance_summary=COALESCE($8,student_attendance_summary),lesson_notes=$9,missed_reason=$10,recovery_date=$11,updated_at=now() WHERE id=$12 AND organization_id=$13`,[lessonPlanId,attendanceSessionId,text(payload.actualStartsAt),text(payload.actualEndsAt),status,text(payload.actualTopic,500),text(payload.actualSubtopic,500),attendance,text(payload.lessonNotes,30000),text(payload.missedReason,10000),dateValue(payload.recoveryDate,'recoveryDate',{optional:true}),recordId,organizationId]);await clearSuppression(transaction);
  if(status==='taught'&&lessonPlanId){await transaction.query("UPDATE acad_lesson_plans SET status='delivered',updated_at=now() WHERE id=$1 AND organization_id=$2 AND status='approved'",[lessonPlanId,organizationId]);const item=(await transaction.query(`SELECT si.id,si.scheme_id FROM acad_lesson_plans lp JOIN acad_scheme_items si ON si.id=lp.scheme_item_id AND si.organization_id=lp.organization_id WHERE lp.id=$1 AND lp.organization_id=$2 LIMIT 1`,[lessonPlanId,organizationId])).rows[0];if(item){await transaction.query(`UPDATE acad_scheme_items SET coverage_status='covered',covered_at=COALESCE(covered_at,now()),teacher_reflection=COALESCE($1,teacher_reflection),updated_at=now() WHERE id=$2 AND organization_id=$3`,[text(payload.lessonNotes,30000),item.id,organizationId]);await recalcCoverage(transaction,organizationId,item.scheme_id);}}
  const saved=(await transaction.query('SELECT * FROM acad_lesson_deliveries WHERE id=$1 AND organization_id=$2',[recordId,organizationId])).rows[0];return{payload:camel(saved),result:{id:recordId}};
}

export async function applyAcademicsActionSync({transaction,organizationId,userId,operation}){
  await requireWrite(transaction,organizationId,userId);if(operation.kind==='delete')error(409,'APPEND_ONLY_COLLECTION','Academic actions cannot be deleted');const recordId=stableId(operation.recordId,'Action'),payload=object(operation.payload??{}),action=String(payload.action??'');
  if(action==='submit_scheme'){
    only(payload,new Set(['action','schemeId']));const schemeId=required(payload.schemeId,'schemeId'),row=(await transaction.query('SELECT teacher_user_id,status FROM acad_schemes WHERE id=$1 AND organization_id=$2 FOR UPDATE',[schemeId,organizationId])).rows[0];if(!row)error(404,'SCHEME_NOT_FOUND','Scheme not found');await own(transaction,organizationId,userId,String(row.teacher_user_id));if(!['draft','rejected'].includes(String(row.status)))error(409,'INVALID_STATUS','Scheme cannot be submitted from its current status');await transaction.query("UPDATE acad_schemes SET status='submitted_hod',updated_at=now() WHERE id=$1 AND organization_id=$2",[schemeId,organizationId]);
  }else if(action==='submit_lesson_plan'){
    only(payload,new Set(['action','lessonPlanId']));const planId=required(payload.lessonPlanId,'lessonPlanId'),row=(await transaction.query('SELECT teacher_user_id,status FROM acad_lesson_plans WHERE id=$1 AND organization_id=$2 FOR UPDATE',[planId,organizationId])).rows[0];if(!row)error(404,'LESSON_PLAN_NOT_FOUND','Lesson plan not found');await own(transaction,organizationId,userId,String(row.teacher_user_id));if(row.status!=='draft')error(409,'INVALID_STATUS','Only draft lesson plans can be submitted');await transaction.query("UPDATE acad_lesson_plans SET status='submitted',updated_at=now() WHERE id=$1 AND organization_id=$2",[planId,organizationId]);
  }else if(action==='ack_observation'){
    only(payload,new Set(['action','observationId','response']));const observationId=required(payload.observationId,'observationId'),row=(await transaction.query('SELECT teacher_user_id,followup_date FROM acad_observations WHERE id=$1 AND organization_id=$2 FOR UPDATE',[observationId,organizationId])).rows[0];if(!row)error(404,'OBSERVATION_NOT_FOUND','Observation not found');if(String(row.teacher_user_id)!==userId)error(403,'SYNC_FORBIDDEN','Only the observed teacher can acknowledge this observation');await transaction.query("UPDATE acad_observations SET status=CASE WHEN followup_date IS NULL THEN 'acknowledged' ELSE 'followup_due' END,teacher_acknowledged_at=now(),teacher_response=$1,updated_at=now() WHERE id=$2 AND organization_id=$3",[text(payload.response,10000),observationId,organizationId]);
  }else error(422,'VALIDATION_ERROR','Unsupported academic action');
  return{payload:{id:recordId,...payload,queuedAt:operation.clientTimestamp??new Date().toISOString(),appliedBy:userId},result:{id:recordId,action}};
}
