import {useEffect,useMemo,useRef,useState} from "react";
import {Expand,Grid2X2,History,Pause,Play,RefreshCw,RotateCcw,RotateCw,Rows3,SkipBack,SkipForward,Video} from "lucide-react";
import {get,post,errorText} from "../../../web/api";
import {WhepPlayer} from "./WhepPlayer";
import {historyWindowAt} from "./nvrPlaybackPolicy";
import "./NvrViewer.css";

type Camera={id:string;name:string;location?:string|null;status:string;server_id?:string|null;stream_status?:string|null;lifecycle_status?:string|null};
type Segment={id:string;started_at:string;ended_at?:string|null;status:string;protected:number;size_bytes:number};
type Timeline={camera:{id:string;name:string};segments:Segment[];gaps:Array<{from:string;to:string;durationMs:number}>;coveredMs:number};
type EventRow={id:string;camera_id:string;event_type:string;severity:string;started_at:string;ended_at?:string};
type LiveSession={id:string;cameraId:string;cameraName:string;expiresAt:string;whepUrl:string;viewerToken:string};
type PlaybackGrant={url:string;expiresAt:string};
type PlaybackState="idle"|"loading"|"playing"|"paused"|"buffering"|"gap"|"error";
const WINDOW_MS=6*60*60*1000;
const fmt=new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",second:"2-digit"});
const zone=Intl.DateTimeFormat().resolvedOptions().timeZone||"Local";

export function NvrViewer(){
 const[cameras,setCameras]=useState<Camera[]>([]),[selected,setSelected]=useState<string[]>([]),[layout,setLayout]=useState<1|4|9>(4),[focus,setFocus]=useState<string|null>(null),[from,setFrom]=useState(Date.now()-WINDOW_MS),[to,setTo]=useState(Date.now()),[playhead,setPlayhead]=useState(Date.now()),[liveMode,setLiveMode]=useState(true),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[timelines,setTimelines]=useState<Record<string,Timeline>>({}),[events,setEvents]=useState<EventRow[]>([]),[live,setLive]=useState<Record<string,LiveSession>>({}),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const liveRef=useRef<Record<string,LiveSession>>({});liveRef.current=live;
 const visible=useMemo(()=>{const ids=focus?[focus]:selected.slice(0,layout);return ids.map(id=>cameras.find(c=>c.id===id)).filter(Boolean) as Camera[]},[cameras,selected,layout,focus]);
 const visibleKey=visible.map(x=>x.id).join(",");
 async function loadBase(){setLoading(true);setError("");try{const cs=await get<Camera[]>("/security-camera/cameras");setCameras(cs);setSelected(old=>old.length?old.filter(id=>cs.some(c=>c.id===id)).slice(0,9):cs.slice(0,4).map(c=>c.id))}catch(e){setError(errorText(e))}finally{setLoading(false)}}
 useEffect(()=>{void loadBase()},[]);
 async function loadHistory(nextFrom=from,nextTo=to){if(!visible.length)return;setLoading(true);setError("");try{const ids=visible.map(c=>c.id),tls=await Promise.all(ids.map(id=>get<Timeline>(`/security-camera/cameras/${id}/timeline?from=${encodeURIComponent(new Date(nextFrom).toISOString())}&to=${encodeURIComponent(new Date(nextTo).toISOString())}&limit=5000`))),ev=await get<EventRow[]>(`/security-camera/events?from=${encodeURIComponent(new Date(nextFrom).toISOString())}&to=${encodeURIComponent(new Date(nextTo).toISOString())}&limit=1000`);setTimelines(old=>({...old,...Object.fromEntries(tls.map(t=>[t.camera.id,t]))}));setEvents(ev.filter(x=>ids.includes(x.camera_id)))}catch(e){setError(errorText(e))}finally{setLoading(false)}}
 useEffect(()=>{if(!liveMode&&visible.length)void loadHistory()},[liveMode,visibleKey,from,to]);
 useEffect(()=>{if(!playing||liveMode)return;let prev=performance.now();const t=window.setInterval(()=>{const now=performance.now(),delta=(now-prev)*speed;prev=now;setPlayhead(p=>{const n=p+delta;if(n>=to){setPlaying(false);return to}return n})},250);return()=>clearInterval(t)},[playing,liveMode,speed,to]);
 useEffect(()=>{let cancelled=false;async function syncLive(){const wanted=new Set(liveMode?visible.filter(c=>canLive(c)).map(c=>c.id):[]);const current=liveRef.current;for(const[id,s]of Object.entries(current))if(!wanted.has(id)){void post(`/security-camera/live/${s.id}/end`,{}).catch(()=>{});if(!cancelled)setLive(v=>{const n={...v};delete n[id];return n})}for(const cam of visible){if(!wanted.has(cam.id)||current[cam.id])continue;try{const s=await post<LiveSession>(`/security-camera/cameras/${cam.id}/live`,{});if(cancelled){void post(`/security-camera/live/${s.id}/end`,{}).catch(()=>{});return}setLive(v=>({...v,[cam.id]:s}))}catch(e){if(!cancelled)setError(x=>x||`${cam.name}: ${errorText(e)}`)}}}void syncLive();return()=>{cancelled=true}},[liveMode,visibleKey]);
 useEffect(()=>()=>{for(const s of Object.values(liveRef.current))void post(`/security-camera/live/${s.id}/end`,{}).catch(()=>{})},[]);
 function historyAt(ms:number){const clamped=Math.max(from,Math.min(to,ms));setLiveMode(false);setPlaying(false);setPlayhead(clamped)}
 function beginHistory(){const w=historyWindowAt(Date.now(),WINDOW_MS,1000);setFrom(w.from);setTo(w.to);setPlayhead(w.playhead);setLiveMode(false);setPlaying(false)}
 function goLive(){const end=Date.now();setPlaying(false);setLiveMode(true);setPlayhead(end);setTo(end);setFrom(end-WINDOW_MS)}
 function shift(ms:number){historyAt(playhead+ms)}
 function toggleCamera(id:string){setSelected(old=>old.includes(id)?old.length===1?old:old.filter(x=>x!==id):old.length<9?[...old,id]:old)}
 function scrub(e:React.PointerEvent<HTMLDivElement>){const r=e.currentTarget.getBoundingClientRect();historyAt(from+(Math.max(0,Math.min(r.width,e.clientX-r.left))/Math.max(1,r.width))*(to-from))}
 function captureScrub(e:React.PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);scrub(e)}
 function moveScrub(e:React.PointerEvent<HTMLDivElement>){if(e.currentTarget.hasPointerCapture(e.pointerId))scrub(e)}
 const modeLabel=liveMode?"LIVE":`HISTORY · ${fmt.format(playhead)}`;
 return <section className="nvr-shell"><header className="nvr-head"><div><span className="nvr-kicker"><Video size={14}/> NVR CONSOLE</span><h2>Live + History</h2><p>One synchronized wall for current feeds and indexed recordings.</p></div><div className="nvr-head-actions"><span className={`nvr-mode ${liveMode?"live":"history"}`}>{modeLabel}</span><button onClick={()=>void loadBase()} title="Refresh"><RefreshCw size={15}/></button>{!liveMode&&<button className="nvr-live-btn" onClick={goLive}>Return to live</button>}</div></header>
 {error&&<div className="nvr-error">{error}</div>}
 <div className="nvr-toolbar"><div className="nvr-camera-picks">{cameras.map(c=><button key={c.id} className={selected.includes(c.id)?"on":""} onClick={()=>toggleCamera(c.id)}><i className={canLive(c)?"online":"offline"}/>{c.name}</button>)}</div><div className="nvr-layouts"><button className={layout===1?"on":""} onClick={()=>setLayout(1)}><Expand size={14}/>1</button><button className={layout===4?"on":""} onClick={()=>setLayout(4)}><Grid2X2 size={14}/>4</button><button className={layout===9?"on":""} onClick={()=>setLayout(9)}><Rows3 size={14}/>9</button></div></div>
 <div className={`nvr-grid cols-${focus?1:layout}`}>{visible.map(cam=><CameraTile key={cam.id} camera={cam} liveMode={liveMode} live={live[cam.id]} timeline={timelines[cam.id]} playhead={playhead} playing={playing} speed={speed} focused={focus===cam.id} onFocus={()=>setFocus(focus===cam.id?null:cam.id)}/>)}</div>
 {!visible.length&&<div className="nvr-empty">Select at least one camera.</div>}
 <div className="nvr-controls"><button onClick={()=>shift(-30000)} disabled={liveMode} title="Rewind 30 seconds"><RotateCcw size={17}/><small>30s</small></button><button onClick={()=>shift(-10000)} disabled={liveMode} title="Skip back 10 seconds"><SkipBack size={18}/><small>10s</small></button><button className="primary" onClick={()=>liveMode?beginHistory():setPlaying(x=>!x)}>{!liveMode&&playing?<Pause size={20}/>:<Play size={20}/>}</button><button onClick={()=>shift(10000)} disabled={liveMode} title="Skip forward 10 seconds"><SkipForward size={18}/><small>10s</small></button><button onClick={()=>shift(30000)} disabled={liveMode} title="Fast forward 30 seconds"><RotateCw size={17}/><small>30s</small></button><label>Speed<select value={speed} disabled={liveMode} onChange={e=>setSpeed(Number(e.target.value))}>{[.25,.5,1,2,4].map(x=><option key={x} value={x}>{x}×</option>)}</select></label><button onClick={()=>{const end=Date.now();setFrom(end-WINDOW_MS);setTo(end);setPlayhead(Math.min(playhead,end));setLiveMode(false)}}><History size={15}/>Last 6h</button></div>
 <div className="nvr-timeline-wrap"><div className="nvr-time-head"><b>{fmt.format(from)}</b><span>{zone} · {new Date().toLocaleTimeString(undefined,{timeZoneName:"short"}).split(" ").pop()}</span><b>{fmt.format(to)}</b></div><div className="nvr-ruler" onPointerDown={captureScrub} onPointerMove={moveScrub}>{ticks(from,to).map((x,i)=><span key={i} style={{left:`${x.pct}%`}}>{x.label}</span>)}<i className="nvr-playhead" style={{left:`${pct(playhead,from,to)}%`}}/></div>{visible.map(cam=><TimelineRow key={cam.id} camera={cam} timeline={timelines[cam.id]} events={events.filter(e=>e.camera_id===cam.id)} from={from} to={to} playhead={playhead} onScrub={historyAt}/>)}</div>
 {loading&&<div className="nvr-loading">Synchronizing NVR…</div>}
 </section>
}

function CameraTile({camera,liveMode,live,timeline,playhead,playing,speed,focused,onFocus}:{camera:Camera;liveMode:boolean;live?:LiveSession;timeline?:Timeline;playhead:number;playing:boolean;speed:number;focused:boolean;onFocus:()=>void}){
 const video=useRef<HTMLVideoElement|null>(null),[grant,setGrant]=useState<PlaybackGrant|null>(null),[segmentId,setSegmentId]=useState(""),[state,setState]=useState<PlaybackState>("idle"),[error,setError]=useState("");
 const seg=useMemo(()=>findSegment(timeline?.segments||[],playhead),[timeline,playhead]);
 useEffect(()=>{if(liveMode){setGrant(null);setSegmentId("");setState("idle");return}if(!seg){setGrant(null);setSegmentId("");setState("gap");return}if(seg.id===segmentId&&grant)return;let cancel=false;setState("loading");setError("");post<PlaybackGrant>(`/security-camera/recordings/${encodeURIComponent(seg.id)}/playback`,{}).then(g=>{if(cancel)return;setGrant(g);setSegmentId(seg.id)}).catch(e=>{if(!cancel){setState("error");setError(errorText(e))}});return()=>{cancel=true}},[liveMode,seg?.id,segmentId,grant]);
 useEffect(()=>{if(liveMode||!grant)return;const renewIn=Date.parse(grant.expiresAt)-Date.now()-15000;if(renewIn<=0){setGrant(null);setSegmentId("");return}const timer=window.setTimeout(()=>{setGrant(null);setSegmentId("")},renewIn);return()=>clearTimeout(timer)},[grant?.expiresAt,liveMode]);
 useEffect(()=>{const v=video.current;if(!v||liveMode||!seg||!grant)return;const wanted=Math.max(0,(playhead-Date.parse(seg.started_at))/1000);if(Math.abs(v.currentTime-wanted)>.8)try{v.currentTime=wanted}catch{}v.playbackRate=speed;if(playing){void v.play().catch(()=>{})}else v.pause()},[playhead,playing,speed,grant,seg?.id,liveMode]);
 return <article className={`nvr-tile ${focused?"focused":""}`}><div className="nvr-tile-head"><div><b>{camera.name}</b><small>{camera.location||camera.stream_status||"Security camera"}</small></div><div><span className={`nvr-badge ${liveMode?"live":"history"}`}>{liveMode?"LIVE":"HISTORY"}</span><button onClick={onFocus}>{focused?"Grid":"Focus"}</button></div></div><div className="nvr-stage">{liveMode?(live?<WhepPlayer url={live.whepUrl} token={live.viewerToken} cameraName={camera.name}/>:<StageMessage title={canLive(camera)?"Requesting live viewer…":"Camera offline"} detail={canLive(camera)?"Authenticated WHEP session is opening.":"The live feed will recover when camera and NVR media are online."}/>):seg&&grant?<video ref={video} src={grant.url} playsInline preload="auto" onLoadedMetadata={()=>setState(playing?"playing":"paused")} onPlaying={()=>setState("playing")} onPause={()=>setState("paused")} onWaiting={()=>setState("buffering")} onError={()=>{setState("error");setError("Recorded video could not be loaded from the NVR.")}}/>:<StageMessage title={state==="loading"?"Loading recording…":state==="gap"?"No recording at this time":"Playback unavailable"} detail={error||`${fmt.format(playhead)} · ${zone}`}/>} {!liveMode&&<div className="nvr-stage-status">{state.toUpperCase()} · {fmt.format(playhead)}</div>}</div></article>
}
function StageMessage({title,detail}:{title:string;detail:string}){return <div className="nvr-stage-message"><b>{title}</b><small>{detail}</small></div>}
function TimelineRow({camera,timeline,events,from,to,playhead,onScrub}:{camera:Camera;timeline?:Timeline;events:EventRow[];from:number;to:number;playhead:number;onScrub:(n:number)=>void}){const ref=useRef<HTMLDivElement|null>(null);function seek(e:React.PointerEvent<HTMLDivElement>){const r=ref.current?.getBoundingClientRect();if(r)onScrub(from+(Math.max(0,Math.min(r.width,e.clientX-r.left))/Math.max(1,r.width))*(to-from))}function start(e:React.PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);seek(e)}function move(e:React.PointerEvent<HTMLDivElement>){if(e.currentTarget.hasPointerCapture(e.pointerId))seek(e)}return <div className="nvr-track-row"><span>{camera.name}</span><div ref={ref} className="nvr-track" onPointerDown={start} onPointerMove={move}>{timeline?.segments.map(s=>{const a=Math.max(from,Date.parse(s.started_at)),b=Math.min(to,Date.parse(s.ended_at||s.started_at));return <i key={s.id} className="coverage" style={{left:`${pct(a,from,to)}%`,width:`${Math.max(.2,pct(b,from,to)-pct(a,from,to))}%`}}/>})}{events.map(e=><i key={e.id} className={`event ${e.severity||"info"}`} title={e.event_type} style={{left:`${pct(Date.parse(e.started_at),from,to)}%`}}/>)}<i className="nvr-playhead" style={{left:`${pct(playhead,from,to)}%`}}/></div></div>}
function canLive(c:Camera){return c.status==="online"&&c.stream_status==="online"&&!!c.server_id&&!['disabled','decommissioned'].includes(String(c.lifecycle_status||""))}
function findSegment(segs:Segment[],ms:number){return segs.find(s=>Date.parse(s.started_at)<=ms&&Date.parse(s.ended_at||s.started_at)>=ms)}
function pct(v:number,a:number,b:number){return Math.max(0,Math.min(100,(v-a)/(b-a)*100))}
function ticks(a:number,b:number){return Array.from({length:7},(_,i)=>{const p=i/6,n=a+(b-a)*p;return{pct:p*100,label:fmt.format(n)}})}
