import {useEffect,useMemo,useState} from "react";
import {Archive,Download,Film,Play,RefreshCw,ShieldAlert} from "lucide-react";
import {get,post,errorText} from "../../../web/api";

type Camera={id:string;name:string;location?:string};
type Segment={id:string;server_id?:string;started_at:string;ended_at?:string;local_path:string;size_bytes:number;protected:number;status:string;server_name?:string};
type Timeline={camera:{id:string;name:string};segments:Segment[];gaps:Array<{from:string;to:string;durationMs:number}>;coveredMs:number};
type Grant={url:string;expiresAt:string;cameraName?:string};
function localInput(d:Date){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
export function SecurityCameraArchive(){
 const[cameras,setCameras]=useState<Camera[]>([]),[cameraId,setCameraId]=useState(""),[from,setFrom]=useState(localInput(new Date(Date.now()-6*3600000))),[to,setTo]=useState(localInput(new Date())),[timeline,setTimeline]=useState<Timeline|null>(null),[playback,setPlayback]=useState<Grant|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{void get<Camera[]>("/security-camera/cameras").then(rows=>{setCameras(rows);if(rows[0])setCameraId(x=>x||rows[0].id)}).catch(e=>setError(errorText(e)))},[]);
 async function load(){if(!cameraId)return;setBusy(true);setError("");try{setTimeline(await get<Timeline>(`/security-camera/cameras/${cameraId}/timeline?from=${encodeURIComponent(new Date(from).toISOString())}&to=${encodeURIComponent(new Date(to).toISOString())}&limit=3000`))}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 useEffect(()=>{if(cameraId)void load()},[cameraId]);
 async function play(id:string){try{setPlayback(await post<Grant>(`/security-camera/recordings/${encodeURIComponent(id)}/playback`,{}))}catch(e){setError(errorText(e))}}
 async function exportClip(){if(!cameraId)return;try{const x=await post<Grant&{id:string}>(`/security-camera/cameras/${cameraId}/export`,{from:new Date(from).toISOString(),to:new Date(to).toISOString()});window.open(x.url,"_blank","noopener,noreferrer")}catch(e){setError(errorText(e))}}
 const duration=useMemo(()=>timeline?.segments.reduce((n,s)=>n+Math.max(0,new Date(s.ended_at||s.started_at).getTime()-new Date(s.started_at).getTime()),0)||0,[timeline]);
 return <div className="sec-ops"><header className="sec-ops-hero"><div><div className="sec-ops-kicker"><Archive size={15}/> CCTV ARCHIVE</div><h1>Recordings & timeline</h1><p>Search the local NVR archive by camera and time. Playback and exports use short-lived grants; the footage itself stays on your NVR.</p></div><button className="sec-op-btn" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></header>
 {error&&<div className="sec-error">{error}</div>}
 <section className="sec-op-card"><div className="sec-filters"><label>Camera<select value={cameraId} onChange={e=>setCameraId(e.target.value)}>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}{c.location?` · ${c.location}`:""}</option>)}</select></label><label>From<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="sec-op-primary" onClick={()=>void load()}>Search archive</button><button className="sec-op-btn" disabled={!timeline?.segments.length} onClick={()=>void exportClip()}><Download size={14}/>Export range</button></div></section>
 {playback&&<section className="sec-op-card"><div className="sec-op-head"><div><span>PLAYBACK</span><h2>{playback.cameraName||timeline?.camera.name||"Camera recording"}</h2></div><small>Grant expires {new Date(playback.expiresAt).toLocaleTimeString()}</small></div><video className="sec-playback" src={playback.url} controls autoPlay playsInline/></section>}
 <section className="sec-op-stats"><div><span>Segments</span><b>{timeline?.segments.length||0}</b></div><div><span>Recorded time</span><b>{fmtDuration(duration)}</b></div><div><span>Gaps detected</span><b>{timeline?.gaps.length||0}</b></div><div><span>Window</span><b>{Math.max(0,Math.round((new Date(to).getTime()-new Date(from).getTime())/3600000))}h</b></div></section>
 <section className="sec-op-card"><div className="sec-op-head"><div><span>TIMELINE</span><h2>{timeline?.camera.name||"Select a camera"}</h2></div><Film size={20}/></div>{timeline?.segments.length?<div className="sec-timeline">{timeline.gaps.map((g,i)=><div className="sec-gap" key={`g${i}`}><ShieldAlert size={14}/><span>No indexed video from {new Date(g.from).toLocaleTimeString()} to {new Date(g.to).toLocaleTimeString()} · {fmtDuration(g.durationMs)}</span></div>)}<div className="sec-archive-list">{timeline.segments.map(s=><div className="sec-archive-row" key={s.id}><div><b>{new Date(s.started_at).toLocaleString()}</b><small>{s.ended_at?`to ${new Date(s.ended_at).toLocaleTimeString()}`:"end time pending"} · {bytes(s.size_bytes)} {s.protected?"· protected":""}</small></div><div><small>{s.server_name||"Local NVR"}</small><code>{s.local_path}</code></div><button onClick={()=>void play(s.id)}><Play size={13}/>Play</button></div>)}</div></div>:<div className="sec-empty">{busy?"Loading archive…":"No indexed footage exists in this time window."}</div>}</section></div>
}
function bytes(n:number){if(!n)return"0 B";const u=["B","KB","MB","GB","TB"];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i<2?0:1)} ${u[i]}`}
function fmtDuration(ms?:number){const s=Math.max(0,Math.round((ms||0)/1000));if(s<60)return`${s}s`;if(s<3600)return`${Math.round(s/60)}m`;return`${(s/3600).toFixed(1)}h`}
