import {useEffect,useMemo,useState} from "react";
import {Activity,Camera,FolderPlus,Image,RefreshCw,Server,ShieldAlert,Stethoscope} from "lucide-react";
import {get,post,errorText} from "../../../web/api";

type CameraRow={id:string;name:string;location?:string;status:string;server_name?:string;device_model?:string;app_version?:string;battery_level?:number;temperature_c?:number;wifi_strength?:number;last_seen_at?:string;last_recording_at?:string;stream_status?:string;lifecycle_status?:string;lifecycle_note?:string};
type Group={id:string;name:string;description?:string;cameras:Array<{camera_id:string;camera_name:string}>};
type Fleet={groups:Group[];views:any[];lifecycle:any[]};
export function SecurityCameraFleet(){
 const[cameras,setCameras]=useState<CameraRow[]>([]),[fleet,setFleet]=useState<Fleet>({groups:[],views:[],lifecycle:[]}),[selected,setSelected]=useState<string[]>([]),[diag,setDiag]=useState<any>(null),[snapshot,setSnapshot]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError("");try{const[c,f]=await Promise.all([get<CameraRow[]>("/security-camera/cameras"),get<Fleet>("/security-camera/fleet")]);setCameras(c);setFleet(f)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),20000);return()=>clearInterval(t)},[]);
 async function saveGroup(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await post("/security-camera/groups",{name:f.get("name"),description:f.get("description"),cameraIds:selected});setSelected([]);e.currentTarget.reset();await load()}catch(x){setError(errorText(x))}}
 async function lifecycle(cameraId:string,status:string){const note=status==="active"?"":window.prompt("Reason / note","")||"";try{await post(`/security-camera/cameras/${cameraId}/lifecycle`,{status,note});await load()}catch(x){setError(errorText(x))}}
 async function diagnostics(id:string){setSnapshot("");try{setDiag(await get<any>(`/security-camera/cameras/${id}/diagnostics`))}catch(x){setError(errorText(x))}}
 async function snap(id:string){setSnapshot("");try{const[x,d]=await Promise.all([post<any>(`/security-camera/cameras/${id}/snapshot`,{}),get<any>(`/security-camera/cameras/${id}/diagnostics`)]);setDiag(d);setSnapshot(x.url)}catch(e){setError(errorText(e))}}
 const counts=useMemo(()=>({online:cameras.filter(c=>c.status==="online").length,attention:cameras.filter(c=>c.lifecycle_status&&c.lifecycle_status!=="active").length,hot:cameras.filter(c=>Number(c.temperature_c||0)>=45).length}),[cameras]);
 return <div className="sec-fleet"><header className="sec-fleet-hero"><div><div className="sec-event-kicker"><Stethoscope size={15}/> FLEET ADMINISTRATION</div><h1>Camera fleet & diagnostics</h1><p>Organize cameras into operational groups, inspect device health and explicitly control lifecycle state without deleting historical recordings.</p></div><button onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></header>{error&&<div className="sec-error">{error}</div>}
 <section className="sec-fleet-stats"><div><Camera/><span>Online</span><b>{counts.online}/{cameras.length}</b></div><div><ShieldAlert/><span>Lifecycle attention</span><b>{counts.attention}</b></div><div><Activity/><span>High temperature</span><b>{counts.hot}</b></div><div><Server/><span>Groups</span><b>{fleet.groups.length}</b></div></section>
 <div className="sec-fleet-layout"><section className="sec-fleet-card"><h2>Device lifecycle</h2><div className="sec-fleet-list">{cameras.map(c=><article key={c.id}><div className="sec-fleet-camera"><span className={`sec-status ${c.status}`}>{c.status}</span><div><b>{c.name}</b><small>{c.location||"No location"} · {c.server_name||"No NVR"}</small></div></div><div className="sec-fleet-health"><span>Battery <b>{c.battery_level==null?"—":`${Math.round(c.battery_level)}%`}</b></span><span>Temp <b>{c.temperature_c==null?"—":`${Number(c.temperature_c).toFixed(1)}°C`}</b></span><span>Stream <b>{c.stream_status||"offline"}</b></span><span>App <b>{c.app_version||"—"}</b></span></div><div className="sec-fleet-actions"><select value={c.lifecycle_status||"active"} onChange={e=>void lifecycle(c.id,e.target.value)}><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="disabled">Disabled</option><option value="decommissioned">Decommissioned</option></select><button onClick={()=>void diagnostics(c.id)}><Stethoscope size={13}/>Diagnostics</button><button onClick={()=>void snap(c.id)}><Image size={13}/>Snapshot</button></div>{c.lifecycle_note?<small className="sec-fleet-note">{c.lifecycle_note}</small>:null}</article>)}</div></section>
 <aside className="sec-fleet-card"><h2><FolderPlus size={17}/> Camera groups</h2><form className="sec-group-form" onSubmit={saveGroup}><input name="name" required placeholder="Perimeter cameras"/><input name="description" placeholder="Main gate, rear gate and parking"/><div className="sec-group-picks">{cameras.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(s=>s.includes(c.id)?s.filter(x=>x!==c.id):[...s,c.id])}/>{c.name}</label>)}</div><button type="submit">Save group ({selected.length})</button></form><div className="sec-group-list">{fleet.groups.map(g=><div key={g.id}><b>{g.name}</b><small>{g.description||"No description"}</small><p>{g.cameras.map(c=>c.camera_name).join(" · ")||"No cameras"}</p></div>)}</div></aside></div>
 {diag?<div className="sec-diagnostic-back" onMouseDown={e=>{if(e.target===e.currentTarget){setDiag(null);setSnapshot("")}}}><div className="sec-diagnostic"><button className="close" onClick={()=>{setDiag(null);setSnapshot("")}}>×</button><h2>{diag.camera.name} diagnostics</h2><div className={`sec-diagnostic-health ${diag.health.ok?"ok":"warn"}`}>{diag.health.ok?"No immediate health issues detected":diag.health.issues.join(" · ")}</div>{snapshot?<img src={snapshot} alt="Latest camera snapshot"/>:null}<dl><div><dt>Device</dt><dd>{diag.camera.device_model||diag.camera.platform||"Android camera"}</dd></div><div><dt>Lifecycle</dt><dd>{diag.lifecycle.lifecycle_status}</dd></div><div><dt>Heartbeat</dt><dd>{diag.camera.last_seen_at?new Date(diag.camera.last_seen_at).toLocaleString():"Never"}</dd></div><div><dt>Latest recording</dt><dd>{diag.latestRecording?.started_at?new Date(diag.latestRecording.started_at).toLocaleString():"None"}</dd></div><div><dt>Latest event</dt><dd>{diag.latestEvent?.event_type||"None"}</dd></div><div><dt>Open alerts</dt><dd>{diag.alerts.length}</dd></div></dl></div></div>:null}{busy?<div className="sec-sync">Refreshing camera fleet…</div>:null}</div>
}
