import {useEffect,useState} from "react";
import {Activity,Camera,HardDrive,Play,Plus,RefreshCw,Server,ShieldCheck,Video,Wifi} from "lucide-react";
import {get,post,errorText} from "../../../web/api";
import {PairingQr} from "./PairingQr";
type CameraRow={id:string;name:string;location?:string;status:string;server_id?:string;server_name?:string;device_model?:string;battery_level?:number;temperature_c?:number;wifi_strength?:number;last_seen_at?:string;recording_enabled?:number;last_recording_at?:string};
type ServerRow={id:string;name:string;location?:string;status:string;local_base_url?:string;storage_total_bytes:number;storage_free_bytes:number;last_seen_at?:string;hostname?:string;app_version?:string};
type Recording={id:string;camera_id:string;camera_name:string;server_name?:string;started_at:string;ended_at?:string;local_path:string;size_bytes:number;protected:number;status:string};
export function SecurityCameraWorkspace(){
 const[cameras,setCameras]=useState<CameraRow[]>([]),[servers,setServers]=useState<ServerRow[]>([]),[recordings,setRecordings]=useState<Recording[]>([]),[overview,setOverview]=useState<any>({}),[cameraPair,setCameraPair]=useState<any>(null),[serverPair,setServerPair]=useState<any>(null),[live,setLive]=useState<any>(null),[showPair,setShowPair]=useState(false),[showServer,setShowServer]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const[o,c,s,r]=await Promise.all([get<any>("/security-camera/overview"),get<CameraRow[]>("/security-camera/cameras"),get<ServerRow[]>("/security-camera/servers"),get<Recording[]>("/security-camera/recordings?limit=100")]);setOverview(o);setCameras(c);setServers(s);setRecordings(r)}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 async function createPair(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setCameraPair(await post<any>("/security-camera/pairings",{name:f.get("name"),location:f.get("location"),serverId:f.get("serverId")||null}));setShowPair(false)}catch(x){setError(errorText(x))}}
 async function createServerPair(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{setServerPair(await post<any>("/security-camera/server-pairings",{name:f.get("name"),location:f.get("location")}));setShowServer(false)}catch(x){setError(errorText(x))}}
 async function assign(cameraId:string,serverId:string){try{await post(`/security-camera/cameras/${cameraId}/assign`,{serverId:serverId||null});await load()}catch(x){setError(errorText(x))}}
 async function recording(camera:CameraRow,enabled:boolean){try{await post(`/security-camera/cameras/${camera.id}/recording`,{enabled});await load()}catch(x){setError(errorText(x))}}
 async function watch(camera:CameraRow){try{setLive(await post<any>(`/security-camera/cameras/${camera.id}/live`,{}));await load()}catch(x){setError(errorText(x))}}
 async function revoke(id:string){if(!window.confirm("Revoke this camera? The phone will immediately lose access to Ledgerly camera services."))return;try{await post(`/security-camera/cameras/${id}/revoke`,{});await load()}catch(x){setError(errorText(x))}}
 const used=Number(overview?.servers?.storage_total_bytes||0)-Number(overview?.servers?.storage_free_bytes||0);
 return <div className="sec-cam"><header className="sec-hero"><div><div className="sec-kicker"><ShieldCheck size={14}/> LEDGERLY LOCAL-FIRST CCTV</div><h1>Security Cameras</h1><p>Android cameras record straight to your local NVR over the LAN. Ledgerly coordinates devices, metadata and on-demand live sessions without uploading the continuous video archive to the cloud.</p></div><div className="sec-actions"><button className="sec-ghost" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button><button className="sec-ghost" onClick={()=>setShowServer(true)}><Server size={16}/>Pair NVR</button><button className="sec-primary" onClick={()=>setShowPair(true)}><Plus size={16}/>Add camera</button></div></header>
 {error&&<div className="sec-error">{error}</div>}
 <section className="sec-stats"><Stat icon={<Camera/>} label="Cameras online" value={`${overview?.cameras?.online||0}/${overview?.cameras?.total||0}`}/><Stat icon={<Server/>} label="NVR servers online" value={`${overview?.servers?.online||0}/${overview?.servers?.total||0}`}/><Stat icon={<HardDrive/>} label="Indexed recordings" value={overview?.recordings?.segments||0}/><Stat icon={<Activity/>} label="Live sessions" value={overview?.live?.active||0}/></section>
 <div className="sec-layout"><section className="sec-card sec-cameras"><div className="sec-cardhead"><div><span>CAMERAS</span><h2>Device fleet</h2></div><button onClick={()=>setShowPair(true)}><Plus size={15}/>Pair by QR</button></div>{cameras.length?<div className="sec-grid">{cameras.map(c=><article className="sec-camera" key={c.id}><div className="sec-preview"><Camera size={32}/><span className={`sec-status ${c.status}`}>{c.status==="online"?<Wifi size={12}/>:null}{c.status}</span></div><div className="sec-camera-body"><div><h3>{c.name}</h3><p>{c.location||"No location set"}</p></div><dl><div><dt>Device</dt><dd>{c.device_model||"Android camera"}</dd></div><div><dt>Battery</dt><dd>{c.battery_level==null?"—":`${Math.round(c.battery_level)}%`}</dd></div><div><dt>Recording</dt><dd>{c.recording_enabled===0?"Paused":c.last_recording_at?`Active · ${ago(c.last_recording_at)}`:"Enabled"}</dd></div><div><dt>Temp.</dt><dd>{c.temperature_c==null?"—":`${c.temperature_c}°C`}</dd></div></dl><label className="sec-assign">Local NVR<select value={c.server_id||""} onChange={e=>void assign(c.id,e.target.value)}><option value="">Not assigned</option>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="sec-camera-actions"><button disabled={!c.server_id||c.status!=="online"} onClick={()=>void watch(c)}><Play size={12}/> Watch live</button><button onClick={()=>void recording(c,c.recording_enabled===0)}>{c.recording_enabled===0?"Resume recording":"Pause recording"}</button><button onClick={()=>void revoke(c.id)}>Revoke</button></div></div></article>)}</div>:<Empty text="No cameras yet. Add a camera and scan its QR using Ledgerly Mobile in Security camera mode."/>}</section>
 <section className="sec-card"><div className="sec-cardhead"><div><span>LOCAL STORAGE</span><h2>Camera servers</h2></div><button onClick={()=>setShowServer(true)}><Plus size={15}/>Pair NVR</button></div>{servers.length?servers.map(s=><div className="sec-server sec-server-full" key={s.id}><div><b>{s.name}</b><small>{s.location||s.hostname||"Local camera server"}</small><small>{s.local_base_url||"Local address not reported"}</small></div><div><span className={`sec-status ${s.status}`}>{s.status}</span><small>{bytes(Math.max(0,s.storage_total_bytes-s.storage_free_bytes))} used</small></div></div>):<Empty text="Pair the computer that will store your camera recordings."/>}<div className="sec-storage"><span>Recorded locally</span><b>{bytes(used)} / {bytes(Number(overview?.servers?.storage_total_bytes||0))}</b></div></section></div>
 <section className="sec-card"><div className="sec-cardhead"><div><span>LOCAL ARCHIVE INDEX</span><h2>Recent recordings</h2></div><Video size={20}/></div>{recordings.length?<div className="sec-recordings"><div className="sec-rec sec-rec-head"><span>Camera</span><span>Started</span><span>Size</span><span>NVR / local path</span></div>{recordings.map(r=><div className="sec-rec" key={r.id}><span><b>{r.camera_name}</b><small>{r.status}{r.protected?" · protected":""}</small></span><span>{new Date(r.started_at).toLocaleString()}</span><span>{bytes(r.size_bytes)}</span><span><b>{r.server_name||"NVR"}</b><small>{r.local_path}</small></span></div>)}</div>:<Empty text="Recording metadata will appear here as soon as a paired phone stores its first MP4 segment on the NVR."/>}</section>
 {showPair&&<Modal title="Add security camera" close={()=>setShowPair(false)}><form onSubmit={createPair}><label>Camera name<input name="name" required placeholder="Main Gate"/></label><label>Location<input name="location" placeholder="Front entrance"/></label><label>Local camera server<select name="serverId"><option value="">Assign later</option>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="sec-primary" type="submit">Generate pairing QR</button></form></Modal>}
 {showServer&&<Modal title="Pair local camera server" close={()=>setShowServer(false)}><form onSubmit={createServerPair}><label>Server name<input name="name" required placeholder="School Security NVR"/></label><label>Location<input name="location" placeholder="Server room"/></label><p className="sec-help">After generating the token, start the camera-server package on the local computer with it. The NVR keeps its own long-lived credential after the first pairing.</p><button className="sec-primary" type="submit">Generate NVR pairing token</button></form></Modal>}
 {cameraPair&&<Modal title="Scan with Ledgerly Mobile" close={()=>setCameraPair(null)}><div className="sec-pair"><PairingQr value={cameraPair.qrPayload}/><h3>{cameraPair.cameraName}</h3><p>On the Android phone choose <b>Security camera</b>, then scan this code. It works once and expires at {new Date(cameraPair.expiresAt).toLocaleTimeString()}.</p></div></Modal>}
 {serverPair&&<Modal title="NVR pairing token" close={()=>setServerPair(null)}><div className="sec-token"><p>Use this once on the local camera computer:</p><code>{serverPair.pairingToken}</code><pre>{`LEDGERLY_API_URL='${location.origin}' \\\nCAMERA_SERVER_PAIRING_TOKEN='${serverPair.pairingToken}' \\\nCAMERA_LOCAL_BASE_URL='http://LOCAL-PC-IP:8789' npm start`}</pre><small>Expires {new Date(serverPair.expiresAt).toLocaleString()}.</small></div></Modal>}
 {live&&<Modal title="Live session requested" close={()=>setLive(null)}><div className="sec-live"><Activity/><h3>Opening {cameras.find(c=>c.id===live.cameraId)?.name||"camera"}</h3><p>The NVR has a five-minute signaling session. WebRTC offer/answer exchange is now wired into the control plane; media negotiation is the remaining live-media implementation.</p><code>{live.id}</code></div></Modal>}
 {busy&&<div className="sec-sync">Refreshing camera status…</div>}</div>
}
function Stat({icon,label,value}:{icon:any;label:string;value:any}){return <div className="sec-stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="sec-empty">{text}</div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:any}){return <div className="sec-modalback" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="sec-modal"><div className="sec-modalhead"><h3>{title}</h3><button onClick={close}>×</button></div>{children}</div></div>}
function bytes(n:number){if(!n)return"0 B";const u=["B","KB","MB","GB","TB"];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i<2?0:1)} ${u[i]}`}
function ago(value:string){const sec=Math.max(0,(Date.now()-new Date(value).getTime())/1000);if(sec<60)return`${Math.round(sec)}s ago`;if(sec<3600)return`${Math.round(sec/60)}m ago`;return`${Math.round(sec/3600)}h ago`}
