import {useEffect,useState} from "react";
import {Activity,Camera,HardDrive,Plus,RefreshCw,Server,ShieldCheck,Wifi} from "lucide-react";
import {get,post,errorText} from "../../../web/api";
import {PairingQr} from "./PairingQr";

type CameraRow={id:string;name:string;location?:string;status:string;server_id?:string;server_name?:string;device_model?:string;battery_level?:number;temperature_c?:number;wifi_strength?:number;last_seen_at?:string};
type ServerRow={id:string;name:string;location?:string;status:string;storage_total_bytes:number;storage_free_bytes:number;last_seen_at?:string};

export function SecurityCameraWorkspace(){
 const[cameras,setCameras]=useState<CameraRow[]>([]),[servers,setServers]=useState<ServerRow[]>([]),[overview,setOverview]=useState<any>({}),[pairing,setPairing]=useState<any>(null),[showPair,setShowPair]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const[o,c,s]=await Promise.all([get<any>("/security-camera/overview"),get<CameraRow[]>("/security-camera/cameras"),get<ServerRow[]>("/security-camera/servers")]);setOverview(o);setCameras(c);setServers(s)}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 async function createPair(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await post<any>("/security-camera/pairings",{name:f.get("name"),location:f.get("location"),serverId:f.get("serverId")||null});setPairing(data);setShowPair(false)}catch(x){setError(errorText(x))}}
 async function revoke(id:string){if(!window.confirm("Revoke this camera? The phone will immediately lose access to Ledgerly camera services."))return;try{await post(`/security-camera/cameras/${id}/revoke`,{});await load()}catch(x){setError(errorText(x))}}
 const used=Number(overview?.servers?.storage_total_bytes||0)-Number(overview?.servers?.storage_free_bytes||0);
 return <div className="sec-cam"><header className="sec-hero"><div><div className="sec-kicker"><ShieldCheck size={14}/> LEDGERLY LOCAL-FIRST CCTV</div><h1>Security Cameras</h1><p>Old Android phones record to your local Ledgerly camera server. Remote live viewing is opened only when an authorized user requests it.</p></div><div className="sec-actions"><button className="sec-ghost" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button><button className="sec-primary" onClick={()=>setShowPair(true)}><Plus size={16}/>Add camera</button></div></header>
 {error&&<div className="sec-error">{error}</div>}
 <section className="sec-stats"><Stat icon={<Camera/>} label="Cameras online" value={`${overview?.cameras?.online||0}/${overview?.cameras?.total||0}`}/><Stat icon={<Server/>} label="NVR servers online" value={`${overview?.servers?.online||0}/${overview?.servers?.total||0}`}/><Stat icon={<HardDrive/>} label="Indexed recordings" value={overview?.recordings?.segments||0}/><Stat icon={<Activity/>} label="Live viewers" value={overview?.live?.active||0}/></section>
 <div className="sec-layout"><section className="sec-card sec-cameras"><div className="sec-cardhead"><div><span>CAMERAS</span><h2>Device fleet</h2></div><button onClick={()=>setShowPair(true)}><Plus size={15}/>Pair by QR</button></div>{cameras.length?<div className="sec-grid">{cameras.map(c=><article className="sec-camera" key={c.id}><div className="sec-preview"><Camera size={32}/><span className={`sec-status ${c.status}`}>{c.status==="online"?<Wifi size={12}/>:null}{c.status}</span></div><div className="sec-camera-body"><div><h3>{c.name}</h3><p>{c.location||"No location set"}</p></div><dl><div><dt>Server</dt><dd>{c.server_name||"Not assigned"}</dd></div><div><dt>Device</dt><dd>{c.device_model||"Android camera"}</dd></div><div><dt>Battery</dt><dd>{c.battery_level==null?"—":`${Math.round(c.battery_level)}%`}</dd></div><div><dt>Temp.</dt><dd>{c.temperature_c==null?"—":`${c.temperature_c}°C`}</dd></div></dl><div className="sec-camera-actions"><button disabled title="Live signaling is the next implementation slice">Watch live</button><button onClick={()=>void revoke(c.id)}>Revoke</button></div></div></article>)}</div>:<Empty text="No cameras yet. Choose Add camera, then scan the QR code using Ledgerly Mobile in Security camera mode."/>}</section>
 <section className="sec-card"><div className="sec-cardhead"><div><span>LOCAL STORAGE</span><h2>Camera servers</h2></div></div>{servers.length?servers.map(s=><div className="sec-server" key={s.id}><div><b>{s.name}</b><small>{s.location||"Local camera server"}</small></div><span className={`sec-status ${s.status}`}>{s.status}</span></div>):<Empty text="No local camera server has been paired yet. The server package is now part of the repository and will be paired in the next slice."/>}<div className="sec-storage"><span>Recorded locally</span><b>{bytes(used)} / {bytes(Number(overview?.servers?.storage_total_bytes||0))}</b></div></section></div>
 {showPair&&<Modal title="Add security camera" close={()=>setShowPair(false)}><form onSubmit={createPair}><label>Camera name<input name="name" required placeholder="Main Gate"/></label><label>Location<input name="location" placeholder="Front entrance"/></label><label>Local camera server<select name="serverId"><option value="">Assign later</option>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="sec-primary" type="submit">Generate pairing QR</button></form></Modal>}
 {pairing&&<Modal title="Scan with Ledgerly Mobile" close={()=>setPairing(null)}><div className="sec-pair"><PairingQr value={pairing.qrPayload}/><h3>{pairing.cameraName}</h3><p>On the Android phone choose <b>Security camera</b>, then scan this code. It works once and expires at {new Date(pairing.expiresAt).toLocaleTimeString()}.</p></div></Modal>}
 {busy&&<div className="sec-sync">Refreshing camera status…</div>}</div>
}
function Stat({icon,label,value}:{icon:any;label:string;value:any}){return <div className="sec-stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div>}
function Empty({text}:{text:string}){return <div className="sec-empty">{text}</div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:any}){return <div className="sec-modalback" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="sec-modal"><div className="sec-modalhead"><h3>{title}</h3><button onClick={close}>×</button></div>{children}</div></div>}
function bytes(n:number){if(!n)return"0 B";const u=["B","KB","MB","GB","TB"];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i<2?0:1)} ${u[i]}`}
