import {useEffect,useState} from "react";
import {Activity,ArrowLeftRight,CheckCircle2,RefreshCw,Server,ShieldCheck,TriangleAlert} from "lucide-react";
import {get,post,errorText} from "../../../web/api";
type Camera={id:string;name:string;server_id?:string};type ServerRow={id:string;name:string;status:string;last_seen_at?:string};
type Redundancy={camera_id:string;camera_name:string;primary_server_id:string;secondary_server_id:string;primary_server_name:string;secondary_server_name:string;primary_status:string;secondary_status:string;state:string;failover_after_seconds:number;failback_enabled:number;failback_after_seconds:number;last_reason?:string;state_changed_at:string};
type FailEvent={id:string;camera_name:string;from_server_name?:string;to_server_name?:string;reason:string;state:string;automatic:number;created_at:string};type Validation={id:string;server_id?:string;camera_id?:string;check_type:string;status:string;message?:string;created_at:string};
export function SecurityCameraResilience(){const[cameras,setCameras]=useState<Camera[]>([]),[servers,setServers]=useState<ServerRow[]>([]),[data,setData]=useState<any>({configs:[],events:[],validation:{runs:[],summary:{}}}),[busy,setBusy]=useState(false),[error,setError]=useState("");async function load(){setBusy(true);setError("");try{const[c,s,r]=await Promise.all([get<Camera[]>("/security-camera/cameras"),get<ServerRow[]>("/security-camera/servers"),get<any>("/security-camera/redundancy")]);setCameras(c);setServers(s);setData(r)}catch(e){setError(errorText(e))}finally{setBusy(false)}}useEffect(()=>{void load();const t=setInterval(()=>void load(),20000);return()=>clearInterval(t)},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),cameraId=String(f.get("cameraId")||"");try{await post(`/security-camera/cameras/${cameraId}/redundancy`,{primaryServerId:f.get("primaryServerId"),secondaryServerId:f.get("secondaryServerId"),failoverAfterSeconds:Number(f.get("failoverAfterSeconds")||90),failbackEnabled:f.get("failbackEnabled")==="on",failbackAfterSeconds:Number(f.get("failbackAfterSeconds")||300),enabled:true});await load()}catch(x){setError(errorText(x))}}
 async function switchTo(cameraId:string,target:"primary"|"secondary"){const reason=window.prompt(`Reason for switching to ${target} NVR`,target==="secondary"?"Manual disaster-recovery test":"Restore primary NVR")||undefined;try{await post(`/security-camera/cameras/${cameraId}/failover`,{target,reason});await load()}catch(x){setError(errorText(x))}}
 const configs:Redundancy[]=data.configs||[],events:FailEvent[]=data.events||[],runs:Validation[]=data.validation?.runs||[],summary=data.validation?.summary||{};
 return <div className="sec-res"><header className="sec-res-hero"><div><div className="sec-res-kicker"><ShieldCheck size={15}/> CAMERA RESILIENCE</div><h1>NVR failover & deployment validation</h1><p>Give critical cameras a secondary recorder, automatically move capture when the primary NVR becomes unhealthy, and verify the local appliance continuously.</p></div><button onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></header>{error&&<div className="sec-error">{error}</div>}
 <section className="sec-res-stats"><Stat label="Protected cameras" value={configs.length}/><Stat label="On secondary NVR" value={configs.filter(x=>x.state==="secondary").length}/><Stat label="Validation failures · 24h" value={summary.failed||0}/><Stat label="Validation warnings · 24h" value={summary.warning||0}/></section>
 <div className="sec-res-grid"><section className="sec-res-card"><h2><ArrowLeftRight size={18}/> Configure automatic failover</h2><form className="sec-res-form" onSubmit={save}><label>Camera<select name="cameraId" required>{cameras.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Primary NVR<select name="primaryServerId" required>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Secondary NVR<select name="secondaryServerId" required>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Fail over after seconds<input name="failoverAfterSeconds" type="number" min="30" max="900" defaultValue="90"/></label><label>Fail back after stable seconds<input name="failbackAfterSeconds" type="number" min="60" max="3600" defaultValue="300"/></label><label className="check"><input name="failbackEnabled" type="checkbox" defaultChecked/> Automatically return to primary</label><button>Save redundancy</button></form><p className="hint">A failover changes the camera's real NVR assignment. Ledgerly Mobile sees that through its normal camera config polling and reconnects to the secondary recorder without requiring a new QR pairing.</p></section>
 <section className="sec-res-card"><h2><Server size={18}/> Current protection state</h2><div className="sec-res-list">{configs.length?configs.map(r=><article key={r.camera_id} className={r.state}><div><b>{r.camera_name}</b><small>{r.primary_server_name} → {r.secondary_server_name}</small><small>{r.last_reason||"Primary recorder selected"}</small></div><span>{r.state}</span><div className="actions"><button onClick={()=>void switchTo(r.camera_id,"primary")}>Use primary</button><button onClick={()=>void switchTo(r.camera_id,"secondary")}>Use secondary</button></div></article>):<div className="sec-empty">No camera redundancy configured yet.</div>}</div></section></div>
 <section className="sec-res-card"><h2><Activity size={18}/> Appliance validation</h2><div className="sec-val-grid">{runs.slice(0,100).map(v=><article key={v.id} className={v.status}>{v.status==="passed"?<CheckCircle2 size={16}/>:<TriangleAlert size={16}/>}<div><b>{v.check_type.replace(/_/g," ")}</b><small>{v.message||"No details"}</small></div><time>{new Date(v.created_at).toLocaleString()}</time></article>)}</div></section>
 <section className="sec-res-card"><h2><ArrowLeftRight size={18}/> Failover history</h2><div className="sec-fail-table"><div className="head"><span>Camera</span><span>Move</span><span>Reason</span><span>Time</span></div>{events.map(e=><div key={e.id}><span><b>{e.camera_name}</b><small>{e.automatic?"automatic":"manual"}</small></span><span>{e.from_server_name||"—"} → {e.to_server_name||"—"}</span><span>{e.reason}</span><span>{new Date(e.created_at).toLocaleString()}</span></div>)}</div></section>{busy&&<div className="sec-sync">Refreshing resilience status…</div>}</div>}
function Stat({label,value}:{label:string;value:any}){return <div className="sec-res-stat"><span>{label}</span><b>{value}</b></div>}
