import {SafeAreaView,StatusBar,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import type {Registration} from "../types";

export function AttendanceModuleScreen({registration,onBack,onRegister,onLaunch}:{registration:Registration|null;onBack:()=>void;onRegister:()=>void;onLaunch:()=>void}){
  return <SafeAreaView style={s.root}><StatusBar barStyle="light-content" backgroundColor="#071c16"/>
    <View style={s.header}><TouchableOpacity style={s.back} onPress={onBack}><Text style={s.backText}>←</Text></TouchableOpacity><View><Text style={s.eyebrow}>LEDGERLY MOBILE</Text><Text style={s.headerTitle}>Attendance</Text></View><View style={s.moduleBadge}><Text style={s.moduleBadgeText}>MODULE 01</Text></View></View>
    <View style={s.hero}><View style={s.heroIcon}><Text style={s.heroIconText}>✓</Text></View><Text style={s.title}>Attendance kiosk</Text><Text style={s.copy}>The existing secure kiosk is now the first operational module in Ledgerly Mobile.</Text><View style={s.status}><View style={[s.statusDot,registration?s.readyDot:s.setupDot]}/><View style={{flex:1}}><Text style={s.statusTitle}>{registration?"This device is registered":"Device setup required"}</Text><Text style={s.statusText}>{registration?"Kiosk credentials are securely available on this device.":"Register once using the QR code created from Ledgerly Attendance on the web."}</Text></View></View></View>
    <View style={s.featureGrid}><View style={s.feature}><Text style={s.featureIcon}>↻</Text><Text style={s.featureTitle}>Offline queue</Text><Text style={s.featureText}>Captures continue when the network is unstable and sync later.</Text></View><View style={s.feature}><Text style={s.featureIcon}>◎</Text><Text style={s.featureTitle}>Multiple capture modes</Text><Text style={s.featureText}>Face, QR, NFC and supervised lookup remain available.</Text></View><View style={s.feature}><Text style={s.featureIcon}>⌁</Text><Text style={s.featureTitle}>Secure device mode</Text><Text style={s.featureText}>Kiosk lock and administrator PIN controls remain unchanged.</Text></View><View style={s.feature}><Text style={s.featureIcon}>✓</Text><Text style={s.featureTitle}>Live sync</Text><Text style={s.featureText}>Roster, settings and attendance events stay connected to Ledgerly.</Text></View></View>
    <View style={s.bottom}><Text style={s.notice}>Launching kiosk mode switches to the dedicated full-screen attendance experience.</Text><TouchableOpacity activeOpacity={.86} style={s.primary} onPress={registration?onLaunch:onRegister}><Text style={s.primaryText}>{registration?"Launch attendance kiosk":"Register this device"}</Text><Text style={s.primaryArrow}>→</Text></TouchableOpacity></View>
  </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f3f6f4"},header:{height:76,backgroundColor:"#071c16",paddingHorizontal:18,flexDirection:"row",alignItems:"center"},back:{width:40,height:40,borderRadius:13,backgroundColor:"#14382d",alignItems:"center",justifyContent:"center",marginRight:12},backText:{color:"white",fontSize:22},eyebrow:{color:"#668f7e",fontSize:8,fontWeight:"900",letterSpacing:1.2},headerTitle:{color:"white",fontSize:20,fontWeight:"900",marginTop:2},moduleBadge:{marginLeft:"auto",borderWidth:1,borderColor:"#2b5746",borderRadius:20,paddingHorizontal:10,paddingVertical:6},moduleBadgeText:{color:"#8cb7a5",fontSize:8,fontWeight:"900",letterSpacing:1},hero:{margin:18,backgroundColor:"#0b2a20",borderRadius:25,padding:20},heroIcon:{width:50,height:50,borderRadius:16,backgroundColor:"#164a37",alignItems:"center",justifyContent:"center"},heroIconText:{fontSize:22,fontWeight:"900",color:"#70d6a6"},title:{color:"white",fontSize:28,fontWeight:"900",letterSpacing:-.7,marginTop:18},copy:{color:"#abc3b8",fontSize:13,lineHeight:20,marginTop:7},status:{marginTop:20,borderTopWidth:1,borderTopColor:"#234437",paddingTop:16,flexDirection:"row",gap:10},statusDot:{width:9,height:9,borderRadius:5,marginTop:4},readyDot:{backgroundColor:"#47c98b"},setupDot:{backgroundColor:"#f2b74b"},statusTitle:{color:"white",fontSize:12,fontWeight:"900"},statusText:{color:"#7e9f91",fontSize:11,lineHeight:17,marginTop:3},featureGrid:{paddingHorizontal:18,flexDirection:"row",flexWrap:"wrap",gap:10},feature:{width:"48.5%",minHeight:128,backgroundColor:"white",borderRadius:18,padding:15,borderWidth:1,borderColor:"#dfe6e2"},featureIcon:{fontSize:18,color:"#158e5c",fontWeight:"900"},featureTitle:{fontSize:12,fontWeight:"900",color:"#263a31",marginTop:10},featureText:{fontSize:10,lineHeight:15,color:"#7a8982",marginTop:4},bottom:{marginTop:"auto",padding:18},notice:{fontSize:10,lineHeight:15,color:"#7d8b84",textAlign:"center",marginHorizontal:18,marginBottom:12},primary:{height:58,borderRadius:17,backgroundColor:"#148e5b",paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},primaryText:{color:"white",fontSize:14,fontWeight:"900"},primaryArrow:{color:"white",fontSize:22}});
