const KEY=/^[a-z0-9][a-z0-9-]{0,79}$/;
function key(value,name){if(typeof value!=='string'||!KEY.test(value))throw Object.assign(new Error(`${name} is invalid`),{code:'PLATFORM_CONFIG_INVALID_KEY',status:400});return value;}
function bool(value,name){if(typeof value!=='boolean')throw Object.assign(new Error(`${name} must be boolean`),{code:'PLATFORM_CONFIG_INVALID_VALUE',status:400});return value;}
function version(value){const n=Number(value);if(!Number.isInteger(n)||n<0)throw Object.assign(new Error('expectedVersion must be a non-negative integer'),{code:'PLATFORM_CONFIG_INVALID_VERSION',status:400});return n;}
function object(value,name){if(value==null)return {};if(typeof value!=='object'||Array.isArray(value))throw Object.assign(new Error(`${name} must be an object`),{code:'PLATFORM_CONFIG_INVALID_VALUE',status:400});return value;}
function actor(actor){if(typeof actor?.actorId!=='string'||!actor.actorId)throw new TypeError('actor.actorId required');return actor;}
export class PlatformConfigService{
 constructor({repository,audit=null}){if(!repository)throw new TypeError('repository required');this.repository=repository;this.audit=audit;}
 async list({organizationId,moduleKey=null}){const modules=await this.repository.listModules(organizationId);const features=await this.repository.listFeatures({organizationId,moduleKey});return{modules,features};}
 async setModule({organizationId,actor:who,moduleKey,enabled,settings={},expectedVersion=0}){actor(who);const prior=await this.repository.getModule(organizationId,key(moduleKey,'moduleKey'));const row=await this.repository.setModule({organizationId,moduleKey,enabled:bool(enabled,'enabled'),settingsJson:JSON.stringify(object(settings,'settings')),updatedBy:who.actorId,expectedVersion:version(expectedVersion)});await this.audit?.write({organizationId,actorType:who.actorType??'human',actorId:who.actorId,action:'platform.module.override.set',entityType:'platform_module_override',entityId:moduleKey,before:prior,after:row});return row;}
 async clearModule({organizationId,actor:who,moduleKey,expectedVersion}){actor(who);key(moduleKey,'moduleKey');const prior=await this.repository.getModule(organizationId,moduleKey);if(!prior)return null;const row=await this.repository.clearModule({organizationId,moduleKey,expectedVersion:version(expectedVersion)});await this.audit?.write({organizationId,actorType:who.actorType??'human',actorId:who.actorId,action:'platform.module.override.clear',entityType:'platform_module_override',entityId:moduleKey,before:prior,after:null});return row;}
 async setFeature({organizationId,actor:who,moduleKey,featureKey,enabled,config={},expectedVersion=0}){actor(who);key(moduleKey,'moduleKey');key(featureKey,'featureKey');const prior=await this.repository.getFeature(organizationId,moduleKey,featureKey);const row=await this.repository.setFeature({organizationId,moduleKey,featureKey,enabled:bool(enabled,'enabled'),configJson:JSON.stringify(object(config,'config')),updatedBy:who.actorId,expectedVersion:version(expectedVersion)});await this.audit?.write({organizationId,actorType:who.actorType??'human',actorId:who.actorId,action:'platform.feature.override.set',entityType:'platform_feature_override',entityId:`${moduleKey}:${featureKey}`,before:prior,after:row});return row;}
 async clearFeature({organizationId,actor:who,moduleKey,featureKey,expectedVersion}){actor(who);key(moduleKey,'moduleKey');key(featureKey,'featureKey');const prior=await this.repository.getFeature(organizationId,moduleKey,featureKey);if(!prior)return null;const row=await this.repository.clearFeature({organizationId,moduleKey,featureKey,expectedVersion:version(expectedVersion)});await this.audit?.write({organizationId,actorType:who.actorType??'human',actorId:who.actorId,action:'platform.feature.override.clear',entityType:'platform_feature_override',entityId:`${moduleKey}:${featureKey}`,before:prior,after:null});return row;}
}
