import type {MobileSession} from "../auth";
import {ledgerlyRequest,query,type SessionUpdater} from "../apiClient";
import type {Admission,BootstrapStatus,DisciplineIncident,DisciplineSummary,FeeDashboard,Guardian,PromotionRun,SchoolFile,SchoolProfile,SchoolRole,SchoolUser,SetupBundle,SetupKey,Staff,Student} from "./types";

type Client={session:MobileSession;onSession?:SessionUpdater};
const req=<T>(c:Client,path:string,init:RequestInit={})=>ledgerlyRequest<T>(c.session,`/school${path}`,init,c.onSession);
const json=(method:string,body?:unknown):RequestInit=>({method,body:body===undefined?undefined:JSON.stringify(body)});
const list=<T>(c:Client,path:string,params:Record<string,any>={})=>req<T[]>(c,`${path}${query(params)}`);

export const schoolApi={
 profile:(c:Client)=>req<SchoolProfile|null>(c,"/setup/profile"),
 saveProfile:(c:Client,body:any)=>req<SchoolProfile>(c,"/setup/profile",json("PUT",body)),
 bootstrapStatus:(c:Client)=>req<BootstrapStatus>(c,"/setup/bootstrap/status"),
 restoreDefaults:(c:Client)=>req<any>(c,"/setup/bootstrap/defaults",json("POST",{})),
 setupList:(c:Client,key:SetupKey,params:Record<string,any>={limit:500})=>list<any>(c,`/setup/${key}`,params),
 setupGet:(c:Client,key:SetupKey,id:string)=>req<any>(c,`/setup/${key}/${id}`),
 setupCreate:(c:Client,key:SetupKey,body:any)=>req<any>(c,`/setup/${key}`,json("POST",body)),
 setupUpdate:(c:Client,key:SetupKey,id:string,body:any)=>req<any>(c,`/setup/${key}/${id}`,json("PUT",body)),
 setupDelete:(c:Client,key:SetupKey,id:string)=>req<void>(c,`/setup/${key}/${id}`,{method:"DELETE"}),
 settings:(c:Client)=>list<any>(c,"/setup/settings/all"),
 saveSetting:(c:Client,body:{group:string;key:string;value:any})=>req<any>(c,"/setup/settings/value",json("PUT",body)),
 setupBundle:async(c:Client):Promise<SetupBundle>=>{const keys:[keyof SetupBundle,SetupKey][]=[["branches","branches"],["academicYears","academicYears"],["terms","terms"],["departments","departments"],["classLevels","classLevels"],["classes","classes"],["streams","streams"],["subjects","subjects"],["lessonPeriods","lessonPeriods"],["feeCategories","feeCategories"],["paymentMethods","paymentMethods"]];const pairs=await Promise.all(keys.map(async([name,key])=>[name,await schoolApi.setupList(c,key)] as const));return Object.fromEntries(pairs) as SetupBundle},
 students:(c:Client,params:Record<string,any>={})=>list<Student>(c,"/student-management/students",{limit:200,...params}),
 student:(c:Client,id:string)=>req<Student>(c,`/student-management/students/${id}`),
 createStudent:(c:Client,body:any)=>req<any>(c,"/student-management/students",json("POST",body)),
 updateStudent:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/students/${id}`,json("PUT",body)),
 changeStudentStatus:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/students/${id}/status`,json("POST",body)),
 transferStudent:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/students/${id}/transfer`,json("POST",body)),
 promoteStudent:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/students/${id}/promote`,json("POST",body)),
 addGuardian:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/students/${id}/guardians`,json("POST",body)),
 addSibling:(c:Client,id:string,siblingStudentId:string)=>req<any>(c,`/student-management/students/${id}/siblings`,json("POST",{siblingStudentId})),
 addStudentDocument:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/students/${id}/documents`,json("POST",body)),
 admissions:(c:Client,params:Record<string,any>={})=>list<Admission>(c,"/student-management/admissions",{limit:200,...params}),
 createAdmission:(c:Client,body:any)=>req<Admission>(c,"/student-management/admissions",json("POST",body)),
 decideAdmission:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/admissions/${id}/decision`,json("POST",body)),
 enrollAdmission:(c:Client,id:string,body:any)=>req<any>(c,`/student-management/admissions/${id}/enroll`,json("POST",body)),
 guardians:(c:Client,params:Record<string,any>={})=>list<Guardian>(c,"/student-management/guardians",{limit:200,...params}),
 enrollmentReport:(c:Client)=>list<any>(c,"/student-management/reports/enrollment"),
 demographicsReport:(c:Client)=>list<any>(c,"/student-management/reports/demographics"),
 staff:(c:Client,params:Record<string,any>={})=>list<Staff>(c,"/staff-management/staff",{limit:200,...params}),
 staffMember:(c:Client,id:string)=>req<Staff>(c,`/staff-management/staff/${id}`),
 createStaff:(c:Client,body:any)=>req<any>(c,"/staff-management/staff",json("POST",body)),
 updateStaff:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/staff/${id}`,json("PUT",body)),
 deleteStaff:(c:Client,id:string)=>req<void>(c,`/staff-management/staff/${id}`,{method:"DELETE"}),
 positions:(c:Client)=>list<any>(c,"/staff-management/positions"),
 createPosition:(c:Client,body:any)=>req<any>(c,"/staff-management/positions",json("POST",body)),
 updatePosition:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/positions/${id}`,json("PUT",body)),
 deletePosition:(c:Client,id:string)=>req<void>(c,`/staff-management/positions/${id}`,{method:"DELETE"}),
 addQualification:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/qualifications`,json("POST",body)),
 verifyQualification:(c:Client,id:string,qid:string)=>req<any>(c,`/staff-management/staff/${id}/qualifications/${qid}/verify`,json("POST",{})),
 deleteQualification:(c:Client,id:string,qid:string)=>req<void>(c,`/staff-management/staff/${id}/qualifications/${qid}`,{method:"DELETE"}),
 addStaffSubject:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/subjects`,json("POST",body)),
 deleteStaffSubject:(c:Client,id:string,subjectId:string)=>req<void>(c,`/staff-management/staff/${id}/subjects/${subjectId}`,{method:"DELETE"}),
 addTeachingAssignment:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/assignments`,json("POST",body)),
 deleteTeachingAssignment:(c:Client,id:string,aid:string)=>req<void>(c,`/staff-management/staff/${id}/assignments/${aid}`,{method:"DELETE"}),
 addCompensation:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/compensation`,json("POST",body)),
 disableCompensation:(c:Client,id:string,cid:string)=>req<void>(c,`/staff-management/staff/${id}/compensation/${cid}`,{method:"DELETE"}),
 payrollAdjustment:(c:Client,id:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/payroll-adjustments`,json("POST",body)),
 payslips:(c:Client,id:string)=>list<any>(c,`/staff-management/staff/${id}/payslips`),
 paySalary:(c:Client,id:string,lineId:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/payslips/${lineId}/payments`,json("POST",body)),
 reverseSalaryPayment:(c:Client,id:string,paymentRecordId:string,body:any)=>req<any>(c,`/staff-management/staff/${id}/salary-payments/${paymentRecordId}/reverse`,json("POST",body)),
 disciplineSummary:(c:Client)=>req<DisciplineSummary>(c,"/discipline/summary"),
 offenceTypes:(c:Client)=>list<any>(c,"/discipline/offence-types"),
 createOffenceType:(c:Client,body:any)=>req<any>(c,"/discipline/offence-types",json("POST",body)),
 incidents:(c:Client,params:Record<string,any>={})=>list<DisciplineIncident>(c,"/discipline/incidents",{limit:200,...params}),
 incident:(c:Client,id:string)=>req<DisciplineIncident>(c,`/discipline/incidents/${id}`),
 createIncident:(c:Client,body:any)=>req<any>(c,"/discipline/incidents",json("POST",body)),
 updateIncident:(c:Client,id:string,body:any)=>req<any>(c,`/discipline/incidents/${id}`,json("PUT",body)),
 promotionRuns:(c:Client)=>list<PromotionRun>(c,"/promotion/runs",{limit:200}),
 promotionRun:(c:Client,id:string)=>req<PromotionRun>(c,`/promotion/runs/${id}`),
 previewPromotions:(c:Client,body:any)=>req<PromotionRun>(c,"/promotion/runs/preview",json("POST",body)),
 updatePromotionItem:(c:Client,runId:string,itemId:string,body:any)=>req<any>(c,`/promotion/runs/${runId}/items/${itemId}`,json("PUT",body)),
 applyPromotionRun:(c:Client,id:string)=>req<any>(c,`/promotion/runs/${id}/apply`,json("POST",{})),
 cancelPromotionRun:(c:Client,id:string)=>req<any>(c,`/promotion/runs/${id}/cancel`,json("POST",{})),
 feeDashboard:(c:Client,params:Record<string,any>={})=>req<FeeDashboard>(c,`/fees/reports/dashboard${query(params)}`),
 feeBalances:(c:Client,params:Record<string,any>={})=>list<any>(c,"/fees/reports/balances",{limit:200,...params}),
 studentStatement:(c:Client,id:string,params:Record<string,any>={})=>req<any>(c,`/fees/students/${id}/statement${query(params)}`),
 roles:(c:Client)=>list<SchoolRole>(c,"/iam/roles"),
 createRole:(c:Client,body:any)=>req<any>(c,"/iam/roles",json("POST",body)),
 updateRole:(c:Client,id:string,body:any)=>req<any>(c,`/iam/roles/${id}`,json("PUT",body)),
 deleteRole:(c:Client,id:string)=>req<void>(c,`/iam/roles/${id}`,{method:"DELETE"}),
 users:(c:Client)=>list<SchoolUser>(c,"/iam/users"),
 createUser:(c:Client,body:any)=>req<any>(c,"/iam/users",json("POST",body)),
 updateUser:(c:Client,id:string,body:any)=>req<any>(c,`/iam/users/${id}`,json("PUT",body)),
 updateUserAssignments:(c:Client,id:string,body:any)=>req<any>(c,`/iam/users/${id}/assignments`,json("PUT",body)),
 userSessions:(c:Client,id:string)=>list<any>(c,`/iam/users/${id}/sessions`),
 revokeUserSession:(c:Client,id:string,sessionId:string)=>req<void>(c,`/iam/users/${id}/sessions/${sessionId}`,{method:"DELETE"}),
 loginHistory:(c:Client)=>list<any>(c,"/iam/login-history"),
 securityPolicy:(c:Client)=>req<any>(c,"/iam/security-policy"),
 saveSecurityPolicy:(c:Client,body:any)=>req<any>(c,"/iam/security-policy",json("PUT",body)),
 bootstrapIam:(c:Client)=>req<any>(c,"/iam/bootstrap",json("POST",{})),
 files:(c:Client,limit=200)=>list<SchoolFile>(c,"/files/",{limit}),
 file:(c:Client,id:string)=>req<SchoolFile>(c,`/files/${id}`),
 deleteFile:(c:Client,id:string)=>req<void>(c,`/files/${id}`,{method:"DELETE"}),
};
