import { useEffect, useMemo, useState } from "react";
import { Archive, FileText, History, Paperclip, RefreshCw, ShieldCheck, Trash2, Upload } from "lucide-react";
import { authStore, errorText } from "../../../web/api";

type Attachment={attachment_id:string;name:string;storage_ref:string;content_type?:string;size?:number|null;created_by?:string;created_at?:string};
type Approval={actor_type?:string;actor_id?:string;actor_name?:string;timestamp?:string;reason?:string|null;official?:boolean};
type DocumentRow={document_id:string;type:string;title:string;content:any;version:number;status:string;creator:any;ai_provenance:any;human_editors?:any[];approvals?:Approval[];attachments?:Attachment[];rendered_pdf_ref?:string|null;updated_at:string};
type VersionRow={document_id:string;version:number;content:any;provenance:any;edited_by:any;created_at:string};

async function api<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("Accept","application/json");if(init.body&&typeof init.body==="string"&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");const token=authStore.getAccess();if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`/selfhost/ai${path}`,{...init,headers});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`AI request failed (${response.status})`);return payload as T;}
const titleCase=(value:string)=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());
const statusClass=(value:string)=>`aiw-pill aiw-${String(value||"unknown").replaceAll("_","-")}`;
const editable=(status:string)=>["draft","in_review","changes_requested"].includes(status);
const sizeText=(value?:number|null)=>value==null?"":value<1024?`${value} B`:value<1024*1024?`${(value/1024).toFixed(1)} KB`:`${(value/1024/1024).toFixed(1)} MB`;

export function AiDocumentsWorkspace(){
 const[rows,setRows]=useState<DocumentRow[]>([]),[selectedId,setSelectedId]=useState(""),[history,setHistory]=useState<VersionRow[]>([]),[draft,setDraft]=useState(""),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const selected=useMemo(()=>rows.find((row)=>row.document_id===selectedId)||rows[0]||null,[rows,selectedId]);
 async function load(){setBusy(true);setError("");try{const result=await api<{items:DocumentRow[]}>("/documents");setRows(result.items||[]);if(!selectedId&&result.items?.[0])setSelectedId(result.items[0].document_id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function loadHistory(id:string){try{setHistory((await api<{items:VersionRow[]}>(`/documents/${id}/history`)).items||[]);}catch(e){setError(errorText(e));}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(selected?.document_id)void loadHistory(selected.document_id)},[selected?.document_id]);
 async function mutate(work:()=>Promise<unknown>){setBusy(true);setError("");try{await work();await load();if(selected?.document_id)await loadHistory(selected.document_id);return true;}catch(e){setError(errorText(e));return false;}finally{setBusy(false);}}
 function startEdit(){if(!selected)return;setDraft(JSON.stringify(selected.content??{},null,2));setEditing(true);}
 async function saveEdit(){if(!selected)return;try{const content=JSON.parse(draft);if(await mutate(()=>api(`/documents/${selected.document_id}`,{method:"PATCH",body:JSON.stringify({content,reason:"Human revision from AI Workforce Documents"})})))setEditing(false);}catch{setError("Document content must be valid JSON.");}}
 async function setStatus(status:string){if(!selected)return;await mutate(()=>api(`/documents/${selected.document_id}/status`,{method:"POST",body:JSON.stringify({status,reason:`${titleCase(status)} by human operator`})}));}
 async function upload(file:File){if(!selected)return;await mutate(async()=>{const headers=new Headers({"X-File-Name":file.name,"Content-Type":file.type||"application/octet-stream"});const token=authStore.getAccess();if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`/selfhost/ai/documents/${selected.document_id}/attachments`,{method:"POST",headers,body:file});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`Attachment upload failed (${response.status})`);});}
 async function removeAttachment(id:string){if(!selected)return;await mutate(()=>api(`/documents/${selected.document_id}/attachments/${encodeURIComponent(id)}`,{method:"DELETE"}));}
 async function openPdf(){if(!selected)return;try{const result=await api<{url:string}>(`/documents/${selected.document_id}/pdf`);window.open(result.url,"_blank","noopener,noreferrer");}catch(e){setError(errorText(e));}}
 return <div className="aiw-shell">
  <header className="aiw-hero"><div><p className="aiw-eyebrow"><FileText size={15}/> Ledgerly AI Workforce</p><h1>Documents</h1><p>Versioned AI drafts with human edits, attachments, official approvals, provenance and local PDF output.</p></div><button onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>{busy?"Refreshing…":"Refresh"}</button></header>
  {error&&<div className="aiw-error">{error}</div>}
  <div className="aiw-admin-grid">
   <div><div className="aiw-section-head"><div><h3>Document register</h3><small>{rows.length} local structured documents</small></div></div><div className="aiw-list">{rows.map((row)=><button key={row.document_id} className={`aiw-row aiw-agent-button ${selected?.document_id===row.document_id?"aiw-selected":""}`} onClick={()=>{setSelectedId(row.document_id);setEditing(false)}}><FileText/><div><b>{row.title}</b><small>{titleCase(row.type)} · v{row.version} · {new Date(row.updated_at).toLocaleString()}</small></div><span className={statusClass(row.status)}>{titleCase(row.status)}</span></button>)}</div>{!rows.length&&!busy&&<div className="aiw-empty">No AI documents yet. Assign the Secretary, Academic Assistant, HR Assistant or another permitted employee a document task.</div>}</div>
   {selected&&<aside className="aiw-editor"><div className="aiw-inline"><span className={statusClass(selected.status)}>{titleCase(selected.status)}</span><span>v{selected.version}</span></div><h3>{selected.title}</h3><small>{titleCase(selected.type)} · {selected.document_id}</small>
    {selected.ai_provenance?.document&&<p className="aiw-origin">✦ AI · {selected.ai_provenance.document.agent_name}<br/><span>{selected.ai_provenance.document.agent_role}</span></p>}
    {(selected.human_editors?.length??0)>0&&<small>Human edits: {selected.human_editors?.length} · original AI provenance retained</small>}
    {editing?<><textarea rows={16} value={draft} onChange={(e)=>setDraft(e.target.value)}/><div className="aiw-actions"><button disabled={busy} onClick={()=>void saveEdit()}>Save revision</button><button className="aiw-secondary" onClick={()=>setEditing(false)}>Cancel</button></div></>:<><pre className="aiw-code">{JSON.stringify(selected.content??{},null,2)}</pre>{editable(selected.status)&&<button className="aiw-secondary" onClick={startEdit}>Edit structured content</button>}</>}
    <div className="aiw-actions">{selected.status==="draft"&&<button disabled={busy} onClick={()=>void setStatus("in_review")}>Send to review</button>}{selected.status==="in_review"&&<><button className="aiw-secondary" disabled={busy} onClick={()=>void setStatus("changes_requested")}>Request changes</button><button disabled={busy} onClick={()=>void setStatus("approved")}><ShieldCheck size={14}/>Officially approve</button></>}{selected.status==="changes_requested"&&<button disabled={busy} onClick={()=>void setStatus("in_review")}>Back to review</button>}{selected.status==="approved"&&<button disabled={busy} onClick={()=>void setStatus("published")}>Publish</button>}{["approved","published"].includes(selected.status)&&<button className="aiw-secondary" disabled={busy} onClick={()=>void mutate(()=>api(`/documents/${selected.document_id}/render-pdf`,{method:"POST",body:"{}"}))}>Render PDF</button>}{selected.rendered_pdf_ref&&<button className="aiw-secondary" onClick={()=>void openPdf()}><Archive size={14}/>Open PDF</button>}{selected.status!=="archived"&&<button className="aiw-secondary" disabled={busy} onClick={()=>void setStatus("archived")}>Archive</button>}</div>
    <section><div className="aiw-section-head"><div><h3><Paperclip size={16}/> Attachments</h3><small>Tenant-scoped local storage; frozen after approval.</small></div>{editable(selected.status)&&<label className="aiw-secondary"><Upload size={14}/>Add file<input hidden type="file" onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file);e.currentTarget.value=""}}/></label>}</div><div className="aiw-list">{(selected.attachments||[]).map((item)=><div className="aiw-row" key={item.attachment_id}><Paperclip/><div><b>{item.name}</b><small>{item.content_type||"file"}{item.size!=null?` · ${sizeText(item.size)}`:""}{item.created_at?` · ${new Date(item.created_at).toLocaleString()}`:""}</small></div>{editable(selected.status)&&<button className="aiw-secondary" disabled={busy} onClick={()=>void removeAttachment(item.attachment_id)}><Trash2 size={14}/>Remove</button>}</div>)}{!(selected.attachments?.length)&&<small>No attachments.</small>}</div></section>
    <section><h3><ShieldCheck size={16}/> Official approval trail</h3><div className="aiw-list">{(selected.approvals||[]).map((item,index)=><div className="aiw-row" key={`${item.timestamp||"approval"}-${index}`}><ShieldCheck/><div><b>{item.actor_name||item.actor_id||"Human approver"}</b><small>{item.timestamp?new Date(item.timestamp).toLocaleString():""}{item.reason?` · ${item.reason}`:""}</small></div><span className={statusClass(item.official?"approved":"in_review")}>{item.official?"Official":"Review"}</span></div>)}{!(selected.approvals?.length)&&<small>No official approval recorded yet.</small>}</div></section>
    <section><h3><History size={16}/> Version history</h3><div className="aiw-list">{history.map((item)=><div className="aiw-row" key={item.version}><History/><div><b>Version {item.version}</b><small>{item.created_at?new Date(item.created_at).toLocaleString():""} · {item.edited_by?.actor_type==="ai_agent"?`AI · ${item.edited_by?.agent_name||item.edited_by?.actor_id}`:item.edited_by?.actor_name||item.edited_by?.actor_id||"Unknown editor"}</small></div></div>)}</div></section>
   </aside>}
  </div>
 </div>;
}
