import { useEffect,useMemo,useState } from "react";
import { Activity,AlertTriangle,Archive,BookOpen,Brain,CheckCircle2,Clock,FileText,RefreshCw,ShieldCheck,Sparkles,UserRoundCog,Users,Wifi,WifiOff,Wrench } from "lucide-react";
import { authStore,errorText } from "../../../web/api";

type Agent={agentId:string;name:string;avatar?:string|null;role:string;department?:string|null;description?:string|null;status:string;provider:string;model?:string|null;autonomyLevel:number;permissions:string[];allowedTools:string[]};
type Task={task_id:string;assigned_agent:string;instruction:string;priority:number;status:string;created_at:string;updated_at:string;due_time?:string|null};
type Approval={approval_id:string;agent_id:string;requested_action:string;reason?:string|null;risk_level:string;status:string;requested_at:string};
type DocumentRow={document_id:string;type:string;title:string;version:number;status:string;creator:any;ai_provenance:any;updated_at:string;rendered_pdf_ref?:string|null};
type Health={ok:boolean;provider:string;runtime?:{online?:boolean;state?:string;model?:string;modelInstalled?:boolean};queueLength?:number;failedTasks?:number;worker?:{activeWorkers?:number;averageExecutionDurationMs?:number|null;lastSuccessfulTask?:string|null};knowledge?:{vectorSearch?:boolean;fullTextSearch?:boolean}};

async function ai<T>(path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("Accept","application/json");if(init.body)headers.set("Content-Type","application/json");const token=authStore.getAccess();if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`/selfhost/ai${path}`,{...init,headers});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`AI request failed (${response.status})`);return payload as T;}
const section=()=>window.location.pathname.split("/").filter(Boolean).pop()||"employees";
const titleCase=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());
const autonomy=(level:number)=>level===1?"Adviser":level===2?"Assistant":"Autonomous";
const statusClass=(value:string)=>`aiw-pill aiw-${value.replaceAll("_","-")}`;
function AgentMark({agent}:{agent:Agent}){return <div className="aiw-mark"><span className="aiw-spark">✦</span><span><b>AI · {agent.name}</b><small>{agent.role}</small></span></div>}

export function AiWorkforceWorkspace(){
 const current=section();const[agents,setAgents]=useState<Agent[]>([]),[tasks,setTasks]=useState<Task[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[documents,setDocuments]=useState<DocumentRow[]>([]),[health,setHealth]=useState<Health|null>(null),[extras,setExtras]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const agentMap=useMemo(()=>new Map(agents.map((a)=>[a.agentId,a])),[agents]);
 async function load(){setBusy(true);setError("");try{const common=await ai<{items:Agent[]}>("/employees");setAgents(common.items||[]);const h=await ai<Health>("/health").catch(()=>null);setHealth(h);if(current==="tasks")setTasks((await ai<{items:Task[]}>("/tasks")).items||[]);else if(current==="approvals")setApprovals((await ai<{items:Approval[]}>("/approvals")).items||[]);else if(current==="documents")setDocuments((await ai<{items:DocumentRow[]}>("/documents")).items||[]);else if(["activity","audit"].includes(current))setExtras((await ai<{items:any[]}>(`/${current}`)).items||[]);else if(current==="knowledge")setExtras((await ai<{items:any[]}>("/knowledge/sources")).items||[]);else if(current==="settings")setExtras([await ai<any>("/settings")]);}catch(e){setError(errorText(e));}finally{setBusy(false)}}
 useEffect(()=>{void load()},[current]);
 async function decide(id:string,approve:boolean){setBusy(true);try{await ai(`/approvals/${id}/decision`,{method:"POST",body:JSON.stringify({approve,reason:approve?"Approved by human reviewer":"Rejected by human reviewer"})});await load();}catch(e){setError(errorText(e));setBusy(false)}}
 async function execute(id:string){setBusy(true);try{await ai(`/approvals/${id}/execute`,{method:"POST",body:"{}"});await load();}catch(e){setError(errorText(e));setBusy(false)}}
 return <div className="aiw-shell">
  <header className="aiw-hero"><div><p className="aiw-eyebrow"><Sparkles size={15}/> Ledgerly AI Workforce</p><h1>{titleCase(current)}</h1><p>Local, permissioned AI employees working through Ledgerly tools, approvals and durable audit.</p></div><div className="aiw-health">{health?.runtime?.online?<Wifi size={18}/>:<WifiOff size={18}/>}<div><b>{health?.runtime?.online?"AI runtime online":"AI runtime offline"}</b><small>{health?.provider||"—"} · {health?.runtime?.model||"No model selected"}</small></div></div></header>
  {error&&<div className="aiw-error"><AlertTriangle size={18}/>{error}</div>}
  <div className="aiw-toolbar"><div className="aiw-metrics"><span><Users size={16}/>{agents.length} employees</span><span><Clock size={16}/>{health?.queueLength??0} queued</span><span><Activity size={16}/>{health?.worker?.activeWorkers??0} active</span><span><ShieldCheck size={16}/>{health?.failedTasks??0} failed</span></div><button onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>{busy?"Refreshing…":"Refresh"}</button></div>
  {current==="employees"&&<Employees agents={agents} tasks={tasks}/>} 
  {current==="roles"&&<Roles agents={agents}/>} 
  {current==="tools"&&<Tools agents={agents}/>} 
  {current==="tasks"&&<Tasks rows={tasks} agentMap={agentMap}/>} 
  {current==="approvals"&&<Approvals rows={approvals} agentMap={agentMap} decide={decide} execute={execute}/>} 
  {current==="documents"&&<Documents rows={documents}/>} 
  {current==="knowledge"&&<SimpleCards rows={extras} kind="knowledge"/>}
  {current==="memory"&&<Memory agents={agents}/>} 
  {current==="activity"&&<Timeline rows={extras}/>} 
  {current==="audit"&&<Audit rows={extras}/>} 
  {current==="settings"&&<Settings health={health} settings={extras[0]}/>} 
 </div>
}

function Employees({agents}:{agents:Agent[]}){return <div className="aiw-grid">{agents.map((agent)=><article className="aiw-agent" key={agent.agentId}><div className="aiw-agent-top"><div className="aiw-avatar">{agent.avatar?<img src={agent.avatar}/>:agent.name.slice(0,1).toUpperCase()}</div><div className="aiw-agent-name"><AgentMark agent={agent}/><span>{agent.department||"General"}</span></div><span className={statusClass(agent.status)}>{agent.status}</span></div><p>{agent.description}</p><div className="aiw-agent-stats"><div><small>Autonomy</small><b>Level {agent.autonomyLevel} · {autonomy(agent.autonomyLevel)}</b></div><div><small>Model</small><b>{agent.model||"Server default"}</b></div><div><small>Allowed tools</small><b>{agent.allowedTools.length}</b></div><div><small>Permissions</small><b>{agent.permissions.length}</b></div></div></article>)}</div>}
function Roles({agents}:{agents:Agent[]}){return <div className="aiw-list">{agents.map(a=><div className="aiw-row" key={a.agentId}><UserRoundCog/><div><b>{a.role}</b><small>{a.department} · template/customizable employee</small></div><span>{autonomy(a.autonomyLevel)}</span></div>)}</div>}
function Tools({agents}:{agents:Agent[]}){const tools=[...new Set(agents.flatMap(a=>a.allowedTools))].sort();return <div className="aiw-grid aiw-tool-grid">{tools.map(tool=><div className="aiw-tool" key={tool}><Wrench size={18}/><b>{titleCase(tool)}</b><small>{agents.filter(a=>a.allowedTools.includes(tool)).map(a=>a.name).join(", ")||"No employee"}</small></div>)}</div>}
function Tasks({rows,agentMap}:{rows:Task[];agentMap:Map<string,Agent>}){return <div className="aiw-table-wrap"><table className="aiw-table"><thead><tr><th>Employee</th><th>Task</th><th>Status</th><th>Priority</th><th>Updated</th></tr></thead><tbody>{rows.map(r=><tr key={r.task_id}><td>{agentMap.get(r.assigned_agent)?<AgentMark agent={agentMap.get(r.assigned_agent)!}/>:r.assigned_agent}</td><td><b>{r.instruction}</b><small>{r.task_id}</small></td><td><span className={statusClass(r.status)}>{titleCase(r.status)}</span></td><td>{r.priority}</td><td>{new Date(r.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div>}
function Approvals({rows,agentMap,decide,execute}:{rows:Approval[];agentMap:Map<string,Agent>;decide:(id:string,a:boolean)=>void;execute:(id:string)=>void}){return <div className="aiw-list">{rows.map(r=><article className="aiw-approval" key={r.approval_id}><div>{agentMap.get(r.agent_id)&&<AgentMark agent={agentMap.get(r.agent_id)!}/>}<h3>{titleCase(r.requested_action)}</h3><p>{r.reason||"No reason supplied"}</p><div className="aiw-inline"><span className={statusClass(r.status)}>{r.status}</span><span className={statusClass(r.risk_level)}>{r.risk_level} risk</span></div></div><div className="aiw-actions">{r.status==="pending"&&<><button onClick={()=>decide(r.approval_id,true)}><CheckCircle2 size={15}/>Approve</button><button className="aiw-secondary" onClick={()=>decide(r.approval_id,false)}>Reject</button></>}{r.status==="approved"&&<button onClick={()=>execute(r.approval_id)}>Execute approved action</button>}</div></article>)}</div>}
function Documents({rows}:{rows:DocumentRow[]}){return <div className="aiw-grid">{rows.map(d=><article className="aiw-doc" key={d.document_id}><div className="aiw-doc-icon"><FileText/></div><div><div className="aiw-inline"><span className={statusClass(d.status)}>{titleCase(d.status)}</span><span>v{d.version}</span></div><h3>{d.title}</h3><small>{titleCase(d.type)} · updated {new Date(d.updated_at).toLocaleString()}</small>{d.ai_provenance?.document&&<p className="aiw-origin">✦ AI · {d.ai_provenance.document.agent_name}<br/><span>{d.ai_provenance.document.agent_role}</span></p>}{d.rendered_pdf_ref&&<span className="aiw-pdf"><Archive size={14}/> PDF rendered</span>}</div></article>)}</div>}
function SimpleCards({rows,kind}:{rows:any[];kind:string}){return <div className="aiw-grid">{rows.map((r,i)=><article className="aiw-doc" key={r.source_id||i}><div className="aiw-doc-icon"><BookOpen/></div><div><span className={statusClass(r.status||"active")}>{r.status||kind}</span><h3>{r.name||r.title||"Knowledge source"}</h3><small>{r.source_type||r.storage_ref||"Local source"}</small></div></article>)}</div>}
function Memory({agents}:{agents:Agent[]}){return <div className="aiw-empty"><Brain size={38}/><h3>Tenant-scoped employee memory</h3><p>Select an employee through its settings to inspect durable memory, expiry state and controls. Task context and organizational knowledge remain separate.</p><div className="aiw-inline">{agents.map(a=><span className="aiw-chip" key={a.agentId}>✦ {a.name}</span>)}</div></div>}
function Timeline({rows}:{rows:any[]}){return <div className="aiw-timeline">{rows.map((r,i)=><div className="aiw-event" key={r.activity_id||i}><span/><div><b>{r.summary||titleCase(r.activity_type||"activity")}</b><small>{r.agent_id||"System"} · {r.occurred_at?new Date(r.occurred_at).toLocaleString():""}</small></div></div>)}</div>}
function Audit({rows}:{rows:any[]}){return <div className="aiw-table-wrap"><table className="aiw-table"><thead><tr><th>Actor</th><th>Action</th><th>Entity</th><th>Reason</th><th>Time</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td>{r.actor_type==="ai_agent"?`✦ AI · ${r.agent_name||r.actor_id}`:r.actor_id}</td><td>{r.action}</td><td>{r.entity_type} {r.entity_id||""}</td><td>{r.reason||"—"}</td><td>{new Date(r.occurred_at).toLocaleString()}</td></tr>)}</tbody></table></div>}
function Settings({health,settings}:{health:Health|null;settings:any}){return <div className="aiw-settings"><section><h3>Runtime</h3><dl><dt>Provider</dt><dd>{settings?.provider?.id||health?.provider||"ollama"}</dd><dt>Endpoint</dt><dd>{settings?.provider?.endpoint||"Local"}</dd><dt>Model</dt><dd>{settings?.provider?.model||"Not selected"}</dd><dt>State</dt><dd>{health?.runtime?.state||"unknown"}</dd></dl></section><section><h3>Resource controls</h3><dl>{Object.entries(settings?.limits||{}).map(([k,v])=><span key={k}><dt>{titleCase(k)}</dt><dd>{String(v)}</dd></span>)}</dl></section><section><h3>Knowledge</h3><dl><dt>Local full-text</dt><dd>{health?.knowledge?.fullTextSearch?"Ready":"Unavailable"}</dd><dt>pgvector</dt><dd>{health?.knowledge?.vectorSearch?"Ready":"Fallback active"}</dd></dl></section></div>}
