import test from "node:test";
import assert from "node:assert/strict";
import { CommunicationsService } from "../src/communications/service.mjs";
import { CommunicationsWorker } from "../src/communications/worker.mjs";

function fake(){
  const deliveries=new Map(); const campaigns=new Map([["c1",{id:"c1",status:"draft"}]]); const recipients=new Map([["r1",{id:"r1",recipient_type:"contact",recipient_id:"p1",recipient_name:"Ada",phone:"+256700000001",email:"a@example.com"}]]); const prefs=new Map(); const jobs=[]; const audits=[]; const sent=[];
  const repo={
    getCampaign:async(o,id)=>campaigns.get(id)||null,listDueCampaignIds:async()=>[],setCampaignState:async(o,id,status)=>{const c=campaigns.get(id);if(!c)return null;c.status=status;return c;},
    listSendableDeliveryIds:async(o,c,{afterId=null,limit=100})=>[...deliveries.values()].filter(d=>d.campaign_id===c&&["queued","failed"].includes(d.status)&&!d.provider_message_id&&(!afterId||d.id>afterId)).sort((a,b)=>a.id.localeCompare(b.id)).slice(0,limit).map(d=>d.id),
    claimDelivery:async(o,id)=>{const d=deliveries.get(id);const c=d&&campaigns.get(d.campaign_id);if(!d||!["queued","failed"].includes(d.status)||d.provider_message_id||!["queued","sending"].includes(c.status))return null;d.status="sending";d.attempts=(d.attempts||0)+1;return {...d};},
    getDeliveryState:async(o,id)=>deliveries.get(id)||null,getPreference:async(o,t,id)=>prefs.get(`${t}:${id}`)||null,getRecipient:async(o,id)=>recipients.get(id)||null,
    markDeliverySent:async(o,id,x)=>{const d=deliveries.get(id);d.status="sent";d.provider=x.provider;d.provider_message_id=x.providerMessageId;return d;},markDeliveryFailed:async(o,id,x)=>{const d=deliveries.get(id);d.status="failed";d.last_error=x.error;return d;},cancelDelivery:async(o,id,reason)=>{const d=deliveries.get(id);d.status="cancelled";d.last_error=reason;return d;},refreshCampaignProgress:async()=>({}),
  };
  const queue={enqueue:async j=>{jobs.push(j);return {queued:true}},take:async()=>null,ack:async()=>true,retry:async()=>({retried:true})}; const notifications={send:async n=>{sent.push(n);return {provider:"egosms",providerMessageId:"provider-1"}}}; const audit={write:async e=>{audits.push(e);return e;}};
  return {deliveries,campaigns,prefs,jobs,audits,sent,repo,queue,notifications,audit};
}
function service(x,extra={}){return new CommunicationsService({repository:x.repo,queue:x.queue,notifications:x.notifications,audit:x.audit,...extra});}
function delivery(id="d1"){return {id,organization_id:"o1",campaign_id:"c1",recipient_snapshot_id:"r1",channel:"sms",recipient_phone:"+256700000001",provider:"egosms",rendered_subject:"Hi",rendered_message:"Hello",template_variables_json:"{}",status:"queued",attempts:0};}

test("campaign batching is durable and idempotency-keyed",async()=>{const x=fake();for(let i=1;i<=205;i++)x.deliveries.set(`d${String(i).padStart(3,"0")}`,delivery(`d${String(i).padStart(3,"0")}`));const r=await service(x,{batchSize:100}).queueCampaign({organizationId:"o1",campaignId:"c1",actor:{actorType:"human",actorId:"u1"}});assert.equal(r.queued,205);assert.equal(x.jobs.length,3);assert.ok(x.jobs.every(j=>j.kind==="communications.delivery-batch"&&j.idempotencyKey.startsWith("communications:c1:")));});
test("confirmed deliveries are never sent twice",async()=>{const x=fake();const d=delivery();d.status="sent";d.provider_message_id="already";x.deliveries.set("d1",d);x.campaigns.get("c1").status="sending";const r=await service(x).processDelivery({organizationId:"o1",deliveryId:"d1"});assert.equal(r.reason,"already_final");assert.equal(x.sent.length,0);});
test("opt-out cancels delivery before provider call",async()=>{const x=fake();x.deliveries.set("d1",delivery());x.campaigns.get("c1").status="sending";x.prefs.set("contact:p1",{do_not_contact:true,sms_enabled:true});const r=await service(x).processDelivery({organizationId:"o1",deliveryId:"d1"});assert.equal(r.reason,"recipient_opt_out");assert.equal(x.deliveries.get("d1").status,"cancelled");assert.equal(x.sent.length,0);});
test("provider ID is persisted and audited",async()=>{const x=fake();x.deliveries.set("d1",delivery());x.campaigns.get("c1").status="sending";const r=await service(x).processDelivery({organizationId:"o1",deliveryId:"d1",actor:{actorType:"ai_agent",actorId:"agent-1"}});assert.equal(r.providerMessageId,"provider-1");assert.equal(x.deliveries.get("d1").provider_message_id,"provider-1");assert.equal(x.audits.at(-1).actorType,"ai_agent");});
test("failed provider call records failure and remains retryable",async()=>{const x=fake();x.deliveries.set("d1",delivery());x.campaigns.get("c1").status="sending";x.notifications.send=async()=>{throw new Error("provider down")};await assert.rejects(()=>service(x).processDelivery({organizationId:"o1",deliveryId:"d1"}),/provider down/);assert.equal(x.deliveries.get("d1").status,"failed");assert.match(x.deliveries.get("d1").last_error,/provider down/);});
test("worker retries failed batch without ack",async()=>{const calls=[];let acked=false;let retried=false;const queue={take:async()=>({job:{jobId:"j1",kind:"communications.delivery-batch",organizationId:"o1",payload:{deliveryIds:["d1"]}},receipt:"r"}),ack:async()=>{acked=true},retry:async()=>{retried=true}};const service={processDelivery:async()=>{calls.push("d1");throw new Error("boom")}};const r=await new CommunicationsWorker({queue,service}).runOnce();assert.equal(r.retried,true);assert.equal(retried,true);assert.equal(acked,false);assert.deepEqual(calls,["d1"]);});
