import test from 'node:test';import assert from 'node:assert/strict';import {CommunicationsService} from '../src/communications/service.mjs';import {CommunicationsWorker} from '../src/communications/worker.mjs';
function fake(){const deliveries=new Map(),campaigns=new Map([['c1',{id:'c1',organization_id:'o1',status:'draft'}]]),recipients=new Map([['r1',{id:'r1',organization_id:'o1',recipient_type:'contact',recipient_id:'p1',recipient_name:'Ada',phone:'+2567'}]]),prefs=new Map(),jobs=[],audits=[],sent=[];const repo={getCampaign:async(o,id)=>{const c=campaigns.get(id);return c?.organization_id===o?c:null},listDueCampaignIds:async(o)=>[...campaigns.values()].filter(c=>c.organization_id===o&&c.status==='scheduled').map(c=>c.id),setCampaignState:async(o,id,s)=>{const c=campaigns.get(id);if(!c||c.organization_id!==o)return null;c.status=s;return c},listSendableDeliveryIds:async(o,c,{afterId=null,limit=100})=>[...deliveries.values()].filter(d=>d.organization_id===o&&d.campaign_id===c&&['queued','failed'].includes(d.status)&&!d.provider_message_id&&(!afterId||d.id>afterId)).sort((a,b)=>a.id.localeCompare(b.id)).slice(0,limit).map(d=>d.id),getDeliveryState:async(o,id)=>{const d=deliveries.get(id);return d?.organization_id===o?d:null},claimDelivery:async(o,id)=>{const d=deliveries.get(id),c=d&&campaigns.get(d.campaign_id);if(!d||d.organization_id!==o||!['queued','failed'].includes(d.status)||d.provider_message_id||!['queued','sending'].includes(c.status))return null;d.status='sending';d.attempts=(d.attempts||0)+1;return {...d}},getRecipient:async(o,id)=>{const r=recipients.get(id);return r?.organization_id===o?r:null},getPreference:async(o,t,id)=>prefs.get(`${o}:${t}:${id}`)||null,markDeliverySent:async(o,id,x)=>{const d=deliveries.get(id);d.status='sent';d.provider_message_id=x.providerMessageId;return d},markDeliveryFailed:async(o,id,x)=>{const d=deliveries.get(id);d.status='failed';d.last_error=x.error;d.next_attempt_at=x.nextAttemptAt;return d},markDeliveryDeadLetter:async(o,id,x)=>{const d=deliveries.get(id);d.status='failed';d.last_error=x.reason;d.next_attempt_at=null;return d},cancelDelivery:async(o,id,r)=>{const d=deliveries.get(id);d.status='cancelled';d.last_error=r;return d},refreshCampaignProgress:async()=>({})};const queue={enqueue:async j=>{if(jobs.some(x=>x.idempotencyKey===j.idempotencyKey))return{queued:false,duplicate:true};jobs.push(j);return{queued:true}},take:async()=>null,ack:async()=>true,retry:async()=>({retried:true})};const notifications={send:async n=>{sent.push(n);return{provider:'egosms',providerMessageId:'p-1'}}},audit={write:async e=>{audits.push(e)}};return{deliveries,campaigns,recipients,prefs,jobs,audits,sent,repo,queue,notifications,audit}}
const mk=(id='d1',o='o1')=>({id,organization_id:o,campaign_id:'c1',recipient_snapshot_id:'r1',channel:'sms',recipient_phone:'+2567',provider:'egosms',rendered_subject:'',rendered_message:'Hi',template_variables_json:'{}',status:'queued',attempts:0});const svc=x=>new CommunicationsService({repository:x.repo,queue:x.queue,notifications:x.notifications,audit:x.audit,batchSize:100});
test('batching and enqueue idempotency',async()=>{const x=fake();for(let i=0;i<205;i++){const id=`d${String(i).padStart(3,'0')}`;x.deliveries.set(id,mk(id))}let r=await svc(x).queueCampaign({organizationId:'o1',campaignId:'c1'});assert.equal(r.queued,205);assert.equal(x.jobs.length,3);r=await svc(x).queueCampaign({organizationId:'o1',campaignId:'c1'});assert.equal(r.queued,0);assert.equal(x.jobs.length,3)});
test('confirmed delivery is not resent',async()=>{const x=fake(),d=mk();d.status='sent';d.provider_message_id='done';x.deliveries.set(d.id,d);x.campaigns.get('c1').status='sending';const r=await svc(x).processDelivery({organizationId:'o1',deliveryId:'d1'});assert.equal(r.reason,'already_final');assert.equal(x.sent.length,0)});
test('opt out is enforced',async()=>{const x=fake();x.deliveries.set('d1',mk());x.campaigns.get('c1').status='sending';x.prefs.set('o1:contact:p1',{do_not_contact:true});const r=await svc(x).processDelivery({organizationId:'o1',deliveryId:'d1'});assert.equal(r.reason,'recipient_opt_out');assert.equal(x.sent.length,0)});
test('provider id persists and audit records actor',async()=>{const x=fake();x.deliveries.set('d1',mk());x.campaigns.get('c1').status='sending';await svc(x).processDelivery({organizationId:'o1',deliveryId:'d1',actor:{actorType:'ai_agent',actorId:'a1'}});assert.equal(x.deliveries.get('d1').provider_message_id,'p-1');assert.equal(x.audits.at(-1).actorType,'ai_agent')});
test('provider failure stays retryable',async()=>{const x=fake();x.deliveries.set('d1',mk());x.campaigns.get('c1').status='sending';x.notifications.send=async()=>{throw new Error('down')};await assert.rejects(()=>svc(x).processDelivery({organizationId:'o1',deliveryId:'d1'}),/down/);assert.equal(x.deliveries.get('d1').status,'failed');assert.ok(x.deliveries.get('d1').next_attempt_at)});
test('worker dead letters delivery when queue exhausts retries',async()=>{let dead=false;const queue={take:async()=>({job:{kind:'communications.delivery-batch',organizationId:'o1',payload:{deliveryIds:['d1']}},receipt:'r'}),retry:async()=>({deadLettered:true}),ack:async()=>assert.fail('should not ack')};const service={processDelivery:async()=>{throw new Error('down')},deadLetterDelivery:async()=>{dead=true}};const r=await new CommunicationsWorker({queue,service}).runOnce();assert.equal(r.deadLettered,true);assert.equal(dead,true)});
test('scheduled dispatch is idempotent',async()=>{const x=fake();x.campaigns.get('c1').status='scheduled';x.deliveries.set('d1',mk());await svc(x).queueDueCampaigns({organizationId:'o1'});await svc(x).queueDueCampaigns({organizationId:'o1'});assert.equal(x.jobs.length,1)});
test('cross tenant delivery is rejected before send',async()=>{const x=fake();x.deliveries.set('d1',mk('d1','o2'));const r=await svc(x).processDelivery({organizationId:'o1',deliveryId:'d1'});assert.equal(r.reason,'not_found');assert.equal(x.sent.length,0)});
test('missing address cancels safely',async()=>{const x=fake();const d=mk();d.recipient_phone=null;x.deliveries.set('d1',d);x.recipients.get('r1').phone=null;x.campaigns.get('c1').status='sending';const r=await svc(x).processDelivery({organizationId:'o1',deliveryId:'d1'});assert.equal(r.reason,'recipient_address_missing');assert.equal(x.sent.length,0)});
