import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import financeExtension from '../src/extensions/finance-api.extension.mjs';
import {TenantCache,createPostCommitInvalidator} from '../src/cache/tenant-cache.mjs';

test('all finance cutovers remain Cloudflare-default and validate modes',()=>{const c=financeExtension.configure({});for(const k of ['referenceCutover','journalsCutover','documentsCutover','paymentsCutover','feesCutover','payrollCutover'])assert.equal(c[k],'cloudflare');assert.equal(financeExtension.configure({LEDGERLY_SCHOOL_FEES_CUTOVER:'node'}).feesCutover,'node');assert.throws(()=>financeExtension.configure({LEDGERLY_PAYROLL_CUTOVER:'yes'}),/cloudflare, shadow, or node/);});
test('tenant cache keys isolate organizations and rollback never invalidates',async()=>{const invalidated=[],cache={get(){},remember(_k,p){return p()},invalidateTag:async t=>invalidated.push(t)};assert.notEqual(new TenantCache({cache,organizationId:'a'}).key('accounts'),new TenantCache({cache,organizationId:'b'}).key('accounts'));const i=createPostCommitInvalidator({cache,organizationId:'a'});i.mark('accounts');i.rollback();assert.deepEqual(invalidated,[]);i.mark('accounts');await i.committed();assert.deepEqual(invalidated,['org:a:accounts']);});
test('new finance routes are granular and only enable in node mode',async()=>{const files=['finance-contacts','finance-products','finance-budgets','finance-documents','school-fees','payroll'];for(const f of files){const r=(await import(`../src/http/routes/${f}.route.mjs`)).default;assert.equal(r.business,true);assert.equal(r.enabled({extensions:{'finance-api':{}}}),false);}assert.equal((await import('../src/http/routes/school-fees.route.mjs')).default.prefix,'/api/v1/school-fees');assert.equal((await import('../src/http/routes/payroll.route.mjs')).default.prefix,'/api/v1/payroll');});
test('high-risk services retain locking, idempotency, source reversal and post-commit invalidation',async()=>{const source=(await Promise.all(['core-api-service.mjs','school-fees-api-service.mjs','payroll-cutover-service.mjs','reversal-service.mjs'].map(f=>readFile(new URL(`../src/finance/${f}`,import.meta.url),'utf8')))).join('\n');for(const p of [/FOR UPDATE/,/idempotency_key/,/school_fee_receipt/,/PAYMENT_OVERALLOCATED/,/PAYROLL_HAS_SALARY_PAYMENTS/,/createPostCommitInvalidator/])assert.match(source,p);});
