import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import financeExtension from '../src/extensions/finance-api.extension.mjs';
import {TenantCache,createPostCommitInvalidator} from '../src/cache/tenant-cache.mjs';

test('all finance cutovers remain Cloudflare-default and validate modes',()=>{const c=financeExtension.configure({});for(const k of ['referenceCutover','journalsCutover','documentsCutover','paymentsCutover','bankingCutover','taxCutover','approvalsCutover','reportsCutover','dashboardCutover','feesCutover','payrollCutover'])assert.equal(c[k],'cloudflare');assert.equal(financeExtension.configure({LEDGERLY_SCHOOL_FEES_CUTOVER:'node'}).feesCutover,'node');assert.throws(()=>financeExtension.configure({LEDGERLY_PAYROLL_CUTOVER:'yes'}),/cloudflare, shadow, or node/);});
test('tenant cache keys isolate organizations and rollback never invalidates',async()=>{const invalidated=[],cache={get(){},remember(_k,p){return p()},invalidateTag:async t=>invalidated.push(t)};assert.notEqual(new TenantCache({cache,organizationId:'a'}).key('accounts'),new TenantCache({cache,organizationId:'b'}).key('accounts'));assert.notEqual(new TenantCache({cache,organizationId:'a'}).key('dashboard-summary','user-u1'),new TenantCache({cache,organizationId:'b'}).key('dashboard-summary','user-u1'));const i=createPostCommitInvalidator({cache,organizationId:'a'});i.mark('accounts');i.rollback();assert.deepEqual(invalidated,[]);i.mark('accounts');await i.committed();assert.deepEqual(invalidated,['org:a:accounts']);});
test('new finance routes are granular and only enable in node mode',async()=>{const files=['finance-contacts','finance-products','finance-budgets','finance-documents','school-fees','payroll','finance-approval-policies','finance-document-approval','finance-approvals','finance-reports','finance-dashboard-summary'];for(const f of files){const r=(await import(`../src/http/routes/${f}.route.mjs`)).default;assert.equal(r.business,true);assert.equal(r.enabled({extensions:{'finance-api':{}}}),false);}assert.equal((await import('../src/http/routes/school-fees.route.mjs')).default.prefix,'/api/v1/school-fees');assert.equal((await import('../src/http/routes/payroll.route.mjs')).default.prefix,'/api/v1/payroll');assert.equal((await import('../src/http/routes/finance-dashboard-summary.route.mjs')).default.prefix,'/api/v1/dashboards/summary');});
test('high-risk services retain locking, idempotency, source reversal and post-commit invalidation',async()=>{const source=(await Promise.all(['core-api-service.mjs','school-fees-api-service.mjs','payroll-cutover-service.mjs','reversal-service.mjs','approval-service.mjs'].map(f=>readFile(new URL(`../src/finance/${f}`,import.meta.url),'utf8')))).join('\n');for(const p of [/FOR UPDATE/,/idempotency_key/,/school_fee_receipt/,/PAYMENT_OVERALLOCATED/,/PAYROLL_HAS_SALARY_PAYMENTS/,/createPostCommitInvalidator/])assert.match(source,p);});
test('keyed payment allocation retries are serialized and short-circuit existing deterministic allocations',async()=>{const source=await readFile(new URL('../src/http/routes/finance-payments.route.mjs',import.meta.url),'utf8');assert.match(source,/namespace:'payment-allocate'/);assert.match(source,/existingAllocationRetry/);assert.match(source,/alreadyApplied:true/);assert.match(source,/pal_/);assert.match(source,/IDEMPOTENCY_CONFLICT/);});
test('dashboard summary reads use tenant-scoped Redis cache and PostgreSQL',async()=>{const source=await readFile(new URL('../src/finance/dashboard-service.mjs',import.meta.url),'utf8');assert.match(source,/TenantCache/);assert.match(source,/remember\('dashboard-summary'/);assert.match(source,/organization_id=\$1/);assert.match(source,/ttlMs:30000/);});
