import test from "node:test";
import assert from "node:assert/strict";
import { D1HttpSource } from "../src/migration/d1-source.mjs";
import { D1MigrationRunner } from "../src/migration/runner.mjs";

test("D1 source snapshot fingerprints row identity and updated-at watermark",async()=>{let body;const source=new D1HttpSource({accountId:"a",databaseId:"d",apiToken:"t",fetchImpl:async(_url,init)=>{body=JSON.parse(init.body);return{ok:true,async json(){return{success:true,result:[{success:true,results:[{count:3,max_rowid:8,rowid_sum:15,max_updated_at:"2026-09-11 08:00:00"}]}]};}};}});const snapshot=await source.snapshot("school_students",{columns:["id","updated_at"]});assert.deepEqual(snapshot,{count:3,maxRowid:8,rowidSum:15,maxUpdatedAt:"2026-09-11 08:00:00"});assert.match(body.sql,/MAX\(rowid\)/);assert.match(body.sql,/MAX\("updated_at"\)/);});

test("migration runner fails closed when prerequisite phase is incomplete",async()=>{const phase={name:"school-people",prerequisites:["school-reference"],tables:[],ensureSchema:async()=>{},relationshipChecks:[]};const database={async query(sql){if(sql.includes("CREATE TABLE")||sql.includes("CREATE INDEX"))return{rows:[]};if(sql.includes("FROM ledgerly_meta.migration_runs")&&sql.includes("status='completed'"))return{rows:[]};throw new Error(`Unexpected SQL ${sql}`);}};const runner=new D1MigrationRunner({database,source:{},sourceIdentity:"db",phase});await runner.prepare();await assert.rejects(()=>runner.assertPrerequisites(),/school-reference/);});

test("copy records a source mutation warning when snapshot changes",async()=>{const validations=[];let snap=0;const source={async tableExists(){return true;},async snapshot(){snap++;return snap===1?{count:1,maxRowid:1,rowidSum:1,maxUpdatedAt:"a"}:{count:1,maxRowid:1,rowidSum:1,maxUpdatedAt:"b"};},async batch(_t,{afterRowid}){return afterRowid?[]:[{__ledgerly_rowid:1,id:"x"}];}};const database={state:{status:"pending",last_rowid:0,copied_rows:0},async query(sql,values=[]){if(sql.includes("INSERT INTO ledgerly_meta.migration_table_state"))return{rows:[]};if(sql.includes("SELECT run_id,table_name,status,last_rowid"))return{rows:[this.state]};if(sql.includes("SET status='copying'"))return{rows:[]};if(sql.includes("SET last_rowid=$3")){this.state.last_rowid=values[2];this.state.copied_rows=values[3];return{rows:[]};}if(sql.startsWith('INSERT INTO "demo"'))return{rows:[]};if(sql.includes('SELECT count(*)::bigint AS count FROM "demo"'))return{rows:[{count:1}]};if(sql.includes("SET status='copied'"))return{rows:[]};if(sql.includes("migration_validations")){validations.push(values);return{rows:[]};}if(sql.includes("SET status='failed'"))return{rows:[]};throw new Error(sql);},async transaction(work){return work({query:this.query.bind(this)});}};const runner=new D1MigrationRunner({database,source,sourceIdentity:"db",phase:{name:"p",prerequisites:[],tables:[],ensureSchema:async()=>{}},logger:{info(){}}});await runner.copyTable("00000000-0000-0000-0000-000000000001",{name:"demo",columns:["id"],conflict:["id"],transform:r=>({id:r.id})});const sourceValidation=validations.find(v=>v[2]==="source_stability");assert.ok(sourceValidation);assert.equal(sourceValidation[3],"warning");});

test("cutover validation fails if source fingerprint moved since copy",async()=>{const validations=[];const source={async snapshot(){return{count:1,maxRowid:1,rowidSum:1,maxUpdatedAt:"new"};},async count(){return 1;}};const database={async query(sql,values=[]){if(sql.includes("CREATE TABLE")||sql.includes("CREATE INDEX"))return{rows:[]};if(sql.includes("FROM ledgerly_meta.migration_runs")&&sql.includes("status='completed'"))return{rows:[{id:"p"}]};if(sql.includes("SELECT actual FROM ledgerly_meta.migration_validations"))return{rows:[{actual:{snapshotEnd:{count:1,maxRowid:1,rowidSum:1,maxUpdatedAt:"old"}}}]};if(sql.startsWith('SELECT count(*)::bigint AS count FROM "demo"'))return{rows:[{count:1}]};if(sql.includes("INSERT INTO ledgerly_meta.migration_validations")){validations.push(values);return{rows:[]};throw new Error(sql);}}};const phase={name:"p",prerequisites:[],tables:[{name:"demo",columns:["id","updated_at"],conflict:["id"],transform:r=>r}],ensureSchema:async()=>{},relationshipChecks:[]};const runner=new D1MigrationRunner({database,source,sourceIdentity:"db",phase});const result=await runner.validateCutover({runId:"00000000-0000-0000-0000-000000000001"});assert.equal(result.ok,false);assert.equal(result.sourceStability[0].ok,false);});
