import test from 'node:test';import assert from 'node:assert/strict';import {MobileSyncService} from '../src/mobile-sync/service.mjs';import {projectMobilePayload} from '../src/mobile-sync/privacy.mjs';
class MemRepo{constructor(){this.devices=new Map([['d1',{id:'d1',organization_id:'o1',user_id:'u1',status:'active',last_push_sequence:0}]]);this.batches=new Map();this.ops=new Map();this.versions=new Map();this.changes=[];this.pulls=new Map();this.acked=new Map();}
 async getDevice({organizationId,userId,deviceId}){const d=this.devices.get(deviceId);return d&&d.organization_id===organizationId&&d.user_id===userId&&d.status==='active'?d:null}async getBatch({organizationId,deviceId,batchUuid}){return this.batches.get(`${deviceId}:${batchUuid}`)||null}async beginBatch(x){const k=`${x.deviceId}:${x.batchUuid}`;const b={id:`b${this.batches.size+1}`,request_hash:x.requestHash,result:null};this.batches.set(k,b);return b}async rejectOperation({operation,code,message}){return{operationUuid:operation.operationUuid,status:'rejected',errorCode:code,errorMessage:message}}
 async applyOperation({organizationId,deviceId,operation,requestHash,apply}){const d=this.devices.get(deviceId);const opKey=`${deviceId}:${operation.operationUuid}`;if(this.ops.has(opKey)){const p=this.ops.get(opKey);if(p.hash!==requestHash)throw Object.assign(new Error('operation idempotency mismatch'),{code:'SYNC_IDEMPOTENCY_MISMATCH'});return{...p.result,status:'duplicate'}}const expected=d.last_push_sequence+1;if(operation.sequenceNumber!==expected)return{operationUuid:operation.operationUuid,status:'rejected',errorCode:'SYNC_SEQUENCE_MISMATCH'};const vk=`${organizationId}:${operation.moduleKey}:${operation.collectionKey}:${operation.recordId}`,current=this.versions.get(vk)?.version||0;if((operation.baseVersion||0)!==current){d.last_push_sequence=operation.sequenceNumber;const result={operationUuid:operation.operationUuid,status:'conflict',serverVersion:current};this.ops.set(opKey,{hash:requestHash,result});return result}const next=current+1;const br=await apply({transaction:{},currentVersion:current,nextVersion:next});this.versions.set(vk,{version:next,deleted:operation.kind==='delete'});const change={change_id:this.changes.length+1,organization_id:organizationId,module_key:operation.moduleKey,collection_key:operation.collectionKey,record_id:operation.recordId,version:next,operation:operation.kind==='delete'?'delete':'upsert',payload_json:operation.kind==='delete'?null:JSON.stringify(br?.payload??operation.payload),changed_at:new Date().toISOString()};this.changes.push(change);d.last_push_sequence=operation.sequenceNumber;const result={operationUuid:operation.operationUuid,status:'applied',serverVersion:next,changeId:change.change_id,result:br?.result??null};this.ops.set(opKey,{hash:requestHash,result});return result}
 async completeBatch({deviceId,batchId,result}){for(const [k,b] of this.batches)if(b.id===batchId){b.result=result;break}}async listChanges({organizationId,moduleKey,collectionKey,afterChangeId,limit}){return this.changes.filter(c=>c.organization_id===organizationId&&c.module_key===moduleKey&&c.collection_key===collectionKey&&c.change_id>afterChangeId).slice(0,limit)}async recordPullDelivery(x){const d={id:`p${this.pulls.size+1}`,...x};this.pulls.set(d.id,d);return d}async acknowledgePull({organizationId,deviceId,deliveryId}){const d=this.pulls.get(deliveryId);if(!d||d.organizationId!==organizationId||d.deviceId!==deviceId)throw new Error('pull delivery not found');const k=`${deviceId}:${d.moduleKey}:${d.collectionKey}`,v=Math.max(this.acked.get(k)||0,d.toChangeId);this.acked.set(k,v);return{deliveryId,lastAckedChangeId:v}}}
function fixture(){const repo=new MemRepo(),rows=new Map();const service=new MobileSyncService({repository:repo,collections:[{moduleKey:'contacts',collectionKey:'contacts',canRead:async()=>true,apply:async({operation,nextVersion})=>{if(operation.kind==='delete')rows.delete(operation.recordId);else rows.set(operation.recordId,{...operation.payload,id:operation.recordId,secret:'hide'});return{payload:rows.get(operation.recordId),result:{version:nextVersion}}}}]});return{repo,rows,service}}
const op=(over={})=>({operationUuid:'op1',sequenceNumber:1,moduleKey:'contacts',collectionKey:'contacts',recordId:'client-id-1',kind:'upsert',schemaVersion:1,baseVersion:0,clientTimestamp:new Date().toISOString(),payload:{name:'Ada',email:'a@x',custom_fields:'secret'},...over});
test('stable client id is authoritative record id',async()=>{const f=fixture();const r=await f.service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[op()]});assert.equal(r.results[0].status,'applied');assert.ok(f.rows.has('client-id-1'))});
test('duplicate mutation replay is idempotent',async()=>{const f=fixture();const req={organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[op()]};const a=await f.service.push(req),b=await f.service.push(req);assert.equal(a.results[0].status,'applied');assert.equal(b.duplicate,true);assert.equal(f.repo.changes.length,1)});
test('conflict is deterministic server-version response',async()=>{const f=fixture();await f.service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[op()]});const r=await f.service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b2',operations:[op({operationUuid:'op2',sequenceNumber:2,baseVersion:0})]});assert.equal(r.results[0].status,'conflict');assert.equal(r.results[0].serverVersion,1)});
test('failed handler can be retried without consuming sequence',async()=>{const repo=new MemRepo();let fail=true;const service=new MobileSyncService({repository:repo,collections:[{moduleKey:'x',collectionKey:'y',canRead:async()=>true,apply:async()=>{if(fail)throw new Error('temporary');return{payload:{ok:true}}}}]});const operation={...op(),moduleKey:'x',collectionKey:'y'};await assert.rejects(()=>service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[operation]}),/temporary/);fail=false;repo.batches.clear();const r=await service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[operation]});assert.equal(r.results[0].status,'applied')});
test('delete propagates as tombstone change',async()=>{const f=fixture();await f.service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[op()]});await f.service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b2',operations:[op({operationUuid:'op2',sequenceNumber:2,kind:'delete',baseVersion:1,payload:null})]});const p=await f.service.pull({organizationId:'o1',userId:'u1',deviceId:'d1',moduleKey:'contacts',collectionKey:'contacts',cursor:1,requestId:'r1'});assert.equal(p.items[0].operation,'delete');assert.equal(p.items[0].payload,null)});
test('privacy projection strips non-mobile contact fields',()=>{const p=projectMobilePayload('contacts','contacts',{id:'1',name:'A',email:'x',active:true,custom_fields:'secret',credit_limit_minor:100});assert.deepEqual(p,{id:'1',name:'A',email:'x',active:true})});
test('pull cursor advances only when acknowledged',async()=>{const f=fixture();await f.service.push({organizationId:'o1',userId:'u1',deviceId:'d1',batchUuid:'b1',operations:[op()]});const p=await f.service.pull({organizationId:'o1',userId:'u1',deviceId:'d1',moduleKey:'contacts',collectionKey:'contacts',cursor:0,requestId:'r1'});assert.equal(f.repo.acked.size,0);const a=await f.service.acknowledgePull({organizationId:'o1',userId:'u1',deviceId:'d1',deliveryId:p.deliveryId});assert.equal(a.lastAckedChangeId,1)});
test('cross tenant device is rejected',async()=>{const f=fixture();await assert.rejects(()=>f.service.pull({organizationId:'o2',userId:'u1',deviceId:'d1',moduleKey:'contacts',collectionKey:'contacts',cursor:0}),e=>e.code==='SYNC_DEVICE_UNAUTHORIZED')});
test('collection visibility filters private records',async()=>{const repo=new MemRepo();repo.changes.push({change_id:1,organization_id:'o1',module_key:'private',collection_key:'notes',record_id:'n1',version:1,operation:'upsert',payload_json:'{"secret":"x"}',changed_at:new Date().toISOString()});const service=new MobileSyncService({repository:repo,collections:[{moduleKey:'private',collectionKey:'notes',canRead:async()=>false}]});const p=await service.pull({organizationId:'o1',userId:'u1',deviceId:'d1',moduleKey:'private',collectionKey:'notes',cursor:0});assert.equal(p.items.length,0);assert.equal(p.cursor,1)});
