import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {PrinterlyProcurementReceiptService} from '../src/printerly/procurement-receipt-service.mjs';

function database({requested=10,received=4,onHand=7}={}){const calls=[];return{calls,transaction:async fn=>fn({query:async(sql,args=[])=>{calls.push([sql,args]);if(sql.includes('FROM prn_purchase_requests')&&sql.includes('FOR UPDATE'))return{rows:[{id:'r1',status:'ordered',currency:'UGX'}]};if(sql.includes('FROM prn_purchase_request_lines')&&sql.includes('FOR UPDATE'))return{rows:[{id:'l1',consumable_id:'c1',description:'Toner',quantity_requested:requested,quantity_received:received,unit_cost_minor:1000}]};if(sql.includes('FROM prn_consumables')&&sql.includes('FOR UPDATE'))return{rows:[{id:'c1',on_hand:onHand,unit_cost_minor:900,active:true}]};if(sql.includes('UPDATE prn_purchase_request_lines'))return{rows:[],rowCount:1};if(sql.includes('SUM(quantity_requested-quantity_received)'))return{rows:[{remaining:0}]};return{rows:[],rowCount:1};}})};}

test('procurement receipt locks request, lines and stock before mutation',async()=>{const source=await readFile(new URL('../src/printerly/procurement-receipt-service.mjs',import.meta.url),'utf8');assert.match(source,/prn_purchase_requests[\s\S]*FOR UPDATE/);assert.match(source,/prn_purchase_request_lines[\s\S]*FOR UPDATE/);assert.match(source,/prn_consumables[\s\S]*FOR UPDATE/);assert.match(source,/quantity_received\+\$1<=quantity_requested/);});

test('procurement receipt rejects over-receipt before creating stock movements',async()=>{const db=database();const service=new PrinterlyProcurementReceiptService({database:db});await assert.rejects(()=>service.receive({organizationId:'o1',userId:'u1',requestId:'r1',data:{lines:[{lineId:'l1',quantity:7}]}}),error=>error.code==='INVALID_RECEIPT_QUANTITY');assert.equal(db.calls.some(([sql])=>sql.includes('INSERT INTO prn_purchase_receipts')),false);assert.equal(db.calls.some(([sql])=>sql.includes('prn_consumable_movements')),false);});

test('procurement receipt updates receipt, line, stock, movement and final request status atomically',async()=>{const db=database(),service=new PrinterlyProcurementReceiptService({database:db});const result=await service.receive({organizationId:'o1',userId:'u1',requestId:'r1',data:{lines:[{lineId:'l1',quantity:6,unitCostMinor:1100}]}});assert.equal(result.status,'received');for(const fragment of ['INSERT INTO prn_purchase_receipts','INSERT INTO prn_purchase_receipt_lines','UPDATE prn_purchase_request_lines','INSERT INTO prn_consumable_movements','UPDATE prn_consumables','UPDATE prn_purchase_requests','DELETE FROM prn_replenishment_claims'])assert.ok(db.calls.some(([sql])=>sql.includes(fragment)),fragment);});

test('tenant isolation is present on every procurement receipt lookup and mutation',async()=>{const source=await readFile(new URL('../src/printerly/procurement-receipt-service.mjs',import.meta.url),'utf8');for(const table of ['prn_purchase_requests','prn_purchase_request_lines','prn_consumables','prn_purchase_receipts','prn_purchase_receipt_lines','prn_consumable_movements'])assert.match(source,new RegExp(`${table}[\\s\\S]{0,700}organization_id`));});
