import { createId } from "../auth/crypto.mjs";
import { emitMobileChange, taskSyncRecord } from "./mobile-sync.mjs";
import { assignTask, postChatMessage } from "./services.mjs";

const TASK_STATUSES = new Set(["backlog","todo","in_progress","blocked","in_review","completed","cancelled"]);
const PROJECT_STATUSES = new Set(["planning","active","on_hold","completed","cancelled"]);
const PRIORITIES = new Set(["low","medium","high","urgent"]);

function fail(status, code, message, details = undefined) { throw Object.assign(new Error(message), { status, code, details }); }
function text(value, max = 10000) { if (typeof value !== "string") return null; const v = value.trim(); return v ? v.slice(0,max) : null; }
function required(value, name, max = 500) { const v = text(value,max); if (!v) fail(422,"VALIDATION_ERROR",`${name} is required`); return v; }
function bounded(value, fallback = 50, max = 500) { const v = Number(value); return Number.isFinite(v) ? Math.max(1,Math.min(Math.trunc(v),max)) : fallback; }
function offset(value) { const v = Number(value); return Number.isFinite(v) ? Math.max(0,Math.trunc(v)) : 0; }
function choice(value, allowed, fallback) { const v=String(value??""); return allowed.has(v)?v:fallback; }
function bool(value) { return value===true||value===1||value==="1"||value==="true"; }
function parseJson(value, fallback) { if (value==null) return fallback; if (typeof value!=="string") return value; try{return JSON.parse(value)}catch{return fallback} }
function camel(row) { if(!row)return row; const out={}; for(const [key,value] of Object.entries(row)){const k=key.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()).replace(/Json$/,"");out[k]=key.endsWith("_json")?parseJson(value,key==="mentions_json"?[]:{}):value;} return out; }
function rows(result){return (result?.rows??[]).map(camel)}
function actor(principal){return principal.userId?.startsWith("apikey:")?null:principal.userId}
function workLevel(principal,level="read"){
  if(["owner","admin"].includes(principal.role))return true;
  const scopes=principal.scopes??[];
  if(scopes.includes("work:*")||scopes.includes(`work:${level}`))return true;
  if(level==="read"&&(scopes.includes("work:write")||scopes.includes("work:manage")))return true;
  if(level==="write"&&scopes.includes("work:manage"))return true;
  if(level==="read")return ["manager","accountant","viewer"].includes(principal.role);
  if(level==="write")return ["manager","accountant"].includes(principal.role);
  return principal.role==="manager";
}

export class TasksWorkApiService {
  constructor({database,audit=null,events=null,tenantStorage=null}){
    if(!database?.query||!database?.transaction)throw new TypeError("TasksWorkApiService requires database");
    this.database=database;this.audit=audit;this.events=events;this.tenantStorage=tenantStorage;
  }
  requireAccess(principal,level="read"){if(!workLevel(principal,level))fail(403,"FORBIDDEN",`Missing Tasks & Work ${level} permission`);}
  async auditWrite(principal,action,entityType,entityId,after=null,reason=null,requestId=null){await this.audit?.write?.({organizationId:principal.organizationId,actorType:"human",actorId:principal.userId,action,entityType,entityId,after,reason,requestId});}
  async requireUser(org,id,label="Member"){const r=await this.database.query(`SELECT u.id,u.display_name AS "fullName",u.email,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.user_id=$2 AND u.status='active'`,[org,id]);if(!r.rows[0])fail(422,"INVALID_MEMBER",`${label} is not an active member of this organization`);return r.rows[0];}
  async requireTask(org,id,{forUpdate=false,tx=this.database}={}){const r=await tx.query(`SELECT * FROM work_tasks WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL ${forUpdate?"FOR UPDATE":""}`,[id,org]);if(!r.rows[0])fail(404,"TASK_NOT_FOUND","Task not found");return r.rows[0];}
  async requireProject(org,id,{tx=this.database}={}){const r=await tx.query(`SELECT * FROM work_projects WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL`,[id,org]);if(!r.rows[0])fail(404,"PROJECT_NOT_FOUND","Project not found");return r.rows[0];}
  async requireTeam(org,id,{tx=this.database}={}){const r=await tx.query(`SELECT * FROM work_teams WHERE id=$1 AND organization_id=$2 AND status='active'`,[id,org]);if(!r.rows[0])fail(404,"TEAM_NOT_FOUND","Team not found");return r.rows[0];}

  manifest(){return {key:"tasks-work",name:"Tasks & Work",version:"1.1.0",features:["teams","shared-contacts","projects","tasks","subtasks","assignees","followers","checklists","comments","time-tracking","notifications","reminders","chat","attachments"],provider:"postgresql-tasks-work"};}
  async organization(p){this.requireAccess(p);return camel((await this.database.query(`SELECT id,name,timezone,status,created_at FROM organizations WHERE id=$1`,[p.organizationId])).rows[0]??null);}
  async members(p){this.requireAccess(p);const r=await this.database.query(`SELECT u.id,u.display_name AS full_name,u.email,u.status,m.role,COALESCE(sf.phone,sp.phone) AS phone,COALESCE(sf.staff_number,sp.staff_number) AS staff_number,sf.id AS staff_id,sf.is_teacher,sf.employment_status,dp.name AS department_name,pos.name AS position_name FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN school_user_profiles sp ON sp.organization_id=m.organization_id AND sp.user_id=m.user_id LEFT JOIN school_staff_profiles sf ON sf.organization_id=m.organization_id AND sf.user_id=m.user_id AND sf.deleted_at IS NULL LEFT JOIN school_departments dp ON dp.id=sf.department_id LEFT JOIN school_staff_positions pos ON pos.id=sf.position_id WHERE m.organization_id=$1 AND u.status='active' ORDER BY u.display_name`,[p.organizationId]);return rows(r);}
  async dashboard(p){this.requireAccess(p);const org=p.organizationId,uid=p.userId;const [ts,ps,due,recent,unread,time]=await Promise.all([
    this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='completed')::int completed,COUNT(*) FILTER(WHERE status='in_progress')::int in_progress,COUNT(*) FILTER(WHERE status='blocked')::int blocked,COUNT(*) FILTER(WHERE status NOT IN ('completed','cancelled') AND due_at IS NOT NULL AND due_at<now())::int overdue FROM work_tasks WHERE organization_id=$1 AND archived_at IS NULL`,[org]),
    this.database.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='active')::int active,COUNT(*) FILTER(WHERE status='completed')::int completed FROM work_projects WHERE organization_id=$1 AND archived_at IS NULL`,[org]),
    this.database.query(`SELECT t.id,t.task_number,t.title,t.status,t.priority,t.due_at,pj.name project_name FROM work_tasks t JOIN work_task_assignees a ON a.task_id=t.id LEFT JOIN work_projects pj ON pj.id=t.project_id WHERE t.organization_id=$1 AND a.user_id=$2 AND t.archived_at IS NULL AND t.status NOT IN ('completed','cancelled') ORDER BY t.due_at NULLS LAST LIMIT 8`,[org,uid]),
    this.database.query(`SELECT t.id,t.task_number,t.title,t.status,t.priority,t.updated_at,pj.name project_name FROM work_tasks t LEFT JOIN work_projects pj ON pj.id=t.project_id WHERE t.organization_id=$1 AND t.archived_at IS NULL ORDER BY t.updated_at DESC LIMIT 8`,[org]),
    this.database.query(`SELECT COUNT(*)::int count FROM work_notifications WHERE organization_id=$1 AND user_id=$2 AND read_at IS NULL`,[org,uid]),
    this.database.query(`SELECT COALESCE(SUM(minutes),0)::int minutes FROM work_time_entries WHERE organization_id=$1 AND user_id=$2 AND started_at>=now()-interval '7 days'`,[org,uid]),
  ]);return {tasks:camel(ts.rows[0]??{}),projects:camel(ps.rows[0]??{}),myDue:rows(due),recent:rows(recent),unreadNotifications:Number(unread.rows[0]?.count??0),myMinutesLast7Days:Number(time.rows[0]?.minutes??0)};}

  async listTeams(p){this.requireAccess(p);return rows(await this.database.query(`SELECT t.*,u.display_name lead_name,(SELECT COUNT(*) FROM work_team_members tm WHERE tm.team_id=t.id)::int member_count FROM work_teams t LEFT JOIN users u ON u.id=t.lead_user_id WHERE t.organization_id=$1 AND t.status='active' ORDER BY t.name`,[p.organizationId]));}
  async createTeam(p,input,requestId){this.requireAccess(p,"manage");const name=required(input.name,"name",160),description=text(input.description),lead=text(input.leadUserId,100),id=createId("wtm");if(lead)await this.requireUser(p.organizationId,lead,"Team lead");await this.database.transaction(async tx=>{await tx.query(`INSERT INTO work_teams(id,organization_id,name,description,lead_user_id,created_by) VALUES($1,$2,$3,$4,$5,$6)`,[id,p.organizationId,name,description,lead,actor(p)]);if(lead)await tx.query(`INSERT INTO work_team_members(team_id,user_id,role) VALUES($1,$2,'lead') ON CONFLICT(team_id,user_id) DO UPDATE SET role='lead'`,[id,lead]);});await this.auditWrite(p,"work.team.created","work_team",id,{name,description,leadUserId:lead},null,requestId);return{id,name,description,leadUserId:lead};}
  async getTeam(p,id){this.requireAccess(p);const team=await this.requireTeam(p.organizationId,id);const members=await this.database.query(`SELECT u.id,u.display_name full_name,u.email,tm.role FROM work_team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=$1 ORDER BY u.display_name`,[id]);return{...camel(team),members:rows(members)};}
  async addTeamMember(p,id,input){this.requireAccess(p,"manage");await this.requireTeam(p.organizationId,id);const userId=required(input.userId,"userId",100);await this.requireUser(p.organizationId,userId);const role=choice(input.role,new Set(["lead","manager","member","viewer"]),"member");await this.database.query(`INSERT INTO work_team_members(team_id,user_id,role) VALUES($1,$2,$3) ON CONFLICT(team_id,user_id) DO UPDATE SET role=excluded.role`,[id,userId,role]);return{teamId:id,userId,role};}

  async listContacts(p,q={}){this.requireAccess(p);const lim=bounded(q.limit,50),off=offset(q.offset),type=text(q.type,30),search=`%${String(q.search??"")}%`;const values=[p.organizationId,type,search,lim,off];const result=await this.database.query(`SELECT c.id,c.type,c.code,c.name,c.email,c.active,c.credit_limit_minor,c.pricing_tier,c.custom_fields,(SELECT cp.name FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id ORDER BY cp.is_primary DESC,cp.created_at LIMIT 1) primary_person_name,(SELECT cp.phone FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id ORDER BY cp.is_primary DESC,cp.created_at LIMIT 1) phone,(SELECT cp.role FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id ORDER BY cp.is_primary DESC,cp.created_at LIMIT 1) primary_person_role,(SELECT COUNT(*)::int FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id) people_count FROM contacts c WHERE c.organization_id=$1 AND c.archived_at IS NULL AND c.active=true AND ($2::text IS NULL OR c.type=$2) AND (c.name ILIKE $3 OR COALESCE(c.email,'') ILIKE $3 OR COALESCE(c.code,'') ILIKE $3 OR EXISTS(SELECT 1 FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id AND (cp.name ILIKE $3 OR COALESCE(cp.phone,'') ILIKE $3 OR COALESCE(cp.email,'') ILIKE $3))) ORDER BY c.name LIMIT $4 OFFSET $5`,values);const count=await this.database.query(`SELECT COUNT(*)::int total FROM contacts c WHERE c.organization_id=$1 AND c.archived_at IS NULL AND c.active=true AND ($2::text IS NULL OR c.type=$2) AND (c.name ILIKE $3 OR COALESCE(c.email,'') ILIKE $3 OR COALESCE(c.code,'') ILIKE $3 OR EXISTS(SELECT 1 FROM contact_people cp WHERE cp.organization_id=c.organization_id AND cp.contact_id=c.id AND (cp.name ILIKE $3 OR COALESCE(cp.phone,'') ILIKE $3 OR COALESCE(cp.email,'') ILIKE $3)))`,[p.organizationId,type,search]);return{items:rows(result),meta:{limit:lim,offset:off,total:Number(count.rows[0]?.total??0)}};}

  async listProjects(p,q={}){this.requireAccess(p);const lim=bounded(q.limit,50),off=offset(q.offset),status=text(q.status,30),teamId=text(q.teamId,100),search=`%${String(q.search??"")}%`;const r=await this.database.query(`SELECT pj.*,u.display_name owner_name,t.name team_name,c.name contact_name,(SELECT COUNT(*)::int FROM work_tasks x WHERE x.project_id=pj.id AND x.archived_at IS NULL) task_count,(SELECT COUNT(*)::int FROM work_project_members pm WHERE pm.project_id=pj.id) member_count FROM work_projects pj LEFT JOIN users u ON u.id=pj.owner_user_id LEFT JOIN work_teams t ON t.id=pj.team_id LEFT JOIN contacts c ON c.id=pj.ledger_contact_id WHERE pj.organization_id=$1 AND pj.archived_at IS NULL AND ($2::text IS NULL OR pj.status=$2) AND ($3::text IS NULL OR pj.team_id=$3) AND (pj.name ILIKE $4 OR pj.code ILIKE $4) ORDER BY pj.updated_at DESC LIMIT $5 OFFSET $6`,[p.organizationId,status,teamId,search,lim,off]);const c=await this.database.query(`SELECT COUNT(*)::int total FROM work_projects WHERE organization_id=$1 AND archived_at IS NULL AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR team_id=$3) AND (name ILIKE $4 OR code ILIKE $4)`,[p.organizationId,status,teamId,search]);return{items:rows(r),meta:{limit:lim,offset:off,total:Number(c.rows[0]?.total??0)}};}
  async createProject(p,input,requestId){this.requireAccess(p,"write");const id=createId("wpj"),code=required(input.code,"code",40).toUpperCase(),name=required(input.name,"name",200),teamId=text(input.teamId,100),contactId=text(input.contactId,100),owner=text(input.ownerUserId,100)||actor(p),priority=choice(input.priority,PRIORITIES,"medium"),status=choice(input.status,PROJECT_STATUSES,"planning");if(teamId)await this.requireTeam(p.organizationId,teamId);if(owner)await this.requireUser(p.organizationId,owner,"Project owner");if(contactId){const c=await this.database.query(`SELECT id FROM contacts WHERE id=$1 AND organization_id=$2 AND archived_at IS NULL AND active=true`,[contactId,p.organizationId]);if(!c.rows[0])fail(422,"INVALID_REFERENCE","Linked contact is invalid");}await this.database.transaction(async tx=>{await tx.query(`INSERT INTO work_projects(id,organization_id,team_id,ledger_contact_id,code,name,description,status,priority,owner_user_id,start_date,due_date,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[id,p.organizationId,teamId,contactId,code,name,text(input.description),status,priority,owner,text(input.startDate,20),text(input.dueDate,20),actor(p)]);if(owner)await tx.query(`INSERT INTO work_project_members(project_id,user_id,role) VALUES($1,$2,'owner') ON CONFLICT(project_id,user_id) DO NOTHING`,[id,owner]);});await this.auditWrite(p,"work.project.created","work_project",id,{code,name,status,priority},null,requestId);return{id,code,name,status,priority,teamId,contactId,ownerUserId:owner};}

  async listTasks(p,q={}){this.requireAccess(p);const lim=bounded(q.limit,50),off=offset(q.offset),status=text(q.status,30),projectId=text(q.projectId,100),assigneeId=text(q.assigneeId,100),parentId=text(q.parentTaskId,100),search=`%${String(q.search??"")}%`;const r=await this.database.query(`SELECT DISTINCT t.*,pj.name project_name,(SELECT COUNT(*)::int FROM work_task_checklist_items ci WHERE ci.task_id=t.id) checklist_total,(SELECT COUNT(*)::int FROM work_task_checklist_items ci WHERE ci.task_id=t.id AND ci.is_completed=true) checklist_completed,(SELECT COUNT(*)::int FROM work_comments cm WHERE cm.task_id=t.id AND cm.deleted_at IS NULL) comment_count FROM work_tasks t LEFT JOIN work_projects pj ON pj.id=t.project_id LEFT JOIN work_task_assignees ta ON ta.task_id=t.id WHERE t.organization_id=$1 AND t.archived_at IS NULL AND ($2::text IS NULL OR t.status=$2) AND ($3::text IS NULL OR t.project_id=$3) AND ($4::text IS NULL OR ta.user_id=$4) AND ($5::text IS NULL OR t.parent_task_id=$5) AND (t.title ILIKE $6 OR COALESCE(t.description,'') ILIKE $6) ORDER BY t.updated_at DESC LIMIT $7 OFFSET $8`,[p.organizationId,status,projectId,assigneeId,parentId,search,lim,off]);const c=await this.database.query(`SELECT COUNT(DISTINCT t.id)::int total FROM work_tasks t LEFT JOIN work_task_assignees ta ON ta.task_id=t.id WHERE t.organization_id=$1 AND t.archived_at IS NULL AND ($2::text IS NULL OR t.status=$2) AND ($3::text IS NULL OR t.project_id=$3) AND ($4::text IS NULL OR ta.user_id=$4) AND ($5::text IS NULL OR t.parent_task_id=$5) AND (t.title ILIKE $6 OR COALESCE(t.description,'') ILIKE $6)`,[p.organizationId,status,projectId,assigneeId,parentId,search]);return{items:rows(r),meta:{limit:lim,offset:off,total:Number(c.rows[0]?.total??0)}};}
  async createTask(p,input,requestId){this.requireAccess(p,"write");const title=required(input.title,"title",300),projectId=text(input.projectId,100),parentId=text(input.parentTaskId,100),status=choice(input.status,TASK_STATUSES,"todo"),priority=choice(input.priority,PRIORITIES,"medium"),assignees=Array.isArray(input.assigneeIds)?[...new Set(input.assigneeIds.filter(x=>typeof x==="string"&&x))]:[],id=createId("tsk");if(projectId)await this.requireProject(p.organizationId,projectId);if(parentId)await this.requireTask(p.organizationId,parentId);for(const uid of assignees)await this.requireUser(p.organizationId,uid,"Assignee");const saved=await this.database.transaction(async tx=>{const seq=await tx.query(`INSERT INTO work_sequences(organization_id,sequence_name,current_value) VALUES($1,'task',1) ON CONFLICT(organization_id,sequence_name) DO UPDATE SET current_value=work_sequences.current_value+1 RETURNING current_value`,[p.organizationId]);const task=await tx.query(`INSERT INTO work_tasks(id,organization_id,project_id,parent_task_id,task_number,title,description,status,priority,start_at,due_at,estimated_minutes,actual_minutes,progress,custom_fields_json,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,0,$13,'{}',$14,$14) RETURNING *`,[id,p.organizationId,projectId,parentId,Number(seq.rows[0].current_value),title,text(input.description),status,priority,input.startAt??null,input.dueAt??null,input.estimatedMinutes==null?null:Math.max(0,Number(input.estimatedMinutes)||0),status==="completed"?100:0,actor(p)]);for(const uid of assignees)await tx.query(`INSERT INTO work_task_assignees(task_id,user_id,assigned_by) VALUES($1,$2,$3) ON CONFLICT(task_id,user_id) DO NOTHING`,[id,uid,actor(p)]);const sync=taskSyncRecord(task.rows[0]);await emitMobileChange(tx,{organizationId:p.organizationId,...sync,changedBy:actor(p)});return task.rows[0];});await this.auditWrite(p,"work.task.created","work_task",id,camel(saved),null,requestId);return camel(saved);}
  async getTask(p,id){this.requireAccess(p);const task=await this.requireTask(p.organizationId,id);const [assignees,followers,checklist,comments,time,subtasks,project]=await Promise.all([this.database.query(`SELECT u.id,u.display_name full_name,u.email,m.role FROM work_task_assignees a JOIN users u ON u.id=a.user_id LEFT JOIN memberships m ON m.organization_id=$1 AND m.user_id=u.id WHERE a.task_id=$2 ORDER BY u.display_name`,[p.organizationId,id]),this.database.query(`SELECT u.id,u.display_name full_name,u.email,m.role FROM work_task_followers f JOIN users u ON u.id=f.user_id LEFT JOIN memberships m ON m.organization_id=$1 AND m.user_id=u.id WHERE f.task_id=$2 ORDER BY u.display_name`,[p.organizationId,id]),this.database.query(`SELECT id,title,is_completed,position FROM work_task_checklist_items WHERE task_id=$1 ORDER BY position,created_at`,[id]),this.database.query(`SELECT c.id,c.body,c.mentions_json,c.created_at,u.display_name author_name FROM work_comments c LEFT JOIN users u ON u.id=c.author_user_id WHERE c.task_id=$1 AND c.organization_id=$2 AND c.deleted_at IS NULL ORDER BY c.created_at`,[id,p.organizationId]),this.database.query(`SELECT e.id,e.description,e.started_at,e.ended_at,e.minutes,e.billable,u.display_name user_name FROM work_time_entries e JOIN users u ON u.id=e.user_id WHERE e.task_id=$1 AND e.organization_id=$2 ORDER BY e.started_at DESC`,[id,p.organizationId]),this.database.query(`SELECT id,task_number,title,status,priority,due_at,progress,parent_task_id FROM work_tasks WHERE parent_task_id=$1 AND organization_id=$2 AND archived_at IS NULL ORDER BY task_number`,[id,p.organizationId]),task.project_id?this.database.query(`SELECT name FROM work_projects WHERE id=$1 AND organization_id=$2`,[task.project_id,p.organizationId]):Promise.resolve({rows:[]})]);return{...camel(task),projectName:project.rows[0]?.name??null,assignees:rows(assignees),followers:rows(followers),checklist:rows(checklist),comments:rows(comments),timeEntries:rows(time),subtasks:rows(subtasks)};}
  async changeTaskStatus(p,id,status,requestId){this.requireAccess(p,"write");const next=choice(status,TASK_STATUSES,null);if(!next)fail(422,"VALIDATION_ERROR","Invalid task status");const saved=await this.database.transaction(async tx=>{await this.requireTask(p.organizationId,id,{forUpdate:true,tx});const r=await tx.query(`UPDATE work_tasks SET status=$3,progress=CASE WHEN $3='completed' THEN 100 ELSE progress END,completed_at=CASE WHEN $3='completed' THEN COALESCE(completed_at,now()) ELSE NULL END,updated_by=$4,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *`,[id,p.organizationId,next,actor(p)]);const sync=taskSyncRecord(r.rows[0]);await emitMobileChange(tx,{organizationId:p.organizationId,...sync,changedBy:actor(p)});return r.rows[0];});await this.auditWrite(p,"work.task.status_changed","work_task",id,{status:next},null,requestId);return camel(saved);}
  async addAssignee(p,id,userId){this.requireAccess(p,"write");await this.requireUser(p.organizationId,userId,"Assignee");return assignTask(this.database,{organizationId:p.organizationId,taskId:id,userId,actorUserId:actor(p),audit:this.audit,events:this.events});}
  async addFollower(p,id,userId){this.requireAccess(p,"write");await this.requireTask(p.organizationId,id);await this.requireUser(p.organizationId,userId,"Follower");await this.database.query(`INSERT INTO work_task_followers(task_id,user_id) VALUES($1,$2) ON CONFLICT(task_id,user_id) DO NOTHING`,[id,userId]);return{taskId:id,userId};}
  async addChecklist(p,id,input){this.requireAccess(p,"write");await this.requireTask(p.organizationId,id);const itemId=createId("wci"),title=required(input.title,"title",300);const pos=await this.database.query(`SELECT COALESCE(MAX(position),-1)+1 AS position FROM work_task_checklist_items WHERE task_id=$1`,[id]);await this.database.query(`INSERT INTO work_task_checklist_items(id,task_id,title,position) VALUES($1,$2,$3,$4)`,[itemId,id,title,Number(pos.rows[0]?.position??0)]);return{id:itemId,title,isCompleted:false,position:Number(pos.rows[0]?.position??0)};}
  async toggleChecklist(p,taskId,itemId,input){this.requireAccess(p,"write");await this.requireTask(p.organizationId,taskId);const completed=bool(input.isCompleted);const r=await this.database.query(`UPDATE work_task_checklist_items SET is_completed=$1,completed_by=CASE WHEN $1 THEN $2 ELSE NULL END,completed_at=CASE WHEN $1 THEN now() ELSE NULL END,updated_at=now() WHERE id=$3 AND task_id=$4 RETURNING id,title,is_completed,position`,[completed,actor(p),itemId,taskId]);if(!r.rows[0])fail(404,"CHECKLIST_ITEM_NOT_FOUND","Checklist item not found");return camel(r.rows[0]);}
  async comment(p,id,input){this.requireAccess(p,"write");await this.requireTask(p.organizationId,id);const commentId=createId("wcm"),body=required(input.body,"body",10000),mentions=Array.isArray(input.mentionUserIds)?[...new Set(input.mentionUserIds.filter(x=>typeof x==="string"&&x))]:[];for(const uid of mentions)await this.requireUser(p.organizationId,uid,"Mentioned user");const r=await this.database.query(`INSERT INTO work_comments(id,organization_id,task_id,author_user_id,body,mentions_json) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[commentId,p.organizationId,id,actor(p),body,JSON.stringify(mentions)]);return camel(r.rows[0]);}
  async logTime(p,id,input){this.requireAccess(p,"write");await this.requireTask(p.organizationId,id);const entryId=createId("wte"),started=input.startedAt?new Date(input.startedAt):new Date(),ended=input.endedAt?new Date(input.endedAt):null;if(Number.isNaN(started.getTime())||(ended&&Number.isNaN(ended.getTime()))||(ended&&ended<started))fail(422,"VALIDATION_ERROR","Invalid time range");const minutes=ended?Math.max(0,Math.round((ended-started)/60000)):0;const r=await this.database.transaction(async tx=>{const row=await tx.query(`INSERT INTO work_time_entries(id,organization_id,task_id,user_id,description,started_at,ended_at,minutes,billable) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[entryId,p.organizationId,id,p.userId,text(input.description),started.toISOString(),ended?.toISOString()??null,minutes,bool(input.billable)]);await tx.query(`UPDATE work_tasks SET actual_minutes=(SELECT COALESCE(SUM(minutes),0) FROM work_time_entries WHERE task_id=$1),updated_at=now() WHERE id=$1 AND organization_id=$2`,[id,p.organizationId]);return row.rows[0];});return camel(r);}

  async listNotifications(p,q={}){this.requireAccess(p);const lim=bounded(q.limit,50),off=offset(q.offset),unread=bool(q.unread);const r=await this.database.query(`SELECT id,title,body,event_type,entity_type,entity_id,data_json,read_at,created_at FROM work_notifications WHERE organization_id=$1 AND user_id=$2 AND ($3::boolean=false OR read_at IS NULL) ORDER BY created_at DESC LIMIT $4 OFFSET $5`,[p.organizationId,p.userId,unread,lim,off]);const c=await this.database.query(`SELECT COUNT(*)::int total FROM work_notifications WHERE organization_id=$1 AND user_id=$2 AND ($3::boolean=false OR read_at IS NULL)`,[p.organizationId,p.userId,unread]);return{items:rows(r),meta:{limit:lim,offset:off,total:Number(c.rows[0]?.total??0)}};}
  async readNotification(p,id){this.requireAccess(p);await this.database.query(`UPDATE work_notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND organization_id=$2 AND user_id=$3`,[id,p.organizationId,p.userId]);return{id,read:true};}
  async readAllNotifications(p){this.requireAccess(p);await this.database.query(`UPDATE work_notifications SET read_at=COALESCE(read_at,now()) WHERE organization_id=$1 AND user_id=$2 AND read_at IS NULL`,[p.organizationId,p.userId]);return{read:true};}
  async notificationPreferences(p){this.requireAccess(p);return rows(await this.database.query(`SELECT event_type,in_app,email,sms,whatsapp,quiet_hours_json FROM work_notification_preferences WHERE organization_id=$1 AND user_id=$2 ORDER BY event_type`,[p.organizationId,p.userId]));}
  async saveNotificationPreference(p,eventType,input){this.requireAccess(p);const event=required(eventType,"eventType",120);const row=await this.database.query(`INSERT INTO work_notification_preferences(organization_id,user_id,event_type,in_app,email,sms,whatsapp,quiet_hours_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id,user_id,event_type) DO UPDATE SET in_app=excluded.in_app,email=excluded.email,sms=excluded.sms,whatsapp=excluded.whatsapp,quiet_hours_json=excluded.quiet_hours_json RETURNING event_type,in_app,email,sms,whatsapp,quiet_hours_json`,[p.organizationId,p.userId,event,bool(input.inApp??true),bool(input.email??true),bool(input.sms),bool(input.whatsapp),input.quietHours?JSON.stringify(input.quietHours):null]);return camel(row.rows[0]);}

  async listChats(p,q={}){this.requireAccess(p);const search=`%${String(q.search??"")}%`;const r=await this.database.query(`SELECT t.id,t.title,t.kind,t.status,t.external_name,t.external_phone,t.last_message_at,p.unread_count,(SELECT COUNT(*)::int FROM work_chat_participants x WHERE x.thread_id=t.id) participant_count,(SELECT body FROM work_chat_messages m WHERE m.thread_id=t.id ORDER BY created_at DESC LIMIT 1) last_message FROM work_chat_threads t JOIN work_chat_participants p ON p.thread_id=t.id AND p.user_id=$2 WHERE t.organization_id=$1 AND t.title ILIKE $3 ORDER BY t.last_message_at DESC`,[p.organizationId,p.userId,search]);return{items:rows(r),unread:r.rows.reduce((n,x)=>n+Number(x.unread_count??0),0)};}
  async getChat(p,id){this.requireAccess(p);const found=await this.database.query(`SELECT t.*,p.unread_count FROM work_chat_threads t JOIN work_chat_participants p ON p.thread_id=t.id WHERE t.id=$1 AND t.organization_id=$2 AND p.user_id=$3`,[id,p.organizationId,p.userId]);if(!found.rows[0])fail(404,"CHAT_NOT_FOUND","Chat not found");await this.database.query(`UPDATE work_chat_participants SET unread_count=0,last_read_at=now() WHERE thread_id=$1 AND user_id=$2`,[id,p.userId]);const [messages,participants]=await Promise.all([this.database.query(`SELECT m.*,u.display_name sender_name FROM work_chat_messages m LEFT JOIN users u ON u.id=m.sender_user_id WHERE m.thread_id=$1 AND m.organization_id=$2 ORDER BY m.created_at`,[id,p.organizationId]),this.database.query(`SELECT u.id,u.display_name full_name,u.email,cp.unread_count,cp.last_read_at FROM work_chat_participants cp JOIN users u ON u.id=cp.user_id WHERE cp.thread_id=$1 ORDER BY u.display_name`,[id])]);return{...camel(found.rows[0]),messages:rows(messages),participants:rows(participants)};}
  async createChat(p,input){this.requireAccess(p,"write");const participants=[...new Set([p.userId,...(Array.isArray(input.participantIds)?input.participantIds:[]).filter(x=>typeof x==="string"&&x)])];if(participants.length<2)fail(422,"VALIDATION_ERROR","Choose at least one other participant");for(const uid of participants)await this.requireUser(p.organizationId,uid);const id=createId("wct"),title=required(input.title,"title",200);await this.database.transaction(async tx=>{await tx.query(`INSERT INTO work_chat_threads(id,organization_id,kind,title,status,created_by) VALUES($1,$2,'internal',$3,'open',$4)`,[id,p.organizationId,title,actor(p)]);for(const uid of participants)await tx.query(`INSERT INTO work_chat_participants(thread_id,user_id) VALUES($1,$2)`,[id,uid]);if(text(input.message))await tx.query(`INSERT INTO work_chat_messages(id,organization_id,thread_id,sender_user_id,direction,message_type,body) VALUES($1,$2,$3,$4,'internal','text',$5)`,[createId("wcm"),p.organizationId,id,actor(p),text(input.message)]);});return{id,title};}
  async postMessage(p,id,input){this.requireAccess(p,"write");const row=await postChatMessage(this.database,{organizationId:p.organizationId,threadId:id,senderUserId:actor(p),direction:"internal",messageType:"text",body:required(input.body,"body",10000)});return camel(row);}
  async closeChat(p,id){this.requireAccess(p,"write");const access=await this.database.query(`SELECT t.id FROM work_chat_threads t JOIN work_chat_participants cp ON cp.thread_id=t.id WHERE t.id=$1 AND t.organization_id=$2 AND cp.user_id=$3`,[id,p.organizationId,p.userId]);if(!access.rows[0])fail(404,"CHAT_NOT_FOUND","Chat not found");await this.database.query(`UPDATE work_chat_threads SET status='closed',closed_by=$3,closed_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2`,[id,p.organizationId,actor(p)]);return{id,status:"closed"};}
  async saveChatAttachment(p,threadId,{fileName,mimeType,bytes}){this.requireAccess(p,"write");const access=await this.database.query(`SELECT t.id FROM work_chat_threads t JOIN work_chat_participants cp ON cp.thread_id=t.id WHERE t.id=$1 AND t.organization_id=$2 AND cp.user_id=$3`,[threadId,p.organizationId,p.userId]);if(!access.rows[0])fail(404,"CHAT_NOT_FOUND","Chat not found");if(!this.tenantStorage)fail(503,"STORAGE_NOT_READY","Tenant storage is unavailable");const safe=(fileName||"attachment").replace(/[^a-zA-Z0-9._ -]/g,"_").slice(0,180)||"attachment";const messageId=createId("wcm"),key=`tasks-work/chats/${threadId}/${messageId}-${safe}`;const storage=this.tenantStorage.forOrganization(p.organizationId);await storage.put(key,bytes,{contentType:mimeType||"application/octet-stream"});const type=String(mimeType||"").startsWith("audio/")?"audio":String(mimeType||"").startsWith("image/")?"image":String(mimeType||"").startsWith("video/")?"video":"document";const r=await this.database.query(`INSERT INTO work_chat_messages(id,organization_id,thread_id,sender_user_id,direction,message_type,file_key,file_name,mime_type,size_bytes) VALUES($1,$2,$3,$4,'internal',$5,$6,$7,$8,$9) RETURNING *`,[messageId,p.organizationId,threadId,actor(p),type,key,safe,mimeType||"application/octet-stream",bytes.length]);await this.database.query(`UPDATE work_chat_threads SET last_message_at=now(),updated_at=now() WHERE id=$1 AND organization_id=$2`,[threadId,p.organizationId]);return camel(r.rows[0]);}
  async getChatFile(p,threadId,messageId){this.requireAccess(p);const r=await this.database.query(`SELECT m.file_key,m.file_name,m.mime_type,m.size_bytes FROM work_chat_messages m JOIN work_chat_participants cp ON cp.thread_id=m.thread_id AND cp.user_id=$3 WHERE m.id=$1 AND m.thread_id=$2 AND m.organization_id=$4 AND m.file_key IS NOT NULL`,[messageId,threadId,p.userId,p.organizationId]);if(!r.rows[0])fail(404,"CHAT_FILE_NOT_FOUND","Chat attachment not found");if(!this.tenantStorage)fail(503,"STORAGE_NOT_READY","Tenant storage is unavailable");const bytes=await this.tenantStorage.forOrganization(p.organizationId).get(r.rows[0].file_key);return{bytes,fileName:r.rows[0].file_name,mimeType:r.rows[0].mime_type||"application/octet-stream",sizeBytes:Number(r.rows[0].size_bytes??bytes.length)};}

  async readiness(){const r=await this.database.query(`SELECT to_regclass('public.work_tasks') IS NOT NULL tasks,to_regclass('public.work_projects') IS NOT NULL projects,to_regclass('public.work_teams') IS NOT NULL teams,to_regclass('public.work_notifications') IS NOT NULL notifications,to_regclass('public.work_chat_threads') IS NOT NULL chats,to_regclass('public.work_chat_messages') IS NOT NULL messages,to_regclass('public.work_recurrence_occurrences') IS NOT NULL recurrence`);const row=r.rows[0]??{};const missing=Object.entries(row).filter(([,v])=>v!==true).map(([k])=>k);return{ok:missing.length===0,provider:"postgresql-tasks-work",missing};}
  describe(){return{provider:"postgresql-tasks-work",frontendApiParity:true,tenantScopedChatStorage:Boolean(this.tenantStorage),cloudflareFallbackPreserved:true};}
}
