import {evaluateReadiness,type ReadinessMetrics} from "./readiness-policy";
function recent(ts:any,seconds=90){const n=Date.parse(String(ts||""));return Number.isFinite(n)&&Date.now()-n<=seconds*1000}
export async function deploymentReadiness(db:D1Database,organizationId:string){
 const [cameras,servers,validations,alerts,volumes,redundancy,backups]=await db.batch([
  db.prepare(`SELECT COUNT(*) cameras,SUM(CASE WHEN recording_enabled=1 THEN 1 ELSE 0 END) recording_cameras,SUM(CASE WHEN recording_enabled=1 AND server_id IS NOT NULL THEN 1 ELSE 0 END) assigned_recording_cameras,SUM(CASE WHEN health_state='critical' THEN 1 ELSE 0 END) critical_health,SUM(CASE WHEN health_state='degraded' THEN 1 ELSE 0 END) degraded_health,SUM(CASE WHEN recording_enabled=1 AND (last_recording_at IS NULL OR last_recording_at<datetime('now','-10 minutes')) THEN 1 ELSE 0 END) stale_recording FROM security_cameras WHERE organization_id=? AND revoked_at IS NULL`).bind(organizationId),
  db.prepare(`SELECT id,status,last_seen_at FROM security_camera_servers WHERE organization_id=?`).bind(organizationId),
  db.prepare(`SELECT SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) failed,SUM(CASE WHEN status='warning' THEN 1 ELSE 0 END) warning FROM security_camera_validation_runs WHERE organization_id=? AND created_at>=datetime('now','-24 hours')`).bind(organizationId),
  db.prepare(`SELECT COUNT(*) total FROM security_camera_alerts WHERE organization_id=? AND status!='resolved' AND severity='critical'`).bind(organizationId),
  db.prepare(`SELECT COUNT(*) low FROM security_camera_server_volumes WHERE organization_id=? AND status='online' AND total_bytes>0 AND (CAST(free_bytes AS REAL)/CAST(total_bytes AS REAL))<0.05`).bind(organizationId),
  db.prepare(`SELECT COUNT(*) total FROM security_camera_redundancy WHERE organization_id=? AND enabled=1`).bind(organizationId),
  db.prepare(`SELECT enabled,status FROM security_camera_backup_status WHERE organization_id=?`).bind(organizationId)
 ]);
 const c:any=cameras.results?.[0]||{},v:any=validations.results?.[0]||{},a:any=alerts.results?.[0]||{},vol:any=volumes.results?.[0]||{},r:any=redundancy.results?.[0]||{};const serverRows:any[]=servers.results||[],backupRows:any[]=backups.results||[];
 const metrics:ReadinessMetrics={cameras:Number(c.cameras)||0,recordingCameras:Number(c.recording_cameras)||0,assignedRecordingCameras:Number(c.assigned_recording_cameras)||0,criticalHealth:Number(c.critical_health)||0,degradedHealth:Number(c.degraded_health)||0,staleRecording:Number(c.stale_recording)||0,servers:serverRows.length,onlineServers:serverRows.filter(x=>x.status==='online'&&recent(x.last_seen_at,90)).length,validationFailed24h:Number(v.failed)||0,validationWarning24h:Number(v.warning)||0,criticalAlerts:Number(a.total)||0,lowStorageVolumes:Number(vol.low)||0,redundancyProtected:Number(r.total)||0,backupsEnabled:backupRows.filter(x=>Number(x.enabled)===1).length,backupsHealthy:backupRows.filter(x=>Number(x.enabled)===1&&x.status==='healthy').length};
 return{...evaluateReadiness(metrics),generatedAt:new Date().toISOString()};
}
export async function recoveryDrill(db:D1Database,organizationId:string){const rows=await db.prepare(`SELECT r.camera_id,c.name camera_name,r.primary_server_id,r.secondary_server_id,r.failover_after_seconds,p.name primary_name,p.status primary_status,p.last_seen_at primary_last_seen,s.name secondary_name,s.status secondary_status,s.last_seen_at secondary_last_seen FROM security_camera_redundancy r JOIN security_cameras c ON c.id=r.camera_id JOIN security_camera_servers p ON p.id=r.primary_server_id JOIN security_camera_servers s ON s.id=r.secondary_server_id WHERE r.organization_id=? AND r.enabled=1 AND c.revoked_at IS NULL ORDER BY c.name`).bind(organizationId).all<any>();const results=(rows.results||[]).map((row:any)=>{const secondaryHealthy=row.secondary_status==='online'&&recent(row.secondary_last_seen,90),primaryHealthy=row.primary_status==='online'&&recent(row.primary_last_seen,90);return{cameraId:row.camera_id,cameraName:row.camera_name,primaryServerId:row.primary_server_id,primaryServerName:row.primary_name,secondaryServerId:row.secondary_server_id,secondaryServerName:row.secondary_name,primaryHealthy,secondaryHealthy,ready:secondaryHealthy,predictedRtoSeconds:Number(row.failover_after_seconds)||90,message:secondaryHealthy?`Dry run passed: ${row.secondary_name} is currently healthy and could receive this camera`:`Dry run failed: ${row.secondary_name} is not currently healthy`}});return{generatedAt:new Date().toISOString(),protectedCameras:results.length,readyCameras:results.filter((x:any)=>x.ready).length,results}}
