// @ts-nocheck
import { Hono } from "hono";
import type { AppVariables, Env } from "../../../src/types";
import { requireScope } from "../../../src/lib/auth";
import { requireModuleEnabled } from "../../../src/lib/modules";
import * as S from "./service";
import * as L from "./live-media";
import * as F from "./fleet";
export const securityCameraRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
const json=async(c:any)=>c.req.json<Record<string,any>>().catch(()=>({}));
const read=[requireModuleEnabled("security-camera"),requireScope("school:read")],write=[requireModuleEnabled("security-camera"),requireScope("school:write")];
securityCameraRoutes.get("/manifest",c=>c.json({data:{key:"security-camera",name:"Security Cameras",version:"0.8.0",cameraProtocol:"6",capabilities:["qr-pairing","nvr-pairing","whip-publish","whep-live-view","nvr-recording","lan-segment-fallback","recording-sync","device-health","appliance-mode","archive-timeline","playback-grants","clip-export","camera-profiles","multi-volume-storage","operational-alerts","event-timeline","motion-events","detector-webhook","person-object-detector-adapter","evidence-snapshots","operator-snapshots","incident-protection","visual-zones","schedules","event-rules","camera-groups","saved-wall-views","monitor-wall","fleet-diagnostics","device-lifecycle","production-watchdog"]}}));
securityCameraRoutes.get("/overview",...read,async c=>c.json({data:await S.overview(c.env.FINANCE_DB,c.get("principal").organizationId)}));
securityCameraRoutes.get("/cameras",...read,async c=>c.json({data:await F.listCameras(c.env.FINANCE_DB,c.get("principal").organizationId)}));
securityCameraRoutes.get("/servers",...read,async c=>c.json({data:await F.listServers(c.env.FINANCE_DB,c.get("principal").organizationId)}));
securityCameraRoutes.get("/recordings",...read,async c=>c.json({data:await S.listRecordings(c.env.FINANCE_DB,c.get("principal").organizationId,c.req.query("cameraId")||undefined,Number(c.req.query("limit"))||200)}));
securityCameraRoutes.get("/live",...read,async c=>c.json({data:await S.listLiveSessions(c.env.FINANCE_DB,c.get("principal").organizationId)}));
securityCameraRoutes.get("/live/:id",...read,async c=>c.json({data:await L.getViewerSession(c.env.FINANCE_DB,c.get("principal").organizationId,c.req.param("id"))}));
securityCameraRoutes.post("/pairings",...write,async c=>{const p=c.get("principal");return c.json({data:await S.createPairing(c.env.FINANCE_DB,p.organizationId,p.userId,await json(c))},201)});
securityCameraRoutes.post("/server-pairings",...write,async c=>{const p=c.get("principal");return c.json({data:await S.createServerPairing(c.env.FINANCE_DB,p.organizationId,p.userId,await json(c))},201)});
securityCameraRoutes.post("/cameras/:id/assign",...write,async c=>{const p=c.get("principal"),body=await json(c);return c.json({data:await S.assignCamera(c.env.FINANCE_DB,p.organizationId,c.req.param("id"),body.serverId||null)})});
securityCameraRoutes.post("/cameras/:id/recording",...write,async c=>{const p=c.get("principal"),body=await json(c);return c.json({data:await S.setCameraRecording(c.env.FINANCE_DB,p.organizationId,c.req.param("id"),body.enabled!==false)})});
securityCameraRoutes.post("/cameras/:id/live",...write,async c=>{const p=c.get("principal");return c.json({data:await L.createViewerSession(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"))},201)});
securityCameraRoutes.post("/live/:id/end",...write,async c=>c.json({data:await L.endViewerSession(c.env.FINANCE_DB,c.get("principal").organizationId,c.req.param("id"))}));
securityCameraRoutes.post("/cameras/:id/revoke",...write,async c=>c.json({data:await S.revokeCamera(c.env.FINANCE_DB,c.get("principal").organizationId,c.req.param("id"))}));
