function boundedLimit(value, fallback=20, max=100){const n=Number(value);return Math.max(1,Math.min(Number.isFinite(n)?Math.trunc(n):fallback,max));}
function text(value){return String(value??"").trim();}
function like(value){return `%${text(value).replace(/[%_]/g,(m)=>`\\${m}`)}%`;}
async function relationExists(database,name){const r=await database.query(`SELECT to_regclass($1) AS relation`,[name]);return Boolean(r.rows[0]?.relation);}
function unavailableDomain(domain){const e=new Error(`${domain} self-hosted domain is not migrated yet`);e.code="AI_DOMAIN_NOT_MIGRATED";throw e;}
async function requireRelation(database,name,domain){if(!(await relationExists(database,name)))unavailableDomain(domain);}

export function createLedgerlyBusinessTools({database,health=null}){
 if(!database?.query)throw new TypeError("createLedgerlyBusinessTools requires database");
 return {
  searchStudents:async({input,context})=>{await requireRelation(database,"school_students","students");const q=text(input.query);const limit=boundedLimit(input.limit,20,50);const r=await database.query(`SELECT id,admission_number,student_number,first_name,middle_name,last_name,preferred_name,current_class_id,current_stream_id,status FROM school_students WHERE organization_id=$1 AND deleted_at IS NULL AND ($2='' OR admission_number ILIKE $3 ESCAPE '\\' OR student_number ILIKE $3 ESCAPE '\\' OR first_name ILIKE $3 ESCAPE '\\' OR last_name ILIKE $3 ESCAPE '\\' OR COALESCE(preferred_name,'') ILIKE $3 ESCAPE '\\') ORDER BY last_name,first_name LIMIT $4`,[context.organizationId,q,like(q),limit]);return {items:r.rows};},
  getStudent:async({input,context})=>{await requireRelation(database,"school_students","students");const id=text(input.studentId||input.id);const r=await database.query(`SELECT id,admission_number,student_number,first_name,middle_name,last_name,preferred_name,gender,date_of_birth,current_academic_year_id,current_class_id,current_stream_id,status FROM school_students WHERE organization_id=$1 AND deleted_at IS NULL AND (id=$2 OR admission_number=$2 OR student_number=$2) LIMIT 1`,[context.organizationId,id]);return r.rows[0]??null;},
  getStaff:async({input,context})=>{await requireRelation(database,"school_staff_profiles","staff");const q=text(input.query||input.staffId||input.id);const limit=boundedLimit(input.limit,20,50);const r=await database.query(`SELECT id,staff_number,first_name,middle_name,last_name,preferred_name,department_id,position_id,campus_id,employment_status,is_teacher FROM school_staff_profiles WHERE organization_id=$1 AND deleted_at IS NULL AND ($2='' OR id=$2 OR staff_number=$2 OR first_name ILIKE $3 ESCAPE '\\' OR last_name ILIKE $3 ESCAPE '\\') ORDER BY last_name,first_name LIMIT $4`,[context.organizationId,q,like(q),limit]);return {items:r.rows};},
  getSchoolProfile:async({context})=>{await requireRelation(database,"school_profiles","school");const r=await database.query(`SELECT organization_id,school_code,registration_number,motto,school_type,ownership_type,education_level,curriculum,website,physical_address,country,district_region,head_teacher_name,language,timezone,default_currency FROM school_profiles WHERE organization_id=$1`,[context.organizationId]);return r.rows[0]??null;},
  getAcademicContext:async({input,context})=>{await requireRelation(database,"school_academic_years","academics");const yearId=text(input.academicYearId);const termId=text(input.termId);const [years,terms,classes,subjects]=await Promise.all([database.query(`SELECT id,code,name,starts_on,ends_on,status,is_current FROM school_academic_years WHERE organization_id=$1 AND ($2='' OR id=$2) ORDER BY starts_on DESC LIMIT 10`,[context.organizationId,yearId]),database.query(`SELECT id,academic_year_id,code,name,sequence_no,starts_on,ends_on,status,is_current FROM school_terms WHERE organization_id=$1 AND ($2='' OR academic_year_id=$2) AND ($3='' OR id=$3) ORDER BY starts_on`,[context.organizationId,yearId,termId]),database.query(`SELECT id,academic_year_id,class_level_id,code,name,active FROM school_classes WHERE organization_id=$1 AND ($2='' OR academic_year_id=$2) ORDER BY name`,[context.organizationId,yearId]),database.query(`SELECT id,code,name,short_name,subject_type,active FROM school_subjects WHERE organization_id=$1 ORDER BY name`,[context.organizationId])]);return {years:years.rows,terms:terms.rows,classes:classes.rows,subjects:subjects.rows};},
  getLessonPlan:async({input,context})=>{await requireRelation(database,"acad_lesson_plans","academics");const r=await database.query(`SELECT * FROM acad_lesson_plans WHERE organization_id=$1 AND id=$2`,[context.organizationId,text(input.lessonPlanId||input.id)]);return r.rows[0]??null;},
  getStudentBalance:async({input,context})=>{await requireRelation(database,"school_student_fee_charges","fees");await requireRelation(database,"school_fee_receipts","fees");const studentId=text(input.studentId);const r=await database.query(`SELECT COALESCE(SUM(GREATEST(total_minor-credited_minor-written_off_minor,0)),0)::bigint AS charged_minor FROM school_student_fee_charges WHERE organization_id=$1 AND student_id=$2 AND status NOT IN ('cancelled','credited','waived','written_off')`,[context.organizationId,studentId]);const receipts=await database.query(`SELECT COALESCE(SUM(allocated_minor),0)::bigint AS allocated_minor FROM school_fee_receipts WHERE organization_id=$1 AND student_id=$2`,[context.organizationId,studentId]);const charged=Number(r.rows[0]?.charged_minor??0),allocated=Number(receipts.rows[0]?.allocated_minor??0);return {studentId,chargedMinor:charged,allocatedMinor:allocated,balanceMinor:charged-allocated};},
  getFinanceSummary:async({input,context})=>{await requireRelation(database,"journal_entries","finance");const from=text(input.from);const to=text(input.to);const r=await database.query(`SELECT COALESCE(SUM(jl.debit_minor),0)::bigint AS debit_minor,COALESCE(SUM(jl.credit_minor),0)::bigint AS credit_minor,COUNT(DISTINCT je.id)::int AS posted_journals FROM journal_entries je JOIN journal_lines jl ON jl.journal_entry_id=je.id AND jl.organization_id=je.organization_id WHERE je.organization_id=$1 AND je.status='posted' AND ($2='' OR je.posting_date::date >= $2::date) AND ($3='' OR je.posting_date::date <= $3::date)`,[context.organizationId,from,to]);return r.rows[0]??{debit_minor:0,credit_minor:0,posted_journals:0};},
  findFinanceAnomalies:async({input,context})=>{await requireRelation(database,"journal_entries","finance");const limit=boundedLimit(input.limit,25,100);const r=await database.query(`SELECT je.id,je.entry_number,je.posting_date,je.description,COALESCE(SUM(jl.debit_minor),0)::bigint AS debit_minor,COALESCE(SUM(jl.credit_minor),0)::bigint AS credit_minor FROM journal_entries je JOIN journal_lines jl ON jl.journal_entry_id=je.id AND jl.organization_id=je.organization_id WHERE je.organization_id=$1 AND je.status='posted' GROUP BY je.id,je.entry_number,je.posting_date,je.description HAVING COALESCE(SUM(jl.debit_minor),0)<>COALESCE(SUM(jl.credit_minor),0) ORDER BY je.posting_date DESC LIMIT $2`,[context.organizationId,limit]);return {items:r.rows};},
  findUnmatchedPayments:async({input,context})=>{await requireRelation(database,"school_fee_receipts","fees");const limit=boundedLimit(input.limit,25,100);const r=await database.query(`SELECT id,receipt_number,student_id,payer_contact_id,payment_id,payment_date,currency,amount_minor,allocated_minor,unallocated_minor FROM school_fee_receipts WHERE organization_id=$1 AND unallocated_minor>0 ORDER BY payment_date DESC,created_at DESC LIMIT $2`,[context.organizationId,limit]);return {items:r.rows};},
  getInventorySummary:async({input,context})=>{await requireRelation(database,"products","inventory");const limit=boundedLimit(input.limit,50,100);const r=await database.query(`SELECT id,sku,name,type,quantity_on_hand_micros,average_cost_minor,reorder_point_micros,active,(quantity_on_hand_micros<=reorder_point_micros) AS at_or_below_reorder FROM products WHERE organization_id=$1 AND active=true ORDER BY at_or_below_reorder DESC,name LIMIT $2`,[context.organizationId,limit]);return {items:r.rows};},
  runConsistencyChecks:async({context})=>{const checks=[];if(await relationExists(database,"journal_entries")){const r=await database.query(`SELECT COUNT(*)::int AS count FROM (SELECT je.id FROM journal_entries je JOIN journal_lines jl ON jl.journal_entry_id=je.id AND jl.organization_id=je.organization_id WHERE je.organization_id=$1 AND je.status='posted' GROUP BY je.id HAVING SUM(jl.debit_minor)<>SUM(jl.credit_minor)) x`,[context.organizationId]);checks.push({name:"unbalanced_posted_journals",count:Number(r.rows[0]?.count??0)});}if(await relationExists(database,"school_students")){const r=await database.query(`SELECT COUNT(*)::int AS count FROM school_students WHERE organization_id=$1 AND status='active' AND deleted_at IS NOT NULL`,[context.organizationId]);checks.push({name:"active_deleted_students",count:Number(r.rows[0]?.count??0)});}return {checks,ok:checks.every((c)=>c.count===0)};},
  getSystemStatus:async({context})=>({organizationId:context.organizationId,health:health?await health():null}),
 };
}
