import { randomUUID } from "node:crypto";
import { createJobEnvelope } from "../contracts.mjs";
import { DOCUMENT_STATUSES, TASK_STATUSES, DEFAULT_LIMITS } from "./constants.mjs";
import { aiAttribution, humanEditProvenance } from "./provenance.mjs";

function assertOrg(context){if(!context?.organizationId)throw new Error("organization context required");return context.organizationId;}
function now(){return new Date().toISOString();}

export class AiApprovalService{
 constructor({database,audit}){this.database=database;this.audit=audit;}
 async request({organizationId,agent,taskId=null,action,reason=null,payload={},riskLevel="medium",requestedApprover=null}){const approvalId=randomUUID();const result=await this.database.query(`INSERT INTO ledgerly_ai.approvals (approval_id,organization_id,task_id,agent_id,requested_action,reason,payload,risk_level,requested_approver) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) RETURNING *`,[approvalId,organizationId,taskId,agent.agentId,action,reason,JSON.stringify(payload),riskLevel,requestedApprover]);await this.audit?.write?.({organization_id:organizationId,actor_type:"ai_agent",actor_id:agent.agentId,agent_id:agent.agentId,agent_name:agent.name,agent_role:agent.role,action:"ai.approval.requested",entity_type:"ai_approval",entity_id:approvalId,reason,metadata:{task_id:taskId,risk_level:riskLevel,requested_action:action}});return result.rows[0];}
 async decide({context,approvalId,approve,reason}){const org=assertOrg(context),status=approve?"approved":"rejected";const result=await this.database.query(`UPDATE ledgerly_ai.approvals SET status=$1,decision_by=$2,decision_reason=$3,decided_at=now() WHERE approval_id=$4 AND organization_id=$5 AND status='pending' RETURNING *`,[status,context.userId,reason,approvalId,org]);if(!result.rowCount)throw new Error("approval not found or already decided");await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:`ai.approval.${status}`,entity_type:"ai_approval",entity_id:approvalId,reason});return result.rows[0];}
 async get({context,approvalId}){const result=await this.database.query(`SELECT * FROM ledgerly_ai.approvals WHERE approval_id=$1 AND organization_id=$2`,[approvalId,assertOrg(context)]);return result.rows[0]??null;}
 async markExecuted({context,approvalId,result:executedResult}){const org=assertOrg(context);const result=await this.database.query(`UPDATE ledgerly_ai.approvals SET status='executed',executed_at=now(),executed_result=$1::jsonb WHERE approval_id=$2 AND organization_id=$3 AND status='approved' RETURNING *`,[JSON.stringify(executedResult??null),approvalId,org]);if(!result.rowCount)throw new Error("approval is not approved or was already executed");await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:"ai.approval.executed",entity_type:"ai_approval",entity_id:approvalId,metadata:{result:executedResult??null}});return result.rows[0];}
}

export class AiTaskService{
 constructor({database,queue,audit,limits=DEFAULT_LIMITS}){this.database=database;this.queue=queue;this.audit=audit;this.limits={...DEFAULT_LIMITS,...limits};}
 async create({context,assignedAgent,instruction,priority=50,dueTime=null,inputReferences=[],idempotencyKey=null,parentTaskId=null,handoffDepth=0,actor=null}){const org=assertOrg(context);if(!instruction||instruction.length>this.limits.maxPromptChars)throw new Error("AI task instruction is empty or exceeds configured input limit");if(handoffDepth>this.limits.maxHandoffs)throw new Error("AI handoff depth limit exceeded");const taskId=randomUUID();const result=await this.database.query(`INSERT INTO ledgerly_ai.tasks (task_id,organization_id,assigned_agent,requested_by,instruction,priority,due_time,input_references,idempotency_key,parent_task_id,handoff_depth) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11) ON CONFLICT (organization_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET updated_at=ledgerly_ai.tasks.updated_at RETURNING *`,[taskId,org,assignedAgent,context.userId,instruction,priority,dueTime,JSON.stringify(inputReferences),idempotencyKey,parentTaskId,handoffDepth]);const task=result.rows[0];if(task.task_id===taskId)await this.queue.enqueue(createJobEnvelope({kind:"ai.task",organizationId:org,jobId:taskId,idempotencyKey:`ai:${taskId}`,payload:{taskId}}));await this.audit?.write?.({organization_id:org,...(actor??{actor_type:"human",actor_id:context.userId}),action:"ai.task.created",entity_type:"ai_task",entity_id:task.task_id,reason:instruction,metadata:{assigned_agent:assignedAgent,parent_task_id:parentTaskId,handoff_depth:handoffDepth,authorized_by:context.userId}});return task;}
 async handoff({context,task,fromAgent,toAgent,instruction}){if(!fromAgent?.agentId)throw new Error("AI handoff requires source agent attribution");const authority=task.requested_by||context.userId;if(!authority)throw new Error("AI handoff has no authorizing actor");const actor={actor_type:"ai_agent",actor_id:fromAgent.agentId,agent_id:fromAgent.agentId,agent_name:fromAgent.name,agent_role:fromAgent.role};const next=await this.create({context:{...context,userId:authority},assignedAgent:toAgent,instruction,priority:task.priority,inputReferences:[...(task.output_references??[]),{type:"task",id:task.task_id}],parentTaskId:task.task_id,handoffDepth:Number(task.handoff_depth??0)+1,idempotencyKey:`handoff:${task.task_id}:${toAgent}`,actor});await this.audit?.write?.({organization_id:context.organizationId,...actor,action:"ai.task.handoff",entity_type:"ai_task",entity_id:task.task_id,reason:instruction,metadata:{to_agent:toAgent,child_task_id:next.task_id,authorized_by:authority}});return next;}
 async setStatus({organizationId,taskId,status,agent=null,error=null,outputReferences=null}){if(!TASK_STATUSES.includes(status))throw new Error(`invalid task status ${status}`);const result=await this.database.query(`UPDATE ledgerly_ai.tasks SET status=$1,last_error=$2,output_references=COALESCE($3::jsonb,output_references),attempts=CASE WHEN $1='working' THEN attempts+1 ELSE attempts END,completed_at=CASE WHEN $1='completed' THEN now() ELSE completed_at END,updated_at=now() WHERE task_id=$4 AND organization_id=$5 RETURNING *`,[status,error,outputReferences?JSON.stringify(outputReferences):null,taskId,organizationId]);if(!result.rowCount)throw new Error("AI task not found");await this.audit?.write?.({organization_id:organizationId,actor_type:agent?"ai_agent":"system",actor_id:agent?.agentId??"ai-worker",agent_id:agent?.agentId,agent_name:agent?.name,agent_role:agent?.role,action:`ai.task.${status}`,entity_type:"ai_task",entity_id:taskId,reason:error});return result.rows[0];}
 async resumeAfterApproval({context,taskId,approvalId,result:executedResult}){
   const org=assertOrg(context);if(!taskId)return {resumed:false,reason:"approval_has_no_task"};
   const reference={type:"approval",id:approvalId,status:"executed",result:executedResult??null};
   const update=await this.database.query(`UPDATE ledgerly_ai.tasks SET status='queued',history=history || jsonb_build_array(jsonb_build_object('type','approval_executed','approval_id',$1,'result',$2::jsonb,'at',now())),output_references=output_references || $3::jsonb,updated_at=now() WHERE task_id=$4 AND organization_id=$5 AND status='waiting_for_approval' RETURNING *`,[approvalId,JSON.stringify(executedResult??null),JSON.stringify([reference]),taskId,org]);
   if(!update.rowCount){const existing=(await this.database.query(`SELECT * FROM ledgerly_ai.tasks WHERE task_id=$1 AND organization_id=$2`,[taskId,org])).rows[0];if(!existing)throw new Error("AI task not found for approval resume");if(["queued","working","completed"].includes(existing.status))return {resumed:false,task:existing,reason:`already_${existing.status}`};throw new Error(`AI task cannot resume from status ${existing.status}`);}
   await this.queue.enqueue(createJobEnvelope({kind:"ai.task",organizationId:org,jobId:taskId,idempotencyKey:`ai:${taskId}:approval:${approvalId}`,payload:{taskId,resumedFromApproval:approvalId}}));
   await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:"ai.task.resumed_after_approval",entity_type:"ai_task",entity_id:taskId,metadata:{approval_id:approvalId}});
   return {resumed:true,task:update.rows[0]};
 }
}

export class AiDocumentService{
 constructor({database,audit}){this.database=database;this.audit=audit;}
 async createAiDraft({context,agent,taskId=null,type,title,content,reason}){const org=assertOrg(context),documentId=randomUUID(),provenance=aiAttribution({agent,taskId,reason});const result=await this.database.query(`INSERT INTO ledgerly_ai.documents (document_id,organization_id,type,title,content,creator,ai_provenance) VALUES ($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7::jsonb) RETURNING *`,[documentId,org,type,title,JSON.stringify(content),JSON.stringify(provenance),JSON.stringify(provenance)]);await this.database.query(`INSERT INTO ledgerly_ai.document_versions (document_id,version,organization_id,content,provenance,edited_by) VALUES ($1,1,$2,$3::jsonb,$4::jsonb,$5::jsonb)`,[documentId,org,JSON.stringify(content),JSON.stringify(provenance),JSON.stringify(provenance)]);await this.audit?.write?.({organization_id:org,actor_type:"ai_agent",actor_id:agent.agentId,agent_id:agent.agentId,agent_name:agent.name,agent_role:agent.role,action:"ai.document.created",entity_type:"document",entity_id:documentId,reason,after:content,metadata:{task_id:taskId,type,title}});return result.rows[0];}
 async update({context,documentId,content,reason=null}){const org=assertOrg(context);return this.database.transaction(async(tx)=>{const current=(await tx.query(`SELECT * FROM ledgerly_ai.documents WHERE document_id=$1 AND organization_id=$2 FOR UPDATE`,[documentId,org])).rows[0];if(!current)throw new Error("document not found");const version=Number(current.version)+1,provenance=humanEditProvenance(current.ai_provenance??{},{userId:context.userId,userName:context.userName??context.userId,reason});await tx.query(`UPDATE ledgerly_ai.documents SET content=$1::jsonb,version=$2,human_editors=human_editors || $3::jsonb,updated_at=now() WHERE document_id=$4 AND organization_id=$5`,[JSON.stringify(content),version,JSON.stringify([{user_id:context.userId,user_name:context.userName??context.userId,timestamp:now()}]),documentId,org]);await tx.query(`INSERT INTO ledgerly_ai.document_versions (document_id,version,organization_id,content,provenance,edited_by) VALUES ($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb)`,[documentId,version,org,JSON.stringify(content),JSON.stringify(provenance),JSON.stringify({actor_type:"human",actor_id:context.userId,actor_name:context.userName??context.userId})]);await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:"document.edited",entity_type:"document",entity_id:documentId,reason,before:current.content,after:content,metadata:{version,original_ai:current.ai_provenance??null}});return{...current,content,version,ai_provenance:current.ai_provenance};});}
 async setStatus({context,documentId,status,reason=null}){if(!DOCUMENT_STATUSES.includes(status))throw new Error(`invalid document status ${status}`);const org=assertOrg(context),result=await this.database.query(`UPDATE ledgerly_ai.documents SET status=$1,updated_at=now() WHERE document_id=$2 AND organization_id=$3 RETURNING *`,[status,documentId,org]);if(!result.rowCount)throw new Error("document not found");await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:`document.${status}`,entity_type:"document",entity_id:documentId,reason});return result.rows[0];}
}
