import { randomUUID } from "node:crypto";
import { createJobEnvelope } from "../contracts.mjs";
import { TASK_STATUSES, DEFAULT_LIMITS } from "./constants.mjs";

function assertOrg(context){if(!context?.organizationId)throw new Error("organization context required");return context.organizationId;}
function stateConflict(message){const error=new Error(message);error.code="AI_TASK_STATE_CONFLICT";error.status=409;return error;}
function invalid(message){const error=new Error(message);error.code="AI_TASK_INVALID";error.status=422;return error;}
function normalizePriority(value){const priority=Number(value??50);if(!Number.isInteger(priority)||priority<1||priority>100)throw invalid("AI task priority must be an integer from 1 to 100");return priority;}
function normalizeInstruction(value,max){const instruction=String(value??"").trim();if(!instruction||instruction.length>max)throw invalid("AI task instruction is empty or exceeds configured input limit");return instruction;}
function normalizeDueTime(value){if(value==null||value==="")return null;const parsed=new Date(value);if(Number.isNaN(parsed.getTime()))throw invalid("AI task dueTime must be a valid date/time");return parsed.toISOString();}

export class AiApprovalService{
 constructor({database,audit}){this.database=database;this.audit=audit;}
 async request({organizationId,agent,taskId=null,action,reason=null,payload={},riskLevel="medium",requestedApprover=null}){
  const approvalId=randomUUID();
  const insert=async(db)=>{
   if(taskId){const task=(await db.query(`SELECT status FROM ledgerly_ai.tasks WHERE task_id=$1 AND organization_id=$2 FOR UPDATE`,[taskId,organizationId])).rows[0];if(!task){const error=new Error("AI task not found for approval");error.code="AI_TASK_NOT_FOUND";throw error;}if(task.status!=="working")throw stateConflict(`AI task cannot request approval from status ${task.status}`);}
   return db.query(`INSERT INTO ledgerly_ai.approvals (approval_id,organization_id,task_id,agent_id,requested_action,reason,payload,risk_level,requested_approver) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9) RETURNING *`,[approvalId,organizationId,taskId,agent.agentId,action,reason,JSON.stringify(payload),riskLevel,requestedApprover]);
  };
  const result=typeof this.database.transaction==="function"?await this.database.transaction(insert):await insert(this.database);
  await this.audit?.write?.({organization_id:organizationId,actor_type:"ai_agent",actor_id:agent.agentId,agent_id:agent.agentId,agent_name:agent.name,agent_role:agent.role,action:"ai.approval.requested",entity_type:"ai_approval",entity_id:approvalId,reason,metadata:{task_id:taskId,risk_level:riskLevel,requested_action:action}});return result.rows[0];
 }
 async decide({context,approvalId,approve,reason}){const org=assertOrg(context),status=approve?"approved":"rejected";const result=await this.database.query(`UPDATE ledgerly_ai.approvals SET status=$1,decision_by=$2,decision_reason=$3,decided_at=now() WHERE approval_id=$4 AND organization_id=$5 AND status='pending' RETURNING *`,[status,context.userId,reason,approvalId,org]);if(!result.rowCount)throw new Error("approval not found or already decided");await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:`ai.approval.${status}`,entity_type:"ai_approval",entity_id:approvalId,reason});return result.rows[0];}
 async get({context,approvalId}){const result=await this.database.query(`SELECT * FROM ledgerly_ai.approvals WHERE approval_id=$1 AND organization_id=$2`,[approvalId,assertOrg(context)]);return result.rows[0]??null;}
 async markExecuted({context,approvalId,result:executedResult}){const org=assertOrg(context);const result=await this.database.query(`UPDATE ledgerly_ai.approvals SET status='executed',executed_at=now(),executed_result=$1::jsonb WHERE approval_id=$2 AND organization_id=$3 AND status='approved' RETURNING *`,[JSON.stringify(executedResult??null),approvalId,org]);if(!result.rowCount)throw new Error("approval is not approved or was already executed");await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:"ai.approval.executed",entity_type:"ai_approval",entity_id:approvalId,metadata:{result:executedResult??null}});return result.rows[0];}
}

export class AiTaskService{
 constructor({database,queue,audit,limits=DEFAULT_LIMITS}){this.database=database;this.queue=queue;this.audit=audit;this.limits={...DEFAULT_LIMITS,...limits};}
 #envelope(organizationId,taskId,suffix="",payload={}){return createJobEnvelope({kind:"ai.task",organizationId,jobId:taskId,idempotencyKey:`ai:${taskId}${suffix}`,payload:{taskId,...payload}});}
 async create({context,assignedAgent,instruction,priority=50,dueTime=null,inputReferences=[],idempotencyKey=null,parentTaskId=null,handoffDepth=0,actor=null}){
  const org=assertOrg(context),employee=String(assignedAgent??"").trim(),work=normalizeInstruction(instruction,this.limits.maxPromptChars),normalizedPriority=normalizePriority(priority),normalizedDue=normalizeDueTime(dueTime);if(!employee)throw invalid("assigned AI employee is required");if(handoffDepth>this.limits.maxHandoffs)throw invalid("AI handoff depth limit exceeded");if(!Array.isArray(inputReferences))throw invalid("AI task inputReferences must be an array");const idem=idempotencyKey==null?null:String(idempotencyKey).trim();if(idem&&idem.length>200)throw invalid("AI task idempotency key is too long");
  const candidateId=randomUUID();const result=await this.database.query(`INSERT INTO ledgerly_ai.tasks (task_id,organization_id,assigned_agent,requested_by,instruction,priority,due_time,input_references,idempotency_key,parent_task_id,handoff_depth) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11) ON CONFLICT (organization_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET updated_at=ledgerly_ai.tasks.updated_at RETURNING *`,[candidateId,org,employee,context.userId,work,normalizedPriority,normalizedDue,JSON.stringify(inputReferences),idem,parentTaskId,handoffDepth]);
  const task=result.rows[0],created=task.task_id===candidateId;if(created||task.status==="queued")await this.queue.enqueue(this.#envelope(org,task.task_id));
  if(created)await this.audit?.write?.({organization_id:org,...(actor??{actor_type:"human",actor_id:context.userId}),action:"ai.task.created",entity_type:"ai_task",entity_id:task.task_id,reason:work,metadata:{assigned_agent:employee,parent_task_id:parentTaskId,handoff_depth:handoffDepth,authorized_by:context.userId}});
  else await this.audit?.write?.({organization_id:org,...(actor??{actor_type:"human",actor_id:context.userId}),action:"ai.task.idempotent_recovered",entity_type:"ai_task",entity_id:task.task_id,reason:work,metadata:{status:task.status,idempotency_key:idem}});return task;
 }
 async handoff({context,task,fromAgent,toAgent,instruction}){if(!fromAgent?.agentId)throw new Error("AI handoff requires source agent attribution");if(!toAgent)throw new Error("AI handoff requires target employee");const authority=task.requested_by||context.userId;if(!authority)throw new Error("AI handoff has no authorizing actor");const actor={actor_type:"ai_agent",actor_id:fromAgent.agentId,agent_id:fromAgent.agentId,agent_name:fromAgent.name,agent_role:fromAgent.role};const next=await this.create({context:{...context,userId:authority},assignedAgent:toAgent,instruction,priority:task.priority,inputReferences:[...(task.output_references??[]),{type:"task",id:task.task_id}],parentTaskId:task.task_id,handoffDepth:Number(task.handoff_depth??0)+1,idempotencyKey:`handoff:${task.task_id}:${toAgent}`,actor});await this.audit?.write?.({organization_id:context.organizationId,...actor,action:"ai.task.handoff",entity_type:"ai_task",entity_id:task.task_id,reason:instruction,metadata:{to_agent:toAgent,child_task_id:next.task_id,authorized_by:authority}});return next;}
 async claimQueued({organizationId,taskId,agent=null}){const result=await this.database.query(`UPDATE ledgerly_ai.tasks SET status='working',attempts=attempts+1,last_error=NULL,updated_at=now() WHERE task_id=$1 AND organization_id=$2 AND status='queued' RETURNING *`,[taskId,organizationId]);if(!result.rowCount)return null;await this.audit?.write?.({organization_id:organizationId,actor_type:agent?"ai_agent":"system",actor_id:agent?.agentId??"ai-worker",agent_id:agent?.agentId,agent_name:agent?.name,agent_role:agent?.role,action:"ai.task.working",entity_type:"ai_task",entity_id:taskId});return result.rows[0];}
 async setStatus({organizationId,taskId,status,agent=null,error=null,outputReferences=null,expectedStatuses=null}){if(!TASK_STATUSES.includes(status))throw new Error(`invalid task status ${status}`);const values=[status,error,outputReferences?JSON.stringify(outputReferences):null,taskId,organizationId];let guard="";if(Array.isArray(expectedStatuses)&&expectedStatuses.length){values.push(expectedStatuses);guard=` AND status = ANY($6::text[])`;};const result=await this.database.query(`UPDATE ledgerly_ai.tasks SET status=$1,last_error=$2,output_references=COALESCE($3::jsonb,output_references),completed_at=CASE WHEN $1='completed' THEN now() ELSE completed_at END,updated_at=now() WHERE task_id=$4 AND organization_id=$5${guard} RETURNING *`,values);if(!result.rowCount)throw stateConflict("AI task state changed before update");await this.audit?.write?.({organization_id:organizationId,actor_type:agent?"ai_agent":"system",actor_id:agent?.agentId??"ai-worker",agent_id:agent?.agentId,agent_name:agent?.name,agent_role:agent?.role,action:`ai.task.${status}`,entity_type:"ai_task",entity_id:taskId,reason:error});return result.rows[0];}
 async cancel({context,taskId,reason=null}){const org=assertOrg(context);const work=async(db)=>{const result=await db.query(`UPDATE ledgerly_ai.tasks SET status='cancelled',last_error=$1,updated_at=now() WHERE task_id=$2 AND organization_id=$3 AND status IN ('queued','working','waiting_for_approval','blocked') RETURNING *`,[reason,taskId,org]);if(result.rowCount)await db.query(`UPDATE ledgerly_ai.approvals SET status='cancelled',decision_by=$1,decision_reason=$2,decided_at=COALESCE(decided_at,now()) WHERE task_id=$3 AND organization_id=$4 AND status IN ('pending','approved')`,[context.userId,reason??"Parent AI task cancelled",taskId,org]);return result;};const result=typeof this.database.transaction==="function"?await this.database.transaction(work):await work(this.database);if(!result.rowCount){const existing=(await this.database.query(`SELECT * FROM ledgerly_ai.tasks WHERE task_id=$1 AND organization_id=$2`,[taskId,org])).rows[0];if(!existing)throw new Error("AI task not found");return existing;}await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:"ai.task.cancelled",entity_type:"ai_task",entity_id:taskId,reason});return result.rows[0];}
 async retry({context,taskId,reason=null}){const org=assertOrg(context),retryId=randomUUID();const work=async(db)=>{const current=(await db.query(`SELECT * FROM ledgerly_ai.tasks WHERE task_id=$1 AND organization_id=$2 FOR UPDATE`,[taskId,org])).rows[0];if(!current)throw new Error("AI task not found");if(current.status==="queued"&&Array.isArray(current.history)&&current.history.at(-1)?.type==="manual_retry")return {task:current,retryId:current.history.at(-1).retry_id,recovered:true};if(!["blocked","failed"].includes(current.status))throw stateConflict(`AI task cannot retry from status ${current.status}`);const result=await db.query(`UPDATE ledgerly_ai.tasks SET status='queued',last_error=NULL,completed_at=NULL,history=history || jsonb_build_array(jsonb_build_object('type','manual_retry','retry_id',$1,'reason',$2,'requested_by',$3,'at',now())),updated_at=now() WHERE task_id=$4 AND organization_id=$5 AND status=$6 RETURNING *`,[retryId,reason,context.userId,taskId,org,current.status]);if(!result.rowCount)throw stateConflict("AI task state changed before retry");return {task:result.rows[0],retryId,recovered:false};};const prepared=typeof this.database.transaction==="function"?await this.database.transaction(work):await work(this.database);await this.queue.enqueue(this.#envelope(org,taskId,`:retry:${prepared.retryId}`,{manualRetry:prepared.retryId}));await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:prepared.recovered?"ai.task.retry_recovered":"ai.task.retried",entity_type:"ai_task",entity_id:taskId,reason,metadata:{retry_id:prepared.retryId}});return {...prepared.task,retryRecovered:prepared.recovered};}
 async resumeAfterApproval({context,taskId,approvalId,result:executedResult}){
   const org=assertOrg(context);if(!taskId)return {resumed:false,reason:"approval_has_no_task"};const reference={type:"approval",id:approvalId,status:"executed",result:executedResult??null};
   const envelope=()=>this.#envelope(org,taskId,`:approval:${approvalId}`,{resumedFromApproval:approvalId});
   const update=await this.database.query(`UPDATE ledgerly_ai.tasks SET status='queued',history=history || jsonb_build_array(jsonb_build_object('type','approval_executed','approval_id',$1,'result',$2::jsonb,'at',now())),output_references=output_references || $3::jsonb,updated_at=now() WHERE task_id=$4 AND organization_id=$5 AND status='waiting_for_approval' RETURNING *`,[approvalId,JSON.stringify(executedResult??null),JSON.stringify([reference]),taskId,org]);
   if(!update.rowCount){const existing=(await this.database.query(`SELECT * FROM ledgerly_ai.tasks WHERE task_id=$1 AND organization_id=$2`,[taskId,org])).rows[0];if(!existing)throw new Error("AI task not found for approval resume");if(existing.status==="queued"){await this.queue.enqueue(envelope());return {resumed:true,recovered:true,task:existing};}if(["working","completed"].includes(existing.status))return {resumed:false,task:existing,reason:`already_${existing.status}`};throw new Error(`AI task cannot resume from status ${existing.status}`);}
   try{await this.queue.enqueue(envelope());}catch(error){await this.database.query(`UPDATE ledgerly_ai.tasks SET status='waiting_for_approval',updated_at=now() WHERE task_id=$1 AND organization_id=$2 AND status='queued'`,[taskId,org]).catch(()=>undefined);throw error;}
   await this.audit?.write?.({organization_id:org,actor_type:"human",actor_id:context.userId,action:"ai.task.resumed_after_approval",entity_type:"ai_task",entity_id:taskId,metadata:{approval_id:approvalId}});return {resumed:true,task:update.rows[0]};
 }
}
