import {useCallback,useEffect,useRef,useState} from "react";
import {SafeAreaView,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import {Camera,useCameraDevice,useCameraPermission,useCodeScanner} from "react-native-vision-camera";
import {DeviceManager} from "../../native";
import {cameraConfig,cameraHeartbeat,cameraHealth,pairCamera,readCameraRegistration,saveCameraRegistration} from "./api";
import {CameraSegmentRuntime} from "./segmentRuntime";
import type {CameraConfig,CameraRegistration,CameraRuntimeState} from "./types";
const PREFIX="LEDGERLY-CAMERA:1:";
const EMPTY_RUNTIME:CameraRuntimeState={recording:false,uploading:false,pendingSegments:0};
export function CameraModeScreen({onChangePurpose}:{onChangePurpose:()=>void}){
 const[registration,setRegistration]=useState<CameraRegistration|null|undefined>(undefined),[config,setConfig]=useState<CameraConfig|null>(null),[busy,setBusy]=useState(false),[online,setOnline]=useState(false),[error,setError]=useState(""),[runtimeState,setRuntimeState]=useState<CameraRuntimeState>(EMPTY_RUNTIME),lock=useRef(false),cameraRef=useRef<Camera|null>(null),runtimeRef=useRef<CameraSegmentRuntime|null>(null),permission=useCameraPermission();
 const facing=config?.capture?.preferredFacing||"back",device=useCameraDevice(facing);
 const sync=useCallback(async(reg:CameraRegistration)=>{try{const[cfg]=await Promise.all([cameraConfig(reg),cameraHeartbeat(reg,runtimeState)]);setConfig(cfg);runtimeRef.current?.update(cfg);setOnline(true);setError("")}catch(e){setOnline(false);setError(e instanceof Error?e.message:String(e))}},[runtimeState.pendingSegments,runtimeState.recording]);
 useEffect(()=>{void permission.requestPermission();void readCameraRegistration().then(reg=>{setRegistration(reg);if(reg)void sync(reg)})},[]);
 useEffect(()=>{if(!registration)return;const timer=setInterval(()=>void sync(registration),15000);return()=>clearInterval(timer)},[registration,sync]);
 useEffect(()=>{const ready=registration&&config&&config.recording.enabled&&config.transport.ingestUrl&&permission.hasPermission&&device;if(!ready){void runtimeRef.current?.stop();runtimeRef.current=null;return}const runtime=new CameraSegmentRuntime(cameraRef,registration,config,setRuntimeState);runtimeRef.current=runtime;const starter=setTimeout(()=>void runtime.start(),800);return()=>{clearTimeout(starter);void runtime.stop();if(runtimeRef.current===runtime)runtimeRef.current=null}},[registration?.deviceId,config?.transport.ingestUrl,config?.recording.enabled,permission.hasPermission,device?.id]);
 async function activate(raw:string){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{if(!raw.startsWith(PREFIX))throw new Error("Scan the QR code shown in Ledgerly Security → Cameras");const fingerprint=await DeviceManager.deviceFingerprint(),reg=await pairCamera(raw,fingerprint);await cameraHealth(reg);await saveCameraRegistration(reg);setRegistration(reg);setOnline(true);void sync(reg)}catch(e){setError(e instanceof Error?e.message:String(e));setTimeout(()=>{lock.current=false},1800)}finally{setBusy(false)}}
 const scanner=useCodeScanner({codeTypes:["qr"],onCodeScanned:codes=>{const value=codes[0]?.value;if(value)void activate(value)}});
 if(registration===undefined)return <View style={s.root}/>;
 if(!registration)return <SafeAreaView style={s.root}><View style={s.header}><Text style={s.eyebrow}>SECURITY CAMERA</Text><Text style={s.title}>Scan pairing QR</Text><Text style={s.copy}>In Ledgerly open Security → Cameras → Add camera, then point this phone at the one-time QR code.</Text></View><View style={s.cameraBox}>{device&&permission.hasPermission?<Camera style={StyleSheet.absoluteFill} device={device} isActive={!busy} codeScanner={scanner}/>:<View style={s.permission}><Text style={s.permissionTitle}>Camera access is required</Text><TouchableOpacity style={s.button} onPress={()=>void permission.requestPermission()}><Text style={s.buttonText}>Allow camera</Text></TouchableOpacity></View>}<View pointerEvents="none" style={s.overlay}><View style={s.frame}/><Text style={s.hint}>{busy?"Pairing camera…":"Place the QR inside the frame"}</Text></View></View>{error?<Text style={s.error}>{error}</Text>:<Text style={s.note}>The QR works once and expires after ten minutes. Dedicated camera mode does not require a normal Ledgerly user login.</Text>}<TouchableOpacity onPress={onChangePurpose}><Text style={s.change}>Choose another device purpose</Text></TouchableOpacity></SafeAreaView>;
 const server=config?.transport?.server,recordingReady=Boolean(server&&config?.transport.ingestUrl&&config?.recording.enabled);
 return <SafeAreaView style={s.applianceRoot}><View style={s.preview}>{device&&permission.hasPermission?<Camera ref={cameraRef} style={StyleSheet.absoluteFill} device={device} isActive video audio={false}/>:<View style={s.permission}><Text style={s.permissionTitle}>Camera permission is required</Text><TouchableOpacity style={s.button} onPress={()=>void permission.requestPermission()}><Text style={s.buttonText}>Allow camera</Text></TouchableOpacity></View>}<View style={s.top}><View><Text style={s.brand}>LEDGERLY CAMERA</Text><Text style={s.name}>{registration.name}</Text><Text style={s.location}>{registration.location||"Security camera"}</Text></View><Pill text={online?"● ONLINE":"● OFFLINE"} good={online}/></View><View style={s.bottom}><View style={s.runtimeRow}><Pill text={runtimeState.recording?"● RECORDING":recordingReady?"○ STARTING":"○ WAITING"} good={runtimeState.recording}/><Pill text={runtimeState.uploading?"↑ UPLOADING":`${runtimeState.pendingSegments} BUFFERED`} good={!runtimeState.pendingSegments}/></View><View style={s.info}><Text style={recordingReady?s.ready:s.waiting}>{recordingReady?"LOCAL NVR RECORDING ENABLED":"WAITING FOR LOCAL NVR"}</Text><Text style={s.infoTitle}>{server?.name||"Camera is securely paired"}</Text><Text style={s.infoCopy}>{recordingReady?`${server?.localBaseUrl} · ${config?.capture.width}×${config?.capture.height} · ${config?.capture.fps} FPS · ${config?.capture.segmentSeconds}s segments`:"Pair a local camera server in Ledgerly and assign this camera to it. Recording starts automatically when the NVR becomes reachable."}</Text>{runtimeState.lastUploadedAt?<Text style={s.meta}>Last stored on NVR: {new Date(runtimeState.lastUploadedAt).toLocaleTimeString()}</Text>:null}{runtimeState.lastError||error?<Text style={s.errorInline}>{runtimeState.lastError||error}</Text>:null}</View><TouchableOpacity onPress={onChangePurpose}><Text style={s.change}>Change device purpose</Text></TouchableOpacity></View></View></SafeAreaView>
}
function Pill({text,good}:{text:string;good:boolean}){return <View style={[s.pill,good&&s.pillGood]}><Text style={[s.pillText,good&&s.pillTextGood]}>{text}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#071c16",padding:20},header:{paddingTop:18,paddingBottom:18},eyebrow:{color:"#6ed09f",fontSize:10,fontWeight:"900",letterSpacing:1.6},title:{color:"white",fontSize:29,fontWeight:"900",marginTop:6},copy:{color:"#a7bfb4",fontSize:13,lineHeight:20,marginTop:7},cameraBox:{flex:1,borderRadius:24,overflow:"hidden",backgroundColor:"#17372b",position:"relative"},overlay:{...StyleSheet.absoluteFill,alignItems:"center",justifyContent:"center"},frame:{width:235,height:235,borderWidth:4,borderColor:"white",borderRadius:24},hint:{color:"white",fontWeight:"900",marginTop:20,textShadowColor:"#000",textShadowRadius:7},permission:{flex:1,alignItems:"center",justifyContent:"center",padding:28,backgroundColor:"#102c23"},permissionTitle:{color:"white",fontSize:18,fontWeight:"900",textAlign:"center"},button:{backgroundColor:"#19955f",paddingHorizontal:17,paddingVertical:11,borderRadius:10,marginTop:14},buttonText:{color:"white",fontWeight:"900"},error:{color:"#ff9f98",fontSize:12,textAlign:"center",marginTop:12},note:{color:"#85a597",fontSize:11,textAlign:"center",lineHeight:17,marginTop:12},change:{color:"#79cfa7",fontSize:12,fontWeight:"800",textAlign:"center",paddingVertical:14,textShadowColor:"#000",textShadowRadius:4},applianceRoot:{flex:1,backgroundColor:"#020705"},preview:{flex:1,position:"relative",backgroundColor:"#0b1712"},top:{position:"absolute",left:18,right:18,top:22,flexDirection:"row",alignItems:"flex-start"},brand:{color:"#70d3a2",fontSize:9,fontWeight:"900",letterSpacing:1.5},name:{color:"white",fontSize:25,fontWeight:"900",marginTop:5,textShadowColor:"#000",textShadowRadius:5},location:{color:"#d4e0da",fontSize:11,marginTop:3,textShadowColor:"#000",textShadowRadius:5},bottom:{position:"absolute",left:15,right:15,bottom:8},runtimeRow:{flexDirection:"row",gap:7,marginBottom:8},info:{backgroundColor:"rgba(4,18,13,.92)",borderWidth:1,borderColor:"#315244",borderRadius:17,padding:15},ready:{color:"#5bd798",fontSize:9,fontWeight:"900",letterSpacing:1.2},waiting:{color:"#f1bd68",fontSize:9,fontWeight:"900",letterSpacing:1.2},infoTitle:{color:"white",fontSize:15,fontWeight:"900",marginTop:5},infoCopy:{color:"#afc1b8",fontSize:11.5,lineHeight:17,marginTop:5},meta:{color:"#79cfa7",fontSize:10,marginTop:8},errorInline:{color:"#ff9f98",fontSize:10.5,marginTop:8},pill:{paddingHorizontal:10,paddingVertical:6,borderRadius:999,backgroundColor:"rgba(104,62,65,.82)",borderWidth:1,borderColor:"#8e565b"},pillGood:{backgroundColor:"rgba(18,86,57,.82)",borderColor:"#3fac76"},pillText:{color:"#ffd5d7",fontSize:9,fontWeight:"900"},pillTextGood:{color:"#91e1b9"}});
