import {useEffect,useRef,useState} from "react";
import {SafeAreaView,StyleSheet,Text,TouchableOpacity,View} from "react-native";
import {Camera,useCameraDevice,useCameraPermission,useCodeScanner} from "react-native-vision-camera";
import {OfflineStore} from "../../native";
import type {MobileSession} from "../auth";

const PREFIX="LEDGERLY-CAMERA:1:";
const REG_KEY="camera.device.registration";
type CameraRegistration={deviceId:string;credential:string;name:string;location?:string;serverId?:string;organizationId:string};

async function readRegistration(){const raw=await OfflineStore.getSecure(REG_KEY);if(!raw)return null;try{return JSON.parse(raw) as CameraRegistration}catch{return null}}
async function saveRegistration(value:CameraRegistration){await OfflineStore.putSecure(REG_KEY,JSON.stringify(value))}
async function pair(session:MobileSession,raw:string){if(!raw.startsWith(PREFIX))throw new Error("Scan the QR code shown in Ledgerly Security → Cameras");const response=await fetch(`${session.apiUrl.replace(/\/$/,"")}/api/v1/security-camera/device/pair`,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({token:raw,platform:"android",appVersion:"0.1.0",capabilities:["video-capture","local-buffer","heartbeat"]})});const body:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||"Camera pairing failed");return body.data as CameraRegistration}
async function heartbeat(session:MobileSession,reg:CameraRegistration){await fetch(`${session.apiUrl.replace(/\/$/,"")}/api/v1/security-camera/device/${reg.deviceId}/heartbeat`,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json","x-camera-credential":reg.credential},body:JSON.stringify({appVersion:"0.1.0"})})}

export function CameraModeScreen({session,onChangePurpose}:{session:MobileSession;onChangePurpose:()=>void}){
 const[registration,setRegistration]=useState<CameraRegistration|null|undefined>(undefined),[busy,setBusy]=useState(false),[error,setError]=useState(""),lock=useRef(false),device=useCameraDevice("back"),permission=useCameraPermission();
 useEffect(()=>{void permission.requestPermission();void readRegistration().then(setRegistration)},[]);
 useEffect(()=>{if(!registration)return;void heartbeat(session,registration);const t=setInterval(()=>void heartbeat(session,registration),15000);return()=>clearInterval(t)},[registration,session]);
 async function activate(raw:string){if(lock.current)return;lock.current=true;setBusy(true);setError("");try{const reg=await pair(session,raw);await saveRegistration(reg);setRegistration(reg)}catch(e){setError(e instanceof Error?e.message:String(e));setTimeout(()=>{lock.current=false},1800)}finally{setBusy(false)}}
 const scanner=useCodeScanner({codeTypes:["qr"],onCodeScanned:codes=>{const value=codes[0]?.value;if(value)void activate(value)}});
 if(registration===undefined)return <View style={s.root}/>;
 if(registration)return <SafeAreaView style={s.root}><View style={s.appliance}><View style={s.brand}><View style={s.mark}><Text style={s.markText}>L</Text></View><Text style={s.brandText}>Ledgerly Camera</Text></View><View style={s.live}><View style={s.cameraIcon}><Text style={s.cameraGlyph}>●</Text></View><Text style={s.name}>{registration.name}</Text><Text style={s.location}>{registration.location||"Security camera"}</Text><View style={s.row}><Pill text="● PAIRED" good/><Pill text={registration.serverId?"● SERVER ASSIGNED":"○ SERVER PENDING"} good={Boolean(registration.serverId)}/></View></View><View style={s.info}><Text style={s.infoTitle}>Camera appliance mode</Text><Text style={s.infoCopy}>This device is registered and sending health heartbeats. Continuous capture, buffering and NVR streaming are implemented in the next camera runtime slice.</Text></View><TouchableOpacity onPress={onChangePurpose}><Text style={s.change}>Change device purpose</Text></TouchableOpacity></View></SafeAreaView>;
 return <SafeAreaView style={s.root}><View style={s.header}><Text style={s.eyebrow}>SECURITY CAMERA</Text><Text style={s.title}>Scan pairing QR</Text><Text style={s.copy}>On Ledgerly web open Security → Cameras → Add camera, then point this phone at the QR code.</Text></View><View style={s.cameraBox}>{device&&permission.hasPermission?<Camera style={StyleSheet.absoluteFill} device={device} isActive={!busy} codeScanner={scanner}/>:<View style={s.permission}><Text style={s.permissionTitle}>Camera access is required</Text><TouchableOpacity style={s.button} onPress={()=>void permission.requestPermission()}><Text style={s.buttonText}>Allow camera</Text></TouchableOpacity></View>}<View pointerEvents="none" style={s.overlay}><View style={s.frame}/><Text style={s.hint}>{busy?"Pairing camera…":"Place the QR inside the frame"}</Text></View></View>{error?<Text style={s.error}>{error}</Text>:null}<TouchableOpacity onPress={onChangePurpose}><Text style={s.change}>Choose another device purpose</Text></TouchableOpacity></SafeAreaView>
}
function Pill({text,good}:{text:string;good:boolean}){return <View style={[s.pill,good&&s.pillGood]}><Text style={[s.pillText,good&&s.pillTextGood]}>{text}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#071c16",padding:20},header:{paddingTop:18,paddingBottom:18},eyebrow:{color:"#6ed09f",fontSize:10,fontWeight:"900",letterSpacing:1.6},title:{color:"white",fontSize:29,fontWeight:"900",marginTop:6},copy:{color:"#a7bfb4",fontSize:13,lineHeight:20,marginTop:7},cameraBox:{flex:1,borderRadius:24,overflow:"hidden",backgroundColor:"#17372b",position:"relative"},overlay:{...StyleSheet.absoluteFill,alignItems:"center",justifyContent:"center"},frame:{width:235,height:235,borderWidth:4,borderColor:"white",borderRadius:24},hint:{color:"white",fontWeight:"900",marginTop:20,textShadowColor:"#000",textShadowRadius:7},permission:{flex:1,alignItems:"center",justifyContent:"center",padding:28},permissionTitle:{color:"white",fontSize:18,fontWeight:"900"},button:{backgroundColor:"#19955f",paddingHorizontal:17,paddingVertical:11,borderRadius:10,marginTop:14},buttonText:{color:"white",fontWeight:"900"},error:{color:"#ff9f98",fontSize:12,textAlign:"center",marginTop:12},change:{color:"#79cfa7",fontSize:12,fontWeight:"800",textAlign:"center",paddingVertical:16},appliance:{flex:1,justifyContent:"space-between"},brand:{flexDirection:"row",alignItems:"center",gap:10,paddingTop:8},mark:{width:40,height:40,borderRadius:12,backgroundColor:"#19955f",alignItems:"center",justifyContent:"center"},markText:{color:"white",fontWeight:"900",fontSize:22},brandText:{color:"white",fontWeight:"900",fontSize:17},live:{alignItems:"center"},cameraIcon:{width:126,height:126,borderRadius:63,borderWidth:1,borderColor:"#245c45",backgroundColor:"#102c23",alignItems:"center",justifyContent:"center"},cameraGlyph:{color:"#46d18c",fontSize:50},name:{color:"white",fontSize:27,fontWeight:"900",marginTop:20},location:{color:"#9db6aa",fontSize:13,marginTop:5},row:{flexDirection:"row",gap:8,marginTop:17,flexWrap:"wrap",justifyContent:"center"},pill:{paddingHorizontal:10,paddingVertical:6,borderRadius:999,backgroundColor:"#2e3834"},pillGood:{backgroundColor:"#123c2b"},pillText:{color:"#b5c0bb",fontSize:10,fontWeight:"900"},pillTextGood:{color:"#64d39b"},info:{backgroundColor:"#102c23",borderRadius:17,padding:17,borderWidth:1,borderColor:"#244b3c"},infoTitle:{color:"white",fontSize:14,fontWeight:"900"},infoCopy:{color:"#9fb8ac",fontSize:12,lineHeight:18,marginTop:5}});
