import {randomUUID} from 'node:crypto';
import {createId} from '../auth/crypto.mjs';
import {TenantCache,createPostCommitInvalidator} from '../cache/tenant-cache.mjs';
const req=(v,n)=>{if(typeof v!=='string'||!v.trim())throw new TypeError(`${n} is required`);return v.trim()};
async function audit(tx,o,a,action,id,after=null){await tx.query(`INSERT INTO ledgerly_meta.audit_events(id,organization_id,actor_type,actor_id,action,entity_type,entity_id,after_data,metadata,occurred_at) VALUES($1,$2,'human',$3,$4,'account',$5,$6::jsonb,'{}'::jsonb,now())`,[randomUUID(),o,a,action,id,after==null?null:JSON.stringify(after)])}
export class FinanceAccountsService{
 constructor({database,cache}){this.db=database;this.cache=cache}
 tenant(o){return new TenantCache({cache:this.cache,organizationId:o})}
 invalidator(o){return createPostCommitInvalidator({cache:this.cache,organizationId:o})}
 async list(o,{limit=50,offset=0}={}){return this.tenant(o).remember('accounts',`${limit}:${offset}`,async()=>(await this.db.query(`SELECT id,code,name,type,subtype,normal_balance AS "normalBalance",currency,allow_posting AS "allowPosting",active,parent_account_id AS "parentAccountId",account_group_id AS "accountGroupId",created_at AS "createdAt" FROM accounts WHERE organization_id=$1 ORDER BY code LIMIT $2 OFFSET $3`,[o,limit,offset])).rows,{ttlMs:60000})}
 async groups(o){return this.tenant(o).remember('accounts','groups',async()=>(await this.db.query(`SELECT id,code,name,type,parent_group_id AS "parentGroupId",active FROM account_groups WHERE organization_id=$1 ORDER BY code`,[o])).rows,{ttlMs:60000})}
 validate(v){const type=req(v.type,'type'),normal=req(v.normalBalance,'normalBalance');if(!['asset','liability','equity','revenue','expense'].includes(type))throw new TypeError('type is invalid');if(!['debit','credit'].includes(normal))throw new TypeError('normalBalance is invalid');return{code:req(v.code,'code'),name:req(v.name,'name'),type,subtype:v.subtype??null,normalBalance:normal,currency:v.currency??null,allowPosting:v.allowPosting!==false,parentAccountId:v.parentAccountId??null,accountGroupId:v.accountGroupId??null,active:v.active!==false}}
 async create(o,a,input){const v=this.validate(input),id=createId('acc'),i=this.invalidator(o);i.mark('accounts','dashboard-summary','reference-counts');try{await this.db.transaction(async tx=>{await tx.query(`INSERT INTO accounts(id,organization_id,code,name,type,subtype,normal_balance,currency,allow_posting,parent_account_id,account_group_id,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[id,o,v.code,v.name,v.type,v.subtype,v.normalBalance,v.currency,v.allowPosting,v.parentAccountId,v.accountGroupId,v.active]);await audit(tx,o,a,'account.created',id,v)});await i.committed();return{id,...v}}catch(e){i.rollback();throw e}}
 async update(o,a,id,input){const v=this.validate(input);if(v.parentAccountId===id)throw Object.assign(new Error('An account cannot be its own parent'),{code:'INVALID_PARENT'});const i=this.invalidator(o);i.mark('accounts','dashboard-summary');try{const out=await this.db.transaction(async tx=>{const r=await tx.query(`UPDATE accounts SET code=$3,name=$4,type=$5,subtype=$6,normal_balance=$7,currency=$8,allow_posting=$9,parent_account_id=$10,account_group_id=$11,active=$12,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING id`,[id,o,v.code,v.name,v.type,v.subtype,v.normalBalance,v.currency,v.allowPosting,v.parentAccountId,v.accountGroupId,v.active]);if(!r.rows[0])throw Object.assign(new Error('Account not found'),{code:'ACCOUNT_NOT_FOUND'});await audit(tx,o,a,'account.updated',id,v);return{id,...v}});await i.committed();return out}catch(e){i.rollback();throw e}}
 async active(o,a,id,value){if(value!==true&&value!==false)throw new TypeError('active must be boolean');const i=this.invalidator(o);i.mark('accounts','dashboard-summary');try{const out=await this.db.transaction(async tx=>{const r=await tx.query(`UPDATE accounts SET active=$3,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING id`,[id,o,value]);if(!r.rows[0])throw Object.assign(new Error('Account not found'),{code:'ACCOUNT_NOT_FOUND'});await audit(tx,o,a,'account.status_changed',id,{active:value});return{id,active:value}});await i.committed();return out}catch(e){i.rollback();throw e}}
 async remove(o,a,id){const i=this.invalidator(o);i.mark('accounts','dashboard-summary','reference-counts');try{await this.db.transaction(async tx=>{if((await tx.query(`SELECT 1 FROM journal_lines WHERE organization_id=$1 AND account_id=$2 LIMIT 1`,[o,id])).rows[0])throw Object.assign(new Error('An account with transactions can only be deactivated'),{code:'ACCOUNT_IN_USE'});const r=await tx.query(`DELETE FROM accounts WHERE id=$1 AND organization_id=$2 RETURNING id`,[id,o]);if(!r.rows[0])throw Object.assign(new Error('Account not found'),{code:'ACCOUNT_NOT_FOUND'});await audit(tx,o,a,'account.deleted',id)});await i.committed()}catch(e){i.rollback();throw e}}
}
