import {randomUUID} from 'node:crypto';
import {createId} from '../auth/crypto.mjs';
import {createPostCommitInvalidator} from '../cache/tenant-cache.mjs';
import {FinanceTransactions,FinanceIntegrityError} from './transactions.mjs';
import {schoolFeeReceiptReversalHandler} from './school-fees-reversal.mjs';
const req=(v,n)=>{if(typeof v!=='string'||!v.trim())throw new TypeError(`${n} is required`);return v.trim()};
const safe=(v,n)=>{const x=Number(v);if(!Number.isSafeInteger(x)||x<0)throw new TypeError(`${n} must be a non-negative safe integer`);return x};
const iso=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''));
async function audit(tx,o,a,action,id,after=null){await tx.query(`INSERT INTO ledgerly_meta.audit_events(id,organization_id,actor_type,actor_id,action,entity_type,entity_id,after_data,metadata,occurred_at) VALUES($1,$2,'human',$3,$4,'journal_entry',$5,$6::jsonb,'{}'::jsonb,now())`,[randomUUID(),o,a,action,id,after==null?null:JSON.stringify(after)])}
export class FinanceJournalsService{
 constructor({database,cache}){this.db=database;this.cache=cache;this.txn=new FinanceTransactions({database,sourceReversalHandlers:new Map([['receipt',schoolFeeReceiptReversalHandler()],['school_fee_receipt',schoolFeeReceiptReversalHandler()],['school-fee-receipt',schoolFeeReceiptReversalHandler()]])})}
 invalidator(o){return createPostCommitInvalidator({cache:this.cache,organizationId:o})}
 async list(o,{limit=50,offset=0}={}){return(await this.db.query(`SELECT id,entry_number AS "entryNumber",transaction_date AS "transactionDate",posting_date AS "postingDate",description,reference,source_type AS "sourceType",status,currency,posted_at AS "postedAt",created_at AS "createdAt" FROM journal_entries WHERE organization_id=$1 ORDER BY posting_date DESC,entry_number DESC LIMIT $2 OFFSET $3`,[o,limit,offset])).rows}
 async get(o,id){const e=(await this.db.query(`SELECT * FROM journal_entries WHERE id=$1 AND organization_id=$2`,[id,o])).rows[0];if(!e)throw Object.assign(new Error('Journal not found'),{code:'JOURNAL_NOT_FOUND'});const lines=(await this.db.query(`SELECT l.*,a.code AS account_code,a.name AS account_name,ct.name AS contact_name,pr.name AS project_name,pr.code AS project_code,cls.name AS class_name,dept.name AS department_name,loc.name AS location_name FROM journal_lines l JOIN accounts a ON a.id=l.account_id AND a.organization_id=l.organization_id LEFT JOIN contacts ct ON ct.id=l.contact_id AND ct.organization_id=l.organization_id LEFT JOIN projects pr ON pr.id=l.project_id AND pr.organization_id=l.organization_id LEFT JOIN dimensions cls ON cls.id=l.class_id AND cls.organization_id=l.organization_id LEFT JOIN dimensions dept ON dept.id=l.department_id AND dept.organization_id=l.organization_id LEFT JOIN dimensions loc ON loc.id=l.location_id AND loc.organization_id=l.organization_id WHERE l.journal_entry_id=$1 AND l.organization_id=$2 ORDER BY l.id`,[id,o])).rows;return{...e,lines}}
 async create(o,a,input,key){if(!iso(input.transactionDate)||!iso(input.postingDate))throw new TypeError('transactionDate and postingDate must be YYYY-MM-DD');if(!/^[A-Z]{3}$/.test(String(input.currency||'').toUpperCase()))throw new TypeError('currency must be a 3-letter code');if(!Array.isArray(input.lines)||input.lines.length<2)throw new TypeError('At least two lines are required');const i=this.invalidator(o);i.mark('dashboard-summary');try{const out=await this.db.transaction(async tx=>{await tx.query(`SELECT pg_advisory_xact_lock(hashtext($1),hashtext($2))`,[`journal:${o}`,key]);const existing=await tx.query(`SELECT id,entry_number AS "entryNumber",status FROM journal_entries WHERE organization_id=$1 AND idempotency_key=$2`,[o,key]);if(existing.rows[0])return existing.rows[0];let debit=0,credit=0;for(const l of input.lines){const d=safe(l.debitMinor??0,'debitMinor'),c=safe(l.creditMinor??0,'creditMinor');if((d>0)===(c>0))throw new FinanceIntegrityError('UNBALANCED_JOURNAL','Each journal line must have exactly one non-zero side');debit+=d;credit+=c}if(debit<=0||debit!==credit)throw new FinanceIntegrityError('UNBALANCED_JOURNAL','Journal must balance');const seq=(await tx.query(`SELECT COALESCE(MAX(NULLIF(regexp_replace(entry_number,'\\D','','g'),'' )::bigint),0)+1 AS next FROM journal_entries WHERE organization_id=$1`,[o])).rows[0]?.next||1,id=createId('je'),number=`JE-${String(seq).padStart(8,'0')}`;await tx.query(`INSERT INTO journal_entries(id,organization_id,entry_number,transaction_date,posting_date,description,reference,source_type,source_id,status,currency,exchange_rate_micros,idempotency_key,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',$10,$11,$12,$13)`,[id,o,number,input.transactionDate,input.postingDate,req(input.description,'description'),input.reference??null,input.sourceType??'manual',input.sourceId??null,String(input.currency).toUpperCase(),input.exchangeRateMicros??1000000,key,JSON.stringify(input.metadata??{})]);for(const l of input.lines){const d=Number(l.debitMinor||0),c=Number(l.creditMinor||0);await tx.query(`INSERT INTO journal_lines(id,organization_id,journal_entry_id,account_id,description,debit_minor,credit_minor,base_debit_minor,base_credit_minor,contact_id,project_id,class_id,department_id,location_id,tax_code) VALUES($1,$2,$3,$4,$5,$6,$7,$6,$7,$8,$9,$10,$11,$12,$13)`,[createId('jl'),o,id,req(l.accountId,'accountId'),l.description??null,d,c,l.contactId??null,l.projectId??null,l.classId??null,l.departmentId??null,l.locationId??null,l.taxCode??null])}await audit(tx,o,a,'journal.created',id,{entryNumber:number,debitMinor:debit,creditMinor:credit});return{id,entryNumber:number,status:'draft'}});await i.committed();return out}catch(e){i.rollback();throw e}}
 async post(o,a,id){const i=this.invalidator(o);i.mark('dashboard-summary','accounts');try{const out=await this.txn.postJournal({organizationId:o,journalId:id,actorId:a});await i.committed();return out}catch(e){i.rollback();throw e}}
 async reverse(o,a,id,{postingDate,reason}){if(!iso(postingDate)||typeof reason!=='string'||reason.trim().length<3)throw new TypeError('A posting date and reason are required');const i=this.invalidator(o);i.mark('dashboard-summary','accounts');try{const out=await this.txn.reverseJournal({organizationId:o,journalId:id,actorId:a,postingDate,reason:reason.trim(),reversalId:createId('je'),reversalNumber:`REV-${Date.now()}-${Math.random().toString(36).slice(2,7)}`});await i.committed();return out}catch(e){i.rollback();throw e}}
 async remove(o,a,id){const i=this.invalidator(o);i.mark('dashboard-summary');try{await this.db.transaction(async tx=>{const r=await tx.query(`DELETE FROM journal_entries WHERE id=$1 AND organization_id=$2 AND status='draft' RETURNING id`,[id,o]);if(!r.rows[0]){const x=(await tx.query(`SELECT status FROM journal_entries WHERE id=$1 AND organization_id=$2`,[id,o])).rows[0];if(!x)throw Object.assign(new Error('Journal not found'),{code:'JOURNAL_NOT_FOUND'});throw Object.assign(new Error('Posted journals must be reversed, not deleted'),{code:'INVALID_JOURNAL_STATE'})}await audit(tx,o,a,'journal.draft_deleted',id)});await i.committed()}catch(e){i.rollback();throw e}}
}
