import { randomUUID } from "node:crypto";

const BUILTINS = Object.freeze([
  { key:"student_announcement", name:"Student / parent announcement", moduleKey:"school-management", category:"general", audienceKind:"students", subjectTemplate:"Student update", messageTemplate:"This is an important update concerning {{student_name}}: {{custom_message}}", audienceDefaults:{ recipientMode:"all_guardians" } },
  { key:"teacher_announcement", name:"Teacher announcement", moduleKey:"school-management", category:"staff", audienceKind:"staff", subjectTemplate:"Teacher update", messageTemplate:"{{custom_message}}", audienceDefaults:{ teacherOnly:true } },
  { key:"staff_announcement", name:"Staff announcement", moduleKey:"school-management", category:"staff", audienceKind:"staff", subjectTemplate:"Staff update", messageTemplate:"{{custom_message}}", audienceDefaults:{ teacherOnly:false } },
  { key:"organization_announcement", name:"Organization-wide announcement", moduleKey:"platform", category:"general", audienceKind:"organization_users", subjectTemplate:"Organization update", messageTemplate:"{{custom_message}}", audienceDefaults:{} },
  { key:"contact_announcement", name:"Contact / client message", moduleKey:"ledgerly-core", category:"general", audienceKind:"contacts", subjectTemplate:"Update", messageTemplate:"{{custom_message}}", audienceDefaults:{} },
  { key:"fee_balance_reminder", name:"Fee balance reminder", moduleKey:"school-fees", category:"finance", audienceKind:"fee_balances", subjectTemplate:"School fees reminder", messageTemplate:"Our records show an outstanding school fees balance of {{balance}} for {{student_name}}. Please arrange payment or contact the school finance office if you need assistance.", audienceDefaults:{ recipientMode:"all_guardians", minimumBalanceMinor:1 } },
  { key:"results_published", name:"Published examination results", moduleKey:"exams", category:"academic", audienceKind:"published_results", subjectTemplate:"Examination results published", messageTemplate:"Results for {{student_name}} in {{exam_name}} have been published. Aggregate: {{aggregate}}. Division: {{division}}.", audienceDefaults:{ recipientMode:"all_guardians" } },
]);

function bounded(value, fallback=50, max=500){const n=Number(value);return Number.isFinite(n)?Math.max(1,Math.min(Math.trunc(n),max)):fallback;}
function fail(status,code,message,details){throw Object.assign(new Error(message),{status,code,details});}
function json(value,fallback){if(value==null)return fallback;try{return typeof value==='string'?JSON.parse(value):value}catch{return fallback}}
function text(value){return String(value??'').trim();}
function fullName(...parts){return parts.map(text).filter(Boolean).join(' ').replace(/\s+/g,' ');}
function cleanPhone(value){let p=text(value).replace(/[\s()\-]/g,'');if(!p)return null;if(p.startsWith('00'))p=`+${p.slice(2)}`;if(/^256\d+$/.test(p))p=`+${p}`;if(/^0\d{9}$/.test(p))p=`+256${p.slice(1)}`;return p.length>=7?p:null;}
function render(template,data){return String(template??'').replace(/{{\s*([a-zA-Z0-9_]+)\s*}}/g,(_,key)=>String(data?.[key]??''));}
function id(prefix){return `${prefix}_${randomUUID().replaceAll('-','')}`;}

export class CommunicationsApiService {
  constructor({ database, service, repository, audit=null, notificationConfig={} }){
    if(!database?.query||!database?.transaction)throw new TypeError('database required');
    this.database=database;this.service=service;this.repository=repository;this.audit=audit;this.notificationConfig=notificationConfig;
  }

  async tableExists(name){const r=await this.database.query('SELECT to_regclass($1) IS NOT NULL AS ok',[`public.${name}`]);return r.rows[0]?.ok===true;}

  providers(){const c=this.notificationConfig??{};return {sms:{provider:'EgoSMS',configured:Boolean(c.sms?.username&&c.sms?.password&&c.sms?.senderId)},whatsapp:{provider:'WhatsApp Support Hub',configured:Boolean(c.whatsapp?.hubUrl&&c.whatsapp?.appKey),templateName:c.whatsapp?.templateName||'general_app_update',language:c.whatsapp?.language||'en_US',status:'approved'}};}

  async ensureBuiltinMessageTypes(organizationId,userId=null){
    await this.database.transaction(async tx=>{for(const x of BUILTINS){await tx.query(`INSERT INTO communication_message_types (id,organization_id,type_key,name,module_key,category,audience_kind,subject_template,message_template,audience_defaults_json,system_type,active,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,true,$11) ON CONFLICT (organization_id,type_key) DO NOTHING`,[id('cmt'),organizationId,x.key,x.name,x.moduleKey,x.category,x.audienceKind,x.subjectTemplate,x.messageTemplate,JSON.stringify(x.audienceDefaults),userId]);}});
  }

  async messageTypes(organizationId,userId){await this.ensureBuiltinMessageTypes(organizationId,userId);const r=await this.database.query(`SELECT id,type_key AS "typeKey",name,module_key AS "moduleKey",category,audience_kind AS "audienceKind",subject_template AS "subjectTemplate",message_template AS "messageTemplate",audience_defaults_json AS "audienceDefaultsJson",system_type AS "systemType",active FROM communication_message_types WHERE organization_id=$1 AND active=true ORDER BY system_type DESC,module_key,name`,[organizationId]);return r.rows.map(x=>({...x,audienceDefaults:json(x.audienceDefaultsJson,{})}));}

  async summary(organizationId){const r=await this.database.query(`SELECT count(*)::int AS campaigns,count(*) FILTER(WHERE status='scheduled')::int AS scheduled,COALESCE(sum(sent_count),0)::int AS sent,COALESCE(sum(failed_count),0)::int AS failed FROM communication_campaigns WHERE organization_id=$1`,[organizationId]);return r.rows[0]??{campaigns:0,scheduled:0,sent:0,failed:0};}

  async campaigns({organizationId,status=null,limit=50,offset=0}){const values=[organizationId];let where='organization_id=$1';if(status){values.push(status);where+=` AND status=$${values.length}`;}values.push(bounded(limit,50,200),Math.max(0,Number(offset)||0));const r=await this.database.query(`SELECT id,type_key AS "typeKey",module_key AS "moduleKey",name,sender_name AS "senderName",channels_json AS "channelsJson",audience_kind AS "audienceKind",status,scheduled_at AS "scheduledAt",started_at AS "startedAt",completed_at AS "completedAt",recipient_count AS "recipientCount",skipped_count AS "skippedCount",delivery_count AS "deliveryCount",sent_count AS "sentCount",failed_count AS "failedCount",created_at AS "createdAt" FROM communication_campaigns WHERE ${where} ORDER BY created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);const c=await this.database.query(`SELECT count(*)::int AS total FROM communication_campaigns WHERE ${where}`,values.slice(0,values.length-2));return {items:r.rows.map(x=>({...x,channels:json(x.channelsJson,[])})),pagination:{limit:values.at(-2),offset:values.at(-1),total:Number(c.rows[0]?.total||0)}};}

  async campaign(organizationId,campaignId){const c=await this.database.query(`SELECT * FROM communication_campaigns WHERE organization_id=$1 AND id=$2`,[organizationId,campaignId]);if(!c.rows[0])fail(404,'CAMPAIGN_NOT_FOUND','Communication campaign not found');const [recipients,deliveries]=await Promise.all([this.database.query(`SELECT id,recipient_type AS "recipientType",recipient_id AS "recipientId",related_entity_type AS "relatedEntityType",related_entity_id AS "relatedEntityId",recipient_name AS "recipientName",phone,email,status,skip_reason AS "skipReason",data_json AS "dataJson" FROM communication_recipients WHERE organization_id=$1 AND campaign_id=$2 ORDER BY recipient_name LIMIT 500`,[organizationId,campaignId]),this.database.query(`SELECT d.id,d.channel,d.recipient_phone AS "recipientPhone",d.recipient_email AS "recipientEmail",d.provider,d.status,d.attempts,d.provider_message_id AS "providerMessageId",d.last_error AS "lastError",d.sent_at AS "sentAt",r.recipient_name AS "recipientName" FROM communication_deliveries d JOIN communication_recipients r ON r.id=d.recipient_snapshot_id AND r.organization_id=d.organization_id WHERE d.organization_id=$1 AND d.campaign_id=$2 ORDER BY d.created_at DESC LIMIT 1000`,[organizationId,campaignId])]);return {...c.rows[0],channels:json(c.rows[0].channels_json,[]),audience:json(c.rows[0].audience_json,{}),recipients:recipients.rows.map(x=>({...x,data:json(x.dataJson,{})})),deliveries:deliveries.rows};}

  async context(organizationId){
    const out={organization:null,years:[],terms:[],classes:[],streams:[],departments:[],exams:[],staff:[],tasks:[],contacts:[]};
    out.organization=(await this.database.query(`SELECT id,name,base_currency AS currency,timezone FROM organizations WHERE id=$1`,[organizationId])).rows[0]??null;
    const specs=[['school_academic_years','years',`SELECT id,name,code,is_current AS "isCurrent",status FROM school_academic_years WHERE organization_id=$1 ORDER BY starts_on DESC`],['school_terms','terms',`SELECT id,name,code,academic_year_id AS "academicYearId",is_current AS "isCurrent",status FROM school_terms WHERE organization_id=$1 ORDER BY starts_on DESC`],['school_classes','classes',`SELECT id,name,code,academic_year_id AS "academicYearId",campus_id AS "campusId" FROM school_classes WHERE organization_id=$1 AND active=true ORDER BY name`],['school_streams','streams',`SELECT id,name,code,class_id AS "classId",campus_id AS "campusId" FROM school_streams WHERE organization_id=$1 AND active=true ORDER BY name`],['school_departments','departments',`SELECT id,name,code FROM school_departments WHERE organization_id=$1 AND active=true ORDER BY name`],['exm_exams','exams',`SELECT id,name,status,academic_year_id AS "academicYearId",term_id AS "termId" FROM exm_exams WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 100`],['school_staff_profiles','staff',`SELECT id,staff_number AS "staffNumber",first_name||' '||last_name AS name,is_teacher AS "isTeacher",department_id AS "departmentId" FROM school_staff_profiles WHERE organization_id=$1 AND deleted_at IS NULL AND employment_status='active' ORDER BY last_name,first_name LIMIT 500`],['work_tasks','tasks',`SELECT id,task_number AS "taskNumber",title,status FROM work_tasks WHERE organization_id=$1 ORDER BY updated_at DESC LIMIT 100`],['contacts','contacts',`SELECT c.id,c.name,c.type,cp.phone FROM contacts c LEFT JOIN contact_people cp ON cp.organization_id=c.organization_id AND cp.contact_id=c.id AND cp.is_primary=true WHERE c.organization_id=$1 AND c.active=true AND c.archived_at IS NULL ORDER BY c.name LIMIT 500`]];
    for(const [table,key,sql] of specs)if(await this.tableExists(table))out[key]=(await this.database.query(sql,[organizationId])).rows;
    return out;
  }

  async resolveAudience(organizationId,audience={}){
    const kind=text(audience.kind);const result=[];
    if(kind==='contacts'){
      if(!await this.tableExists('contacts'))return result;const ids=Array.isArray(audience.contactIds)?audience.contactIds:[];const values=[organizationId];let extra='';if(ids.length){values.push(ids);extra=` AND c.id=ANY($2::text[])`;}
      const r=await this.database.query(`SELECT c.id,c.name,c.email,cp.phone FROM contacts c LEFT JOIN LATERAL (SELECT phone FROM contact_people p WHERE p.organization_id=c.organization_id AND p.contact_id=c.id ORDER BY p.is_primary DESC,p.created_at LIMIT 1) cp ON true WHERE c.organization_id=$1 AND c.active=true AND c.archived_at IS NULL${extra} ORDER BY c.name`,values);for(const x of r.rows)result.push({recipientType:'contact',recipientId:x.id,name:x.name,phone:cleanPhone(x.phone),email:x.email,data:{contact_name:x.name}});
    } else if(kind==='organization_users'||kind==='work_users'){
      const r=await this.database.query(`SELECT u.id,u.display_name AS name,u.email FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND u.status='active' ORDER BY u.display_name`,[organizationId]);for(const x of r.rows)result.push({recipientType:'user',recipientId:x.id,name:x.name,email:x.email,phone:null,data:{user_name:x.name}});
    } else if(kind==='staff'){
      if(!await this.tableExists('school_staff_profiles'))return result;const values=[organizationId];let extra='';if(audience.departmentId){values.push(audience.departmentId);extra+=` AND department_id=$${values.length}`;}if(audience.teacherOnly){extra+=' AND is_teacher=true';}const r=await this.database.query(`SELECT id,first_name,middle_name,last_name,email,phone,staff_number FROM school_staff_profiles WHERE organization_id=$1 AND deleted_at IS NULL AND employment_status='active'${extra} ORDER BY last_name,first_name`,values);for(const x of r.rows)result.push({recipientType:'staff',recipientId:x.id,name:fullName(x.first_name,x.middle_name,x.last_name),phone:cleanPhone(x.phone),email:x.email,data:{staff_number:x.staff_number,staff_name:fullName(x.first_name,x.middle_name,x.last_name)}});
    } else if(kind==='students'){
      if(!await this.tableExists('school_students'))return result;const values=[organizationId];let extra=" AND s.status='active' AND s.deleted_at IS NULL";for(const [field,column] of [['academicYearId','current_academic_year_id'],['classId','current_class_id'],['streamId','current_stream_id'],['campusId','campus_id']])if(audience[field]){values.push(audience[field]);extra+=` AND s.${column}=$${values.length}`;}const r=await this.database.query(`SELECT s.id,s.first_name,s.middle_name,s.last_name,s.phone,s.email,s.admission_number,g.id AS guardian_id,g.first_name AS guardian_first,g.middle_name AS guardian_middle,g.last_name AS guardian_last,g.phone_primary AS guardian_phone,sg.is_primary FROM school_students s LEFT JOIN school_student_guardians sg ON sg.organization_id=s.organization_id AND sg.student_id=s.id LEFT JOIN school_guardians g ON g.organization_id=sg.organization_id AND g.id=sg.guardian_id AND g.active=true WHERE s.organization_id=$1${extra} ORDER BY s.last_name,s.first_name,sg.is_primary DESC`,values);const mode=audience.recipientMode||'all_guardians';for(const x of r.rows){const student=fullName(x.first_name,x.middle_name,x.last_name),data={student_id:x.id,student_name:student,admission_number:x.admission_number};if(mode==='student_direct'||mode==='guardians_and_student')result.push({recipientType:'student',recipientId:x.id,relatedEntityType:'student',relatedEntityId:x.id,name:student,phone:cleanPhone(x.phone),email:x.email,data});if(mode!=='student_direct'&&x.guardian_id&&(mode!=='primary_guardian'||x.is_primary===true))result.push({recipientType:'guardian',recipientId:x.guardian_id,relatedEntityType:'student',relatedEntityId:x.id,name:fullName(x.guardian_first,x.guardian_middle,x.guardian_last)||'Parent/Guardian',phone:cleanPhone(x.guardian_phone),data});}
    } else if(['fee_balances','published_results','attendance','discipline'].includes(kind)) {
      fail(409,'COMMUNICATIONS_AUDIENCE_DEPENDENCY',`${kind} audience requires its owning module to be cut over before Communications can resolve it.`);
    } else fail(422,'VALIDATION_ERROR','Unsupported audience kind');
    const seen=new Set();return result.filter(x=>{const key=`${x.recipientType}:${x.recipientId}:${x.relatedEntityId??''}:${x.phone??''}:${x.email??''}`;if(seen.has(key))return false;seen.add(key);return true;});
  }

  async previewAudience(organizationId,audience,channels=[]){const rows=await this.resolveAudience(organizationId,audience);const usable=rows.filter(r=>channels.every(ch=>ch==='email'?Boolean(r.email):Boolean(r.phone)));return {total:rows.length,sendable:usable.length,skipped:rows.length-usable.length,sample:rows.slice(0,20).map(r=>({name:r.name,phone:r.phone,email:r.email,recipientType:r.recipientType}))};}

  async createCampaign({organizationId,userId,input}){
    const typeKey=text(input.typeKey);if(!typeKey)fail(422,'VALIDATION_ERROR','typeKey is required');await this.ensureBuiltinMessageTypes(organizationId,userId);const type=(await this.database.query(`SELECT * FROM communication_message_types WHERE organization_id=$1 AND type_key=$2 AND active=true`,[organizationId,typeKey])).rows[0];if(!type)fail(404,'MESSAGE_TYPE_NOT_FOUND','Message type not found');const channels=[...new Set(Array.isArray(input.channels)?input.channels.map(String):[])].filter(x=>['sms','whatsapp','email'].includes(x));if(!channels.length)fail(422,'VALIDATION_ERROR','At least one delivery channel is required');const audience={...json(type.audience_defaults_json,{}),...(input.audience||{}),kind:input.audience?.kind||type.audience_kind};const recipients=await this.resolveAudience(organizationId,audience);const org=(await this.database.query('SELECT name FROM organizations WHERE id=$1',[organizationId])).rows[0];const campaignId=id('cmp'),senderName=text(input.senderName)||org?.name||'Ledgerly',subject=text(input.subject)||type.subject_template,message=text(input.message)||type.message_template,scheduledAt=input.scheduledAt?new Date(input.scheduledAt):null,status=input.sendNow?'queued':scheduledAt&&scheduledAt>Date.now()?'scheduled':'draft';
    await this.database.transaction(async tx=>{await tx.query(`INSERT INTO communication_campaigns (id,organization_id,message_type_id,type_key,module_key,name,sender_name,subject_template,message_template,channels_json,audience_kind,audience_json,status,scheduled_at,recipient_count,skipped_count,delivery_count,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,0,0,$16,$16)`,[campaignId,organizationId,type.id,type.type_key,type.module_key,text(input.name)||type.name,senderName,subject,message,JSON.stringify(channels),audience.kind,JSON.stringify(audience),status,scheduledAt?.toISOString()??null,recipients.length,userId]);for(const recipient of recipients){const rid=id('rcp'),phone=recipient.phone??null,email=recipient.email??null,sendable=channels.some(ch=>ch==='email'?Boolean(email):Boolean(phone));await tx.query(`INSERT INTO communication_recipients (id,organization_id,campaign_id,recipient_type,recipient_id,related_entity_type,related_entity_id,recipient_name,phone,email,data_json,status,skip_reason) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[rid,organizationId,campaignId,recipient.recipientType,recipient.recipientId,recipient.relatedEntityType??null,recipient.relatedEntityId??null,recipient.name,phone,email,JSON.stringify(recipient.data??{}),sendable?'ready':'skipped',sendable?null:'recipient_address_missing']);if(!sendable)continue;for(const channel of channels){const address=channel==='email'?email:phone;if(!address)continue;const rendered=render(message,{...(recipient.data??{}),recipient_name:recipient.name,custom_message:message});await tx.query(`INSERT INTO communication_deliveries (id,organization_id,campaign_id,recipient_snapshot_id,channel,recipient_phone,recipient_email,provider,template_name,template_language,template_variables_json,rendered_subject,rendered_message,status,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'queued',$14)`,[id('dlv'),organizationId,campaignId,rid,channel,phone,email,channel==='sms'?'egosms':channel==='whatsapp'?'whatsapp-support-hub':'resend',channel==='whatsapp'?(this.notificationConfig?.whatsapp?.templateName||'general_app_update'):null,channel==='whatsapp'?(this.notificationConfig?.whatsapp?.language||'en_US'):null,JSON.stringify([recipient.name,senderName,subject,rendered]),render(subject,recipient.data??{}),rendered,`${campaignId}:${rid}:${channel}`]);}}await tx.query(`UPDATE communication_campaigns SET skipped_count=(SELECT count(*) FROM communication_recipients WHERE organization_id=$1 AND campaign_id=$2 AND status='skipped'),delivery_count=(SELECT count(*) FROM communication_deliveries WHERE organization_id=$1 AND campaign_id=$2) WHERE organization_id=$1 AND id=$2`,[organizationId,campaignId]);});
    if(input.sendNow)await this.service.queueCampaign({organizationId,campaignId,actor:{actorType:'human',actorId:userId}});return {id:campaignId,status,recipientCount:recipients.length};
  }

  queue({organizationId,campaignId,userId}){return this.service.queueCampaign({organizationId,campaignId,actor:{actorType:'human',actorId:userId}});}
  cancel({organizationId,campaignId,userId}){return this.service.cancelCampaign({organizationId,campaignId,actor:{actorType:'human',actorId:userId}});}
  async retryFailed({organizationId,campaignId,userId}){await this.database.query(`UPDATE communication_deliveries SET status='queued',next_attempt_at=NULL,updated_at=now() WHERE organization_id=$1 AND campaign_id=$2 AND status='failed' AND provider_message_id IS NULL`,[organizationId,campaignId]);return this.queue({organizationId,campaignId,userId});}
  async deliveries({organizationId,channel=null,status=null,limit=100}){const v=[organizationId];let w='d.organization_id=$1';if(channel){v.push(channel);w+=` AND d.channel=$${v.length}`;}if(status){v.push(status);w+=` AND d.status=$${v.length}`;}v.push(bounded(limit,100,500));const r=await this.database.query(`SELECT d.id,d.campaign_id AS "campaignId",c.name AS "campaignName",r.recipient_name AS "recipientName",d.recipient_phone AS "recipientPhone",d.channel,d.provider,d.status,d.attempts,d.provider_message_id AS "providerMessageId",d.last_error AS "lastError",d.sent_at AS "sentAt",d.created_at AS "createdAt" FROM communication_deliveries d JOIN communication_campaigns c ON c.id=d.campaign_id AND c.organization_id=d.organization_id JOIN communication_recipients r ON r.id=d.recipient_snapshot_id AND r.organization_id=d.organization_id WHERE ${w} ORDER BY d.created_at DESC LIMIT $${v.length}`,v);return r.rows;}
  async preference(organizationId,recipientType,recipientId){const r=await this.database.query(`SELECT sms_enabled AS "smsEnabled",whatsapp_enabled AS "whatsappEnabled",do_not_contact AS "doNotContact",quiet_hours_json AS "quietHoursJson",updated_at AS "updatedAt" FROM communication_preferences WHERE organization_id=$1 AND recipient_type=$2 AND recipient_id=$3`,[organizationId,recipientType,recipientId]);const x=r.rows[0];return x?{recipientType,recipientId,...x,quietHours:json(x.quietHoursJson,{})}:{recipientType,recipientId,smsEnabled:true,whatsappEnabled:true,doNotContact:false,quietHours:{},configured:false};}
  async setPreference({organizationId,userId,recipientType,recipientId,input}){await this.database.query(`INSERT INTO communication_preferences (organization_id,recipient_type,recipient_id,sms_enabled,whatsapp_enabled,do_not_contact,quiet_hours_json,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(organization_id,recipient_type,recipient_id) DO UPDATE SET sms_enabled=EXCLUDED.sms_enabled,whatsapp_enabled=EXCLUDED.whatsapp_enabled,do_not_contact=EXCLUDED.do_not_contact,quiet_hours_json=EXCLUDED.quiet_hours_json,updated_by=EXCLUDED.updated_by,updated_at=now()`,[organizationId,recipientType,recipientId,input.smsEnabled!==false,input.whatsappEnabled!==false,input.doNotContact===true,JSON.stringify(input.quietHours??{}),userId]);return this.preference(organizationId,recipientType,recipientId);}
}
