function iso(value){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))throw new TypeError("invalid date");return d.toISOString();}
export class PostgresCommunicationsRepository{
 constructor({database}){if(!database?.query)throw new TypeError("communications repository requires database");this.database=database;}
 async getCampaign(o,id){const r=await this.database.query(`SELECT * FROM communication_campaigns WHERE organization_id=$1 AND id=$2`,[o,id]);return r.rows[0]??null;}
 async listDueCampaignIds(o,now=new Date(),limit=100){const r=await this.database.query(`SELECT id FROM communication_campaigns WHERE organization_id=$1 AND status='scheduled' AND scheduled_at <= $2::timestamptz ORDER BY scheduled_at,id LIMIT $3`,[o,iso(now),Math.max(1,Math.min(Number(limit)||100,500))]);return r.rows.map(x=>x.id);}
 async setCampaignState(o,id,status,{actorId=null,completedAt=null}={}){const r=await this.database.query(`UPDATE communication_campaigns SET status=$3,updated_by=COALESCE($4,updated_by),started_at=CASE WHEN $3='sending' THEN COALESCE(started_at,now()) ELSE started_at END,completed_at=COALESCE($5::timestamptz,completed_at),updated_at=now() WHERE organization_id=$1 AND id=$2 RETURNING *`,[o,id,status,actorId,completedAt]);return r.rows[0]??null;}
 async listSendableDeliveryIds(o,c,{afterId=null,limit=100}={}){const v=[o,c];let after="";if(afterId){v.push(afterId);after=` AND d.id > $${v.length}`;}v.push(Math.max(1,Math.min(Number(limit)||100,500)));const r=await this.database.query(`SELECT d.id FROM communication_deliveries d JOIN communication_campaigns c ON c.id=d.campaign_id AND c.organization_id=d.organization_id WHERE d.organization_id=$1 AND d.campaign_id=$2 AND c.status IN ('queued','sending') AND d.status IN ('queued','failed') AND d.provider_message_id IS NULL ${after} ORDER BY d.id LIMIT $${v.length}`,v);return r.rows.map(x=>x.id);}
 async claimDelivery(o,id){const r=await this.database.query(`UPDATE communication_deliveries d SET status='sending',attempts=attempts+1,updated_at=now() FROM communication_campaigns c WHERE d.id=$2 AND d.organization_id=$1 AND c.id=d.campaign_id AND c.organization_id=d.organization_id AND c.status IN ('queued','sending') AND d.status IN ('queued','failed') AND d.provider_message_id IS NULL RETURNING d.*`,[o,id]);return r.rows[0]??null;}
 async getDeliveryState(o,id){const r=await this.database.query(`SELECT id,status,provider_message_id,campaign_id,recipient_snapshot_id,next_attempt_at FROM communication_deliveries WHERE organization_id=$1 AND id=$2`,[o,id]);return r.rows[0]??null;}
 async getPreference(o,t,id){if(!t||!id)return null;const r=await this.database.query(`SELECT * FROM communication_preferences WHERE organization_id=$1 AND recipient_type=$2 AND recipient_id=$3`,[o,t,id]);return r.rows[0]??null;}
 async getRecipient(o,id){const r=await this.database.query(`SELECT * FROM communication_recipients WHERE organization_id=$1 AND id=$2`,[o,id]);return r.rows[0]??null;}
 async markDeliverySent(o,id,{provider,providerMessageId}){const r=await this.database.query(`UPDATE communication_deliveries SET status='sent',provider=$3,provider_message_id=$4,last_error=NULL,sent_at=COALESCE(sent_at,now()),next_attempt_at=NULL,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status='sending' RETURNING *`,[o,id,provider,providerMessageId]);return r.rows[0]??null;}
 async markDeliveryFailed(o,id,{error,nextAttemptAt=null}){const r=await this.database.query(`UPDATE communication_deliveries SET status='failed',last_error=$3,failed_at=now(),next_attempt_at=$4::timestamptz,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status='sending' RETURNING *`,[o,id,String(error).slice(0,4000),nextAttemptAt?iso(nextAttemptAt):null]);return r.rows[0]??null;}
 async markDeliveryDeadLetter(o,id,{reason}){const r=await this.database.query(`UPDATE communication_deliveries SET status='failed',last_error=$3,failed_at=COALESCE(failed_at,now()),next_attempt_at=NULL,updated_at=now() WHERE organization_id=$1 AND id=$2 AND provider_message_id IS NULL AND status IN ('failed','sending','queued') RETURNING *`,[o,id,String(reason).slice(0,4000)]);return r.rows[0]??null;}
 async cancelDelivery(o,id,reason){const r=await this.database.query(`UPDATE communication_deliveries SET status='cancelled',last_error=$3,next_attempt_at=NULL,updated_at=now() WHERE organization_id=$1 AND id=$2 AND status IN ('queued','failed','sending') RETURNING *`,[o,id,reason]);return r.rows[0]??null;}
 async refreshCampaignProgress(o,c){const r=await this.database.query(`WITH stats AS (SELECT count(*)::int delivery_count,count(*) FILTER(WHERE status IN ('sent','delivered'))::int sent_count,count(*) FILTER(WHERE status='failed')::int failed_count,count(*) FILTER(WHERE status='failed' AND next_attempt_at IS NULL)::int dead_count,count(*) FILTER(WHERE status='cancelled')::int cancelled_count,count(*) FILTER(WHERE status IN ('queued','sending') OR (status='failed' AND next_attempt_at IS NOT NULL))::int pending_count FROM communication_deliveries WHERE organization_id=$1 AND campaign_id=$2) UPDATE communication_campaigns c SET delivery_count=stats.delivery_count,sent_count=stats.sent_count,failed_count=stats.failed_count,status=CASE WHEN c.status='cancelled' THEN 'cancelled' WHEN stats.pending_count>0 THEN CASE WHEN c.status='paused' THEN 'paused' ELSE 'sending' END WHEN stats.dead_count>0 THEN 'partial' ELSE 'completed' END,completed_at=CASE WHEN stats.pending_count=0 THEN COALESCE(c.completed_at,now()) ELSE NULL END,updated_at=now() FROM stats WHERE c.organization_id=$1 AND c.id=$2 RETURNING c.*,stats.pending_count,stats.cancelled_count,stats.dead_count`,[o,c]);return r.rows[0]??null;}
}
