import { Hono } from "hono";
import { z } from "zod";
import type { AppVariables, Env } from "../../../src/types";
import { requireScope } from "../../../src/lib/auth";
import { AppError } from "../../../src/lib/errors";
import { createId } from "../../../src/lib/ids";

export const audioCallRoutes=new Hono<{Bindings:Env;Variables:AppVariables}>();
audioCallRoutes.use("*",requireScope("audio-calls:read"));

const activeStatuses=["ringing","accepted"];
const signalSchema=z.object({toUserId:z.string().min(1),type:z.enum(["offer","answer","ice","hangup","renegotiate"]),payload:z.record(z.string(),z.unknown()).default({})});
const heartbeatSchema=z.object({availability:z.enum(["available","busy","do_not_disturb"]).default("available"),deviceId:z.string().max(200).optional().nullable()});

async function activeMembership(db:D1Database,org:string,userId:string){
 return db.prepare(`SELECT u.id,u.display_name AS displayName,u.email,m.role FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? AND m.user_id=? AND u.status='active' LIMIT 1`).bind(org,userId).first<{id:string;displayName:string;email:string;role:string}>();
}
async function participantCall(db:D1Database,org:string,userId:string,callId:string){
 const row=await db.prepare(`SELECT * FROM audio_calls WHERE id=? AND organization_id=? AND (caller_user_id=? OR callee_user_id=?)`).bind(callId,org,userId,userId).first<Record<string,any>>();
 if(!row)throw new AppError(404,"AUDIO_CALL_NOT_FOUND","Call not found");return row;
}
async function hasActiveCall(db:D1Database,org:string,userId:string){
 return db.prepare(`SELECT id,status FROM audio_calls WHERE organization_id=? AND status IN ('ringing','accepted') AND (caller_user_id=? OR callee_user_id=?) LIMIT 1`).bind(org,userId,userId).first<{id:string;status:string}>();
}
function callView(row:Record<string,any>){return{id:row.id,callerUserId:row.caller_user_id,calleeUserId:row.callee_user_id,status:row.status,startedAt:row.started_at,answeredAt:row.answered_at,endedAt:row.ended_at,endedByUserId:row.ended_by_user_id,endReason:row.end_reason};}
function list(value?:string){return (value||"").split(",").map(x=>x.trim()).filter(Boolean);}

// Directory is organization membership based, so this module works for every Ledgerly organization.
audioCallRoutes.get("/directory",async c=>{const p=c.get("principal"),q=(c.req.query("q")||"").trim().toLowerCase(),like=`%${q}%`;const rows=await c.env.FINANCE_DB.prepare(`SELECT u.id,u.display_name AS displayName,u.email,m.role,COALESCE(pr.availability,'offline') AS declaredAvailability,pr.last_seen_at AS lastSeenAt,pr.active_call_id AS activeCallId FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN audio_call_presence pr ON pr.organization_id=m.organization_id AND pr.user_id=m.user_id WHERE m.organization_id=? AND m.user_id<>? AND u.status='active' AND (?='' OR lower(u.display_name) LIKE ? OR lower(u.email) LIKE ?) ORDER BY u.display_name LIMIT 200`).bind(p.organizationId,p.userId,q,like,like).all<any>();const now=Date.now();return c.json({data:rows.results.map(r=>({...r,availability:r.activeCallId?"busy":r.lastSeenAt&&now-new Date(r.lastSeenAt).getTime()<45_000?r.declaredAvailability:"offline"}))})});

audioCallRoutes.get("/ice-config",c=>{const stun=list(c.env.AUDIO_CALL_STUN_URLS),turn=list(c.env.AUDIO_CALL_TURN_URLS),iceServers:RTCIceServer[]=[];iceServers.push({urls:stun.length?stun:["stun:stun.cloudflare.com:3478"]});if(turn.length&&c.env.AUDIO_CALL_TURN_USERNAME&&c.env.AUDIO_CALL_TURN_CREDENTIAL)iceServers.push({urls:turn,username:c.env.AUDIO_CALL_TURN_USERNAME,credential:c.env.AUDIO_CALL_TURN_CREDENTIAL});return c.json({data:{iceServers,turnConfigured:turn.length>0&&Boolean(c.env.AUDIO_CALL_TURN_USERNAME&&c.env.AUDIO_CALL_TURN_CREDENTIAL)}})});

audioCallRoutes.get("/recent",async c=>{const p=c.get("principal"),limit=Math.max(1,Math.min(Number(c.req.query("limit")||50),200));const rows=await c.env.FINANCE_DB.prepare(`SELECT ac.*,cu.display_name AS callerName,tu.display_name AS calleeName FROM audio_calls ac JOIN users cu ON cu.id=ac.caller_user_id JOIN users tu ON tu.id=ac.callee_user_id WHERE ac.organization_id=? AND (ac.caller_user_id=? OR ac.callee_user_id=?) ORDER BY ac.started_at DESC LIMIT ?`).bind(p.organizationId,p.userId,p.userId,limit).all<any>();return c.json({data:rows.results.map(r=>({...callView(r),callerName:r.callerName,calleeName:r.calleeName,direction:r.caller_user_id===p.userId?"outgoing":"incoming"}))})});

audioCallRoutes.get("/incoming",async c=>{const p=c.get("principal"),row=await c.env.FINANCE_DB.prepare(`SELECT ac.*,u.display_name AS callerName,u.email AS callerEmail FROM audio_calls ac JOIN users u ON u.id=ac.caller_user_id WHERE ac.organization_id=? AND ac.callee_user_id=? AND ac.status='ringing' ORDER BY ac.started_at DESC LIMIT 1`).bind(p.organizationId,p.userId).first<any>();return c.json({data:row?{...callView(row),callerName:row.callerName,callerEmail:row.callerEmail}:null})});

audioCallRoutes.post("/presence/heartbeat",async c=>{const p=c.get("principal"),s=heartbeatSchema.safeParse(await c.req.json().catch(()=>({})));if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid call presence",s.error.flatten());const active=await hasActiveCall(c.env.FINANCE_DB,p.organizationId,p.userId);await c.env.FINANCE_DB.prepare(`INSERT INTO audio_call_presence(organization_id,user_id,availability,active_call_id,device_id,last_seen_at,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(organization_id,user_id) DO UPDATE SET availability=excluded.availability,active_call_id=excluded.active_call_id,device_id=excluded.device_id,last_seen_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP`).bind(p.organizationId,p.userId,active?"busy":s.data.availability,active?.id||null,s.data.deviceId||null).run();return c.json({data:{availability:active?"busy":s.data.availability,activeCallId:active?.id||null}})});

const startSchema=z.object({calleeUserId:z.string().min(1),metadata:z.record(z.string(),z.unknown()).default({})});
audioCallRoutes.post("/calls",requireScope("audio-calls:write"),async c=>{const p=c.get("principal"),s=startSchema.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid call request",s.error.flatten());if(s.data.calleeUserId===p.userId)throw new AppError(422,"SELF_CALL_NOT_ALLOWED","You cannot call yourself");if(!await activeMembership(c.env.FINANCE_DB,p.organizationId,s.data.calleeUserId))throw new AppError(404,"CALLEE_NOT_FOUND","Worker is not an active member of this organization");const [mine,theirs]=await Promise.all([hasActiveCall(c.env.FINANCE_DB,p.organizationId,p.userId),hasActiveCall(c.env.FINANCE_DB,p.organizationId,s.data.calleeUserId)]);if(mine)throw new AppError(409,"CALLER_BUSY","You already have an active call",mine);if(theirs)throw new AppError(409,"CALLEE_BUSY","Worker is already on another call",theirs);const id=createId("acl");await c.env.FINANCE_DB.prepare(`INSERT INTO audio_calls(id,organization_id,caller_user_id,callee_user_id,status,metadata_json) VALUES(?,?,?,?, 'ringing',?)`).bind(id,p.organizationId,p.userId,s.data.calleeUserId,JSON.stringify(s.data.metadata)).run();await c.env.FINANCE_DB.batch([c.env.FINANCE_DB.prepare(`INSERT INTO audio_call_presence(organization_id,user_id,availability,active_call_id,last_seen_at,updated_at) VALUES(?,?,'busy',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(organization_id,user_id) DO UPDATE SET availability='busy',active_call_id=excluded.active_call_id,last_seen_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP`).bind(p.organizationId,p.userId,id),c.env.FINANCE_DB.prepare(`INSERT INTO audio_call_presence(organization_id,user_id,availability,active_call_id,last_seen_at,updated_at) VALUES(?,?,'busy',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(organization_id,user_id) DO UPDATE SET availability='busy',active_call_id=excluded.active_call_id,updated_at=CURRENT_TIMESTAMP`).bind(p.organizationId,s.data.calleeUserId,id)]);return c.json({data:{id,status:"ringing",calleeUserId:s.data.calleeUserId}},201)});

async function finish(c:any,callId:string,next:"declined"|"cancelled"|"ended"|"failed",reason:string){const p=c.get("principal"),call=await participantCall(c.env.FINANCE_DB,p.organizationId,p.userId,callId);if(!activeStatuses.includes(call.status))return callView(call);if(next==="declined"&&!(call.status==="ringing"&&call.callee_user_id===p.userId))throw new AppError(409,"INVALID_CALL_STATE","Only the callee can decline a ringing call");if(next==="cancelled"&&!(call.status==="ringing"&&call.caller_user_id===p.userId))throw new AppError(409,"INVALID_CALL_STATE","Only the caller can cancel a ringing call");await c.env.FINANCE_DB.prepare(`UPDATE audio_calls SET status=?,ended_at=CURRENT_TIMESTAMP,ended_by_user_id=?,end_reason=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND status IN ('ringing','accepted')`).bind(next,p.userId,reason,callId,p.organizationId).run();await c.env.FINANCE_DB.prepare(`UPDATE audio_call_presence SET active_call_id=NULL,availability='available',updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND active_call_id=?`).bind(p.organizationId,callId).run();return{...callView(call),status:next,endedByUserId:p.userId,endReason:reason};}

audioCallRoutes.post("/calls/:id/accept",requireScope("audio-calls:write"),async c=>{const p=c.get("principal"),call=await participantCall(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"));if(call.callee_user_id!==p.userId||call.status!=="ringing")throw new AppError(409,"INVALID_CALL_STATE","Only the callee can accept a ringing call");const r=await c.env.FINANCE_DB.prepare(`UPDATE audio_calls SET status='accepted',answered_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND organization_id=? AND status='ringing'`).bind(call.id,p.organizationId).run();if(!r.meta.changes)throw new AppError(409,"CALL_ALREADY_HANDLED","Call is no longer ringing");return c.json({data:{...callView(call),status:"accepted",answeredAt:new Date().toISOString()}})});
audioCallRoutes.post("/calls/:id/decline",requireScope("audio-calls:write"),async c=>c.json({data:await finish(c,c.req.param("id"),"declined","declined")}));
audioCallRoutes.post("/calls/:id/cancel",requireScope("audio-calls:write"),async c=>c.json({data:await finish(c,c.req.param("id"),"cancelled","cancelled")}));
audioCallRoutes.post("/calls/:id/end",requireScope("audio-calls:write"),async c=>{const body=await c.req.json<{reason?:string}>().catch(()=>({}));return c.json({data:await finish(c,c.req.param("id"),"ended",String(body.reason||"ended").slice(0,120))})});

audioCallRoutes.post("/calls/:id/signals",requireScope("audio-calls:write"),async c=>{const p=c.get("principal"),call=await participantCall(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id"));if(!activeStatuses.includes(call.status))throw new AppError(409,"CALL_NOT_ACTIVE","Cannot signal a finished call");const s=signalSchema.safeParse(await c.req.json());if(!s.success)throw new AppError(422,"VALIDATION_ERROR","Invalid WebRTC signal",s.error.flatten());const other=call.caller_user_id===p.userId?call.callee_user_id:call.caller_user_id;if(s.data.toUserId!==other)throw new AppError(403,"INVALID_SIGNAL_RECIPIENT","Signals may only be sent to the other call participant");const id=createId("acs");await c.env.FINANCE_DB.prepare(`INSERT INTO audio_call_signals(id,organization_id,call_id,from_user_id,to_user_id,signal_type,payload_json) VALUES(?,?,?,?,?,?,?)`).bind(id,p.organizationId,call.id,p.userId,other,s.data.type,JSON.stringify(s.data.payload)).run();return c.json({data:{id}},201)});

audioCallRoutes.get("/calls/:id/signals",async c=>{const p=c.get("principal"),call=await participantCall(c.env.FINANCE_DB,p.organizationId,p.userId,c.req.param("id")),after=Math.max(0,Number(c.req.query("after")||0));const rows=await c.env.FINANCE_DB.prepare(`SELECT sequence,id,from_user_id AS fromUserId,signal_type AS type,payload_json AS payloadJson,created_at AS createdAt FROM audio_call_signals WHERE organization_id=? AND call_id=? AND to_user_id=? AND sequence>? ORDER BY sequence LIMIT 200`).bind(p.organizationId,call.id,p.userId,after).all<any>();const data=rows.results.map(r=>({sequence:r.sequence,id:r.id,fromUserId:r.fromUserId,type:r.type,payload:JSON.parse(r.payloadJson||"{}"),createdAt:r.createdAt}));if(data.length)await c.env.FINANCE_DB.prepare(`UPDATE audio_call_signals SET consumed_at=COALESCE(consumed_at,CURRENT_TIMESTAMP) WHERE organization_id=? AND call_id=? AND to_user_id=? AND sequence<=?`).bind(p.organizationId,call.id,p.userId,data[data.length-1]!.sequence).run();return c.json({data})});
