import{useEffect,useMemo,useState}from"react";
import{Alert,RefreshControl,ScrollView,StyleSheet,Switch,Text,TouchableOpacity,View}from"react-native";
import type{MobileSession}from"../auth";
import type{SessionUpdater}from"../apiClient";
import{Card,Empty,ErrorNotice,Field,Metric,Pill,PrimaryButton,SecondaryButton,SectionTitle,SelectField}from"../school/ui";
import{err}from"./context";
import{printerlyServiceDeskApi}from"./serviceDeskApi";
import type{ServiceAsset,ServiceDeskDashboard,ServiceDeskSettings,ServiceTicketDetail,ServiceTicketStatus}from"./serviceDeskTypes";

type Mode="queue"|"new"|"sla";
const MODES:[Mode,string][]=[["queue","Queue"],["new","New ticket"],["sla","SLA policy"]];
const OPEN=new Set<ServiceTicketStatus>(["new","assigned","in_progress","waiting"]);
const DEFAULT_SETTINGS:ServiceDeskSettings={autoCreateFromAlerts:true,autoResolveRecovered:true,p1ResponseMinutes:30,p1ResolutionMinutes:240,p2ResponseMinutes:120,p2ResolutionMinutes:480,p3ResponseMinutes:480,p3ResolutionMinutes:1440,p4ResponseMinutes:1440,p4ResolutionMinutes:4320};
const EMPTY:ServiceDeskDashboard={capabilities:{canWrite:false,canAdmin:false},settings:DEFAULT_SETTINGS,summary:{open:0,p1:0,breached:0,dueSoon:0,resolvedToday:0},tickets:[],users:[],printers:[],nodes:[],scanners:[]};
const PRIORITIES=[{label:"P1 · Critical",value:"p1"},{label:"P2 · High",value:"p2"},{label:"P3 · Normal",value:"p3"},{label:"P4 · Low",value:"p4"}];
const CATEGORIES=["printer","node","scanner","scan_job","print_job","maintenance","supplies","other"].map(x=>({label:x.replaceAll("_"," "),value:x}));
const ASSET_TYPES=[{label:"Printer",value:"printer"},{label:"Node",value:"node"},{label:"Scanner",value:"scanner"},{label:"No linked asset",value:""}];
const MAINTENANCE_TYPES=["repair","service","cleaning","inspection","parts"].map(x=>({label:x,value:x}));
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString():"—";
const toIso=(v:string)=>{if(!v.trim())return undefined;const d=new Date(v.length===16?`${v}:00`:v);return Number.isFinite(d.getTime())?d.toISOString():v};
const pTone=(v:string):"neutral"|"good"|"warn"|"bad"=>v==="p1"?"bad":v==="p2"?"warn":v==="p4"?"good":"neutral";
const statusTone=(v:string):"neutral"|"good"|"warn"|"bad"=>v==="resolved"||v==="closed"?"good":v==="cancelled"?"bad":"warn";

export function ServiceDeskTab({session,onSession}:{session:MobileSession;onSession:SessionUpdater}){
 const client={session,onSession};
 const[data,setData]=useState<ServiceDeskDashboard>(EMPTY),[selected,setSelected]=useState<ServiceTicketDetail|null>(null),[mode,setMode]=useState<Mode>("queue"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const[title,setTitle]=useState(""),[description,setDescription]=useState(""),[priority,setPriority]=useState("p3"),[category,setCategory]=useState("printer"),[assetType,setAssetType]=useState("printer"),[assetId,setAssetId]=useState(""),[assigneeId,setAssigneeId]=useState(""),[plannedStart,setPlannedStart]=useState(""),[plannedEnd,setPlannedEnd]=useState("");
 const[workNote,setWorkNote]=useState(""),[statusNote,setStatusNote]=useState(""),[resolution,setResolution]=useState(""),[recordMaintenance,setRecordMaintenance]=useState(false),[maintenanceType,setMaintenanceType]=useState("repair"),[technician,setTechnician]=useState(""),[cost,setCost]=useState("0"),[resetClock,setResetClock]=useState(true);
 const[sla,setSla]=useState<ServiceDeskSettings>(DEFAULT_SETTINGS);
 const userOptions=useMemo(()=>data.users.map(x=>({label:x.displayName,value:x.id,detail:[x.role,x.email].filter(Boolean).join(" · ")})),[data.users]);
 const assets:ServiceAsset[]=assetType==="printer"?data.printers:assetType==="node"?data.nodes:assetType==="scanner"?data.scanners:[];
 const assetOptions=assets.map(x=>({label:x.name,value:x.id,detail:[x.location,x.status].filter(Boolean).join(" · ")}));
 const openTickets=data.tickets.filter(x=>OPEN.has(x.status)),finishedTickets=data.tickets.filter(x=>!OPEN.has(x.status));

 async function load(){setLoading(true);setError("");try{const next=await printerlyServiceDeskApi.dashboard(client);setData(next);setSla(next.settings);if(selected){try{setSelected(await printerlyServiceDeskApi.ticket(client,selected.id))}catch{setSelected(null)}}}catch(e){setError(err(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[session.accessToken]);
 async function open(id:string){setLoading(true);setError("");try{const t=await printerlyServiceDeskApi.ticket(client,id);setSelected(t);setMode("queue");setAssigneeId(t.assigneeId||"");setWorkNote("");setStatusNote("");setResolution("");setRecordMaintenance(false);setTechnician("");setCost("0");setResetClock(true)}catch(e){setError(err(e))}finally{setLoading(false)}}
 async function run<T>(fn:()=>Promise<T>,refreshSelected=true):Promise<T|undefined>{setLoading(true);setError("");try{const result=await fn();const next=await printerlyServiceDeskApi.dashboard(client);setData(next);setSla(next.settings);if(refreshSelected&&selected){try{setSelected(await printerlyServiceDeskApi.ticket(client,selected.id))}catch{setSelected(null)}}return result}catch(e){setError(err(e));return undefined}finally{setLoading(false)}}
 async function create(){if(!title.trim()){setError("Service ticket title is required.");return}const body:any={title:title.trim(),description:description.trim(),priority,category,assigneeId:assigneeId||undefined,scheduledStartAt:toIso(plannedStart),scheduledEndAt:toIso(plannedEnd)};if(assetType&&assetId)body[`${assetType}Id`]=assetId;const out=await run<any>(()=>printerlyServiceDeskApi.createTicket(client,body),false);if(out?.id){setTitle("");setDescription("");setAssetId("");setAssigneeId("");setPlannedStart("");setPlannedEnd("");await open(out.id)}}
 async function resolve(){if(!selected||resolution.trim().length<3){setError("Describe how the incident was resolved.");return}await run(()=>printerlyServiceDeskApi.resolve(client,selected.id,{resolutionNotes:resolution.trim(),recordMaintenance:recordMaintenance&&Boolean(selected.printerId),maintenanceEventType,technician:technician.trim()||undefined,costMinor:Math.max(0,Number(cost)||0),resetServiceClock:resetClock}));setResolution("");setRecordMaintenance(false)}
 function cancelTicket(){if(!selected)return;Alert.alert("Cancel service ticket?","Cancellation closes this active incident without marking it resolved.",[{text:"Keep",style:"cancel"},{text:"Cancel ticket",style:"destructive",onPress:()=>void run(()=>printerlyServiceDeskApi.setStatus(client,selected.id,"cancelled",statusNote.trim()||undefined))}])}
 const updateSlaNumber=(key:keyof ServiceDeskSettings,value:string)=>setSla(current=>({...current,[key]:Math.max(1,Number(value)||1)}));

 return <ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={s.scroll}>
  {error?<ErrorNotice message={error} onRetry={load}/>:null}
  <View style={s.hero}><Text style={s.eyebrow}>INCIDENT · ASSIGN · SLA · RESOLVE</Text><Text style={s.title}>Service desk & SLA</Text><Text style={s.copy}>Turn Printerly faults into owned service work with response deadlines, resolution targets, work history and optional maintenance records.</Text></View>
  <View style={s.metrics}><Metric label="Open" value={data.summary.open}/><Metric label="P1" value={data.summary.p1} tone={data.summary.p1?"warn":"plain"}/><Metric label="Breached" value={data.summary.breached} tone={data.summary.breached?"bad":"plain"}/><Metric label="Due ≤ 2h" value={data.summary.dueSoon} tone={data.summary.dueSoon?"warn":"plain"}/><Metric label="Resolved today" value={data.summary.resolvedToday}/></View>
  <View style={s.modes}>{MODES.map(([id,label])=><TouchableOpacity key={id} style={[s.mode,mode===id&&s.modeOn]} onPress={()=>setMode(id)}><Text style={[s.modeText,mode===id&&s.modeTextOn]}>{label}</Text></TouchableOpacity>)}</View>

  {mode==="queue"?<>
   <SectionTitle title="Active service queue" subtitle="Critical, breached and soon-due work stays visible" action={data.capabilities.canAdmin?"Run sweep":undefined} onAction={data.capabilities.canAdmin?()=>void run(()=>printerlyServiceDeskApi.sweep(client),false):undefined}/>
   <Card>{openTickets.length?openTickets.map(t=><TouchableOpacity key={t.id} onPress={()=>void open(t.id)} style={[s.ticket,selected?.id===t.id&&s.active]}><View style={{flex:1}}><Text style={s.name}>{t.ticketNumber} · {t.title}</Text><Text style={s.meta}>{[t.assigneeName||"Unassigned",t.printerName||t.nodeName||t.scannerName||t.category,`resolve ${fmt(t.resolutionDueAt)}`].join(" · ")}</Text></View><View style={s.badges}><Pill text={t.priority.toUpperCase()} tone={pTone(t.priority)}/>{t.responseBreachedAt||t.resolutionBreachedAt?<Pill text="SLA" tone="bad"/>:null}<Pill text={t.status.replaceAll("_"," ")} tone="warn"/></View></TouchableOpacity>):<Empty title="No open tickets" copy="Printerly currently has no active service work."/>}</Card>
   {finishedTickets.length?<><SectionTitle title="Recently finished"/><Card>{finishedTickets.slice(0,30).map(t=><TouchableOpacity key={t.id} onPress={()=>void open(t.id)} style={s.ticket}><View style={{flex:1}}><Text style={s.name}>{t.ticketNumber} · {t.title}</Text><Text style={s.meta}>{[t.assigneeName||"Unassigned",t.category,fmt(t.resolvedAt||t.closedAt)].join(" · ")}</Text></View><Pill text={t.status} tone={statusTone(t.status)}/></TouchableOpacity>)}</Card></>:null}
   {selected?<><SectionTitle title={selected.ticketNumber} subtitle={[selected.printerName||selected.nodeName||selected.scannerName||selected.category,selected.assigneeName||"Unassigned"].join(" · ")}/><Card>
    <View style={s.top}><View style={{flex:1}}><Text style={s.detailTitle}>{selected.title}</Text><Text style={s.description}>{selected.description||"No description."}</Text></View><View style={s.badges}><Pill text={selected.priority.toUpperCase()} tone={pTone(selected.priority)}/><Pill text={selected.status.replaceAll("_"," ")} tone={statusTone(selected.status)}/></View></View>
    {selected.scheduledStartAt||selected.scheduledEndAt?<Text style={s.planned}>Planned service · {fmt(selected.scheduledStartAt)} → {fmt(selected.scheduledEndAt)}</Text>:null}
    <View style={s.slaRow}><View style={{flex:1}}><Text style={s.slaLabel}>Response SLA</Text><Text style={s.meta}>{fmt(selected.responseDueAt)}</Text></View><Pill text={selected.responseBreachedAt?"breached":selected.firstRespondedAt?"met":"pending"} tone={selected.responseBreachedAt?"bad":selected.firstRespondedAt?"good":"warn"}/></View>
    <View style={s.slaRow}><View style={{flex:1}}><Text style={s.slaLabel}>Resolution SLA</Text><Text style={s.meta}>{fmt(selected.resolutionDueAt)}</Text></View><Pill text={selected.resolutionBreachedAt?"breached":selected.status==="resolved"||selected.status==="closed"?"met":"tracking"} tone={selected.resolutionBreachedAt?"bad":selected.status==="resolved"||selected.status==="closed"?"good":"neutral"}/></View>
    {selected.alertTitle?<View style={s.alert}><Text style={s.name}>Linked alert · {selected.alertTitle}</Text><Text style={s.meta}>{selected.alertBody}</Text><Pill text={selected.alertResolvedAt?"recovered":"active"} tone={selected.alertResolvedAt?"good":"warn"}/></View>:null}
    {OPEN.has(selected.status)&&data.capabilities.canWrite?<>
     <SelectField label="Assignee" value={assigneeId} onChange={v=>{setAssigneeId(v);if(v)void run(()=>printerlyServiceDeskApi.assign(client,selected.id,v))}} options={[{label:"Choose assignee",value:""},...userOptions]}/>
     <View style={s.actions}><PrimaryButton compact title="Acknowledge / start" disabled={loading} onPress={()=>void run(()=>printerlyServiceDeskApi.acknowledge(client,selected.id))}/><SecondaryButton compact title="Waiting" onPress={()=>void run(()=>printerlyServiceDeskApi.setStatus(client,selected.id,"waiting",statusNote.trim()||undefined))}/><SecondaryButton compact title="In progress" onPress={()=>void run(()=>printerlyServiceDeskApi.setStatus(client,selected.id,"in_progress",statusNote.trim()||undefined))}/></View>
     <Field label="Status note · optional" value={statusNote} onChangeText={setStatusNote} multiline/>
     <Field label="Work note" value={workNote} onChangeText={setWorkNote} multiline/>
     <PrimaryButton title="Add work note" disabled={loading||!workNote.trim()} onPress={()=>void run(async()=>{await printerlyServiceDeskApi.comment(client,selected.id,workNote.trim());setWorkNote("")})}/>
     <SectionTitle title="Resolve incident" subtitle={selected.printerId?"Optionally copy this work into printer maintenance history":"Resolution requires a clear work summary"}/>
     <Field label="Resolution notes" value={resolution} onChangeText={setResolution} multiline/>
     {selected.printerId?<><View style={s.switchRow}><View style={{flex:1}}><Text style={s.name}>Record printer maintenance</Text><Text style={s.meta}>Creates a linked service record during resolution.</Text></View><Switch value={recordMaintenance} onValueChange={setRecordMaintenance}/></View>{recordMaintenance?<><SelectField label="Maintenance event" value={maintenanceType} onChange={setMaintenanceType} options={MAINTENANCE_TYPES}/><Field label="Technician · optional" value={technician} onChangeText={setTechnician}/><Field label="Cost · UGX" value={cost} onChangeText={setCost} keyboardType="number-pad"/><View style={s.switchRow}><Text style={[s.name,{flex:1}]}>Reset service clock</Text><Switch value={resetClock} onValueChange={setResetClock}/></View></>:null}</>:null}
     <PrimaryButton title="Resolve ticket" disabled={loading||resolution.trim().length<3} onPress={()=>void resolve()}/><PrimaryButton danger title="Cancel ticket" disabled={loading} onPress={cancelTicket}/>
    </>:selected.status==="resolved"&&data.capabilities.canWrite?<PrimaryButton title="Close resolved ticket" onPress={()=>void run(()=>printerlyServiceDeskApi.setStatus(client,selected.id,"closed"))}/>:null}
   </Card><SectionTitle title="Ticket timeline"/><Card>{selected.events.length?selected.events.slice().reverse().map(e=><View key={e.id} style={s.event}><Text style={s.name}>{e.eventType.replaceAll("_"," ")}</Text><Text style={s.meta}>{e.actorName||"System"} · {fmt(e.createdAt)}</Text>{e.notes?<Text style={s.description}>{e.notes}</Text>:null}</View>):<Empty title="No ticket events" copy="Work actions appear here as the incident progresses."/>}</Card></>:null}
  </>:
  mode==="new"?<><SectionTitle title="Create service ticket" subtitle="Link a live Printerly asset and assign the incident at creation"/><Card>{data.capabilities.canWrite?<><Field label="Title" value={title} onChangeText={setTitle} placeholder="Printer jamming in staff room"/><Field label="Description" value={description} onChangeText={setDescription} multiline/><SelectField label="Priority" value={priority} onChange={setPriority} options={PRIORITIES}/><SelectField label="Category" value={category} onChange={setCategory} options={CATEGORIES}/><SelectField label="Asset type" value={assetType} onChange={v=>{setAssetType(v);setAssetId("")}} options={ASSET_TYPES}/>{assetType?<SelectField label="Asset" value={assetId} onChange={setAssetId} options={[{label:"No linked asset",value:""},...assetOptions]}/>:null}<SelectField label="Assignee" value={assigneeId} onChange={setAssigneeId} options={[{label:"Unassigned",value:""},...userOptions]}/><View style={s.two}><View style={s.half}><Field label="Planned start · optional" value={plannedStart} onChangeText={setPlannedStart} placeholder="2026-09-09T10:00"/></View><View style={s.half}><Field label="Planned end · optional" value={plannedEnd} onChangeText={setPlannedEnd} placeholder="2026-09-09T12:00"/></View></View><PrimaryButton title="Create service ticket" disabled={loading||!title.trim()} onPress={()=>void create()}/></>:<Empty title="Read-only service desk" copy="Your role can inspect tickets but cannot create service work."/>}</Card></>:
  <><SectionTitle title="SLA automation" subtitle="Targets are applied when each service ticket is created" action={data.capabilities.canAdmin?"Run sweep":undefined} onAction={data.capabilities.canAdmin?()=>void run(()=>printerlyServiceDeskApi.sweep(client),false):undefined}/><Card>{data.capabilities.canAdmin?<>
   <View style={s.switchRow}><View style={{flex:1}}><Text style={s.name}>Auto-create from Printerly alerts</Text><Text style={s.meta}>Unresolved device and job faults become owned service tickets.</Text></View><Switch value={sla.autoCreateFromAlerts} onValueChange={v=>setSla(x=>({...x,autoCreateFromAlerts:v}))}/></View>
   <View style={s.switchRow}><View style={{flex:1}}><Text style={s.name}>Auto-resolve recovered alerts</Text><Text style={s.meta}>Untouched automated tickets can close when their source alert recovers.</Text></View><Switch value={sla.autoResolveRecovered} onValueChange={v=>setSla(x=>({...x,autoResolveRecovered:v}))}/></View>
   {(["p1","p2","p3","p4"] as const).map(p=><View key={p} style={s.policy}><View style={s.policyHead}><Text style={s.policyTitle}>{p.toUpperCase()} · {p==="p1"?"Critical":p==="p2"?"High":p==="p3"?"Normal":"Low"}</Text><Pill text={`${sla[`${p}ResponseMinutes`]} / ${sla[`${p}ResolutionMinutes`]} min`} tone={pTone(p)}/></View><View style={s.two}><View style={s.half}><Field label="Response minutes" value={String(sla[`${p}ResponseMinutes`])} onChangeText={v=>updateSlaNumber(`${p}ResponseMinutes`,v)} keyboardType="number-pad"/></View><View style={s.half}><Field label="Resolution minutes" value={String(sla[`${p}ResolutionMinutes`])} onChangeText={v=>updateSlaNumber(`${p}ResolutionMinutes`,v)} keyboardType="number-pad"/></View></View></View>)}
   <PrimaryButton title="Save SLA policy" disabled={loading} onPress={()=>void run(()=>printerlyServiceDeskApi.updateSettings(client,sla),false)}/>
  </>:<><Text style={s.readOnly}>Only organization owners and administrators can change Printerly SLA policy.</Text><View style={s.policySummary}>{(["p1","p2","p3","p4"] as const).map(p=><View key={p} style={s.slaRow}><Text style={s.name}>{p.toUpperCase()}</Text><Text style={s.meta}>{sla[`${p}ResponseMinutes`]} min response · {sla[`${p}ResolutionMinutes`]} min resolution</Text></View>)}</View></>}</Card></>}
 </ScrollView>
}

const s=StyleSheet.create({scroll:{padding:16,paddingBottom:44,gap:12},hero:{backgroundColor:"#2a302d",borderRadius:24,padding:20},eyebrow:{fontSize:8,fontWeight:"900",letterSpacing:1.05,color:"#d5b96f"},title:{fontSize:26,fontWeight:"900",color:"white",marginTop:7},copy:{fontSize:10.5,lineHeight:17,color:"#c5cec9",marginTop:6},metrics:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",gap:10},modes:{flexDirection:"row",backgroundColor:"#e7ebe8",borderRadius:15,padding:4,gap:4},mode:{flex:1,paddingVertical:9,borderRadius:11,alignItems:"center"},modeOn:{backgroundColor:"#4a4030"},modeText:{fontSize:9.5,fontWeight:"900",color:"#718078"},modeTextOn:{color:"white"},ticket:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:11,borderBottomWidth:1,borderBottomColor:"#edf1ef"},active:{backgroundColor:"#f6f1e7",marginHorizontal:-8,paddingHorizontal:8,borderRadius:12},name:{fontSize:10.5,fontWeight:"900",color:"#293f35"},meta:{fontSize:8.7,lineHeight:13,color:"#829087",marginTop:3},badges:{flexDirection:"row",flexWrap:"wrap",gap:5,justifyContent:"flex-end"},top:{flexDirection:"row",gap:10,alignItems:"flex-start"},detailTitle:{fontSize:16,fontWeight:"900",color:"#253d32"},description:{fontSize:10,lineHeight:16,color:"#687a71",marginTop:5},planned:{fontSize:9.5,fontWeight:"800",color:"#6e765f",backgroundColor:"#f7f3e8",padding:10,borderRadius:12,marginTop:12},slaRow:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#edf1ef"},slaLabel:{fontSize:10,fontWeight:"900",color:"#344b40"},alert:{backgroundColor:"#fff7e7",borderRadius:14,padding:12,marginVertical:10,gap:4},actions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:12},switchRow:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#edf1ef"},event:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#edf1ef"},two:{flexDirection:"row",justifyContent:"space-between",gap:10},half:{flex:1},policy:{borderTopWidth:1,borderTopColor:"#edf1ef",paddingTop:12,marginTop:8},policyHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8,marginBottom:8},policyTitle:{fontSize:11,fontWeight:"900",color:"#354b41"},readOnly:{fontSize:10,lineHeight:16,color:"#7b8982"},policySummary:{marginTop:8}});
